### ISSUE TITLE
#!inv Page bug

### ISSUE THREAD

**Issue by StikElLoco** [DiscordDungeons/Bugs#100]
I noticed i couldn't open the second page of my inventory and instead it opened page 1, but after i got another item it worked.
It seems it can't open an inventory page if it has only 1 item in it. But if it has 2 it works as expected.
In this case i got 2 eggs (screenshots attached).

**EDIT:** Sold the Eggs, but was able use !inv 2 to show page 2 even with 1 item. So it wasn't working for some other reason.

![screenshot_34](https://cloud.githubusercontent.com/assets/21270788/21077105/b1199600-bf47-11e6-984a-be614c9925f3.png)
![screenshot_35](https://cloud.githubusercontent.com/assets/21270788/21077106/b341189a-bf47-11e6-8043-ee7719b6a98a.png)

**Comment by Sven65** [comment]
This is a known issue, though I don't know what the cause of it is, I will look into it more though.

**Comment by Sven65** [comment]
This was fixed long ago.
