### ISSUE TITLE
Some icon of guild did’t show

### ISSUE THREAD

**Issue by Killer-S-serious-no-underscode-in-name** [DiscordDungeons/Bugs#1002]
The guild icon only show a white line on the place that should show the icon

**To Reproduce**
1. Use #!gset icon 🏕(i use this icon)
2. Use #!guild
3. 
![FD48E8D1-0814-44F0-BE47-146C0AEE19D3](https://user-images.githubusercontent.com/84571012/119124981-d865a200-ba63-11eb-96c4-34174b264294.jpeg)
See error

**Expected behavior**
There should show the icon but it did’t

**Version**
4.15.6

**Comment by Sven65** [comment]
The issue is due to the requested icon not existing on the resource server.

Going to look into alternatives, or just uploading the image file itself.
