### ISSUE TITLE
can't donate upgraded weapon

### ISSUE THREAD

**Issue by mario7331** [DiscordDungeons/Bugs#1004]
ii am not able to donate a upgraded weapon to another player
using the /idonate player Iron Sword +5 1

buy weapon upgrade it using ulrist then try donating it to another player
 
being able to donate the weapon

version 4.15.6

**Comment by FelixArgyle** [comment]
Not a bug.
You can't trade/donate Meta Items
Meta Items = Upgraded / Enchanted / Sockets on a weapon.
close the issue since I can't 👍

**Comment by mario7331** [comment]
> Not a bug.
> You can't trade/donate Meta Items
> Meta Items = Upgraded / Enchanted / Sockets on a weapon.
> close the issue since I can't 👍

how do close  it
