### ISSUE TITLE
Battle glitch

### ISSUE THREAD

**Issue by Killer-S-serious-no-underscode-in-name** [DiscordDungeons/Bugs#1006]
So I found a glitch of battle that if you don’t #!brefuse ,that guy how battle you can battle untill you #!brefuse
1.Have someone battle you
2. Ignore him
3. See error

**Expected behavior**
It should said current time out and close the battle
**Screenshots**
Nah no screenshots sorry

**Version**
4.15.6

Yah I just forgot that guy who battle me and he cannot battle for a month

**Comment by ISven1337** [comment]
They can just type #!bcancel

**Comment by FelixArgyle** [comment]
> They can just type #!bcancel

As Sven mentioned, there is a way already to cancel a battle if a user becomes inactive.
if a battle has started too then `#!bstop` is the alternative.
