### ISSUE TITLE
Arriving at a location isn't sending out a ping

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1008]
**Describe the bug**
When travelling to a location it should send you a ping saying "mentioned you arrived at location", it is not doing this at all now, it was working earlier today but decided to break? very strange....

**To Reproduce**
1. `#!travel location`
2. See that you will not auto arrive when for the location travel time, you will not receive any message.
3. 
**Expected behavior**
For it to show that you arrived at the location with a ping!

**Version**
What is the current version at the time of creating this issue?

4.15.7

**Additional context**
It was working earlier today but decided to break

**Comment by Willard21** [comment]
RabbitMQ broken?

**Comment by Sven65** [comment]
It was rabbitmq, fixed now.
