### ISSUE TITLE
Embed glitch

### ISSUE THREAD

**Issue by Xaphantasia** [DiscordDungeons/Bugs#1026]
**Describe the bug**
After you change an Embed, typing #+adv or #+adv 2 will show the same mob until it is defeated

**To Reproduce**
1. Switch your adventure embed to 3 then back
2. Type #+adv
3. Type #+adv again (without the 2), it will show the same mob.

**Expected behavior**
Will show the same mob, even with trying to flee from it, until defeated

**Screenshots**
<img width="676" alt="Screenshot 2021-09-28 183810" src="https://user-images.githubusercontent.com/91536630/135109118-88f34c64-bb2a-4d49-9e9a-4f1ddb053e8f.png">
<img width="689" alt="Screenshot 2021-09-28 183915" src="https://user-images.githubusercontent.com/91536630/135109285-db1a3f32-197f-4fb3-a957-96c90c12e2b8.png">

**Version**
DRPG Version 16.4.13-beta

Use `#!info` to find the version.

**Additional context**

**Comment by Willard21** [comment]
It's `#+adv 1` to run away. Everything else is treated the same as `#+adv`. The `2` is ignored. It's not a bug.
