### ISSUE TITLE
Leaderboard command (#+lead) bug

### ISSUE THREAD

**Issue by LolisSushiHut** [DiscordDungeons/Bugs#1029]
**Describe the bug**
Displays the error on the attached screenshot when using the command.

**To Reproduce**
1. After starting just type '#+lead' lol

**Expected behavior**
Should hopefully show the leaderboard for the top levelled players using the beta bot (assuming that the leaderboard command is still meant to work for beta).

**Screenshots**
![Screenshot_20210929-121311_Discord](https://user-images.githubusercontent.com/91580156/135192640-9f929f3b-3c4b-40b6-96af-3feb4379e7f8.jpg)

**Version**
16.4.13-beta

**Additional context**
This was confusing for my stupid brain but I did it yay me

**Comment by Sven65** [comment]
Thanks for reporting the bug! It's been fixed now :)
