### ISSUE TITLE
Using stats on a userid will error (BETA)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1032]
**Describe the bug**
Using stats on a userid will error
**To Reproduce**
1. #+stats 240971835330658305
2. Error
```js
TypeError: toDiscordUser.displayAvatarURL is not a function
    at Stats.sendStats (/bin/src/Commands/Commands/User/Stats.ts:109:24)
    at Stats.execute (/bin/src/Commands/Commands/User/Stats.ts:192:4)
```

**Expected behavior**
No error

**Screenshots**
![user error](http://felix.is-a-good-waifu.com/5Uq5cBF.png)

**Comment by Sven65** [comment]
Fixed now
