### ISSUE TITLE
Many Admin cmds borked (BETA)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1035]
**Describe the bug**
Many of the admin commands do not work with "user input" part,  
Givegold seems to be the only working one out of them.
**To Reproduce**
1. `#+giveitem userid/mention item amount` etc

**Comment by mount2010** [comment]
Investigated and found that staff cannot add items/gold themselves now because the user resolver has been to set up to reject self mentions. Received verbal instruction from @Sven65 to change this so this will be fixed.
