### ISSUE TITLE
Stats with userid does not display the users name on the stats display

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1040]
**Describe the bug**
Stats with userid does not display the users name on the stats display

**To Reproduce**
1. stats with userid (that has display set to 1)

**Expected behavior**
instead of it showing "141610251299454976", stats it should show the users name on the stats.
**Screenshots**
![stats](http://felix.is-a-good-waifu.com/ARJYkfe.png)

**Comment by mount2010** [comment]
Issue is in the user resolver. @Sven65 does the user resolver also populate the username field? If it does, we can make every command use the username (and if there is a undefined username somewhere, that's an issue with the resolver).

**Comment by Sven65** [comment]
This is also fixed now
