### ISSUE TITLE
🐛 Bug Report: Bot status wrong

### ISSUE THREAD

**Issue by Sirfirelord69** [DiscordDungeons/Bugs#1046]
### 👟 Reproduction steps

Look at it

### 👍 Expected behavior

Should be "Type /stats to start your adventure!"

### 👎 Actual Behavior

"Type #!stats to start your adventure!"

### 🎲 DRPG version

16.4.13-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Willard21** [comment]
I edited this since it was never fixed and is now in production.

**Comment by mount2010** [comment]
pr made
