### ISSUE TITLE
🐛 Bug Report: Travel crashes the bot

### ISSUE THREAD

**Issue by Sirfirelord69** [DiscordDungeons/Bugs#1063]
### 👟 Reproduction steps

#+travel mourn

### 👍 Expected behavior

travel to mournstead

### 👎 Actual Behavior

bot doesnt reply then bluescreens

### 🎲 DRPG version

16.4.13-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

@Sven65 has said report this

**Comment by Sirfirelord69** [comment]
Actually its just for me since i have no location data (Chapter 2 of #1057 )

**Comment by Sven65** [comment]
This is fixed.
