### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by silencer101** [DiscordDungeons/Bugs#1064]
### 👟 Reproduction steps

Adventured twice and either lagged or lost service because the bot never responded. data must have gone through, because i  got the kill report and leveled up twice in a row. Points are still there. Not sure if bug or not. when from level 204 to 206. I cannot find the exp chart to verify how much exp is needed between levels.

### 👍 Expected behavior

it should have just adventured. I know for certain i was close to leveling up to 205.

### 👎 Actual Behavior

![ss1](https://user-images.githubusercontent.com/92663569/137614971-d4e51982-b2c4-448f-a008-cd6edc7b3865.jpg)
![ss2](https://user-images.githubusercontent.com/92663569/137614972-3e848afe-9f1c-4796-b456-4aa92fd7c585.jpg)
![ss3](https://user-images.githubusercontent.com/92663569/137614981-4e395d62-f65c-49d1-bbfd-0d3e0d55b661.jpg)

### 🎲 DRPG version

4.15.7

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Seems to be a hidden error with the adv command. Should be fixed in the beta.
