### ISSUE TITLE
🐛 Bug Report: Pets gain experience in dungeons and can level up within a dungeon

### ISSUE THREAD

**Issue by Sirfirelord69** [DiscordDungeons/Bugs#1072]
### 👟 Reproduction steps

have a pet with non-zero xprate in a dungeon and xp dropped is sufficient to [](url)

### 👍 Expected behavior

Not level up, as per normal rules where xp gotten is sufficient to level up

### 👎 Actual Behavior

Pet leveled up

### 🎲 DRPG version

16.4.15-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

can be abused as a free heal for the pet - keep it at 0% xp rate, just under level up threshold, then when it is low, give it xp to level up.

NB: seems to be purely visual bug, pet hp and level did not change when checked with #+pet

**Comment by Sven65** [comment]
Pets should be able to level up when they exit the dungeon.
