### ISSUE TITLE
🐛 Bug Report: Dungeon resume does not always show the character ("&")

### ISSUE THREAD

**Issue by Sirfirelord69** [DiscordDungeons/Bugs#1073]
### 👟 Reproduction steps

#+dungeon resume

### 👍 Expected behavior

generate the dungeon map with the "&" displayed

### 👎 Actual Behavior

does not show it until a valid move is made (part 1a), leaving behind a question mark where the player was (this is bug part 1b). valid move means that if there is a wall to the left and the left arrow is clicked, no "&" is displayed and nothing is said by the bot.

### 🎲 DRPG version

16.4.15-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
I know this has happened, but I am unable to reproduce it, seems like it's gotten fixed.
