### ISSUE TITLE
🐛 Bug Report: #+lead is bugged (Secondary tags)

### ISSUE THREAD

**Issue by Sirfirelord69** [DiscordDungeons/Bugs#1074]
### 👟 Reproduction steps

#+lead level showid
or 
#+lead level rank
substitute any option for "level" doesnt matter

### 👍 Expected behavior

show id, or rank

### 👎 Actual Behavior

doesnt

### 🎲 DRPG version

16.4.15-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

@FelixArgyle

**Comment by Sven65** [comment]
Works as intended. The options need `--` as a prefix, i.e. `--showid`
