### ISSUE TITLE
🐛 Bug Report: Lead second args [showid / rank] borked (BETA)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1075]
### 👟 Reproduction steps

`#+lead level showid`
`#+lead level rank`

### 👍 Expected behavior

For showid to show index userids instead of usernames
for rank to show users rank on the lead

### 👎 Actual Behavior

it does not output the expected behaviour, it just does lead as the default usage

### 🎲 DRPG version

 16.4.15

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Not a bug. They have been changed to `--showid` and `--rank`.
