### ISSUE TITLE
🐛 Bug Report: #+inv : is borked

### ISSUE THREAD

**Issue by Sirfirelord69** [DiscordDungeons/Bugs#1081]
### 👟 Reproduction steps

`#+inv :` 

### 👍 Expected behavior

show inventory normally, from page 1

### 👎 Actual Behavior

```diff
!===== [DeusExMachina's Inventory (Page 1/1)] =====!
+ 18,144 Gold.
!==================================================!
```

### 🎲 DRPG version

16.4.15-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 📝 Additional context

@Sven65 part 1 of inventory testing

**Comment by Sirfirelord69** [comment]
It also fucks up with non-universal emotes eg :moukn:

**Comment by Sirfirelord69** [comment]
same error occurs if inventory page specified >16 chars eg
#+inv 98765432123456789
```
DiscordAPIError: Unknown User
    at RequestHandler.execute (/bin/rpgbot/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RequestHandler.push (/bin/rpgbot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at UserManager.fetch (/bin/rpgbot/node_modules/discord.js/src/managers/UserManager.js:69:18)
    at getDiscordUser (/bin/src/Util/UserUtils.ts:31:20)
    at Inv.execute (/bin/src/Commands/Commands/User/Inv.ts:195:23)
    ```

**Comment by Sirfirelord69** [comment]
#+pset :moukn: and #+uset :moukn: simply give no response, and also no response from other emotes, numbers, characters, but the cooldown REMAINS (also for #+inv, #+skills and #+stats - likely because it searches for "valid" inputs as user IDs)

**Comment by Sirfirelord69** [comment]
#+ginv has the same bug with `:` as #+inv, for same reason (think its cuz of the `type:` filtering getting an error)

**Comment by mount2010** [comment]
The #!inv + bug applies to #!items #!ginv #!gbsearch #!gmsearch #!inv and #!recipe

**Comment by mount2010** [comment]
As for the issues with users, those are issues with the user resolver, and not with the item commands. @Sirfirelord69, please make a new issue for those.
