### ISSUE TITLE
🐛 Bug Report: Achievements for gold do not register until user data is updated somehow

### ISSUE THREAD

**Issue by Sirfirelord69** [DiscordDungeons/Bugs#1086]
### 👟 Reproduction steps

complete one of the achievements (this case getting rich)

### 👍 Expected behavior

ping with achievement immediately

### 👎 Actual Behavior

user has to update (by adv, sides, etc) before achievement registers (resulting in double ping earlier from dropping twice - hole in my backpack) 

### 🎲 DRPG version

16.4.15-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

probably connected to weird achievement latency and/or double ping bug

**Comment by Sven65** [comment]
Achievements are only checked when the user data is updated. This behaviour is by design, although some commands don't do the checks, as they don't update user data. What command did you use for this?

**Comment by Willard21** [comment]
I mentioned 1 example in #862 before you closed it for "stale". A quick glance in the `#!assign` file shows it's not fixed there. `#!gbsell`, `#!gmstop`, and `#!gmbuy` don't check achievements for the person collecting the gold.

Unrelated, but I think `#!donate` is probably checking for achievements too many times lol
![image](https://user-images.githubusercontent.com/24826881/140508562-a8d74723-1428-4e84-9951-75c9dcab5594.png)

**Comment by Sven65** [comment]
> I mentioned 1 example in #862 before you closed it for "stale". A quick glance in the `#!assign` file shows it's not fixed there. `#!gbsell`, `#!gmstop`, and `#!gmbuy` don't check achievements for the person collecting the gold.
> 
> Unrelated, but I think `#!donate` is probably checking for achievements too many times lol ![image](https://user-images.githubusercontent.com/24826881/140508562-a8d74723-1428-4e84-9951-75c9dcab5594.png)

Thanks for the additional info!
