### ISSUE TITLE
🐛 Bug Report: Emote controls do not remove player's reaction anymore

### ISSUE THREAD

**Issue by Sirfirelord69** [DiscordDungeons/Bugs#1087]
### 👟 Reproduction steps

use any command (eg #+inv) that has emote controls.

### 👍 Expected behavior

remove the player's reaction after a second-ish

### 👎 Actual Behavior

doesnt remove the player's reaction

### 🎲 DRPG version

16.4.15-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Not really high-priority since the migration to buttons and whatnot

**Comment by mount2010** [comment]
This is probably not a bug. The bot requires the Manage Messages permission to remove messages, and the beta bots don't have this permission. If this continues even when the bot has Manage Messages, please reopen this issue.

**Comment by mount2010** [comment]
Reopening because I just tested it with the manage messages permission and it doesn't remove the reaction then either
