### ISSUE TITLE
🐛 Bug Report: Alex/Task is bugged

### ISSUE THREAD

**Issue by Sirfirelord69** [DiscordDungeons/Bugs#1088]
### 👟 Reproduction steps

#+talk alex

### 👍 Expected behavior

give the task dialogue

### 👎 Actual Behavior

{Alex} - Good evening.

### 🎲 DRPG version

16.4.15-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

@Sven65 seems broken

**Comment by mount2010** [comment]
Private testing on my bot couldn't reproduce this bug. It might be an issue with userdata?

**Comment by mount2010** [comment]
There are several issues with tasks:
Completing a task makes the cooldown absurdly long;
some item amounts are infinity. I suspect this is because of division by 0 due to invalid item values. @Sven65 could you look into this?

**Comment by Sven65** [comment]
I think this has been solved.
