### ISSUE TITLE
Battledraw-Bug

### ISSUE THREAD

**Issue by jayr0flmc** [DiscordDungeons/Bugs#109]
Whoops. An error occured. Please report this in the official server.
```
TypeError: Cannot read property 'draw' of undefined
    at User.getBattle.then (/home/Mackan/RPGBot/src/Commands/battles/bdaccept.js:20:14)
```

I think it should be enough to fix it. ;)
And yes, i wasn't in a battle.

**Comment by Sven65** [comment]
How do I reproduce the issue?

**Comment by jayr0flmc** [comment]
I just used the `bdraw`-command it that happend.
