### ISSUE TITLE
🐛 Bug Report: User fetcher doesn't work right with certain inputs

### ISSUE THREAD

**Issue by mount2010** [DiscordDungeons/Bugs#1113]
### 👟 Reproduction steps

- Try and provide any command such as #+inv which uses the user fetches with an invalid input such as :moukn: or an invalid id

### 👍 Expected behavior

- No error should occur, tell the user they supplied invalid input

### 👎 Actual Behavior

- An error occurs

```
DiscordAPIError: Unknown User
    at RequestHandler.execute (/bin/rpgbot/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RequestHandler.push (/bin/rpgbot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at UserManager.fetch (/bin/rpgbot/node_modules/discord.js/src/managers/UserManager.js:69:18)
    at getDiscordUser (/bin/src/Util/UserUtils.ts:31:20)
    at Inv.execute (/bin/src/Commands/Commands/User/Inv.ts:195:23)
```

### 🎲 DRPG version

4.16.15-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

First reported here https://github.com/DiscordDungeons/Bugs/issues/1081#issuecomment-948473321

**Comment by Sven65** [comment]
We should add a regex check to see if the input is a valid snowflake before we fetch the user by ID. If it's not a valid snowflake, we should return an error message about that.

**Comment by mount2010** [comment]
@Sven65 I don't think it's easy to check if something is a valid snowflake (we have no idea, it might not be in our cache, and might exist as a user on Discord), but we can probably add a catch for the error and make it return an empty object in that case. But then commands generate errors due to not handling an empty object.

**Comment by Willard21** [comment]
Valid snowflakes are easy to check, but there's no way to know if the snowflake is a user ID, channel ID, message ID, emoji ID, or just a random number that happens to be a valid snowflake.

**Comment by mount2010** [comment]
> Valid snowflakes are easy to check, but there's no way to know if the snowflake is a user ID, channel ID, message ID, emoji ID, or just a random number that happens to be a valid snowflake.

Yup, that's what I meant. We need to run it through the Discord.JS fetch function, and if it errors, that means the user doesn't exist.
