### ISSUE TITLE
🐛 Bug Report: Can use more potions than needed to heal

### ISSUE THREAD

**Issue by mount2010** [DiscordDungeons/Bugs#1114]
### 👟 Reproduction steps

- Try to heal with more than you need (e.g. heal with 100 potions when you have 4999/5000 hp)

### 👍 Expected behavior

It uses only the amount needed (1 potion)

### 👎 Actual Behavior

It lets you use 100 potions if you want

### 🎲 DRPG version

4.15.7

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mount2010** [comment]
@Sven65 Let's wait till we have released the beta version, then rewrite/refactor the heal command?

**Comment by Sven65** [comment]
> @Sven65 Let's wait till we have released the beta version, then rewrite/refactor the heal command?

Seems like a good idea seeing as we're focusing on getting to the release.

**Comment by Sven65** [comment]
Leaving this in as an item sink. Players can use `/heal auto`.
