### ISSUE TITLE
🐛 Bug Report:  Bot doesn't work in threads

### ISSUE THREAD

**Issue by Sven65** [DiscordDungeons/Bugs#1116]
### 👟 Reproduction steps

try using the bot in a thread

### 👍 Expected behavior

It should work

### 👎 Actual Behavior

It doesn't

### 🎲 DRPG version

4.16.16-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mount2010** [comment]
Does it really not work? I tested it on my development bot and it seems to be working

**Comment by mount2010** [comment]
Update, @FelixArgyle says this is an issue with mod commands, and is an issue with channel types. Working on it
