### ISSUE TITLE
🐛 Bug Report: can't adventure

### ISSUE THREAD

**Issue by Devils-Horns** [DiscordDungeons/Bugs#1119]
### 👟 Reproduction steps

I type adventure like this #!Adventure and It triggers an error ;v;

### 👍 Expected behavior

it should allow me to adventure ._.

### 👎 Actual Behavior

when I type the code for adventure, I get this

![Screenshot_218](https://user-images.githubusercontent.com/94225818/141643480-2e53a0b6-64d7-4735-9fbe-1dadfdd9f1fb.png)

### 🎲 DRPG version

current I think

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by didyouknowhat** [comment]
I am having this same issue.

**Comment by GregorThyStinky** [comment]
I just had the same problem, I'm new to Dungeons but I'm being told to do #!adventure but it keeps giving me the very same error

**Comment by mount2010** [comment]
Hello,
Thanks for reporting this bug.
We're looking into the cause of this issue. The earliest this can be fixed is tomorrow because Mackan is unavailable today. Please be patient.

**Comment by SnowyWolfo** [comment]
I am having the same problem cant adventure

**Comment by Lexidasical** [comment]
I am also new, just started today and cannot adventure.

**Comment by francisyzy** [comment]
Same, I had this issue as well. The bug just went away tho
```
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:220:20)
```
![image](https://user-images.githubusercontent.com/24467184/141669539-5deb0b39-a7b8-46e6-a40c-55309954a119.png)
