### ISSUE TITLE
Prefix locked?

### ISSUE THREAD

**Issue by Ulcerava** [DiscordDungeons/Bugs#112]
So yes, I understand that you need the DiscordRPG Commander role to change the prefix, but what if someone were to change the prefix then delete the messages without knowing the prefix, the owner/server would be locked and if you were to kick and re-invite DiscordRPG, it would still keep the prefix. There is nothing that you can do, so maybe add a command with a unchangeable prefix/no prefix for DiscordRPG Commander only that would reset the prefix to the default "#!"

**Comment by Cloudham** [comment]
if it does happen, you may use @DiscordRPG#0366 (which mentions the bot) as a prefix to change the prefix back to #! or something else

**Comment by Ulcerava** [comment]
I tried doing that, but it didn't work. The bot gave no response to either "@DiscordRPG#0366setprefix ," or "@DiscordRPG#0366 setprefix ,"
I also tried doing any other command both ways, with no response. I'm probably doing something wrong, and if not is there anything I can do to reset the bot's setting on my server entirely?

**Comment by Sven65** [comment]
If the bot didn't respond it might be muted or down. Just try again.
