### ISSUE TITLE
🐛 Bug Report: Redeeming the Donator Tag code

### ISSUE THREAD

**Issue by DamieMoon** [DiscordDungeons/Bugs#1120]
### 👟 Reproduction steps

Redeeming the DRPG code results in a blank string.

"Damien Moon redeemed a code and got "

Steps to reproduce:
1. Buy the 1$ Donator Tag and redeem the code

### 👍 Expected behavior

Tell you that you got the donator tag/role.

### 👎 Actual Behavior

Blank string.

### 🎲 DRPG version

4.17.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

NOTE: I already have the donator tag.

**Comment by Sven65** [comment]
I am unable to reproduce this issue.
