### ISSUE TITLE
Unexpected trap behavior

### ISSUE THREAD

**Issue by Rain247fire** [DiscordDungeons/Bugs#1122]
To reproduce:

Check trap: harvest items from current trap

Try to set new trap, there is already a trap set

Trap info
You have a legacy Bear Trap set almost 52 years ago. You'll need to check it before buying a trap field.

Check trap
Rainfire checked the trap they set almost 52 years ago.
There was 4,431 Balls of Wool, 4,494 Golden Feathers, 4,519 Meats, 4,648 Raven Feathers, A Bear inside.

It loops from there; check trap rewards are the same each time. A friend and I found this together~ it happened to him in one location (rivermouth) and I reproduced it (silverkeep).

**Comment by Rain247fire** [comment]
Also, his initial trap collect was a bear trap. Mine was a Felix's trap. But both resulted in the same loop.

**Comment by thejawesomeone** [comment]
I wound up having the same problem, yet I can't figure out where on earth I'm supposed to harvest this mysterious 52-year bear trap that I never set. I checked on every location I own but it doesn't let me and I can't set a new one because of it. Lame

**Comment by Sven65** [comment]
> I wound up having the same problem, yet I can't figure out where on earth I'm supposed to harvest this mysterious 52-year bear trap that I never set. I checked on every location I own but it doesn't let me and I can't set a new one because of it. Lame

If this is with the `#!trap check` command, this is a known issue that we're working on fixing. Please note that this issue is only visual, meaning you should be able to set traps as normal in locations where you own a trap spot.
