### ISSUE TITLE
Bug Report: Cannot mine at Aeston, Brimstone, Copperfall, Frostridge, Glimmerhelm, Miree, Primeval, Ravengate, Sariila, Silverkeep Altar's

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1125]
### 👟 Reproduction steps

Go to respective Altar and mine

### 👍 Expected behavior

It should return either  Essence or Rocks

### 👎 Actual Behavior

It says You can't mine here, Weebs.

### 🎲 DRPG version

4.17.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

I suspect it might be all altar's but I won't know until later today when I do my task run. 
Update can mine at Caeli Altar, I will check the rest now.

**Comment by Sven65** [comment]
Have you done the meditative magic quest?
