### ISSUE TITLE
Bug Report: Damage calculation is out, I can no longer one-shot

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1126]
### 👟 Reproduction steps

#!adv

### 👍 Expected behavior

I should be able to one-shot up to level 2,463

### 👎 Actual Behavior

I cannot any more

### 🎲 DRPG version

4.1.17

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

I am 480 strength wielding a Accelerator's Premium Lance 2SXR+32. I am also using a donator item with 2 Rubies which provide a +40% Strength. The base damage of a APL+32 should be 79992 - 81693
If I roll a 1 I do 84,465 damage with the donator item.
If I roll a 2 I do 81,408 damage without the donator item. 

I think either the donator item or rubies or both are not being taken into account re weapon damage.

**Comment by Willard21** [comment]
Before:
![image](https://user-images.githubusercontent.com/24826881/141856879-70a5998f-6961-4a3a-91f5-bd0afa0da9eb.png)

After:
![image](https://user-images.githubusercontent.com/24826881/141856922-1cb52ab6-c68a-424b-b725-217f6cec5846.png)

Spot the difference
