### ISSUE TITLE
🐛 Bug Report: inv name filter broken

### ISSUE THREAD

**Issue by towstone** [DiscordDungeons/Bugs#1131]
### 👟 Reproduction steps

#!inv name:<text> 
#!inv name:log

### 👍 Expected behavior

Return list of all inv items that contain text

### 👎 Actual Behavior

#!inv name:log returns only gold count.

### 🎲 DRPG version

4.17.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mount2010** [comment]
Hello,
Thanks for reporting this! 
This was my fault - I didn't realise that the item filter was meant to be comparing strings, and swapped it out for a strict equality check. I'll fix it in a bit.

**Comment by mount2010** [comment]
fixed
