### ISSUE TITLE
🐛 Bug Report: My friend get a pet

### ISSUE THREAD

**Issue by NikitasDiscor** [DiscordDungeons/Bugs#1142]
### 👟 Reproduction steps

My friend got a pet when he had level 2. 

### 👍 Expected behavior

It should be okay. 

### 👎 Actual Behavior

In fact, my friend was very good at the pet level. The friend had level 2.

### 🎲 DRPG version

4.17.4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by FelixArgyle** [comment]
@NikitasDiscor Hi, could you post your friend's Discord User ID
If unsure on how to obtain a User ID, follow [Here](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)

**Comment by NikitasDiscor** [comment]
> @NikitasDiscor Привет, не могли бы вы опубликовать идентификатор пользователя Discord вашего друга. Если вы не знаете, как получить идентификатор пользователя, следуйте [здесь](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)

ID - 628564082185994240

**Comment by Sven65** [comment]
Unable to gather more info, closing the issue.
