### ISSUE TITLE
🐛 Bug Report: Level Up Multiple Times Through Sides

### ISSUE THREAD

**Issue by Coziestest** [DiscordDungeons/Bugs#1143]
### 👟 Reproduction steps

Level up through sides.

### 👍 Expected behavior

Level up only once.

### 👎 Actual Behavior

Leveled up four times.

11/26:
![ss+(2021-11-26+at+12 02 50)](https://user-images.githubusercontent.com/19909188/143626818-fe5929c1-f9fe-4ee7-bef4-8559b00c5645.png)
11/27:
![ss+(2021-11-27+at+01 07 08)](https://user-images.githubusercontent.com/19909188/143675261-3e515ba9-740c-41b4-bb91-489c76c3a642.png)

### 🎲 DRPG version

4.16.18

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

A similar mention in issue #410 
(total experience required still remains the same)
The "Gained 1 levels" phrase doesn't meet subject-verb agreement, but that's a minor issue.

**Comment by Weebs666** [comment]
I suspect that this and 1144 are the same issue. As I have just experienced 1144, see attached.
![error](https://user-images.githubusercontent.com/94192849/143681662-f3309105-f9a0-44df-9126-35821a291b1e.jpg)

And then 1143, again see attached. 
![after_sides](https://user-images.githubusercontent.com/94192849/143681675-cb5dcaf8-d2b7-40b3-bfb2-64986407cd65.jpg)

**Comment by Willard21** [comment]
Should be fixed with #1144
