### ISSUE TITLE
🐛 Bug Report: I got enough xp to level up, but didn't level up

### ISSUE THREAD

**Issue by pogchimp1** [DiscordDungeons/Bugs#1144]
### 👟 Reproduction steps

You have to first reach enough xp to get to the next level![Screenshot 2021-11-27 5 38 33 AM](https://user-images.githubusercontent.com/95126672/143677867-cc8e8c04-2c41-4017-9ef9-943e8a0a5200.png) Then you just don't level up.

### 👍 Expected behavior

make you level up

### 👎 Actual Behavior

did not level up, and ended with me getting 
![Screenshot 2021-11-27 5 38 33 AM](https://user-images.githubusercontent.com/95126672/143677943-590186fb-0102-49cd-942e-0da59d61b35f.png)
this

### 🎲 DRPG version

4.16.18

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Hi, I'll be pushing a patch fixing this tomorrow
