### ISSUE TITLE
🐛 Bug Report: Trap Bug

### ISSUE THREAD

**Issue by Shark3y** [DiscordDungeons/Bugs#1145]
### 👟 Reproduction steps

When I attempt to set a trap I receive the following message
You have a legacy Bear Trap set almost 52 years ago. You'll need to check it before buying a trap field.
I have no trap set.

### 👍 Expected behavior

It should inform me that a trap has been successfully set.

### 👎 Actual Behavior

It actually blocks any trap from being set.

### 🎲 DRPG version

4.16.18

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Mackan is aware of the bug as it is one that was supposed to have been resolved.

**Comment by Sven65** [comment]
This happens due to the `lastTrap` key being set to `-1` in the users data.

**Comment by Sven65** [comment]
This has been fixed.
