### ISSUE TITLE
🐛 Bug Report: #!invval throws errors

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#1146]
### 👟 Reproduction steps

Type #!invval

### 👍 Expected behavior

It should show me the value of my inventory.

### 👎 Actual Behavior

It says
```js
TypeError: Cannot read properties of undefined (reading 'cost')
    at Object.entries.reduce.itemCount (/bin/src/Commands/Commands/User/Invval.ts:43:13)
    at Array.reduce (<anonymous>)
    at Invval.execute (/bin/src/Commands/Commands/User/Invval.ts:32:67)
```

### 🎲 DRPG version

4.17.6

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Seems to happen to everyone, including me.

**Comment by FelixArgyle** [comment]
https://github.com/DiscordDungeons/Bugs/issues/1134 apparently mount "fixed" it?
🤔 it not actually fixed then @mount2010 ? mackan has updated the bot to do other fixes so veri srange

**Comment by Willard21** [comment]
I just checked his fix. It appears he didn't actually test it (tsk tsk).
`Cannot read properties of undefined (reading 'cost')` means it was doing `undefined.cost`.
![image](https://user-images.githubusercontent.com/24826881/143789444-57f40a9b-b6e3-4671-a666-67446dbed05b.png)
was his change. In this case, `item` is clearly the undefined value, but the change is still accessing a property of it before checking `item`'s existence. The proper fix would be `if (item?.cost > 0) {`

The reason `item` is undefined in the first place is because I have 10 `""` and 1 `null` in my inventory (according to the API). Neither of those are valid item IDs, so naturally they don't exist. It was another old player that pinged me about it, so it's possible new players don't have those in their inventory.

**Comment by mount2010** [comment]
![IMG_20211129_080820](https://user-images.githubusercontent.com/13136505/143791934-7827a5fe-a757-4dbf-9a7d-0ade705b3a3b.jpg)

I actually did test it, but I thought the issue was caused by an undefined cost. I would appreciate it if you didn't question if I did my work properly. Regardless, I didn't have access to the user's production data. Thanks for telling me the issue. I'll take a look at it when I can.

**Comment by Willard21** [comment]
Gotta reproduce the error before you can test if it's fixed. If it didn't throw errors before, and it doesn't throw errors after, then there's nothing to test. When I was active as a dev, Mackan always got onto me when I made mistakes too, usually in the form of him accusing me of not testing some random edge case lol. That's why I never miss an opportunity to point out his mistakes, especially when it's obvious he didn't test at all.

Don't take "you made a mistake" to be equivalent to "you didn't do your job properly." Software developers usually spend more time fixing mistakes than adding new features. It just comes with the job. Most mistakes are avoidable though, so there's always room for improvement. Denying you did anything wrong isn't how you improve. If I see an avoidable mistake, I'm going to point it out.

JS doesn't throw errors from accessing properties that don't exist, so for example `12 .potato` won't produce any errors. The only time TypeErrors are generated are when you do `undefined.property` or `null.property`. I know it's written in TS, but it runs in JS, so only JS rules apply at runtime.
```js
await fetch('https://api.discorddungeons.me/v3/user/400476562752929804', {
    headers: {
        'Authorization': 'API_KEY_HERE',
        'Content-Type': 'application/json'
    }
}).then(response => response.json())
```
You can throw this in the Chrome dev console on a random website to view people's production userdata in the future. You can request an API key from https://api.discorddungeons.me/dash/applications
