### ISSUE TITLE
🐛 Bug Report: Air,Fire, Earth & Water Keys not working

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1147]
### 👟 Reproduction steps

When I use any of the above key's, I have over 1000 chests. 

### 👍 Expected behavior

It should open the chest and tell me what is inside. 

### 👎 Actual Behavior

It does nothing no response from the Bot.
The key is still in my inventory. 

### 🎲 DRPG version

4.17.6

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

The cool down timer is working.

**Comment by mount2010** [comment]
There's two issues here. The first is that the key should be recognised and used, but we rewrote the code for usable items a while ago and Mackan forgot to reimplement the key type. The second is that the bot should respond with something like "Sorry, mount2010, you can't use that item" if an item (for example most items in the type dummy) can't be used.
