### ISSUE TITLE
🐛 Bug Report: CheckStatus says there's 6,400 shards

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#1148]
### 👟 Reproduction steps

#!checkstatus in the main server

### 👍 Expected behavior

I was expecting it to say 80 shards were online.

### 👎 Actual Behavior

It said all 6,400 shards were online.
![image](https://user-images.githubusercontent.com/24826881/143810487-0ee214b7-442b-437c-9d4b-71629d1d4ae4.png)

### 🎲 DRPG version

4.17.6

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

I'm not sure if it says there's 6400 shards because there's 6400 shards, or if it's being broadcast to all shards multiple times. I assume the latter since we'd be ratelimited before it finished booting up if it tried to log in that many times.

**Comment by Sven65** [comment]
This is fixed.
