### ISSUE TITLE
🐛 Bug Report: I can't use bear traps

### ISSUE THREAD

**Issue by TheJustK** [DiscordDungeons/Bugs#1150]
### 👟 Reproduction steps

When I try to use the bear trap from my inventory it doesn't work. I did #!buytrapspot but it keeps on saying "there is no trap spot"
even though that place is available for traps. Please help me fix this bug. 

### 👍 Expected behavior

It should place a trap spot and trap animals normally. 

### 👎 Actual Behavior

![Screenshot (289)](https://user-images.githubusercontent.com/95165800/144702643-aff3f605-c9e1-4e23-af0d-deac071b60f9.png)
![Screenshot (290)](https://user-images.githubusercontent.com/95165800/144702647-24b32568-b1d2-4e30-8572-ada16054e5f9.png)
![Screenshot (292)](https://user-images.githubusercontent.com/95165800/144744852-959f760c-4872-48a2-8ce9-1e5d354eea06.png)

 
Sadly it doesn't work. I have a trap spot, I am at a place where you can trap but it doesn't work....

### 🎲 DRPG version

I am not sure

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Please help me, I wanna craft something after using the trap and getting some materials...

**Comment by Sven65** [comment]
As you can see in the first screenshot, the bot replies with "There's no trap spot here" when you try to buy it in Silverkeep. This is because Silverkeep doesn't have a trap spot available for purchase.

As you don't own a trap spot there you can't set a trap at the location.

**Comment by TheJustK** [comment]
> As you can see in the first screenshot, the bot replies with "There's no trap spot here" when you try to buy it in Silverkeep. This is because Silverkeep doesn't have a trap spot available for purchase.
> 
> As you don't own a trap spot there you can't set a trap at the location.

May I ask where are trap spots located?

**Comment by Sven65** [comment]
According to previous guides, it should be available in silverkeep, so I'll be re-opening this bug.
At the moment, there are none in the starter areas that will work for buying due to this bug, we'll get it fixed for the next release.

Once this is fixed, you should be able to find them in silverkeep and copperfall to name a few.

**Comment by mount2010** [comment]
@Sven65 The reason for this bug is because buytrapspot hasn't been updated to use the "fields are trap spots" paradigm. Should I make the check for an owned trap spot a check for an owned field instead? Perhaps we should remove buytrapspot entirely, and use buyfield for this purpose?
