### ISSUE TITLE
🐛 Bug Report: Disabled quests are not disabled

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1156]
### 👟 Reproduction steps

You are able to get disabled quests i.e try starting Spooktober Spectacle

### 👍 Expected behavior

For the quest to not appear with the npcs since they are "disabled"

### 👎 Actual Behavior

You can start disabled quests.

### 🎲 DRPG version

 4.17.7

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

I think majority of checks for stuff is real broken (same goes with locations, i.e altars with "mining" this got fixed btw) so pls go through all and test them all out to make sure they _work_

**Comment by Sven65** [comment]
Fixed with the beta.
