### ISSUE TITLE
🐛 Bug Report: Quests do not work  "A Small Task" and "Meditative Magic"

### ISSUE THREAD

**Issue by NTMone** [DiscordDungeons/Bugs#1157]
### 👟 Reproduction steps

I tried to do both quests ( "A Small Task" from NPC Nadia and "Meditative Magic" from NPC Rune Guru) but if I talk to Rune Guru it does not start and the other quest can not be finished because last step "talk to Nadia" there is no reaction.
I am above the Level requirement for both quest's and there is no info about a needed item to talk to Rune Guru.

### 👍 Expected behavior

I have literally no clue.

### 👎 Actual Behavior

![DC dugeon asmalltask](https://user-images.githubusercontent.com/96319181/146617030-bb07375c-354d-41c2-ae54-bd96f8f2656b.JPG)

### 🎲 DRPG version

DRPG Version 4.17.7

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Before I started "a small Task" Quest I was accept a Task from NPC Alex (craft 3 empty vial and giv them to nadia -> could not finish it too). NPC Nadia just says "hello there."

**Comment by mount2010** [comment]
Issue is with talk logic. Because we currently have changes planned for talk this will probably be fixed in beta in order to not fix this twice.

**Comment by Shadow79851** [comment]
It has been a month and i cannot do it

**Comment by mount2010** [comment]
I've just finished the reorganisation of quests. This should be fixed when that is released (hopefully soon). It does need some testing since it's new.

**Comment by Sven65** [comment]
This has been fixed.
