### ISSUE TITLE
🐛 Bug Report: NPC Peter is bugged

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1158]
### 👟 Reproduction steps

#!talk peter  (in Sanctum of Serenity)

### 👍 Expected behavior

for peter to respond with the rune capacity upgrade thingy

### 👎 Actual Behavior

peter borked

### 🎲 DRPG version

4.17.9 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

rip peter ;-;

**Comment by CaptainLifeless** [comment]
Ive got the Problem too, when I try to use #!talk peter, nothing happens

**Comment by mount2010** [comment]
Hi,

I made a fix for this, but we are now working on porting DiscordRPG to slash commands. I will need to fix it in that version as well.
Please be patient!

**Comment by Sven65** [comment]
Is the fix still relevant @mount2010?

**Comment by mount2010** [comment]
This issue still exists AFAIK @Sven65
