### ISSUE TITLE
Show Unlocked Items at Level Up

### ISSUE THREAD

**Issue by angelolz1** [DiscordDungeons/Bugs#116]
You know how you need to be a certain level to use something? Why not show that item when you reach that level? 

Let's say for example, I reached level 10.
So it would look like:
"Angelolz Leve​led up! They've been awarded wi​th ​5​ att​ribute poin​ts, and, along with their max HP in​creasing by 50, they've been fu​lly healed!

They have unlocked:
+ Cookie
+ Apple
+ Golden Hammer
+ Empty Vial
+ Water Vial
+ Plank
+ String"

...and the other level 5 items.

I think it would be great to know what new items are available to you now c:

**Comment by toastyonyt** [comment]
I think you should have added the "enhancement" tag. This isn't really a bug in the bot, since it's not added.

**Comment by angelolz1** [comment]
I typed this on mobile, so I didn't know how to add an enhancement tag. Sorry D:
