### ISSUE TITLE
🐛 Bug Report: typeError?

### ISSUE THREAD

**Issue by hoa-xinh** [DiscordDungeons/Bugs#1161]
### 👟 Reproduction steps

I just arrived at Murkwell Mine and do mining as usual 

### 👍 Expected behavior

That it should give me something from mining

### 👎 Actual Behavior

The error pops up, it said type error but I don’t really understand 
![C3AF76A9-4463-4F30-8126-F73CC7D7B3A2](https://user-images.githubusercontent.com/31380940/147937864-1d89f4f0-9af1-4867-8e93-47aa782eed6e.jpeg)

### 🎲 DRPG version

4.17.9

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Willard21** [comment]
After reviewing the code, my conclusion is that you had a pickaxe equipped that didn't exist. Did you just recently enchant it at Theodora before this happened? If IPC was down and the items failed to update globally, but you got a new pickaxe ID that didn't previously exist, then that would explain this error. If this was the case, it would resolve itself after a restart.

**Comment by Sven65** [comment]
No more info provided, issue is fixed, closing.
