### ISSUE TITLE
🐛 Bug Report:Weapon bug

### ISSUE THREAD

**Issue by hoa-xinh** [DiscordDungeons/Bugs#1162]
### 👟 Reproduction steps

I was just upgrading my weapon at Urist
Nothing weird happen during the convo, 
But after I finished the upgrade and received my weapon back I seem to be having a same one?
In this situation is another Blue ceremonial card SRR+24

### 👍 Expected behavior

Got my weapon back normally 

### 👎 Actual Behavior

![F5E1AE36-1B33-450B-B572-DE2F08599D16](https://user-images.githubusercontent.com/31380940/147938810-5f9801cc-d301-4c1c-9335-da05fa8ee64b.png)
Nothing special happened during my chat with Urist

### 🎲 DRPG version

4.17.9

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by hoa-xinh** [comment]
![43CF9038-FBBF-4D50-B83B-8D6CAC250813](https://user-images.githubusercontent.com/31380940/147939626-dda5a6a9-4f4c-47ef-8508-7ceafbd3e1d0.jpeg)
It worked normally too
Not a inventory bug

**Comment by FelixArgyle** [comment]
Already reported, #1153 (just include all info you have in that report 👍
