### ISSUE TITLE
🐛 Bug Report: Jade not adding to skill gain on Elemental Air Shears

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1163]
### 👟 Reproduction steps

Just crafted a set of Elemental Air Shears. 
Added a Jade, had 2 failures, 

### 👍 Expected behavior

#!item Elemental Air Shears 2SJ should report a Skill XP Bonus +32 

### 👎 Actual Behavior

it actually reports a Skill XP Bonus +30

### 🎲 DRPG version

4.17.9

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Weebs666** [comment]
Update I checked after the reboot on 6th Jan and there was no change.
However on the 10th Jan I put in another Jade and it is now correctly reporting +34

**Comment by Sven65** [comment]
Looks like it's fixed. If not, re-open the issue.
