### ISSUE TITLE
inconsistency with "search" results

### ISSUE THREAD

**Issue by lewboehm** [DiscordDungeons/Bugs#1165]
Not really a bug just an inconsistency.  When you forage or fish etc the result comes back saying for example "Bodog went foraging..."  when you perform the "search" command it comes back with "You searched"  When there are multiple players searching at once the results can be hard to interpret.

**Comment by Sven65** [comment]
The search command features the username of the player executing the action at the end, i.e. `You search the location, {username}...`.

I'll close the issue, but if further discussion is wanted, feel free to re-open.
