### ISSUE TITLE
Uhm, did we break the bot?

### ISSUE THREAD

**Issue by Jonzka** [DiscordDungeons/Bugs#117]
So, in a discord server, the bot glitched out and now every command is twice, so whenever you type +adv or just any command, it is duplicated and it the adventure actually continues on both boxes, if you try to sell something you get twice the amount etc, the server is called 9GAG and we need help fixing this.

**Comment by Jonzka** [comment]
it is fixed now, somehow

**Comment by Sven65** [comment]
It restarted.
