### ISSUE TITLE
🐛 Bug Report: incorrect message for low pet level

### ISSUE THREAD

**Issue by mount2010** [DiscordDungeons/Bugs#1172]
### 👟 Reproduction steps

- Try something like pset display with a low pet level

### 👍 Expected behavior

It tells you your pet's level is low

### 👎 Actual Behavior

It tells you *your* level is low

### 🎲 DRPG version

4.17.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
This has been fixed through the deprecation of the method that sends the message.
