### ISSUE TITLE
💡 Feature Request: Add inventorySort/invSort to gset

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1174]
### Is your feature request related to a problem?

It's always a pain when doing a ginv and not having the inventory listed as I can when I do an inv.
Would it be possible to get the following added to gset?

inventorySort/invSort
- Amount Ascending/Descending
- itemName Ascending/Descending
- itemType Ascending/Descending
- itemLevel Ascending/Descending

### Describe alternatives you've considered

There isn't any other than manually sorting the list in a vi session.

**Comment by FelixArgyle** [comment]
https://github.com/DiscordDungeons/Bugs/discussions/958  // already suggested time ago
in future feature/ideas go at https://github.com/DiscordDungeons/Bugs/discussions
