### ISSUE TITLE
Trap Check🐛 Bug Report: 

### ISSUE THREAD

**Issue by echagen22** [DiscordDungeons/Bugs#1177]
I think I had a trap set before but when I typed in trap info, it said there is none. Then I bought a trapspot, when I am setting a trap, there is already a trap set. Then I entered trap check, the error message is written below.
```js
TypeError: Cannot read properties of undefined (reading 'id')
    at Trap._checkTrap (/bin/src/Commands/Commands/Sides/Trap.ts:196:53)
    at Trap.execute (/bin/src/Commands/Commands/Sides/Trap.ts:342:16) 
```

**Comment by Sven65** [comment]
This has been fixed in the beta.
