### ISSUE TITLE
🐛 Bug Report: Crafting nova dagger but did not recieve dagger

### ISSUE THREAD

**Issue by vVvGurkvVv** [DiscordDungeons/Bugs#1180]
### 👟 Reproduction steps

Attempted to craft a nova dagger

### 👍 Expected behavior

Materials should be removed from inventory and nova dagger should be added to inventory.

### 👎 Actual Behavior

Materials are removed from inventory and nova dagger is not added to inventory.
![Screenshot (11)](https://user-images.githubusercontent.com/98835811/155866301-8360be38-05ea-412e-8987-b0b444185294.png)
![Screenshot (12)](https://user-images.githubusercontent.com/98835811/155866304-210ed84e-83bf-47b4-adc2-d4b54621e367.png)
![Screenshot (13)](https://user-images.githubusercontent.com/98835811/155866308-39acd864-2808-4e0a-9004-b6bb8019fb9c.png)
![Screenshot (14)](https://user-images.githubusercontent.com/98835811/155866312-f0c29a05-a820-4491-ab69-319e26411e84.png)
![Screenshot (15)](https://user-images.githubusercontent.com/98835811/155866317-b5cfd937-134f-4898-91b1-94ae0c9b9f41.png)

### 🎲 DRPG version

4.17.13

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed in beta.
