### ISSUE TITLE
🐛 Bug Report: Adding Socket Iron Fishing Rod

### ISSUE THREAD

**Issue by echagen22** [DiscordDungeons/Bugs#1181]
### 👟 Reproduction steps

Talk to Urist and successfully added a socket.

### 👍 Expected behavior

Receives an Iron Fishing Rod 1S.

### 👎 Actual Behavior

I don't receive any and even the original item is gone. The cost of adding socket also deducted in my gold.

### 🎲 DRPG version

4.17.3

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by FelixArgyle** [comment]
Going to close the issue and just refer it to #1181 since it's linked to how items are being updated (meta item wise)
