### ISSUE TITLE
🐛 Bug Report: did not recieve dungeon rewards

### ISSUE THREAD

**Issue by vVvGurkvVv** [DiscordDungeons/Bugs#1182]
### 👟 Reproduction steps

When I exited the dungeon.

### 👍 Expected behavior

Should recieve items, experience, and gold.

### 👎 Actual Behavior

Did not recieve any rewards.
![Screenshot_20220228-164037_Discord](https://user-images.githubusercontent.com/98835811/156063928-9680fa8d-ea8a-4350-94e1-414fcb784361.jpg)
![Screenshot_20220228-164049_Discord](https://user-images.githubusercontent.com/98835811/156063947-4c2f96eb-4c36-4ef4-bab2-b495a480ec2a.jpg)
![Screenshot_20220228-164103_Discord](https://user-images.githubusercontent.com/98835811/156063956-50cbe2ad-e7cd-4271-8c27-46b39e0c073b.jpg)

### 🎲 DRPG version

4.17.13

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed in beta.
