### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by cooleagle666** [DiscordDungeons/Bugs#1183]
### 👟 Reproduction steps

I talked to illyena after defeating yeti

### 👍 Expected behavior

Quest would end and I would get a quest point and some gold and xp

### 👎 Actual Behavior

It errored out. 
![Screenshot_20220301-122833_Discord](https://user-images.githubusercontent.com/100715012/156218760-1ca0c86f-b54c-42af-a663-0fd42ef306de.jpg)
![Screenshot_20220301-122839_Discord](https://user-images.githubusercontent.com/100715012/156218765-703f3b53-e3f5-4924-85ff-9c2fcb7e06ca.jpg)

### 🎲 DRPG version

4.17.13

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
This has been solved now.
