### ISSUE TITLE
🐛 Bug Report: crafting errored 

### ISSUE THREAD

**Issue by cooleagle666** [DiscordDungeons/Bugs#1185]
### 👟 Reproduction steps

When doing the land above quest, I was crafting the 2 guages needed and it errored out

### 👍 Expected behavior

2 guages to be crafted

### 👎 Actual Behavior

The system errored out and didn't not craft the items
![Screenshot_20220301-183152_Discord](https://user-images.githubusercontent.com/100715012/156266534-d96a2fa6-3dfd-4c7f-9590-94802824d157.jpg)
![Screenshot_20220301-183200_Discord](https://user-images.githubusercontent.com/100715012/156266537-304f7cd7-4ac8-4eb6-95d5-0342d5991c05.jpg)

### 🎲 DRPG version

4.17.13

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by FelixArgyle** [comment]
Already reported #1180  tho issue isn't specific to the reported things, it's database not allowing update for data as Mackan has mentioned.
@Sven65 wanna just close all issues that have the error but just keep the initial created issue?
