### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by lewboehm** [DiscordDungeons/Bugs#1187]
### 👟 Reproduction steps

I sold a bunch of stuff
Went to urist
Unequipped my light longbow or mourning whigh was +6 with one socket
I asked urist for a second socket which worked
I asked urist for a level increase and it worked
I went to re-equip the weapon and it was gone

### 👍 Expected behavior

I expected my newly improved weapon to be equipped 

### 👎 Actual Behavior

My weapon vanished from my inventory’s 

### 🎲 DRPG version

4.17.13

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed in beta.
