### ISSUE TITLE
Bug: #!uset invSort itemType leads to error

### ISSUE THREAD

**Issue by BuoYancYdabl** [DiscordDungeons/Bugs#1190]
### 👟 Reproduction steps

use #!uset invSort itemType

### 👍 Expected behavior

Sort items in inventry by type

### 👎 Actual Behavior

Throws error.

### 💥 Error message

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at Uset.execute (/bin/src/Commands/Commands/User/Uset.ts:346:15)

### 🎲 DRPG version

4.17.20

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

#!uset inventorySort itemType leads to the same error.

**Comment by FelixArgyle** [comment]
You need to provide "ascending" or "descending", tho if you fail to put those it should have a message saying that instead of throwing an error

**Comment by BuoYancYdabl** [comment]
> You need to provide "ascending" or "descending", tho if you fail to put those it should have a message saying that instead of throwing an error

it seems function doesnt have error catcher. Also using #!uset invSort without arguments or with wrong ones leads to error

**Comment by Sven65** [comment]
Confirmed to also happen in beta

**Comment by Sven65** [comment]
Fixed in beta.
