### ISSUE TITLE
🐛 Bug Report: [BETA] /buy with negative amount

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1193]
### 👟 Reproduction steps

/buy name: Health Potion amount: -1

### 👍 Expected behavior

it should not buy any health potions

### 👎 Actual Behavior

buys health potion for negative gold
![image](https://felix.is-a-good-waifu.com/34QCvn7.png)

### 🎲 DRPG version

Version 4.18.1-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
