### ISSUE TITLE
🐛 Bug Report: [BETA] /inv filter is broken

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1197]
### 👟 Reproduction steps

/inv filter:type:helm
doesn't work

### 👍 Expected behavior

it should filter your inv to show types matching helm

### 👎 Actual Behavior

doesn't work, it just shows your inventory with no filter applied

### 🎲 DRPG version

v4.18.1-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
