### ISSUE TITLE
🐛 Bug Report: [BETA] /use doesn't work for some item types

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1198]
### 👟 Reproduction steps

/use item:
doesn't seem to work for some item types

Runes
Armor (Helm, Boots, Chest)
Necklace
Keys, fire, water, air, earth (for chests)

### 👍 Expected behavior

For all usable items to be allowed in /use

### 👎 Actual Behavior

use doesn't allow all usable items

### 🎲 DRPG version

v4.18.1-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
