### ISSUE TITLE
🐛 Bug Report: [BETA] Tutorial inconsistent with /buy prototype

### ISSUE THREAD

**Issue by Ciborn** [DiscordDungeons/Bugs#1199]
### 👟 Reproduction steps

Go through the starter tutorial and read the instructions.

### 👍 Expected behavior

The first parameter of `buy` should be named `item`, or the tutorial should tell us to use `/buy name:pickaxe amount:1` instead of `/buy item:pickaxe amount:1`.

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/17595049/165148309-36cb51c8-6a23-421e-8698-88fce1b6fbce.png)

### 🎲 DRPG version

4.18.0-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

`/use` uses item as its item name parameter name, which makes it inconsistent with `/buy` as is.

**Comment by Sven65** [comment]
Fixed
