### ISSUE TITLE
🐛 Bug Report: [BETA] "Interaction failed" if attempting to click on someone else's pager jump page button

### ISSUE THREAD

**Issue by mount2010** [DiscordDungeons/Bugs#1200]
### 👟 Reproduction steps

- click on someone else's pager jump page button (middle button)

### 👍 Expected behavior

ephermal message saying it's not your pager

### 👎 Actual Behavior

notice "interaction failed"

### 🎲 DRPG version

4.18.1-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
