### ISSUE TITLE
🐛 Bug Report: [BETA] - market doesn't say something is untradable if limit is 0 gold

### ISSUE THREAD

**Issue by mount2010** [DiscordDungeons/Bugs#1201]
### 👟 Reproduction steps

try to trade something that has market limit of 0 gold

### 👍 Expected behavior

should say that it is untradable

### 👎 Actual Behavior

says market limit is 0 gold

### 🎲 DRPG version

4.18.1-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
