### ISSUE TITLE
🐛 Bug Report: [BETA] Plant set no worky

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1205]
### 👟 Reproduction steps

goto a field that is empty and use /plant set item:whatever seed

### 👍 Expected behavior

for it to plant a seed in that location (if it's a field + empty + owned
)

### 👎 Actual Behavior

it says you have a plant set there already
![screenshot](https://felix.is-a-good-waifu.com/6CWnw3x.png)

### 🎲 DRPG version

v4.18.2-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed.
