### ISSUE TITLE
🐛 Bug Report: [BETA] Pet Heal

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1207]
### 👟 Reproduction steps

/pet set option:healitem value:(put a potion you do not have)

/pet heal

### 👍 Expected behavior

For it to check that you have the item you are trying to heal with

### 👎 Actual Behavior

it can use any potion without owning the potion
![image](https://felix.is-a-good-waifu.com/4ExBbno.png)

### 🎲 DRPG version

v4.18.2-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed.
