### ISSUE TITLE
🐛 Bug Report: [BETA] achievement stats /s stats

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1208]
### 👟 Reproduction steps

/s stats

### 👍 Expected behavior

For

> + locationsVisited: 0 Items
> + npcInteractions: 0 Items
> + fieldsOwned: 0 Items

to not have "items", since none of those are item related 

### 👎 Actual Behavior

3 stats have items listed on them,

> + locationsVisited: 0 Items
> + npcInteractions: 0 Items
> + fieldsOwned: 0 Items

### 🎲 DRPG version

v4.18.2-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
