### ISSUE TITLE
🐛 Bug Report: [BETA] Brew

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1209]
### 👟 Reproduction steps

/brew
add no items
start brew

### 👍 Expected behavior

For it to say you must enter atleast 1 item to brew something @user 

### 👎 Actual Behavior

you can brew with 0 items

### 🎲 DRPG version

v4.18.2-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed.
