### ISSUE TITLE
🐛 Bug Report: [BETA] G perms set

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1210]
### 👟 Reproduction steps

/g permissions set permissions: +DEPOSIT_GOLD user: @Crusch Karsten (felix69)

### 👍 Expected behavior

For it to run checks on if user has permission to set permissions

### 👎 Actual Behavior

users can set permissions without actually having permissions, so anyone can just join a guild and set themselves to deposit etc

### 🎲 DRPG version

v4.18.2-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by FelixArgyle** [comment]
> Hello! Why is my github account being mentioned in these emails? I haven't used it in ages. Thanks - Chelsea
That's my fault, sorry. I just copy pasted a message from the input which included the @ (with your username)

**Comment by Sven65** [comment]
Fixed.
