### ISSUE TITLE
🐛 Bug Report: [BETA] NPC Selection

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1211]
### 👟 Reproduction steps

/talk npc: Urist the Blacksmith

Make sure to have atleast 2 pages of items that you can select from

Goto second page and try to select an item, you can't select any option that is on that page.

### 👍 Expected behavior

For it to allow selection for other pages

### 👎 Actual Behavior

Doesn't show selection for other pages

EDITED;; seem like selections work but it's showing the wrong pages for each input i can't explain well just test it pls

### 🎲 DRPG version

v4.18.2-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed.
