### ISSUE TITLE
🐛 Bug Report: [BETA] Menu expire spam?

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1212]
### 👟 Reproduction steps

get any menu, like i did with npc
/talk npc: Urist the Blacksmith
(interaction failed so i couldn't do a single thing)
_it did it around 3-4 times on different talk interactions_

### 👍 Expected behavior

idk if possible but if you talk to another npc can it locate the past interaction and just "cancel/stop" it?
if we have people experiencing interaction failed on things and goto run the same command again and get more till it finally works they just gonna experience a barrage of spam of menu expires

maybe just make the time shorter for it to expire if 0 interaction is being done? if interaction is done on a part reset the expire time? idk im not a dev ;-;

### 👎 Actual Behavior

SPAM
![spam](https://felix.is-a-good-waifu.com/4vDvUAn.png)

### 🎲 DRPG version

v4.18.2-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

this'll just be bad if it happens frequently for users... being barraged by spam like that due to failed interactions :(

**Comment by Sven65** [comment]
This issue has to do with the fact that Discord only sends us information about an expired interaction once a player uses *any* interaction. When they do this, we get the information about **all** expired interactions for a user, which in turn runs our expiration handlers.

Solving this requires more research, cc @mount2010

**Comment by Sven65** [comment]
Turns out that it's not a limitation of Discord, but rather with slash-create. I've talked with @Snazzah about it, but there's no plans on adding an option where we can handle the expirations one-by-one at the moment.

**Comment by Sven65** [comment]
Fixed.
