### ISSUE TITLE
🐛 Bug Report: [BETA] Lead command

### ISSUE THREAD

**Issue by hoa-xinh** [DiscordDungeons/Bugs#1214]
### 👟 Reproduction steps

I tried /lead field:(well idk why but on my device it showed up like twice after the bug then the third time it doesn’t show up any field that I could choose so I type lux)
so /lead field:lux
but it still show up the error below

### 👍 Expected behavior

leaderboard 

### 👎 Actual Behavior

error

### 💥 Error message

```
TypeError: Cannot read properties of undefined (reading 'toString')
    at formatNumber (/bin/src/Util/Extenders.ts:50:69)
    at LeadCommand.run (/bin/src/SlashCommands/Commands/General/Lead.ts:254:87)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:663:28)
```

### 🎲 DRPG version

v4.18.2-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed.
