### ISSUE TITLE
🐛 Bug Report: [BETA] Trap set not setting in the location you are

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1215]
### 👟 Reproduction steps

(have 0 traps set)

travel to copperfall 

/trap set item:bear trap

### 👍 Expected behavior

For the trap set to be put in your current location (that has a field)

### 👎 Actual Behavior

It seems to set the trap at silverkeep (it overwrites the trap set at silverkeep too it seems)

This trap was set in silverkeep
![trap set in silverkeep ](https://felix.is-a-good-waifu.com/2Fk3XqH.png) 

This trap was set in copperfall but seems to have set in silverkeep
![trap set in coperrfall](https://felix.is-a-good-waifu.com/7DVG9ko.png)

### 🎲 DRPG version

v4.18.3-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
