### ISSUE TITLE
🐛 Bug Report: [BETA] Plant not setting at correct location

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1216]
### 👟 Reproduction steps

(have 0 plantset)

travel to copperfall

/plant set item:wheat seed

### 👍 Expected behavior

For the plant set to be put in your current location (that has a field)

### 👎 Actual Behavior

It seems to set the plant at silverkeep (it overwrites the plant set at silverkeep too it seems)

me checking plant at copperfall
![copperfall check](https://felix.is-a-good-waifu.com/63o97Hj.png)

me setting olive at copperfall
![set plant](https://felix.is-a-good-waifu.com/A7rRDdD.png)

### 🎲 DRPG version

v4.18.3-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed

**Comment by FelixArgyle** [comment]
this is not fixed

**Comment by Sven65** [comment]
It wasn't fixed, but it is now. Will be released with the next beta update.
