### ISSUE TITLE
🐛 Bug Report: [BETA] uset nick /s profile not updating nickname

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1217]
### 👟 Reproduction steps

/uset set variable: nick value: 3
(it should have automatically changed it here)

+ it should change when you run stats
/s profile

### 👍 Expected behavior

For nickname to update by the bot with the current uset nick option

### 👎 Actual Behavior

nickname doesn't get updated

### 🎲 DRPG version

v4.18.3-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
