### ISSUE TITLE
🐛 Bug Report: [BETA] setting display color shows as decimal value

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1218]
### 👟 Reproduction steps

/uset set variable: displayColor value: baff00

outputs the change as decimal value

### 👍 Expected behavior

for it to show the hex code instead of decimal value

### 👎 Actual Behavior

shows decimal value 

### 🎲 DRPG version

v4.18.3-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
