### ISSUE TITLE
🐛 Bug Report: [BETA] Dungeon 

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1219]
### 👟 Reproduction steps

Find mob
Click ✅ Button
You can move (it doesn't lock you into the fight)

### 👍 Expected behavior

When you click the ✅ button when fighting a mob it should lock you in having to fight the mob, you shouldn't be allowed to continue to move or interact with buttons until you kill the mob

### 👎 Actual Behavior

When Click ✅ Button
You can move (it doesn't lock you into the fight)

### 🎲 DRPG version

v4.18.3-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
