### ISSUE TITLE
Foraging...

### ISSUE THREAD

**Issue by DavidThePro21** [DiscordDungeons/Bugs#122]
```Markdown
#=When I foraged with the command, it didn't say what I did.=#

![screen shot 2017-02-08 at 3 07 37 d](https://cloud.githubusercontent.com/assets/24858477/22761613/6233ca04-ee10-11e6-8e1f-023e7649506c.png)

**Comment by Sven65** [comment]
Strange. How do I reproduce it?

**Comment by Rosenkreuz12** [comment]
it probably one of those times where discord error and doesn't show the reply message while the command is actually done and he actually get something. happens quite a bit if you don't have reliable connection

**Comment by Sven65** [comment]
Unable to reproduce, most likely a ratelimit issue.
