### ISSUE TITLE
🐛 Bug Report: [BETA] Dungeon RED BUTTON

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1220]
### 👟 Reproduction steps

/dungeon start

RED BUTTON DOES NOTHING?

### 👍 Expected behavior

idk what the red button is meant to do?
is it meant to disable your current dungeon map block

### 👎 Actual Behavior

red button does nothing at all it's always disabled

### 🎲 DRPG version

v4.18.3-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed.
