### ISSUE TITLE
🐛 Bug Report: [BETA] Stuck in dungeon

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1222]
### 👟 Reproduction steps

IDK HOW TO REPRODUCE....
seem like you can get stuck in an active dungeon map block, it's been a good like 20+ hours since I been stuck now

### 👍 Expected behavior

Being able to /dungeon resume without being stuck!!!

### 👎 Actual Behavior

Your stuck in an active dungeon map block (infinitely without it ever expiring)

### 🎲 DRPG version

v4.18.3-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Dev note: most likely something to do with the redis key for the active map block not expiring

**Comment by Sven65** [comment]
Issue was with redis keys not expiring properly, which is now fixed.

Fixed.

**Comment by FelixArgyle** [comment]
Seems to not be fixed
msg link to it [link[(https://discord.com/channels/172382467385196544/891988245955637328/972088682326659072)

> I move a couple times
then it stop move
now I cant exit
- Lonk

**Comment by Sven65** [comment]
Is this still an issue?

**Comment by Sven65** [comment]
Closing this as no new information has been provided.
