### ISSUE TITLE
🐛 Bug Report: [BETA] Market banned users can use x

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1225]
### 👟 Reproduction steps

Makret banned users can use the following commands whilst market banned,

m list
m view
m info
m cancel

### 👍 Expected behavior

for them not to be able to use any of those market features.

### 👎 Actual Behavior

they are able to use several market features with an active market ban.

### 🎲 DRPG version

v4.18.4-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mount2010** [comment]
This is carried over from the production bot where market banned users can also use those commands.
It's up to @Sven65 if he wants to block market banned users from using these commands.

**Comment by Sven65** [comment]
We need to discuss this with the game moderators before moving forward with a decision.

**Comment by Sven65** [comment]
We've had a discussion and concluded that market banned users should be able to view the market, but not interact with it. As such, I'm closing this issue.
