### ISSUE TITLE
🐛 Bug Report: [BETA] MOD set market limit

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1227]
### 👟 Reproduction steps

/mod
set market limit
health potion
gmmax:50

### 👍 Expected behavior

for gmmax to be a valid type like it is in the main bot?

### 👎 Actual Behavior

gmmax type is "invalid

![gmmax](https://felix.is-a-good-waifu.com/7xoREVx.png)

### 🎲 DRPG version

v4.18.4-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
