### ISSUE TITLE
🐛 Bug Report: /search command doesn’t found anything 

### ISSUE THREAD

**Issue by hoa-xinh** [DiscordDungeons/Bugs#1228]
### 👟 Reproduction steps

I was doing the cold north quest and after talking to the npc and received a quest that require to use the /search command, it didn’t find anything 

### 👍 Expected behavior

found the yeti hair

### 👎 Actual Behavior

nothing found 

### 🎲 DRPG version

v4.18.4-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by FelixArgyle** [comment]
Just tested without already having yeti hair and it works normally 👍
[Link to me testing](https://discord.com/channels/172382467385196544/891988222056468510/970358702982959114)
