### ISSUE TITLE
🐛 Bug Report: [BETA] QUEST Meditative Magic

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1231]
### 👟 Reproduction steps

start meditative magic quest and get to the step that is
```
!====[Crusch Karsten (felix69)'s conversation]====!
Rune Guru - You must start by going to the peak of Copperfall and meeting with the monk who lives there among the cold. Only he can teach you to find peace within yourself.
!=================================================!
```
clicking ok button does nothing

### 👍 Expected behavior

for quest to proceed after clicking ok button

### 👎 Actual Behavior

ok button does nothing

### 🎲 DRPG version

v4.18.4-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed by the same fix as #1230
