### ISSUE TITLE
🐛 Bug Report: [BETA] QUEST Menu Special (membership)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1233]
### 👟 Reproduction steps

Get to step
Quest Updated - Make a hamburger!
and you can't proceed :(

### 👍 Expected behavior

for you to be able to proceed past the make a hamburger step

### 👎 Actual Behavior

you can't proceed past the make a hamburger step

### 🎲 DRPG version

v4.18.4-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
