### ISSUE TITLE
🐛 Bug Report: [BETA] Some interaction buttons fail first time but works fine second time

### ISSUE THREAD

**Issue by RagingLink** [DiscordDungeons/Bugs#1235]
### 👟 Reproduction steps

```
/party create

/party view
```
![image](https://user-images.githubusercontent.com/15198000/166523447-e761a865-1ed6-4b06-8f3d-88f4e9a7bd66.png)

and then `/party view` again and attempt to **Disband party**.

### 👍 Expected behavior

For it to work first time.

### 👎 Actual Behavior

I have to execute the command two times for it work.

### 🎲 DRPG version

4.18.3-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

This also occurs when using other commands, but I can't really reproduce any of those anymore. It seems like it occurs whenever some data is not initialized when executing a command like **Disband party** in `/party view` the first time.

**Comment by RagingLink** [comment]
Felix mentioned it might be related to the discord failing sometimes, but it's really weird how this only happens when you first use it after a while. 

Here a video of what occurs (last 10 seconds can be ignored)

https://user-images.githubusercontent.com/15198000/166566453-f4b4affd-f631-48c1-b7e9-926bec19949c.mp4

**Comment by Sven65** [comment]
I'm unable to reproduce this from the information given. If you're able to give more examples of how to reproduce, please add them.

**Comment by Sven65** [comment]
More info has not been provided. Please re-open issue if it's still relevant.
