### ISSUE TITLE
🐛 Bug Report: [BETA] Can't open multiple chests

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1236]
### 👟 Reproduction steps

Have 5 chests and do
/use item:fire key quantity:5

### 👍 Expected behavior

For it to allow you to open 5 chests (if user has 5 chests) using the amount of keys provided

### 👎 Actual Behavior

Doesn't allow to open multiple chests in one /use

### 🎲 DRPG version

v4.18.4-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Main bot does allow for multiple, checked over [Message Link](https://discord.com/channels/172382467385196544/331585104185131008/963288821334704178)

**Comment by Sven65** [comment]
Fixed
