### ISSUE TITLE
🐛 Bug Report: [BETA] Checking user Inv

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1239]
### 👟 Reproduction steps

/inv view user: Felix Argyle
(make sure you are not me :D)

### 👍 Expected behavior

Allow so checking other users inventory works

### 👎 Actual Behavior

Returns your own inventory upon checking another users

### 🎲 DRPG version

v4.18.4-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
