### ISSUE TITLE
BOT - Cooldown message reformat needed (low importance)

### ISSUE THREAD

**Issue by RDardelet** [DiscordDungeons/Bugs#124]
In some cases the bot sends cooldown messages that say:
**You are too tired to do that, <player_name> (0 seconds).**

It would be nice to have the bot say **1 second** and **>1 second**

Like I said in the title, it's low importance, but I think it does not require much addition in code.

**Comment by TheConceptionist** [comment]
I think that this error has to do more with the user executing a command within 0.49 seconds of the cooldown ending, and the bot rounds down to zero. I'm sure there's a workaround for this, but it's not at the top of our priority list.

**Comment by PlayTheFallen** [comment]
@TheConceptionist 
For reference - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/ceil

**Comment by Willard21** [comment]
I'm gonna reopen this since Mackan suggested it would be fixed eventually, which means it needs an open issue.
![image](https://user-images.githubusercontent.com/24826881/65697804-32208980-e041-11e9-8e92-2189cf970732.png)

**Comment by Sven65** [comment]
Will look at this.
