### ISSUE TITLE
🐛 Bug Report: Itemdisplay variable is invalid

### ISSUE THREAD

**Issue by Sh3nme1** [DiscordDungeons/Bugs#1243]
### 👟 Reproduction steps

I tried changing my itemdisplay from 2 to 1, but it didn't work and kept saying that the variable is invalid

![Screenshot 2022-06-29 103631](https://user-images.githubusercontent.com/108388749/176368350-5c46f72e-0086-4f97-bc88-3cf2de267eec.jpg)

![Screenshot 2022-06-29 103720](https://user-images.githubusercontent.com/108388749/176368386-1c64f5e0-4f89-4326-a0b4-15a6e6f59263.jpg)

### 👍 Expected behavior

I searched their website and copied the same variable but it still says that it's invalid
![Screenshot 2022-06-29 103720](https://user-images.githubusercontent.com/108388749/176368537-cf7e8f02-2b01-4c29-97aa-166c961c98ae.jpg)

### 👎 Actual Behavior

![Screenshot 2022-06-29 103936](https://user-images.githubusercontent.com/108388749/176368729-d9d3a4f3-04f1-45e3-853e-e9b81335c1f8.jpg)
![Screenshot 2022-06-29 103946](https://user-images.githubusercontent.com/108388749/176368746-15b9cc46-4240-4855-86e6-f447e9052817.jpg)

### 💥 Error message

none

### 🎲 DRPG version

 4.17.20

### 👀 Have you spent some time to check if this issue has been raised before?

- [ ] I checked and didn't find similar issue

### 📝 Additional context

I even tried typing in "itemDisplay" "ItemDisplay" "Itemdisplay" but it didn't work either

**Comment by FelixArgyle** [comment]
Itemdisplay seems to have been removed for a while, the default had been changed to show items in embed form.
Wiki needs to have the info updated,  suggest running in-game command `#!help command-name` to see if stuff matches.
