### ISSUE TITLE
🐛 Bug Report: Old users Adv Error (pet related)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1245]
### 👟 Reproduction steps

find user that is too old that `#!started` doesn't work for them and hasn't played since then.
#!adv
error

### 👍 Expected behavior

idk honestly... maybe something replaced with the error message telling user to run stats which should just fix any broken data of theirs?

### 👎 Actual Behavior

errors with error below

### 💥 Error message

```js
TypeError: Cannot read properties of undefined (reading 'disabled')
    at Adv.execute (/bin/src/Commands/Commands/Adventure/Adventure.ts:402:21)
```
   

### 🎲 DRPG version

4.17.21 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

likely happens in beta too so just push a change to beta in prep for slash.

**Comment by AenonThePro** [comment]
Hi it might be an item issue but did mack put your data there to like inv stuff or no since i also have the same error but its kida different and mack says its an item issue
![image](https://user-images.githubusercontent.com/109204065/178890892-7f47d800-9387-4143-a87c-ebcb97c1571c.png)

![image](https://user-images.githubusercontent.com/109204065/178890829-5898896a-c5c1-4f26-b902-1dfe1c6b9228.png)

**Comment by FelixArgyle** [comment]
> Hi it might be an item issue but did mack put your data there to like inv stuff or no since i also have the same error but its kida different and mack says its an item issue ![image](https://user-images.githubusercontent.com/109204065/178890892-7f47d800-9387-4143-a87c-ebcb97c1571c.png)
> 
> ![image](https://user-images.githubusercontent.com/109204065/178890829-5898896a-c5c1-4f26-b902-1dfe1c6b9228.png)

nope, it a complete different issue. (error is different) // this issue isn't for the "beta bot" instance, it's the main bot.

**Comment by Sven65** [comment]
Is this still an issue?

**Comment by mount2010** [comment]
@Sven65 Seems easy enough to test if it's still a problem

**Comment by Sven65** [comment]
The related code no longer exists on the same lines. Please re-open issue and update if it still occurs.
