### ISSUE TITLE
🐛 Bug Report: Adventure (The application did not respond)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1247]
### 👟 Reproduction steps

/adv

### 👍 Expected behavior

For you to be able to adventure.

### 👎 Actual Behavior

Adventure no work and displays "The application did not respond"

### 🎲 DRPG version

4.18.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

discords fault 😠

**Comment by mount2010** [comment]
related to #1244

**Comment by Sven65** [comment]
Closing as the issue exists. #1244
