### ISSUE TITLE
🐛 Bug Report: Guild Ad! stole me monies

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1249]
### 👟 Reproduction steps

/g info
try really really really hard to click send ad then send ad again!

### 👍 Expected behavior

for it to send ad (with gold being taken)

### 👎 Actual Behavior

my gold got stolen 😢 and ad did not send

https://discord.com/channels/172382467385196544/172388244007288832/1010664234809561241 - 7,281,083,833
https://discord.com/channels/172382467385196544/172388244007288832/1010664699743973458 - 7,276,493,270 
https://discord.com/channels/172382467385196544/172388244007288832/1010665002472050739 - 7,271,902,707 

Interaction fails stuff

### 🎲 DRPG version

4.18.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by FelixArgyle** [comment]
Doesn't appear to be fixed
[I clicked Send Ad here](https://discord.com/channels/172382467385196544/172388244007288832/1047598880956633159)
[Gold gone after I clicked it](https://discord.com/channels/172382467385196544/172388244007288832/1047599008006279288)
- No ad is being sent to `260363601158733825`

_I'm manually putting my ad there because yes...  If others do want their ads put then I'll do so too_

**Comment by Sven65** [comment]
Is this still an issue?
