### ISSUE TITLE
🐛 Bug Report: Ulrist false negative

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1250]
### 👟 Reproduction steps

When I talk to UIrist to put a socket in my Elemental Eclipse Fishing Rod. 
I navigate all of the drop downs and it takes me to the final bit 
+ Urist the Blacksmith - That's gonna cost you 300,000 gold and has a 80% chance of working. You okay with that?
+ 1 - Do it.
+ 2 - On second thought...

I choose "Do it." and the Bot responds with "This interaction failed" but when I look in my inv I see
Elemental Eclipse Fishing Rod 1S

### 👍 Expected behavior

It should work

### 👎 Actual Behavior

It reports it failed when it actually worked

### 🎲 DRPG version

4.18.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mount2010** [comment]
"This interaction failed" just means the bot didn't respond in time due to the ongoing high latency.
We're aware of the issue and working on it. Please be patient.
