### ISSUE TITLE
🐛 Bug Report: Talking to Ulrist is buggy

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1251]
### 👟 Reproduction steps

When I try and talk to Ulrist

### 👍 Expected behavior

It should enable to talk drop downs

### 👎 Actual Behavior

About 70% of the time I get "This interaction failed"

### 🎲 DRPG version

4.18.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mount2010** [comment]
This applies to all commands. We're aware of the high latency/non-response issues and are working on it.
