### ISSUE TITLE
🐛 Bug Report: DM Info is wrong [MARKET]

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1256]
### 👟 Reproduction steps

Have someone sell/buy from your trade

### 👍 Expected behavior

for the total amount bought so far to be the actual total amount.
i.e
Trade l6xk6ww2 updated. (Speeding Jolteon#6843 bought a Compass)
4 out of 25 items have been sold so far for a total of 20,000 gold

### 👎 Actual Behavior

It just shows the total amount your trade has up
i.e my trade has 25 compasses for sale at 5k per

every sale happening says "
 Trade l6xk6ww2 updated. (Speeding Jolteon#6843 bought a Compass)
**25 items have been sold so far for a total of AMOUNT gold**

![bug](https://felix.is-a-good-waifu.com/2PmxwBT.png)

### 🎲 DRPG version

4.18.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mount2010** [comment]
Yeah, my bad. fixing
