### ISSUE TITLE
🐛 Bug Report: inv value error

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1257]
### 👟 Reproduction steps

/inv value

### 👍 Expected behavior

for it to show the value of user inv

### 👎 Actual Behavior

errors

### 💥 Error message

```
TypeError: Cannot read properties of undefined (reading 'user')
    at InventoryCommand.run (/bin/src/SlashCommands/Commands/User/Inventory.ts:209:49)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:670:28)
```

### 🎲 DRPG version

v4.18.11

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mount2010** [comment]
Looks like we forgot to include the user argument in the slash command. Not sure why it doesn't just default to the user calling the command but I'll fix that

**Comment by mount2010** [comment]
Nvm, we're trying to query /inv view arguments before the commands are separated into view and value

**Comment by mount2010** [comment]
pr made
