### ISSUE TITLE
🐛 Bug Report: plant command does not work

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1258]
### 👟 Reproduction steps

/plant 

### 👍 Expected behavior

should bring back information about what plant's I have etc etc

### 👎 Actual Behavior

Reports: - the DiscordRPG API seems down, please retry later.

### 🎲 DRPG version

4.18.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Trap command works it just seems to be plant

**Comment by FelixArgyle** [comment]
That Aldebaran#0362you were trying with not the DiscordRPG#0366 bot. API is up and running for Discord Dungeons so best to bug report with the Aldebaran `/bugreport`
