### ISSUE TITLE
Double response from the bot

### ISSUE THREAD

**Issue by SirVoice** [DiscordDungeons/Bugs#126]
Every time I input a command I get a double response from the bot, looks like for every command. It is not visual, I get double XP and items from each activity.
I don't know how to reproduce it but I do know this might be Discord sided bug. I have double message bug happen to myself and other people, where you write one line and it duplicates it.
P.S. Having 500/500 XP doesn't level the character, need to be 1 XP over it.

**Comment by Rosenkreuz12** [comment]
nah the one happened yesterday seems to only happen on a certain shard and few ppl, since it double each and every commands done on the shard

**Comment by Sven65** [comment]
Two shards had double processes.
