### ISSUE TITLE
🐛 Bug Report: Global Market list's completed trades

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1265]
### 👟 Reproduction steps

When I run a /m list offers market:Buying Trades or /m list offers market:Selling Trades

### 👍 Expected behavior

It should only list the offers which are applicable

### 👎 Actual Behavior

It list's offers which have been completed... 

For example 
┃≻ 600 Fir Logs (800G each) {ID. L0ocrpv9} [600 sold]
┃≻ 300 Willow Logs (800G each) {ID. L0ocgdor} [300 sold]
┃≻ 300 Fir Logs (800G each) {ID. L0obxzyr} [300 sold]

Or
≺┃ 1 Iron Sword (99G each) {ID. kwq1aqs6} [1 bought]

### 🎲 DRPG version

4.18.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Willard21** [comment]
Trades are supposed to immediately be stopped when they're fully completed. Last time a similar bug happened, it was because we were accidentally storing the amounts as strings instead of integers in the database (the only type error ever to reach production back when it was in JS :pensive:)

**Comment by Sven65** [comment]
@mount2010 please look into this
