### ISSUE TITLE
🐛 Bug Report: Traps are broken AGAINE

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1268]
### 👟 Reproduction steps

Set a trap in any location 
check trap in that location
try set new trap in that location

Guess... the last time data for traps and stuff happened to be messed up is the same exact reason why it's messed up for the slash update?

### 👍 Expected behavior

for users to be able to set traps after checking them in a location

### 👎 Actual Behavior

the entire trap feature is unusable - you can get 1 single use per location then your locked from setting a trap in that location forever yay!. 

### 🎲 DRPG version

4.18.12

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

likely plant too since... lazy to check...  they work the same so they likely are broken. 

I tested if traps were broken on my alt after a user mentioned about their issue with setting traps in [support](https://discord.com/channels/172382467385196544/1022982131732992060/1022982131732992060)

**Comment by FelixArgyle** [comment]
_Entire feature is broken..._ 
could we possibly get this fixed asap? 
people want to use the feature but they cannot.

It's bad for me to tell people to just 'wait' or even say 'it's being looked into' when it isn't, a response would be good to give within a week of an initial bug report since no response just seem like no one cares :( 

I know that there are more important things to be done / what you do in your own time, but feel it would be good to give just a response in the support post(s) /or here.

-- added tag for bugs in support so it would be easier for you to find issues to give some response back
-- @mount2010 @Sven65

**Comment by joewhi86** [comment]
No issues with planting, just traps.

Joseph Whitehouse used /trap info
DiscordRPG BOT — Today at 2:19 PM
=== Traps ===
-Silverkeep:      Empty
-Rivermouth:      Empty
-Copperfall:      Empty
-Redhorn:         Empty
-Lemontree Plaza: Empty
=============

Joseph Whitehouse used /trap set
DiscordRPG BOT — Today at 2:19 PM
You already have a trap set, Joseph Whitehouse.

Joseph Whitehouse used /trap check
DiscordRPG BOT — Today at 2:20 PM
You don't have a trap set here, Joseph Whitehouse.

![2022-10-01_142121](https://user-images.githubusercontent.com/78335017/193425166-a8fc1293-6287-43f8-b475-a9a28a4f53db.png)

**Comment by mount2010** [comment]
I have looked into this. The issue is that it thinks that you have a legacy trap (if it were a non-legacy trap it would say "you already have a trap set **here**"). It thinks you have a legacy trap because `userData.trap.time` is set to -1 for some reason. I'll take a look at why that is the case.

**Comment by joewhi86** [comment]
Oh awesome! Thank you so much!

**Comment by mount2010** [comment]
Fixed for next release

**Comment by joewhi86** [comment]
Great! Thank you so much!!! Nice work!
