### ISSUE TITLE
🐛 Bug Report: Donated gold gives achievement to donator instead of receptient

### ISSUE THREAD

**Issue by mount2010** [DiscordDungeons/Bugs#1270]
### 👟 Reproduction steps

- Donate 1 million gold to a user who does not have the millionaire achievement

### 👍 Expected behavior

Give the receptient the millionaire achievement

### 👎 Actual Behavior

Gives the donator the millionaire receptient

### 🎲 DRPG version

4.18.19

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mount2010** [comment]
@Ciborn Do you want to work on this issue?

**Comment by Ciborn** [comment]
@mount2010 Sure!
