### ISSUE TITLE
🐛 Bug Report: /sell command's categories have buy command's description 

### ISSUE THREAD

**Issue by Prospy006** [DiscordDungeons/Bugs#1272]
### 👟 Reproduction steps

When I type "/sell name:" or "/sell name:something value:", the description after I type that is copied from the buy command.

### 👍 Expected behavior

It's just too annoying for me... And a few others noticed it too. So it'd be amazing if you'd fix it.

### 👎 Actual Behavior

Sry I'm in my phone, i cannot close this webpage and it'll all have to be typed again.

But it works on any device, so ig you can try it for urself =)

### 🎲 DRPG version

(latest version on 28-10-2022)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mount2010** [comment]
literally unplayable
