### ISSUE TITLE
🐛 Bug Report: Talk command failed

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1273]
### 👟 Reproduction steps

When I tried to talk to Alex in Lemontree Plazza

### 👍 Expected behavior

It should provide task details

### 👎 Actual Behavior

It errored

### 💥 Error message

Error: getaddrinfo EAI_AGAIN discord.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)

### 🎲 DRPG version

4.18.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Weebs666** [comment]
May or may not be related but I am also seeing a lot of "The application did not respond" error messages at the same time

**Comment by Sven65** [comment]
Error occurs due to issues connecting to discord and fixes itself.
