### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by IndigoIceCream** [DiscordDungeons/Bugs#1275]
### 👟 Reproduction steps

Just want to be clear, I reset my profile after this: I did /sell salt (I was trying to sell my 2 rocksalt I had just mined) and it said "sold 2 salt for 2 gold". So I was like "How? I have no salt in my inventory.. right?" So I do /inv view ... no salt...So I did /sell salt , and even though I had none, it said "sold 1 salt for 1 gold". Now I'm super confused, so I try it with another item. Sure enough I can sell it even though I do not have the item. (See image, I show me doing a command of selling items I do not have.)
![image](https://user-images.githubusercontent.com/103970165/199867617-04bb86c6-8696-4e99-9741-9c9b0acfa091.png)

### 👍 Expected behavior

You should not be able to sell items you do not have

### 👎 Actual Behavior

You can sell infinite of any item with /sell [item] [amount]

### 🎲 DRPG version

 4.18.21

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

N/A

**Comment by Sven65** [comment]
Fixed.
