### ISSUE TITLE
🐛 Bug Report: Urist [Weapon Upgrade] Broken

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1277]
### 👟 Reproduction steps

Travel to redhorn and try and upgrade a weapon via NPC Urist
You cannot select a weapon  (there is no selection drop down / button)

### 👍 Expected behavior

For there to be a drop down selection or button

### 👎 Actual Behavior

You cannot select a weapon  (there is no selection drop down / button)

### 🎲 DRPG version

4.18.22

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Can this please get fixed and pushed as a hotfix (since it is rather a large feature that helps users out with progression with better weapon damage)

_assigned you mackan since you can push updates_

**Comment by mount2010** [comment]
Will take a look at this

**Comment by mount2010** [comment]
@FelixArgyle can you check if Theodora is also broken, if so I know exactly what this issue is - it's probably to do with IUP changes

**Comment by FelixArgyle** [comment]
Yup, theodora also broken 
(was just checking other npcs to make sure they not broke, i.e felix, mathilda *they work fine*) idk what other npcs have selectors but best to just check for all maybe.

**Comment by mount2010** [comment]
Fixed in PR
