### ISSUE TITLE
🐛 Bug Report: Trap space at Aquaerin Isle

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1278]
### 👟 Reproduction steps

When I do a location command at Aquaerin Isle.

### 👍 Expected behavior

It should not offer me to "Buy Trap Spot"

### 👎 Actual Behavior

It should does offer me to "Buy Trap Spot"

### 🎲 DRPG version

4.18.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Not a bug.

**Comment by Weebs666** [comment]
If this is not a bug could you please confirm the following.

I can buy a spot and thus have 15 trap spot's and not be banned for cheating / taking advantage of code issues.

**Comment by Sven65** [comment]
The code says that the location should have a trap spot, and thusly you won't get banned. However, I'd appreciate things that say it shouldn't have the spot to be pointed out and provided, if possible

**Comment by Weebs666** [comment]
Thanks for the confirmation. 

Might need to get the map updated then, https://imgur.com/84srKD2 
Also I can't ever recollect anyone saying was a trap location at Aquaerin Isle. 

I wonder where else there is I'm harvesting tomorrow or Sunday so I will check the Kingdom's and locations and get back to you if I find any discrepancies.  

Happy Poets day, Slàinte Mhath
