### ISSUE TITLE
🐛 Bug Report: "this interaction failed" allowed me to have 11 Market Slots in use and get a weapon for free

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1279]
### 👟 Reproduction steps

I put a Spear of Indra up for sale on the Global Market. 
When I clicked on OK the bot responded "this interaction failed" so I clicked on OK again and once again got "this interaction failed"

Imagine my surprise when I checked my listing and there was 2 distinct offers on the market.

This was despite having only 1 spear and I now have 11 market slot's rather than the 10 I am allowed as a member

### 👍 Expected behavior

This should not happen

### 👎 Actual Behavior

This actually happened

### 🎲 DRPG version

4.18.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

≻ 1 Iron Flail (186G each) {ID. Laewohif} [0 sold]
┃≻ 1 Sharpened Sickle (3,876G each) {ID. Laewq7iv} [0 sold]
┃≻ 1 Spear of Indra (500,000G each) {ID. Laj88u0n} [0 sold]
┃≻ 19 Iron Maces (126G each) {ID. Laewnox9} [0 sold]
┃≻ 5 Nova Daggers (55,000G each) {ID. Laewusvc} [0 sold]
┃≻ 1 Damp Trident (5,626G each) {ID. Laewr874} [0 sold]
┃≻ 1 Conjurer's Foresight (35,936G each) {ID. Laewtq8f} [0 sold]
┃≻ 1 Golden Small Dagger (2,750,000G each) {ID. Laewwnjm} [0 sold]
┃≻ 3 Magy's Scythes (8,876G each) {ID. Laews9pe} [0 sold]
┃≻ 1 Nova Energy Blade (650,000G each) {ID. Laewvp5i} [0 sold]
┃≻ 1 Spear of Indra (500,000G each) {ID. Laj88ozL} [0 sold]

I have cancelled both of the trade's Laj88ozL and Laj88u0n and now I have 2 spear's!

This would allow a player to get a large amount of weapons for free which they could then sell for free gold

**Comment by Sven65** [comment]
This has been fixed in beta.
