### ISSUE TITLE
Leveled up 3 times without getting the required exp

### ISSUE THREAD

**Issue by ABodaciousPeach** [DiscordDungeons/Bugs#128]
So, as the title explained, I leveled up 3 times without getting the required exp. I use a copy paste for all of the "basic commands" (#!mine, #!fish, etc). I got the exp from doing the jobs, but for a reason unknown to me, I got the level up text from the bot 3 times. 

![capture](https://cloud.githubusercontent.com/assets/26044366/23341874/cec1c1b0-fc1d-11e6-8785-4e56e4aeeab3.PNG)

I now have to get over 3000 exp to level up again. If you need to know, I got from level 10 to level 13.

**Comment by ABodaciousPeach** [comment]
Here's my stats page
![capture](https://cloud.githubusercontent.com/assets/26044366/23341893/38fad6de-fc1e-11e6-8a70-50c40eb64d8f.PNG)

**Comment by Sven65** [comment]
Did you have more than the required XP to level up before the issue?

**Comment by ABodaciousPeach** [comment]
I don't think I had more than the required exp to level up. As you can see from here: 

https://wiki.discorddungeons.me/commands/stats/experience

the wiki states I need 6240 exp to level up to level 13. As you can see from my previous stats shown, I have only 4505 exp.

**Comment by Sven65** [comment]
Do you have any images of your stats before the issue?

**Comment by fishporange** [comment]
mackan, this is a result of the multiple output issue i've reported via dm before

**Comment by ABodaciousPeach** [comment]
For my old stats, here you go!

![das](https://cloud.githubusercontent.com/assets/26044366/23406302/3cb761ce-fd8c-11e6-9bff-d1b2cc298061.PNG)

**Comment by Sven65** [comment]
Yeah, that's really strange.
I'm not even sure how I'd be able to reproduce it.

**Comment by Thaviel** [comment]
I reproduced this bug
![image](https://cloud.githubusercontent.com/assets/3307419/26005513/4af5afd4-3707-11e7-9863-ff0eeec3b5c7.png)

it looks to me like 2 commands are running while the state of the character is 1 exp from leveling

so you'd have your character at say 1exp from level up.
you then submit more then 1 command that gains you 1 exp at the time time.
the state of your character when the server is beginning to run the command is from leveling up.
then during running the command it can't see your character has already gained a level from another simultaneous process. 

a very annoying solution would be make the basic commands have a cooldown shared between them of like 1 second. that would really reduce the quality of everyone's life.
