### ISSUE TITLE
🐛 Bug Report: Urist Upgrading + Socket

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1280]
### 👟 Reproduction steps

/talk npc:Urist
Select either option Socket, or Upgrade weapon
Selecting an item does nothing it seems.

### 👍 Expected behavior

For upgrade to let me choose how much I want
To add a socket to the item. 

### 👎 Actual Behavior

Nothing happens after selecting an item.
![gem](https://felix.is-a-good-waifu.com/A6gP4wA.png)
![weapon upgrade](https://felix.is-a-good-waifu.com/6T48pcV.png)

### 🎲 DRPG version

4.18.23

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

My guess is that it's somehow silently failing the interaction? idk just a guess considering there is "interaction failed" + "application did not respond" for everything ;-;

**Comment by Sven65** [comment]
Occured due to interaction failures. It has been fixed in the beta.
