### ISSUE TITLE
💡 Feature Request: `/sell ... amount: 'all'`

### ISSUE THREAD

**Issue by ShadowGaming100** [DiscordDungeons/Bugs#1287]
### Is your feature request related to a problem?

I hate when I have to use more then one time the sell command

instead of /sell crabs all can do /sell crabs, freshwater fish ect amount:all

### Describe alternatives you've considered

There isn't any other than manually sorting the list in a vi session.

**Comment by sudojunior** [comment]
As it stands, the `amount` argument on `/sell` can only accept integers and providing a string would be inaccurate to what Discord intends to send over to the bot.

**Comment by Sven65** [comment]
This has been implemented.
