### ISSUE TITLE
🐛 Bug Report: spammed follow-up response

### ISSUE THREAD

**Issue by ShadowGaming100** [DiscordDungeons/Bugs#1289]
### 👟 Reproduction steps

Bot spamming everything time I reach in the destination or get achievement in dms

### 👍 Expected behavior

Is should only send one message 

### 👎 Actual Behavior

It is sending 5 messages of the same thing

### 🎲 DRPG version

4.18.27

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

![14468078-F474-4335-AD66-D8F844F45E35](https://user-images.githubusercontent.com/81495140/210496425-9cce3f27-14da-42d3-add8-da0279cc0d26.png)
![4A7FF560-D240-4365-9511-935810BEF5E7](https://user-images.githubusercontent.com/81495140/210496448-940e2b89-2ed7-4c29-91cf-84925f336222.png)

**Comment by sudojunior** [comment]
Current theory leads towards problems occurring with gateway sharding and interactions.
> A single _initial_ response is sent, but the determinant of `x`, with relation to active shards, and **follow-up** as many times as possible before the rate limit tokens are expended.

If this is the case, `slash-create` would not be aware of what shard it is on by itself, and also on the verge of / be running into rate limits on interaction responses without knowing it.

_As for why Discord wouldn't do the same for DM messages as they would for DM interactions, is beyond me for their continued incompetence. Reporting this as a bug to Discord probably doesn't matter unless it's been tried and tested **and** the bot or service you contribute to is significant enough for them to notice._

**Comment by sudojunior** [comment]
I have set the priority as High, but I was not able to confirm this myself.
![image](https://user-images.githubusercontent.com/8607699/210663848-15acef3e-9bee-4c43-9a06-d43b074509c2.png)

**Comment by ShadowGaming100** [comment]
https://media.discordapp.net/attachments/1057907264616407073/1060492639469838357/RPReplay_Final1672911465.mov

**Comment by ShadowGaming100** [comment]
If want i can try on alt account

**Comment by ShadowGaming100** [comment]
> Please do, as it'd help localize if the issue is only your account, or relates to all, which helps us with a fix.

After 2 travel it didn’t send message like my main account

**Comment by ShadowGaming100** [comment]
I don’t know if have do something with using slash commands for some days then starts to do that

**Comment by Sven65** [comment]
Internal: This is related to the RabbitMQ services, which handles the travel arrival queue

**Comment by Sven65** [comment]
Unsure at the moment. We'll have a look into it, as we're unsure if it's on the bot end or the service that handles the travel timers

**Comment by ShadowGaming100** [comment]
I don’t know if this will work to find the problem and I don’t know if this is even possible 

Transfer my data to an alt account/someone account and try it

**Comment by ShadowGaming100** [comment]
I tried it again bot is now sending 7 message same

**Comment by ShadowGaming100** [comment]
Not all on the same time

**Comment by Sven65** [comment]
This has been fixed in the beta.
