### ISSUE TITLE
Spelling Errors/Typos

### ISSUE THREAD

**Issue by FelixCATus** [DiscordDungeons/Bugs#129]
# Post them here.

### #!invval
FelixCATus has items ___at at___ a total cost value of gold and a total sell value of gold.
Double mistake.

### Cooldown message
You need to rest FelixCATus, (14 seconds)
Comma should be at _rest_.

You're too tired to do that FelixCATus (3 seconds)
Maybe add a comma at _that_ and a fullstop at username.

**Comment by BigBrainAFK** [comment]
You need to rest FelixCATus, (14 seconds)

The comma should be at rest AND a fullstop at the username

**Comment by HustlePuff** [comment]
the spelling of receive
![image](https://cloud.githubusercontent.com/assets/24603749/23605133/79406050-0296-11e7-99bc-21cf76b42ed0.png)

**Comment by Anthonyk747** [comment]
> Deathdealers747 sold a Iron Sword and got 25 gold.

It says I sold "a Iron Sword" - supposed to be "an Iron Sword".

**Comment by PlayTheFallen** [comment]
This is not a major bug, compared to the `#!lead` bug for example.

**This will not be on the top of the to-do list!**

**Comment by BigBrainAFK** [comment]
No shit this isn't game breaking but it's quick to fix in most cases like the whole a and an thing just needs a check of the first letter of the item and the others are probably hardcoded or in a language file

**Comment by nathanielcwm** [comment]
would love stuff like this to be fixed they aren't normally noticable unless like you're a grammar nazi or something or you just notice it but when you do you never feel the same way again

**Comment by Sven65** [comment]
Gonna close this, it's a megathread one, please post each one as a new issue if they're still there.
