### ISSUE TITLE
🐛 Bug Report: `amount` describes use of 'all' as an argument when it cannot be used.

### ISSUE THREAD

**Issue by sudojunior** [DiscordDungeons/Bugs#1290]
This has been opened in relation to #1287 with possibility of misguiding users as for what the argument can be used for.

The `amount` argument exists on **eight** with the only **one** below mentioning the use of the literal when it is not possible:
- [ ] `/buy`
- [ ] `/crack`
- [ ] `/craft`
- [x] `/drop`
- [ ] `/heal`
- [ ] `/m create buy`
- [ ] `/m create sell`
- [ ] `/m sell`
- [ ] `/pet heal`
- [ ] `/sell`

![image](https://user-images.githubusercontent.com/8607699/210665015-c9d0da68-1e02-4429-95ef-81773ab2bf29.png)

The implication of drop describing this logic would seem to have the intention of _omitting_ the argument entirely and then having the bot default to sell all that it can - but equally so that is a relatively dangerous operation to perform when the amount of items to sell / discard or otherwise handle is larger.

As described in https://github.com/DiscordDungeons/Bugs/issues/1287#issuecomment-1371514134, Discord won't accept logic to have duel-purpose argument types (or type unions as the devs would know it for using TypeScript).

**Comment by Sven65** [comment]
Already fixed
