### ISSUE TITLE
🐛 Bug Report: Mystic Gravestone [Quest]

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1291]
### 👟 Reproduction steps

Start the Mystic Gravestone quest

Up until trying to get through the 2nd interaction and replying with 

> 1 - Sure, just tell me what I have to do.

it does not let the user go pass that point.

### 👍 Expected behavior

For the quest to work the way it is intended.

### 👎 Actual Behavior

User gets stuck at the 2nd interaction

### 🎲 DRPG version

4.18.27

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by joewhi86** [comment]
Checking again one moment.

**Comment by joewhi86** [comment]
Yea still the same issue. Doesn't matter what I choose at the 2nd interaction, just thinks then stops without giving an error
![2023-01-08_210044](https://user-images.githubusercontent.com/78335017/211234646-8511e1b8-ac0a-46ec-926b-b7918a3f68ac.png)

**Comment by joewhi86** [comment]
Switch to #2 option and still no change----
![2023-01-08_210202](https://user-images.githubusercontent.com/78335017/211234715-fcf4a34a-70fe-491f-91ed-40f1757e5d34.png)

**Comment by joewhi86** [comment]
Just the 3 dots thinking then disappearing...
![2023-01-08_210253](https://user-images.githubusercontent.com/78335017/211234770-e9f808a8-2a4a-43da-bd19-3d928374c9ba.png)
