### ISSUE TITLE
🐛 Bug Report: Can fish in a location which has no sides

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1292]
### 👟 Reproduction steps

When I type fish in Moledin

### 👍 Expected behavior

It should say "You cannot fish here"

### 👎 Actual Behavior

It allows me to fish

### 🎲 DRPG version

4.18.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

I think it is also the case at Flamebay Island. 
I will go through the whole map over the course of the next week and sanity check.

**Comment by Willard21** [comment]
Can confirm, there's no code in /fish to check your location, unlike the other sides.
