### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by nahuelcorrea05** [DiscordDungeons/Bugs#1296]
### 👟 Reproduction steps

It happens on almost every command that have a query/buttons to interact, after two query/button i interact i get this "Interaction failed" error
![image](https://user-images.githubusercontent.com/104454382/230815888-bfadaed9-1483-484f-af17-d41cca14668d.png)

### 👍 Expected behavior

the button/query should work

### 👎 Actual Behavior

the button/query dont work

### 🎲 DRPG version

4.18.27

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

now im stuck on a dungeon i cannot leave
![image](https://user-images.githubusercontent.com/104454382/230815480-b60b578c-a256-433c-8e96-fee6302ea9c4.png)

**Comment by Sven65** [comment]
Should be fixed in beta. Leaving open since it's prod.

For now, please try /dungeon resume

**Comment by Sven65** [comment]
Closing as fixed in beta.
