### ISSUE TITLE
🐛 Bug Report: Travel timer does not send a message when it reaches 0.

### ISSUE THREAD

**Issue by Dx8pi** [DiscordDungeons/Bugs#1299]
### 👟 Reproduction steps

Travel somewhere. There is no message upon arrival.

### 👍 Expected behavior

It should send a message when you arrive at a location.

### 👎 Actual Behavior

Nothing happens. You arrive safely without issue, but there is no message to announce your arrival.

### 💥 Error message

No error.

### 🎲 DRPG version

4.18.28

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed in beta.
