### ISSUE TITLE
🐛 Bug Report: /talk doesn't suggest correctly

### ISSUE THREAD

**Issue by Dx8pi** [DiscordDungeons/Bugs#1300]
### 👟 Reproduction steps

Travel somewhere, do /talk to get the suggestions pop up.

### 👍 Expected behavior

It should suggest the correct NPC's for the location I'm in.

### 👎 Actual Behavior

It suggests NPC's form my previous location.

### 💥 Error message

No error.

### 🎲 DRPG version

4.18.28

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed in beta
