### ISSUE TITLE
🐛 Bug Report: Searching for specific achievements don't work

### ISSUE THREAD

**Issue by Dx8pi** [DiscordDungeons/Bugs#1305]
### 👟 Reproduction steps

/s achievements name:<any achiewvement that has I, II, III etc>

Even if you write the full name of the achievement, it'll still show you "found multiple, be more specific"

For example, doing "/s achievements name:Killimanjaro V" will say you have to write either Killimanjaro IV or V, which doesn't make sense, since I already wrote the full name of it, even for achievements where you're not """"missing"""" some characters, for example "Killimanjaro III" It'll still say it found multiple, I.e "Killimanjaro I, II, III and IV" even though I wrote more characters than exist in those names.

### 👍 Expected behavior

It should show the achievement when you've written the full name, or when there are no other options.

### 👎 Actual Behavior

It shows options for achievements when you write the full name of the achievement, even if you write more characters than the suggested name.

### 💥 Error message

No error.

### 🎲 DRPG version

4.18.28

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

I love u mackan mwah

**Comment by mount2010** [comment]
We can possibly fix this by only searching for the base achievement first (for example Killmanjaro). If there is a base achievement that matches, then split out the second part (I, II, III, etc) and get the subachievement.
