### ISSUE TITLE
🐛 Bug Report: Dungeon message doesn't update when moving onto stairs or chest

### ISSUE THREAD

**Issue by Dx8pi** [DiscordDungeons/Bugs#1308]
### 👟 Reproduction steps

Move onto a chest/stairs after reaching floor 2.

### 👍 Expected behavior

Update message and say I've landed on chest/stairs

### 👎 Actual Behavior

Does nothing to the message (but after clicking checkmark it updates and tells me I've interacted with the tile)

### 💥 Error message

No error

### 🎲 DRPG version

v4.18.33

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Edit: seems to happen at random, usually when you press buttons too quickly and it has to think. Never have had it happen when I go around on empty tiles I've already explored. I.e, when the bot has to update the least amount of text.

**Comment by Sven65** [comment]
Happens due to a mismatch with discord being late at sending us updates, and the bot not being able to process them fast enough. Won't fix.
