### ISSUE TITLE
🐛 Bug Report: Not always 4 chests in dungeon

### ISSUE THREAD

**Issue by Dx8pi** [DiscordDungeons/Bugs#1309]
### 👟 Reproduction steps

Enter dungeon and descend. Every now and then a floor will only have 3 chests, instead of 4.

### 👍 Expected behavior

Always have 4 chests.

### 👎 Actual Behavior

Sometimes only has 3.

### 💥 Error message

No error.

### 🎲 DRPG version

v4.18.33

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Not a bug. There's nothing that says a dungeon should always have 4 chests. That's the maximum a dungeon *can* have.
