### ISSUE TITLE
🐛 Bug Report: error on adv

### ISSUE THREAD

**Issue by Dx8pi** [DiscordDungeons/Bugs#1315]
### 👟 Reproduction steps

did /adv

### 👍 Expected behavior

show adventure

### 👎 Actual Behavior

throws error

### 💥 Error message

```
Error: getaddrinfo EAI_AGAIN wireguard-db-proxy-service.wireguard.svc.cluster.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
```

### 🎲 DRPG version

v4.18.34

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Only happened once, worked afterwards, felt like I should report either way though

**Comment by Sven65** [comment]
Wontfix: This an issue with the networking from Node.js. It fixes itself.
