### ISSUE TITLE
Character Reset

### ISSUE THREAD

**Issue by AngelOniiChan** [DiscordDungeons/Bugs#132]
When you reset Your Character with "#!reset" or "#!reset YES" If you attacked the Monster down to "17 HP" or something like that and reset your character The Monsters Keep the same amount of Health They did before the Reset.

**Comment by Sven65** [comment]
Known issue.

**Comment by MohoraFlorin** [comment]
Encountered once again, please fix.

**Comment by SamuiNe** [comment]
The current known workaround is to use `#!adv 1` or `#!adventure 1`, this should allow the monster to be replaced to the ones that is appropriate to your current level.
