### ISSUE TITLE
Buying Undefined

### ISSUE THREAD

**Issue by fake3h** [DiscordDungeons/Bugs#134]
when buying more than 2 guild tag in one command, the bot says "3h bought 2 undefined for 2000 gold..." Proof : https://cdn.discordapp.com/attachments/255337919143739392/286814403234365440/strawberry.png

**Comment by SamuiNe** [comment]
Can confirm

**Comment by Sven65** [comment]
Known issue, there's no plural for guild tag in the DB, will fix when I have time

**Comment by Sven65** [comment]
Fixed.
