### ISSUE TITLE
🐛 Bug Report: No images show in embeds

### ISSUE THREAD

**Issue by Dx8pi** [DiscordDungeons/Bugs#1342]
### 👟 Reproduction steps

do /location on any location in Illeria that is not Dsian's house, or look up an item that has an image related to it

### 👍 Expected behavior

Show the image

### 👎 Actual Behavior

No image

### 💥 Error message

No error

### 🎲 DRPG version

v4.18.35

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Turns out that this is caused by Discord itself (How surprising.).

See discord/discord-api-docs#6171 for more info.

**Comment by Sven65** [comment]
Confirmed as fixed.
