### ISSUE TITLE
🐛 Bug Report: error on sides

### ISSUE THREAD

**Issue by Dx8pi** [DiscordDungeons/Bugs#1345]
### 👟 Reproduction steps

usually when doing /mine

### 👍 Expected behavior

work

### 👎 Actual Behavior

doesn't

### 💥 Error message

```
Error: getaddrinfo EAI_AGAIN wireguard-db-proxy-service.wireguard.svc.cluster.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
```

### 🎲 DRPG version

v4.18.36

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

idk wireguard

**Comment by Sven65** [comment]
This issue is to do with DNS lookups in node.js. It fixes itself, nothing we can fix.
