### ISSUE TITLE
🐛 Bug Report: Dungeons don't generate

### ISSUE THREAD

**Issue by Dx8pi** [DiscordDungeons/Bugs#1348]
### 👟 Reproduction steps

travel to redhorn dungeon, start dungeon.

### 👍 Expected behavior

Generate dungeon

### 👎 Actual Behavior

Loads infinitely and eats the dungeon fee gold anyways.

### 🎲 DRPG version

v4.18.35

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

You can't resume either. So it takes the payment, and doesn't put you in the dungeon.

**Comment by Sven65** [comment]
Could not replicate. Restarted production and it works again.
