### ISSUE TITLE
🐛 Bug Report: Admin perms messed up

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1349]
### 👟 Reproduction steps

BE FELIX
Run admin 
See that you has no access to things you should have access to.

### 👍 Expected behavior

Give correct access perm

### 👎 Actual Behavior

Perms set wrong? 

### 🎲 DRPG version

4.18.36

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

ALSO PLS JUST ADD GIVEGOLD BUTTON TOO SINCE IT STUPID TO USE (EDIT USERDATA) TO GIVE GOLD????

**Comment by Sven65** [comment]
Fixed. Was an issue with configuration.
