### ISSUE TITLE
🐛 Bug Report: gold/item donation DM doesn't work

### ISSUE THREAD

**Issue by Dx8pi** [DiscordDungeons/Bugs#1357]
### 👟 Reproduction steps

Not sure. Even though I have both values set to "on", I don't get a DM when someone donates gold/items

### 👍 Expected behavior

Send DM

### 👎 Actual Behavior

Nothing happens

### 🎲 DRPG version

v.4.18.37

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by turbiepants** [comment]
Same goes for MarketDM. It did not send a DM when a sale was going on.

Screenshot of my marketDM is turned on:
![Discord_iEJKElYIbn](https://github.com/DiscordDungeons/Bugs/assets/43326333/473eeda7-0603-4154-b79a-ae469a7c5d48)

Version: 4.18.38
