### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by ArtoriasAbyssWalker** [DiscordDungeons/Bugs#1362]
### 👟 Reproduction steps

When i try to execute any command it gives me the error message attached 

### 👍 Expected behavior

N/A

### 👎 Actual Behavior

Error code 

### 💥 Error message

![19EDBF33-2250-44A7-BC5D-849EA44994A4](https://github.com/DiscordDungeons/Bugs/assets/32173974/20c0513b-ae4a-40b4-a142-5cd5f1834b98)

### 🎲 DRPG version

4.18.38

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
This has been fixed.
