### ISSUE TITLE
🐛 Bug Report:  Wrong cooldown timers

### ISSUE THREAD

**Issue by UniversalGamer** [DiscordDungeons/Bugs#1365]
### 👟 Reproduction steps

When the commands are used during the cool down timezone:
/adv
/fi
/fo
/mi
/ch
/sea

are used the cool down timer displayed is as follows;
/adv > 5 minutes
/fi -- /ch > 10 minutes
/sea > 15 minutes

### 👍 Expected behavior

/adv > 14s
/fi -- /ch > 5 minutes
/sea > 5 minutes

### 👎 Actual Behavior

Though the cool down timer states high times the execution is within the actual time frame

![Screenshot_2023-08-14 Discord - A New Way to Chat with Friends Communities(5)](https://github.com/DiscordDungeons/Bugs/assets/142229290/67308491-491d-4bb0-867d-209d61b3f0c2)
![Screenshot_2023-08-14 Discord - A New Way to Chat with Friends Communities(4)](https://github.com/DiscordDungeons/Bugs/assets/142229290/139c476b-2643-448a-ae50-770dae9bdaed)
![Screenshot_2023-08-14 Discord - A New Way to Chat with Friends Communities(3)](https://github.com/DiscordDungeons/Bugs/assets/142229290/116ab5fc-6572-44fb-9ba9-3fea309f558a)
![Screenshot_2023-08-14 Discord - A New Way to Chat with Friends Communities(2)](https://github.com/DiscordDungeons/Bugs/assets/142229290/02548d92-07ba-4192-87c3-ebfb674ac2e6)
![Screenshot_2023-08-14 Discord - A New Way to Chat with Friends Communities(1)](https://github.com/DiscordDungeons/Bugs/assets/142229290/d8911198-04b9-4cd4-b253-830d17551d30)
![Screenshot_2023-08-14 Discord - A New Way to Chat with Friends Communities](https://github.com/DiscordDungeons/Bugs/assets/142229290/4b57093c-203c-40eb-ba36-f07102c27691)

### 🎲 DRPG version

The live version on Discord as of 14-08-23

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Discord accessed through Firefox ver 78.150esr (64 bit)

Macbook Pro
Processor: 2.8 GHz Intel Core i7
Memory: 8 GB 1333 MHz DDR3

OS X El Capitan

**Comment by Sven65** [comment]
Can't replicate this issue.
