### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by UniversalGamer** [DiscordDungeons/Bugs#1368]
### 👟 Reproduction steps

typed in commands /adv, /fish, /forage, /mine, /chop and the following error appeared...

Error: getaddrinfo EAI_AGAIN wireguard-db-proxy-service.wireguard.svc.cluster.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)

### 👍 Expected behavior

The commands shouldwork

### 👎 Actual Behavior

error came up with ...

Error: getaddrinfo EAI_AGAIN wireguard-db-proxy-service.wireguard.svc.cluster.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)

### 💥 Error message

```
Error: getaddrinfo EAI_AGAIN wireguard-db-proxy-service.wireguard.svc.cluster.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
```

### 🎲 DRPG version

v4.18.44

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
This is an edge case, and we are working on the issue, however, it relates to an issue with the server host, and I will thus be closing this. Please refer to #status-updates on the official discord server.
