### ISSUE TITLE
🐛 Bug Report: DiscordRPG API  is down

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1369]
### 👟 Reproduction steps

When I use the Aldebaran trap or plant command

### 👍 Expected behavior

It should work and bring back the respective details

### 👎 Actual Behavior

It actually reports 

the DiscordRPG API seems down, please retry later.

### 🎲 DRPG version

4.18.41

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

I am aware that this might be an Aldebaran issue but I thought I would start at this end before going to them.

**Comment by Sven65** [comment]
The API is up. Aldebaran is a third party product, please contact _cib.
