### ISSUE TITLE
🐛 Bug Report: The application did not respond ( But with additional message from an application called Clyde )

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1376]
### 👟 Reproduction steps

When I do any command

### 👍 Expected behavior

It should run that command.

### 👎 Actual Behavior

The application did not respond
Only you can see this • Dismiss message
But also the following. 

Your message could not be delivered. This is usually because you don't share a server with the recipient or the recipient is only accepting direct messages from friends. You can see the full list of reasons here: https://support.discord.com/hc/en-gb/articles/360060145013

### 🎲 DRPG version

v4.18.48

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Last previously worked at 12th June 2024 02:25 BST.
Stopped working 12th June 2024 02:26 - 02:52
Now working 12th June 2024 05:10

**Comment by Sven65** [comment]
Issue with discord, not us.
