### ISSUE TITLE
Pet can take damage even when at 0HP

### ISSUE THREAD

**Issue by rhayward2** [DiscordDungeons/Bugs#138]
Pet can continue to take damage, even when at 0HP (Dead/Disabled)

Ex:
!​=====​=== [HaX^'s adven​ture] =====​===!
% Ro​lled a 4.
- Los​t 8 HP.
+ Dea​lt 11 HP Damage.
- Pet Rock to​ok 4 HP Da​mage.
**- Pet Rock h​as 0/50 HP l​eft**
+ HaX^ has 102/250 HP left.
+ The en​emy Ulgrth has 23/185 HP left.
!========================================!

.adv

!​=====​=== [HaX^'s adven​ture] =====​===!
% Ro​lled a 1.
- Los​t 10 HP.
+ Dea​lt 8 HP Damage.
- Pet Rock to​ok 5 HP Da​mage.
**- Pet Rock h​as 0/50 HP l​eft**
+ HaX^ has 92/250 HP left.
+ The en​emy Ulgrth has 15/185 HP left.
!========================================!

**Comment by lifelineiscancer** [comment]
this isn't a bug, it does this to everyone.

**Comment by Sven65** [comment]
Not a bug.
