### ISSUE TITLE
🐛 Bug Report: getaddrinfo

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1381]
### 👟 Reproduction steps

When I did an /adv, although it also happens with other commands

### 👍 Expected behavior

Do an /adv or the other command

### 👎 Actual Behavior

I got an error

### 💥 Error message

Error: getaddrinfo EAI_AGAIN discord.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)

### 🎲 DRPG version

4.18.49

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Weebs666** [comment]
Also seeing the following. 

Error: getaddrinfo EAI_AGAIN wireguard-db-proxy-service.wireguard.svc.cluster.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)

**Comment by Sven65** [comment]
Yeah this is an intermittent issue, no need to report it, it solves itself after a bit :)
