### ISSUE TITLE
Pet does not gain XP/level up even when pset xprate is set

### ISSUE THREAD

**Issue by rhayward2** [DiscordDungeons/Bugs#139]
My pet is not levelling up even when I set xprate to 10%.

**Comment by HustlePuff** [comment]
it should gain xp and wait for the pet to level up it takes time :)

**Comment by Sven65** [comment]
Does it gain XP? At the moment it won't gain XP from bossfights.

**Comment by HustlePuff** [comment]
so pets can gain xp from bosses later on?

**Comment by rhayward2** [comment]
So this may be a mistake on my part, or the "pet rock" pet is broken. My pet rock evolved once and then didn't gain XP. I then got a butterfly net and started catching other pets, and they are now gaining XP. I'm not sure if the "pet rock" is supposed to gain XP or not, but after leveling, it did not.

**Comment by Naoeaoe** [comment]
I think this only happens when your pet dies during the battle, after you heal it back it cannot get the xp from the monster even if the xprate is set but then again it happens very rarely.

**Comment by Sven65** [comment]
It's as @Naoeaoe says.
