### ISSUE TITLE
Boss Bug regarding Damage and Number of Hits

### ISSUE THREAD

**Issue by FelixCATus** [DiscordDungeons/Bugs#140]
__FIRST HIT__ on boss does not count as a hit, and only the user's damage is added to __user.dmg__.

Second hit on boss only starts counting user.hits from 1, and only the pet's damage from __FIRST HIT__ is added to __user.dmg__ this time.

Following hits on boss starts to count user.hits normally and both user and pet's damage from the previous hit are added to __user.dmg__, NOT from current hit.

__FIRST HIT__
![image](https://cloud.githubusercontent.com/assets/23120572/23744487/5bbe4532-04ef-11e7-926d-df4b70248876.png)

Second hit
![image](https://cloud.githubusercontent.com/assets/23120572/23744601/d7d37516-04ef-11e7-8327-d948655b9055.png)

Following hits (Third hit)
![image](https://cloud.githubusercontent.com/assets/23120572/23744748/6c1be3e8-04f0-11e7-8aa9-6b3c442e42d8.png)

**Comment by Sven65** [comment]
Fixed
