### ISSUE TITLE
Cannot use/sell grape item

### ISSUE THREAD

**Issue by rhayward2** [DiscordDungeons/Bugs#141]
When I try to use/sell grapes, I get the following message:

HaX^: .use grape
[4:33 AM] BOTDungeon Master: Found 1 item
Grapes

[4:34 AM] HaX^: .sell grape
[4:34 AM] BOTDungeon Master: Found 1 item.
Grapes

**Comment by Sven65** [comment]
That's because the name of the item is `grapes` regardless.
It is however planned to be able to use both the singular and plural names of items in these commands.

**Comment by rhayward2** [comment]
OK, thanks for the explanation. I've only been using the singular with all of the other items, since that's what seemed to work in the past.
