### ISSUE TITLE
Remove level requirement from eating food

### ISSUE THREAD

**Issue by Kitteh6660** [DiscordDungeons/Bugs#142]
Level requirement makes no logical sense for mundane food and those food don't even heal as much HP as healing potions anyway.

I would suggest removing the level requirement from those following items:

* Apple
* Banana
* Carrot
* Cherry
* Grapes
* Mushroom

**Comment by SamuiNe** [comment]
Sometimes real life logic apply does not apply to video games, and the suggestion would give minor benefits due to the current usage of those items. Lowering this to Low Priority.
