### ISSUE TITLE
Bug with Achievement: "A hero? I dunno."

### ISSUE THREAD

**Issue by Anthonyk747** [DiscordDungeons/Bugs#144]
I got an achievement that claims I killed 10 enemies, but it was my 23rd enemy killed. Achievement: "A hero? I dunno."
![capture_001_14032017_212208](https://cloud.githubusercontent.com/assets/7320748/23929431/75fc3da8-08fc-11e7-9613-d71bfc02148f.jpg)
![capture_002_14032017_212226](https://cloud.githubusercontent.com/assets/7320748/23929432/75ff6c94-08fc-11e7-8957-a631f5525c8e.jpg)
![capture_003_14032017_212243](https://cloud.githubusercontent.com/assets/7320748/23929433/76041dd4-08fc-11e7-81a4-6a02dfce0c7f.jpg)

**Comment by Sven65** [comment]
This has to do with the fact that every command doesn't check for achievements.

**Comment by Sven65** [comment]
Fixed.
