### ISSUE TITLE
Pet damage is significantly lower

### ISSUE THREAD

**Issue by ButtWrecker** [DiscordDungeons/Bugs#146]
I've been aware of this bug based on a comment in the Pets page of the Discord Dungeons Wiki, but I've made the mistake of trying to catch one after I turned level 22.

From a Level 21 pet hitting like this:

![image](https://cloud.githubusercontent.com/assets/26465626/24007479/b1d3e584-0aa9-11e7-8e5f-4f1677eefc81.png)

It is now this:

![image](https://cloud.githubusercontent.com/assets/26465626/24007501/c08b4838-0aa9-11e7-9e3b-0be277d5c1e5.png)

You can imagine how suddenly disappointed I am. :( 

![image](https://cloud.githubusercontent.com/assets/26465626/24007426/7a842364-0aa9-11e7-95cd-b9291c0289c6.png)

**Comment by Rosenkreuz12** [comment]
stuff's called dynamic mobs and apparently started appearing after lvl 21 reads the wiki for more info.
