### ISSUE TITLE
Inv has a space after !

### ISSUE THREAD

**Issue by AuroraKy** [DiscordDungeons/Bugs#147]
`! ===== [Angelic Bunny Aurora's inventory (Page 1/2)] ===== !`
(...)
`! ===== [Angelic Bunny Aurora's inventory (Page 2/2)] ===== !`
(...)
Nothing else seem to have that space and it doesn't line up with the bottom.
~~Not sure if it's really a bug~~
![2nd](https://puu.sh/uOvOe/af1aa8c822.png)

**Comment by HustlePuff** [comment]
Not really a bug. It's because your name is too long to be lined up with the bottom

**Comment by can1** [comment]
No, I think he means compared to the other commands like adventure, which is like,
!​=====​=== [users's adven​ture] =====​===!
there is no space betwixt ! and =, but on #!inv, the header to the reply has a space.

Plus while on subject of header vs footer, why not calc the name length so the footer ends up being the same length?

**Comment by SnazzyPine25** [comment]
I'm guessing this is fixed.
