### ISSUE TITLE
New command for “#!heal auto”

### ISSUE THREAD

**Issue by ChihiroKosaka** [DiscordDungeons/Bugs#148]
It would be great that there will be a new command that is related to the “#!heal auto”, which this command will calculate the amount of health potions needed to consume to gain an almost full heal. I believe this will likely help people who would like to save Health Potions when they do not want to use the last potion in getting a lesser amount of health points than it usually have. . 
 
eg. 
- User has 45/500 HP left. 
- **“#!heal auto 2”** 
- User has used 9 Health Potions and got 450HP. (495/500 HP)

**Comment by SamuiNe** [comment]
Having the ability to set max value of the auto heal would be interesting, but the benefit gained from it is quite minor due to the health potion's low price.
