### ISSUE TITLE
Cannot level up even though total exp > required exp to level

### ISSUE THREAD

**Issue by alvinburgos** [DiscordDungeons/Bugs#149]
Current status:

!======== [<username>'s Stats] ========!
+ Health: 60/100HP.
+ Inventory is in #!inv.
+ Weapon: Iron Sword
+ Ring: None | Helmet: None
+ Chestplate: None | Boots: None
+ Level 2 | (171/150 XP)
+ 113 Gold
+ Slain 0 times. Killed 13 enemies.
+ 5 Strength, 0 Defense.
+ 5 Luck, 0 Charisma.
+ Unassigned: 0 points.
!======================================!

**Comment by Sven65** [comment]
This is fixed.
