### ISSUE TITLE
Cooldown Error

### ISSUE THREAD

**Issue by charmiin** [DiscordDungeons/Bugs#152]
There is a cooldown/rest issue when using different commands in DiscordDungeons. The game works fine when I do commands, but as soon as my buddy enters them, the cooldown notification will continue to pop up. The only way they seem to be able to get the time to go down is by spamming commands until the time reaches ZERO. That does not always  work. Usually they get an error similar to the attached files. 
![2017-04-05 15_17_22- dungeon-master - discord](https://cloud.githubusercontent.com/assets/26946431/24733380/0a5fb5de-1a13-11e7-9632-3c15b1d6f1a6.png)
![2017-04-05 15_16_46- dungeon-master - discord](https://cloud.githubusercontent.com/assets/26946431/24733383/107e6226-1a13-11e7-97aa-6c5a13323333.png)

(also please ignore the name my friend)

**Comment by Sven65** [comment]
Really weird.

How do I reproduce the issue?

**Comment by charmiin** [comment]
The issue happens on and off, but I'm not sure how to replicate it in any
way. I do not get the error when I play, but I've seen it happen in my
server when he does. It seems to be working right now, but as I said, he'll
occasionally get the rest/cooldown error.

On Apr 5, 2017 21:11, "Mackan" <notifications@github.com> wrote:

Really weird.

How do I reproduce the issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DiscordDungeons/Bugs/issues/152#issuecomment-292088621>,
or mute the thread

**Comment by SnazzyPine25** [comment]
Was opened before the rewrite. Not confirmed so i'm closing this.
