### ISSUE TITLE
if ``#!use [item] [amount]`` is used to heal, typing the amount over the 'supposed to use this many' will use up the amount of items inputted

### ISSUE THREAD

**Issue by FelixCATus** [DiscordDungeons/Bugs#153]
https://owo.whats-th.is/f05c71.png
https://owo.whats-th.is/45bf2a.png
https://owo.whats-th.is/0c6e19.png

**Comment by SamuiNe** [comment]
Seems similar to #148 in a way, but in a different situation. marking as duplicate.
