### ISSUE TITLE
I'm having a bug where it forces me to rest for 290+ seconds

### ISSUE THREAD

**Issue by KiukenTile** [DiscordDungeons/Bugs#154]
I encountered an Ogre and I'm only level 1, I ran from the battle because I would have died and now I'm forced to rest for 290+ seconds. Please help, and I can't even reset my stats.

**Comment by FlamePrince** [comment]
Could you please provide your Discord ID?

**Comment by SamuiNe** [comment]
Can you provide the screenshot of the bug? It would be really nice.

**Comment by SamuiNe** [comment]
Due to lack of details and inactivity, I'll close and mark this as invalid.
