### ISSUE TITLE
[WEBSITE/API] API link = 502 Bad Gateway

### ISSUE THREAD

**Issue by FlamePrince** [DiscordDungeons/Bugs#155]
http://api.discorddungeons.me/docs/ leads to http://prntscr.com/ex9t16

#!item [insertitem] provides no embed, as well. http://prntscr.com/ex9the

Easily fixed by using #!uset itemdisplay 2 instead of embedded api link.

**Comment by Sven65** [comment]
This is due to the API crashing.

I've restarted the API and fixed the issue.
