### ISSUE TITLE
BOT - #!stats in DM not working (with or without mention)

### ISSUE THREAD

**Issue by RDardelet** [DiscordDungeons/Bugs#16]
This is what I get whenever I try to ``#!stats`` in DM to DRPG
The same error occurs when using ``#!stats <@someone>``

![image](https://cloud.githubusercontent.com/assets/9199809/18198044/c9b1c94e-70fa-11e6-82df-96b7c2659724.png)

**Comment by Sven65** [comment]
Fixed.
