### ISSUE TITLE
Butterfly Net

### ISSUE THREAD

**Issue by HonoShirayuki** [DiscordDungeons/Bugs#161]
In the shop it says you can buy it for 5000G and yet you can't actually buy it?

**Comment by Sven65** [comment]
Uh, what?

**Comment by SnazzyPine25** [comment]
Be more descriptive.

**Comment by SamuiNe** [comment]
The 5000G one might have listed at the buying global market than selling global market, you cannot purchase items from buying global market.

You can list a buying order at buying global market by entering #!gbbuy <item> <amount> <price>.
Alternatively, you can buy current selling global market by entering #!gmbuy <item> <amount> <price>.
