### ISSUE TITLE
Lost rewards from checking a trap

### ISSUE THREAD

**Issue by AliAmmarKh** [DiscordDungeons/Bugs#166]
https://cdn.discordapp.com/attachments/173361708885213186/318053200022208514/image.jpg This bug occurred 30 minutes after v3 was up.

**Comment by Sven65** [comment]
Did we not fix this?

**Comment by TrulyRogue** [comment]
The trap disappears when left alone for a long period of time. (Possibly a few days?) All I know is that you can check the trap shortly after putting it down and you'll get the rewards for it, if you have enough luck.

I've put down a trap 1-2 weeks ago and checked it today, and it said I didn't have a trap set. The same occurred to one of my guild members after he tried checking his trap after I checked mine.

**Comment by SamuiNe** [comment]
Seems to working properly on my side.

![Trap and Plant check](https://wawawa.s-ul.eu/mTo4g45P.png)

**Comment by Sven65** [comment]
Hm, I'll do some tests later, might be an issue with the UNIX time format I'm using and I might've reversed some variables.

**Comment by Sven65** [comment]
Unable to reproduce.
