### ISSUE TITLE
Armor not unequipping 

### ISSUE THREAD

**Issue by calac64** [DiscordDungeons/Bugs#170]
I am level 5 and have an adventurers chestplate. I am wearing a leather belt.

When I type [#!use adventurer's chestplate] or [#!use Adventurers Chestplate] the bot doesn't respond.

I successfully equipped the adventurers boots and helmet using the above.commands

**Comment by SnazzyPine25** [comment]
What's the bug?

**Comment by calac64** [comment]
second paragraph. 

when I type the command the bot doesn't respond. 

what does happen: nothing 

what should happen is: my leather belt is put into my inventory and my adventures chestplate is equippes to my character.

**Comment by Sven65** [comment]
Does the items you try to use get equipped and does the items you had equipped get placed back into your inventory?

**Comment by calac64** [comment]
no

**Comment by calac64** [comment]
@sven65
That does not happen
