### ISSUE TITLE
Error whilst using #!gjoin 

### ISSUE THREAD

**Issue by KawaiiArtistAlex** [DiscordDungeons/Bugs#176]
So a user tried to join the guild Rogue Revolution and an error popped up
![screenshot_51](https://cloud.githubusercontent.com/assets/12903523/26525562/9b5ed624-4352-11e7-9a0f-f017a12f2855.png)
this was the error.

**Comment by MohoraFlorin** [comment]
Could not manage to reproduce it, tried that 20+ times.

**Comment by Sven65** [comment]
Seems fixed, reopen the issue if it's not.
