### ISSUE TITLE
Guild deposit bug / error

### ISSUE THREAD

**Issue by KawaiiArtistAlex** [DiscordDungeons/Bugs#184]
The trade error occurred  whilst a user tried to deposit an item back to the guild
![530cbaf6e7cd47c18b2b78f2803abe25](https://cloud.githubusercontent.com/assets/12903523/26529059/b00ada06-43b0-11e7-8779-47c8f4795013.png)

**Comment by SnazzyPine25** [comment]
#171 has more info.
