### ISSUE TITLE
Force stop trades

### ISSUE THREAD

**Issue by deadb0t** [DiscordDungeons/Bugs#188]
Force stopping trades results in an error grabbing price in the gm but not the gb

**Comment by Sven65** [comment]
What?

**Comment by deadb0t** [comment]
When using #!fgmstop you can force stop trades in the gblist but not the
gmglist.  It gives an error

**Comment by Sven65** [comment]
Just saying it shows an error without showing me the error isn't helpful

**Comment by deadb0t** [comment]
Here

**Comment by PlayTheFallen** [comment]
@deadb0t still nothing to confirm this...

**Comment by deadb0t** [comment]
http://prntscr.com/fdv26e

**Comment by Sven65** [comment]
Thanks, gonna look into it
