### ISSUE TITLE
BOT- bfight finished, can't buy from store?!

### ISSUE THREAD

**Issue by chaoticeffect** [DiscordDungeons/Bugs#19]
I was doing a bfight with a friend, I do believe thatI won but now I ccan't buy from store and do any bdraw or bcancel or brefuse
please help

**Comment by Sven65** [comment]
Did any error message pop up?

**Comment by chaoticeffect** [comment]
Cannot buy because you are fighting
or something along those lines

**Comment by chaoticeffect** [comment]
i cancelled out of adv with adv 1, but still no luck

**Comment by Sven65** [comment]
The battles are a separate thing from the adventures, if you join the official server at https://discord.discorddungeons.me and ping me, (@Mackan#7196 ), I can fix it for you.

**Comment by chaoticeffect** [comment]
thanks, will do
