### ISSUE TITLE
OP-ness

### ISSUE THREAD

**Issue by Aemberr** [DiscordDungeons/Bugs#193]
I did #!adv and this happened:
!​=====​=== [Aether's adven​ture] =====​===!
% Rolled a 2
- Los​t 17 HP.
+ Dea​lt 33 HP Damage
+ Poudretteite deal​t 16 HP damage.
- Poudretteite to​ok 8 HP Da​mage.
+ Poudretteite h​as 285/487 HP l​eft
+ Aether has 723/900 HP left.
+ The en​emy Bleght has 167/310 HP left.
!==========================================!
I did 49 damage but the enemy lost over a hundred? This has happened a couple times today, actually. In one case I did over 700 damage, if I remember right. I don't have any enhancements equipped like strength rings, either.

**Comment by Nuratai** [comment]
I am facing a similar, but far more useful(if not annoying for pet catching)glitch. Every enemy is dying in a single hit every time. It is amazing for the near limitless xp and g, but catching pet's becomes impossible.
