### ISSUE TITLE
One Hit Killing

### ISSUE THREAD

**Issue by Nuratai** [DiscordDungeons/Bugs#194]
For the past few days, people using DiscordRPG on the server I am in are killing every enemy in a single hit, which in most cases, would be perfectly fine. Not when we need to catch stuff. If all enemies are dying instantly we are incapable of catching new pet's due to no adventure in progress. 

I did both of these battles back to back and it did this.

!​=====​=== [Railee's adven​ture] =====​===!
% Rolled a 3
- Los​t 4 HP.
+ Dea​lt 9 HP Damage
- Pet Rock to​ok 2 HP Da​mage.
- Pet Rock h​as 0/50 HP l​eft
+ Railee has 446/450 HP left.
+ The en​emy Zulp was s​lain by Railee!
+ Re​wards: 20 Gol​d and 17 X​P.
+ Pet Rock got 0 XP.
!==========================================!

!​=====​=== [Railee's adven​ture] =====​===!
% Rolled a 1
- Los​t 5 HP.
+ Dea​lt 7 HP Damage
- Pet Rock to​ok 2 HP Da​mage.
- Pet Rock h​as 0/50 HP l​eft
+ Railee has 441/450 HP left.
+ The en​emy Zulp was s​lain by Railee!
+ Re​wards: 21 Gol​d and 17 X​P.
+ Pet Rock got 0 XP.
!==========================================!

**Comment by Devils089** [comment]
I've been dealing with this myself

**Comment by Sven65** [comment]
Seems to be low-leveled static mobs.
