### ISSUE TITLE
Guild channel wasn't private.

### ISSUE THREAD

**Issue by astr0aster** [DiscordDungeons/Bugs#198]
I started a guild and bought the roles and channels but the channel wasn't private for some reason.

**Comment by HustlePuff** [comment]
what do you mean not private?

**Comment by astr0aster** [comment]
Well, after I got the channel everyone could see it and chat in it. It's supposed to be only for guild members right?

**Comment by HustlePuff** [comment]
Mackan and other guild members can see it

**Comment by astr0aster** [comment]
Everyone in the server could see it.

**Comment by HustlePuff** [comment]
screenshot?>

**Comment by astr0aster** [comment]
It's fixed now.

**Comment by HustlePuff** [comment]
okie
