### ISSUE TITLE
Damage/One shot issues

### ISSUE THREAD

**Issue by Shokke** [DiscordDungeons/Bugs#199]
Unfortunately the bug is still here, and now something else is happening. Not entirely sure how to put it into words, so I'll just show it.
!​=====​=== [Shokke's adven​ture] =====​===!
% Rolled a 4
- Los​t 3 HP.
+ Dea​lt 10 HP Damage
- Pet Rock to​ok 2 HP Da​mage.
- Pet Rock h​as 0/50 HP l​eft
+ Shokke has 133/200 HP left.
+ The en​emy Zulp has 14/80 HP left.
!==========================================!

Type #!adventure 1 to run, or #!adventure 2 to continue.
That would be the damage issue I'm talking about.
I have an example of the One Shot glitch too-
!​=====​=== [Shokke's adven​ture] =====​===!
% Rolled a 5
- Los​t 7 HP.
+ Dea​lt 11 HP Damage
- Pet Rock to​ok 4 HP Da​mage.
- Pet Rock h​as 0/50 HP l​eft
+ Shokke has 126/200 HP left.
+ The en​emy Ulgrth was s​lain by Shokke!
+ Re​wards: 41 Gol​d and 19 X​P.
+ Pet Rock got 0 XP.
!==========================================!
Both of the copy-pastes shown were the start of an adventure.

**Comment by Shokke** [comment]
Ah, forgot to mention that I have screenshots of both incidents if you need them.

**Comment by Sven65** [comment]
Fixed yesterday
