### ISSUE TITLE
BOT - #!getchannel not working

### ISSUE THREAD

**Issue by RDardelet** [DiscordDungeons/Bugs#20]
Using ``#!getchannel`` (with sufficient permissions) in the official server will trigger the following error message:

```
TypeError: message.guild.permissionsFor is not a function
at Object.defaults.getchannel.process (/root/RPGBot/cmds/defaults.js:6451:23)
```

Tested on DRPG server

**Comment by SnazzyPine25** [comment]
Its a library bug, will get fixed later on

**Comment by Sven65** [comment]
Fixed.
