### ISSUE TITLE
Heal bug

### ISSUE THREAD

**Issue by Bykey** [DiscordDungeons/Bugs#202]
Usually, if I type huge number of heal, the number of potion used for healing will depend on how much it usually needed to heal us to full hp, but now it no longer automatically calculated the number of potion needed. For example if i have 99/100 HP usually, even if I type heal 10, it will only use 1 potion, but now it use 10 of them to heal 1HP

**Comment by Sven65** [comment]
Do you have screenshots of the issue and how to reproduce it?

**Comment by Bykey** [comment]
![screenshot_20170530_135830](https://cloud.githubusercontent.com/assets/29047961/26569978/6c99d3f8-4540-11e7-8158-4c4ec32bbe40.jpg)

this is how it looks like

**Comment by Sven65** [comment]
Oh, that's not a bug though, it's supposed to do that
