### ISSUE TITLE
Pet not recieving xp when killing mobs

### ISSUE THREAD

**Issue by xIAmEzyx** [DiscordDungeons/Bugs#204]
<img width="570" alt="screen shot 2017-05-30 at 10 30 03 am" src="https://cloud.githubusercontent.com/assets/29053363/26566104/176265d4-4523-11e7-8137-79eb0dc222a1.png">

In the case that the screenshot doesnt work, it says this:
!​=====​=== [xIAmEzyx's adven​ture] =====​===!
% Rolled a 2
- Los​t 12 HP.
+ Dea​lt 19 HP Damage
+ Bleght deal​t 8 HP damage.
- Bleght to​ok 7 HP Da​mage.
+ Bleght h​as 192/232 HP l​eft
+ xIAmEzyx has 383/600 HP left.
+ The en​emy Hulp was s​lain by xIAmEzyx!
+ Re​wards: 44 Gol​d and 41 X​P.
+ Bleght got 0 XP.
!============================================!

**Comment by Sven65** [comment]
Have you set the XP rate using `#!pset xprate`?

**Comment by xIAmEzyx** [comment]
I think that fixed it oops my bad 👍
