### ISSUE TITLE
Strength Ring is broken for #!chop and #!mine

### ISSUE THREAD

**Issue by Vari3** [DiscordDungeons/Bugs#205]
http://puu.sh/w5sa2/f6cd4321dd.jpg
http://puu.sh/w5s9y/abae350f7f.jpg

I have 250 strength, level 14 chop and level 14 mine

**Comment by SamuiNe** [comment]
From what I've known so far, Ring of Strength only affects the damage dealt by x1.25.
However if the ring is for damage only, it should be noted at the ring description.

**Comment by HustlePuff** [comment]
Ring of Strength also affects chop and mine

**Comment by Sven65** [comment]
Not broken.
