### ISSUE TITLE
Plant check not working

### ISSUE THREAD

**Issue by Cardzz** [DiscordDungeons/Bugs#207]
![screenshot_13](https://cloud.githubusercontent.com/assets/29095655/26630081/de41eebc-4637-11e7-8f79-2b3fa5468804.png)

**Comment by SamuiNe** [comment]
Try using #!plant check instead of #!plant check magic sapling, does it work?

**Comment by ciliorkun18** [comment]
i had the same problem and i tried >plant check and it didnt work https://puu.sh/wbxbF/1a412b94e2.png
also tried >plant check magic sapling and it didnt work again https://puu.sh/wbzA5/c267320856.png

**Comment by PuckleA** [comment]
I can confirm this happened to someone I know. They told me, they stopped playing the game about 7 months ago until today (a time period from 2016 Nov until now).  They checked trap and managed to collect items, however not with plant check.

**Comment by ciliorkun18** [comment]
Maybe, it was a problem with old ones because i havent checked my plant like 5 months and when i did, it didnt work...

**Comment by BADEVILEVIL** [comment]
Same here check plant after 5 months.

#!plant check
[11:22 AM] BOTDiscordRPG: Whoops. An error occured. Please report this in the official server.
TypeError: Cannot read property 'time' of undefined
    at itemClass.getAll.then.items (/home/mackan/RPGBot/src/Commands/Commands/Sides/Plant.js:157:23)

[11:30 AM] BADEVIL: #!plant set
[11:30 AM] BOTDiscordRPG: You already have a sapling planted, BADEVIL.
