### ISSUE TITLE
trade bug

### ISSUE THREAD

**Issue by akmalhaziq12** [DiscordDungeons/Bugs#209]
my rock salt is 0 but when i trade rocks i got rock salts
this is my error
'''#!gbsell j3d4uaza rocks 10 '''
'''Sagiri Izumi(shy) executed trade j3d4uaza (10 Rock Salt at 15 gold each)'''

**Comment by FakePeer** [comment]
Picture?

**Comment by SamuiNe** [comment]
Can confirm about the issue, tagged as high priority

**Comment by SamuiNe** [comment]
Mackan fixed this several hours ago, should be working fine now.
