### ISSUE TITLE
Use command?

### ISSUE THREAD

**Issue by ScionSpy** [DiscordDungeons/Bugs#210]
We had a user issue this command, not sure if this should happen but it has.
I reported it in rpg-support, and i was directed here.
Hope it helps fix the issue, if it is indeed one.
+-+-+-+

> {к๓є}𝔖𝔠𝔦𝔬𝔫𝔖𝔭𝔶

 - Today at 11:54 AM
!rpg.use

> DiscordRPGBOT

 - Today at 11:54 AM
Whoops. An error occured. Please report this in the official server.
TypeError: Cannot read property 'formatNumber' of undefined
    at Use.checkResults (/home/mackan/RPGBot/src/Commands/Commands/User/Use.js:66:37)
    at Items.getAll.then.items (/home/mackan/RPGBot/src/Commands/Commands/User/Use.js:346:31)

**Comment by SamuiNe** [comment]
The error happens when you did not specify what item to use, though it should tell the user what to do rather than showing the error message.

**Comment by SnazzyPine25** [comment]
Already opened for #250.
