### ISSUE TITLE
Tried to buy 1000 Health pots, bot doesn't respond after that

### ISSUE THREAD

**Issue by riddlefoxy** [DiscordDungeons/Bugs#213]
Just like title states, I was playing the game for a week now with no problems. Then I tried to buy 1000 Health potions from the shop, and since then the bot doesn't respond to me anymore. To reproduce it I guess you can buy 1000 Health potions, just be careful.
![dead](https://cloud.githubusercontent.com/assets/29143182/26722028/938c832a-478e-11e7-9f1c-4c183b19e3b2.png)

**Comment by Sven65** [comment]
Can't reproduce, ![image](https://food.is-pretty.sexy/c6a664.png)

**Comment by riddlefoxy** [comment]
hmm... Then there has to be something else then. I'll look more into it, sorry for wasting your time >.<
