### ISSUE TITLE
Assign Points

### ISSUE THREAD

**Issue by MudkipzXD** [DiscordDungeons/Bugs#215]
I cant assign my unassigned 10 points :'( .And the Discord Link on the bot expired

![screenshot_2017-06-03-18-26-16](https://cloud.githubusercontent.com/assets/29160634/26752911/050646ea-488d-11e7-9847-a018912e92d6.png)

**Comment by Sven65** [comment]
This isn't a bug. Try doing `!help assign`

**Comment by MudkipzXD** [comment]
What about the link?

**Comment by Sven65** [comment]
The app is broken and won't be fixed for a good while.
