### ISSUE TITLE
plant check bug

### ISSUE THREAD

**Issue by Zigiry** [DiscordDungeons/Bugs#219]
TypeError: Cannot read property 'time' of undefined
    at itemClass.getAll.then.items (/home/mackan/RPGBot/src/Commands/Commands/Sides/Plant.js:157:23)

**Comment by ciliorkun18** [comment]
Same thing happens to me :c plant check doesnt work https://puu.sh/wbxbF/1a412b94e2.png
tried plant check magic sapling too but it didnt work :( https://puu.sh/wbzA5/c267320856.png

**Comment by Sven65** [comment]
Already reported in issue #207
