### ISSUE TITLE
Gwditem and Pet

### ISSUE THREAD

**Issue by fake3h** [DiscordDungeons/Bugs#226]
**Gwditem**
the bot gives an error if the amount field is put to random characters. Gdepitem however isn't affected by this.
ss: https://u.nya.is/mplyff.PNG

**Pet**
there's a random "}" at the very end of the pet info.
ss: https://u.nya.is/cwdjpx.PNG

**Comment by Sven65** [comment]
(You should really make these seperate issues in the future)
