### ISSUE TITLE
Suggestion: Attribute adjustments

### ISSUE THREAD

**Issue by Tehmaxx** [DiscordDungeons/Bugs#227]
# **Strength**

> Every 10 in strength gives +1 to base damage reduced to every 5 in strength.

_At 50 strength(the highest any guide recommends to go in strength) this currently only gives +5 to damage. This change would also mean that you could increase your base damage in a single level-up rather than across 2 of them._

_It also wouldn't be a bad idea to add additional power curves to the attribute such as Every 50 you get +5 damage._

> Every 65 in Strength +1 increased output from foraging

_Instead of having a charm stat affect your ability to carry and forage items move it over to strength_.

# **Defense**

> Every 10 gives -1 Damage taken from enemies

_Change the name of the stat to Vitality, make it every 5 points._

_Every 10 points of Vitality increases the healing effectiveness of items by 10%. Make it additive IE. 20 points of defense = 20% of healing boost rather than 10% of the 10% boosted effect. _

# **Charisma**

_A lot of the buffs granted for leveling charisma seem ambiguous with no real clarity on what they do, elaborating what things like the quote below mean would be helpful._

> Increases quest maximum requested item amount by 1 per 25 charisma.

_Moving the foraging buff to strength makes more sense as currently, I have no idea how you'd charm a tree into giving you more lemons._

_Also allowing the stat to dictate pet bonuses rather than just catch rate seems like a logical step, just as increased HP, Damage, XP bonus by X amounts would be additional incentive to push stats into the ability._

A lot of these seem minor or "Useless" as it seems is a favorite word to use for suggested changes to the game or playstyle within the chatrooms but I honestly don't like seeing the cookie cutter build of "Just dump everything in 1 stat" on every single character in an RPG.

**Comment by SamuiNe** [comment]
This would require too much changes as changes the stats may cause huge imbalance if it is adjusted.
Lowering this to Low Priority.

**Comment by Sven65** [comment]
Attribute expansion has been done, closing.
