### ISSUE TITLE
#!stats [User ID] comes up with 'undefined'

### ISSUE THREAD

**Issue by TrulyRogue** [DiscordDungeons/Bugs#230]
Trying to find out which guild members are not in my server and I've tried checking their IDs on both servers.

**Comment by TrulyRogue** [comment]
Some of my members that have only the IDs since they're not in my server and 'undefined' are also not actually in my guild and in another guild.

**Comment by SamuiNe** [comment]
Yeah, this bug applies to any ID entered at the `#!stats` command, marking this as a bug.

**Comment by SamuiNe** [comment]
Just a note, using user mention for the `#!stats` command does not have this bug.
