### ISSUE TITLE
i did someones stats then...

### ISSUE THREAD

**Issue by lifelineiscancer** [DiscordDungeons/Bugs#232]
DiscordRPGBOT - Today at 12:41 PM
Whoops. An error occured. Please report this in the official server.
TypeError: Cannot read property 'formatNumber' of null
    at Items.getAll.then.items (/home/mackan/RPGBot/src/Commands/Commands/User/Stats.js:60:43)

**Comment by Sven65** [comment]
Edge case, not fixing.
