### ISSUE TITLE
#!uset nick doesn't work

### ISSUE THREAD

**Issue by archagy** [DiscordDungeons/Bugs#233]
Tried using 

- #!uset nick 1 
- #!uset nick 2
- #!uset nick 3

There are no response and nothing happened.

![error](https://user-images.githubusercontent.com/4847289/27239555-05c823be-5297-11e7-9f6c-3869218f0203.PNG)

**Comment by Sven65** [comment]
This is a glitch that happens sometimes, there's not much I can do about it.
