### ISSUE TITLE
 when i try to use one of the potions i bought/found It said i had none even though i got them 

### ISSUE THREAD

**Issue by Tehchuteam** [DiscordDungeons/Bugs#234]
![screenshot from 2017-06-17 14-23-39](https://user-images.githubusercontent.com/29511002/27256072-a7afc0c0-5368-11e7-9890-0d0e61e21d9d.png)
![screenshot from 2017-06-17 14-23-52](https://user-images.githubusercontent.com/29511002/27256076-be075c8e-5368-11e7-874a-9f1cc194340c.png)
Can you please fix it?

**Comment by Tehmaxx** [comment]
You did not buy a health potion during your first attempt as it clearly states in your screenshot.

**Comment by Sven65** [comment]
Simple misspelling.
