### ISSUE TITLE
#!trap commands dont work

### ISSUE THREAD

**Issue by ewuewu123** [DiscordDungeons/Bugs#237]
the #!trap command wint work for anyone why ? when i type #!trap then this come i dont know what you wannt plz fix this big fast

**Comment by SamuiNe** [comment]
If possible, please provide screenshot about the bug, we're unsure about the situation at your side.

**Comment by PuckleA** [comment]
The full command is #!trap set bear trap and to check it it's #!trap check

**Comment by Sven65** [comment]
Not a bug, it's a simple matter of not using the `#!help` command.
