### ISSUE TITLE
TimerChan outputs 1 DM reminder when doing #!adv too soon...

### ISSUE THREAD

**Issue by PuckleA** [DiscordDungeons/Bugs#239]
I will try to keep it short in 3 steps. This bug can be reproduced, because it happened several times.

Firstly, my #!adv is done too soon. Notice the time.
![step 1](https://user-images.githubusercontent.com/29098459/27501909-3bba55f6-5868-11e7-83c8-bb12895c63be.PNG)

Secondly, I receive a random reminder from TimerChan (only servers that have it are DRPG Official or our guild server) at the exact 10:53.
![step 2](https://user-images.githubusercontent.com/29098459/27501958-7ee1b54a-5868-11e7-8ec2-2f64eff5befe.PNG)

Finally, I did a screenshot of doing my sides after 1 minute just to show that I actually didn't do them at 10:53(my time)
![step 3](https://user-images.githubusercontent.com/29098459/27501994-bc6f8996-5868-11e7-832e-88346317ab30.PNG)

**Comment by SamuiNe** [comment]
Talk to BigBrainAFK for issues related to TimerChan, this repository is for DiscordRPG.

**Comment by PuckleA** [comment]
I see. Thought to ask just in case, since it included DRPG functionality triggering it. Thanks though.

**Comment by SamuiNe** [comment]
You're welcome, and I hope the issue would be resolved quickly.

**Comment by PuckleA** [comment]
I contacted Brain and surprisingly nobody mentioned this before. I've been told there is going to be a fix for it.
