### ISSUE TITLE
[REWRITE] #!adv - Bot not reporting battles

### ISSUE THREAD

**Issue by FlamePrince** [DiscordDungeons/Bugs#24]
Adventure related commands not working 100% of the time. (unrelated to server lag or ping as other commands such as forage will still work.)

![loll](https://cloud.githubusercontent.com/assets/18062412/18617678/d4b7ed38-7dab-11e6-964e-1f097a5f21af.png)

**Comment by FlamePrince** [comment]
Further issue with #!adv, it would seem you cannot level up from the #!adv command. Your XP will continue going up and it won't count you as levelled until you do a side activity that gains XP

![level](https://cloud.githubusercontent.com/assets/18062412/18617765/e3e157b6-7dad-11e6-98f2-0d7e7ce6827e.png)

**Comment by FlamePrince** [comment]
Bot is still calculating fights, not reporting them.

![stillfighting](https://cloud.githubusercontent.com/assets/18062412/18617965/c1896f50-7db2-11e6-983e-9bb109d19d01.png)

**Comment by FlamePrince** [comment]
Bot **will** report victories.

![finish](https://cloud.githubusercontent.com/assets/18062412/18618194/d80407fe-7db7-11e6-9fa7-914c64f7fe39.png)

**Comment by Fluffninja** [comment]
When I tried typing the adventure command, it sent an error and then it stopped displaying the adventure report

Reference error: userxp is not defined
At
Data.user.addkills.then (/root/RPGBot/cmds/adventure.js:389:23)

**Comment by Sven65** [comment]
Just fixed it.
