### ISSUE TITLE
Gwditem and gdepitem moves all balls of wool even if being specific

### ISSUE THREAD

**Issue by PuckleA** [DiscordDungeons/Bugs#242]
Sorry about before. I've found out this issue just now. I have tested this with this item so I am not sure if it affects just this or some other ones.

![gdepitem issue](https://user-images.githubusercontent.com/29098459/27517264-88d127ac-59c1-11e7-94e7-1c5cabec73ca.PNG)
![gwditem issue](https://user-images.githubusercontent.com/29098459/27517268-8de58d50-59c1-11e7-882c-d28bc22660c6.PNG)

**Comment by SamuiNe** [comment]
Ball of wool seems to be affected, but not logs when I was testing it earlier. I'll perform more testing later on.

**Comment by PuckleA** [comment]
Thank you.

**Comment by SamuiNe** [comment]
You're welcome, and the bug seems awfully specific in terms of the conditions.

So far from what I have seen, ball of wool and small dagger is affected. Most items are not affected, but I have not yet tested all of the items.

**Comment by SamuiNe** [comment]
After running around testing, the bug seems to affect all items that contains `ll` on its name.

**Comment by SamuiNe** [comment]
Found the issue, it seems to pick item name that have `all` as `all` for the quantity.

**Comment by PuckleA** [comment]
I could guess it's related to this case when you try to check for an item. For example, I tried to check for "orhid sword" and it instantly prompted the output of orchid sword without showing matches that can be chosen from. It's like the search command in Linux terminal with the function of ignoring case sensitivity.

**Comment by Sven65** [comment]
So it picks all items with "All" in the name?

**Comment by SamuiNe** [comment]
Yup, if the item name contains `all` like small dagger or ball of wool, it thinks the quantity is all rather than the one user has specified.
