### ISSUE TITLE
Guild join seems to have made an error

### ISSUE THREAD

**Issue by KawaiiArtistAlex** [DiscordDungeons/Bugs#243]
So, a user tried to join the guild I am in name Rogue Revolution , and it seems to have spilled an error, not sure what would have caused it , here is a screenshot of the error to give you an idea on what could've caused it. [https://japan.is-pretty.cool/41cc57.png](url)

**Comment by SamuiNe** [comment]
The issue was caused by simple guild name misspelling, but it should have notified the user that the "guild name is invalid" or "guild not found".

**Comment by Sven65** [comment]
Screenshot is broken, please fix.

**Comment by KawaiiArtistAlex** [comment]
![41cc57](https://user-images.githubusercontent.com/12903523/27578559-618b29fc-5b1c-11e7-8e6a-d3eefc79cbc9.png)
Here is a screenshot to help, sorry about the other :) , plus Happy Birthday
