### ISSUE TITLE
pet name

### ISSUE THREAD

**Issue by nobodythatishere** [DiscordDungeons/Bugs#245]
You can name your pet
```
anything
```
and it will make the adv message super ugly

Example: 
![image](https://user-images.githubusercontent.com/29800890/27743060-a031ad20-5d6f-11e7-8dea-71b76a522540.png)

**Comment by KawaiiArtistAlex** [comment]
I can say that the same happens if you have your Discord name with a similar thing.

**Comment by FakePeer** [comment]
Isn't it obvious.

**Comment by Sven65** [comment]
That's not a bug, that's you not knowing how a codeblock works.
