### ISSUE TITLE
embed #!adv bug?

### ISSUE THREAD

**Issue by FakePeer** [DiscordDungeons/Bugs#246]
My friend is #!adv-ing and this happen 
![image](https://user-images.githubusercontent.com/29004336/27743908-c5e612a4-5de7-11e7-9e61-884476070aef.png)

**Comment by Sven65** [comment]
What's the bug?

**Comment by FakePeer** [comment]
A user name SkyEleventh is in minh's #!adv for some reason 
![image](https://user-images.githubusercontent.com/29004336/27744225-e35ee67a-5de8-11e7-9e0d-085502fdeb7b.png)

**Comment by Sven65** [comment]
Ah, I see, that's extremely strange, might be the bot concatenating two adventures into one embed to save space.

**Comment by Sven65** [comment]
Known issue, it's discord.js, I can't do anything about it.
