### ISSUE TITLE
pet attack

### ISSUE THREAD

**Issue by kevinluvian** [DiscordDungeons/Bugs#247]
my pet level 30 (chrolat) but only have 3-7 damage. is this intended?

**Comment by PuckleA** [comment]
have you changed the pet's name when you caught it? Just checking info.

**Comment by kevinluvian** [comment]
nope.
i just checked the wiki and there's a post from asianotakuguy, he said that pet above level 21 will have small dmg

**Comment by PuckleA** [comment]
Yep, they are dynamic mobs made for level ups. It's not recommended to catch them. I'd stick to a static pet instead.

**Comment by kevinluvian** [comment]
how to differentiate static with dynamic pet?

**Comment by Sven65** [comment]
This is intended as they are dynamic mobs.

**Comment by PuckleA** [comment]
A very easy way is to use Blargbot to benchmark them at higher levels. Usually Blarg returns invalid value if the pet can't be found. Additionally, they are not in the established pet list in the Wiki.

**Comment by kevinluvian** [comment]
@PuckleA can you please explain how to use Blargbot to check the value? Thanks for the answer by the way!

**Comment by PuckleA** [comment]
@kevinluvian Are you in the official DRPG server now? What's your name?

**Comment by kevinluvian** [comment]
no i'm not, is there any documentation where I can read about this? I don't want to troubles you lol

**Comment by PuckleA** [comment]
Right, I'll take a screen of the output as a practical example. 
![capture](https://user-images.githubusercontent.com/29098459/27788636-4fd69182-5fe1-11e7-9683-2ab61e4d43ae.PNG)

**Comment by kevinluvian** [comment]
ah i see, thanks man!
