### ISSUE TITLE
Citrus blade not tradable

### ISSUE THREAD

**Issue by kevinluvian** [DiscordDungeons/Bugs#248]
it should be tradable from the wiki
https://wiki.discorddungeons.me/items/citrus_blade

**Comment by PuckleA** [comment]
There is more. Hunters Sorrow

**Comment by kevinluvian** [comment]
hunters sorrow is not tradable
https://wiki.discorddungeons.me/items/hunters_sorrow

**Comment by Tehmaxx** [comment]
Both items are unable to be traded, your only real option is to deposit to your guild inventory or to sell it back to the in-game store.

**Comment by Sven65** [comment]
There's no information on  whether or not the item is tradable on the wiki.

**Comment by kevinluvian** [comment]
@Sven65 there's

> tradable: Yes

in the wiki https://wiki.discorddungeons.me/items/citrus_blade below the sell price
could you please check it again?

**Comment by Tehmaxx** [comment]
http://i.imgur.com/i0OSodB.png

In-game and wiki don't reflect the same information.
