### ISSUE TITLE
#!crack 28

### ISSUE THREAD

**Issue by djdracoo** [DiscordDungeons/Bugs#249]
i'm not sure if there's a randomness. but i used #!crack geode 28 i got 28 water crystals.

**Comment by PuckleA** [comment]
That sounds odd...Usually it's shards.

**Comment by djdracoo** [comment]
sorry i ment water shard. my mistake

**Comment by PuckleA** [comment]
Case closed then

**Comment by djdracoo** [comment]
is there no randomness? in all 28 being opened at the same time?

**Comment by PuckleA** [comment]
From what I observed, no matter the amount you open up, it will always select 1 possibility from the list and apply to that amount selected. It will not be like 20 water shards and 8 fire shards from 28 geodes. So, I'd avoid using "#!crack all" for you might end up getting loads of rocks. Do 16 or 32 at a time if you plan creating keys.

**Comment by djdracoo** [comment]
thanks

**Comment by SamuiNe** [comment]
can you show screenshots of the bug?

**Comment by SamuiNe** [comment]
This isn't an issue, just rng doing its job
