### ISSUE TITLE
[REWRITE] Skill Levels not increasing/ skills decreasing / Rings not working (read comments)

### ISSUE THREAD

**Issue by FlamePrince** [DiscordDungeons/Bugs#25]
Issues regarding the math in mining, chopping and foraging are off.

![math](https://cloud.githubusercontent.com/assets/18062412/18617697/36fc97e6-7dac-11e6-8a2e-5ccb0125a36c.png)

**Comment by VladyTheImplier** [comment]
![mining and choping](https://cloud.githubusercontent.com/assets/12383993/18617737/c7b51c66-7da4-11e6-9737-a0c8f2e59def.png)

**Comment by FlamePrince** [comment]
Issue related to rings not working.

![ring](https://cloud.githubusercontent.com/assets/18062412/18617889/8ef09b64-7db1-11e6-8b6f-a6a2d9f91299.png)

**Comment by FlamePrince** [comment]
Percher™ᅠ#2490 had this similar issue:

Before switching rings:
![ejwfwdenhcamanbdgibcoag4dugcrqueavy43o733lc941kr2kx6xag2y2yem57ci9wik3o9surh1jlvscip73dpmseg57wnhogwtm6sb8sa5hmxukaboycdtzsbv033vtxvdwgviuk](https://cloud.githubusercontent.com/assets/18062412/18619840/fdf5a4e8-7ddc-11e6-83ab-160d37a7dc5a.jpg)

After:
![unknown](https://cloud.githubusercontent.com/assets/18062412/18619841/ff97a74c-7ddc-11e6-8bfe-c16411a2e3f2.jpg)

**Comment by FlamePrince** [comment]
Chief Tots#2741 reported no skill xp increase:
![1](https://cloud.githubusercontent.com/assets/18062412/18621942/026ed40e-7e00-11e6-875c-81c42dc683fa.jpg)

Tested this myself, to find my skills did not go up appropriately:
![skills](https://cloud.githubusercontent.com/assets/18062412/18621947/09c47eb6-7e00-11e6-8964-1c5b33ab9ab2.png)

**Comment by Kagera1706** [comment]
Just leveled up in fishing this morning, the issue seems fixed (at least the exp part) however due to this i am still lacking a level in all my skills.

**Comment by Sven65** [comment]
The XP issue is fixed, I'll look into the rings.
