### ISSUE TITLE
#!use command caused an error.

### ISSUE THREAD

**Issue by KawaiiArtistAlex** [DiscordDungeons/Bugs#250]
Noticed when a user tried to use the #!use command it caused an error whilst nothing was wrote after use.
![07b00c](https://user-images.githubusercontent.com/12903523/27800249-7074576a-6010-11e7-86e0-287f4d974e5c.png)

**Comment by Tehmaxx** [comment]
http://i.imgur.com/taxYXDC.png

**Comment by ciliorkun18** [comment]
You have to write down what item you wanted to use in order to use the command, I don't think this is an error or bug.

**Comment by KawaiiArtistAlex** [comment]
It's not meant to display an error if nothing is set, it's meant to display something like "Cilorkun18, please type in an item name."

**Comment by ciliorkun18** [comment]
That's true too but, I usually do #!help <command> before I use it.
