### ISSUE TITLE
#!sell Freshwater all

### ISSUE THREAD

**Issue by Tehmaxx** [DiscordDungeons/Bugs#251]
http://i.imgur.com/FWpmMEQ.png

**Comment by ciliorkun18** [comment]
You spelled item's name wrong but dont worry you didnt lose any Freshwater fish.

**Comment by Tehmaxx** [comment]
I understand what happened, just not sure it's intended to work like that or if the intended shorthand for the item attempted to be sold is returning the intended query.

**Comment by ciliorkun18** [comment]
Yeah, it shouldnt do that. I accidently found it while i was trying to sell my crabs and when i typed "#!sell crab all" it said the same thing that you got, then i had to type "#!sell crab (specific number)" to make it work.
