### ISSUE TITLE
Bug on the Trade Market

### ISSUE THREAD

**Issue by RJain12** [DiscordDungeons/Bugs#253]
I had a trade of buying small daggers for 20501. I received several dm's that people had sold their daggers to me. I went to my gmlist, and stopped the trade and didn't receive any daggers and just the gold. Here is a screenshot of the dm's from the bot:
![capture](https://user-images.githubusercontent.com/29895437/27834870-818e2cd8-608d-11e7-904f-3fa00d2a2aeb.PNG)

**Comment by SamuiNe** [comment]
quite sure this is fixed with the recent patch, closing the issue
