### ISSUE TITLE
Some stuff apparently is not shown to new players

### ISSUE THREAD

**Issue by adih2001** [DiscordDungeons/Bugs#256]
So i saw one guy typing #!stats for the first time and i noticed that "Creating new account" message didn't show up. Also i noticed in #!stats that there was no command that showed to player about how to assign points. This can be VERY fustrating for new players.

[http://cctps.fluctis.com/new_player.png](http://cctps.fluctis.com/new_player.png)

**Comment by Sven65** [comment]
Unable to see image,

**Comment by adih2001** [comment]
The link works... just put it in the search bar.

**Comment by Sven65** [comment]
Ah, works now, I'll look into it.

**Comment by Sven65** [comment]
Fixed.
