### ISSUE TITLE
#!sell not working properly

### ISSUE THREAD

**Issue by VoxelBuster** [DiscordDungeons/Bugs#259]

**Comment by VoxelBuster** [comment]
Trying to sell items and even if the item exists the bot doesn't respond when the command is executed

**Comment by SnazzyPine25** [comment]
Can you give a screenshot please?

**Comment by blacj** [comment]
I encountered this http://imgur.com/6JsXWJd - wondering if this might be what they're referring to. Those items don't end up in my inventory but it seems to happen consistently. But I have realized since that the command should be `#!sell log 11` - not logs - oops!

**Comment by Sven65** [comment]
User error, closing.
