### ISSUE TITLE
Can't gkick

### ISSUE THREAD

**Issue by smikolai** [DiscordDungeons/Bugs#262]
![screen shot 2017-07-24 at 2 38 38 pm](https://user-images.githubusercontent.com/12926884/28543769-190899fe-707e-11e7-9128-da6ec89833fe.png)

**Comment by ryudragon98** [comment]
you have to use their id to kick them.

**Comment by RJain12** [comment]
Also, you don't have to include the < > around the username of the person.

**Comment by Sven65** [comment]
Fixed.
