### ISSUE TITLE
Lvl 22 Byrn pet

### ISSUE THREAD

**Issue by SleuthCyber** [DiscordDungeons/Bugs#264]
Captured it early this morning, it has an appropriate amount of HP but the damage suddenly downgraded to 2-5. http://puu.sh/wTWEd/4fcb6e0080.png

**Comment by Tehmaxx** [comment]
It looks like you've caught a Dynamic Mob, these mobs will always do significantly less damage than a static mob.

To see a list of monsters you should attempt to catch you should reference the wiki and this list. https://wiki.discorddungeons.me/pets

Also, the FAQ has some useful information you should also take some time to reference which will help you with future problems pertaining to pets.

> Pets
> Q: What are pets?
> A: pets are the mobs you fight in adventures, you can catch them to use as weapons against other mobs.
> Q: How do I get a pet?
> A: you can get a pet at lv5+ by using #!catch if you have a butterfly net.
> Q: I keep failing when I use catch, does health effect whether I catch it or not?
> A: no health has nothing to do with catching a pet the catch rate for pets, chance to catch something according to Mackan earlier: ((user.level*5.678)/10)
> At lv5 this is a catch rate of 2.839 %
> Q: do I lose my pet if it dies?
> A: no it's health will stay at 0 until you heal it.
> Q: how do I heal my pet?
> A: heal your pet by using #!pheal <amount/auto> this is the only way to heal a pet. you can only heal with the normal, basic health potion.
> Q: can I name my pet?
> A: yes by using #!pset name <name of pet>
> Q: can i change the display of my pet?
> A: yes by using #!pset display 2 when you catch a lv20+ pet.
> Q: can I set an image for my pet?
> A: yes by using #!pset image <url to image>
> Q: how do I lvl up my pet?
> A: by using #!pset xprate <0-100> this drains xp from your gained xp so its best to not give xp to your pets until you are at least lv120+.
> Q: what is the best pet?
> A: Flibknort is by far the best pet that can be caught at lv21 and when you are able to lv it up it becomes the best pet overall with higher damage than the base damage of higher lv pets making flibknort a great asset to your adventure.
> Q: is there a list for pets?
> A: yes do tagbot petlist
> Q: can I have more than one pet?
> A: no you can only have one pet at a time and if catch a new pet the other is replaced and will lose all progress it had.
> Q: how do I check what pet I have?
> A: use #!pet and it will show you your pet and its stats

**Comment by SleuthCyber** [comment]
Gotcha. Wasn't aware I could catch something like that, since its not really stated anywhere that catching a pet that isn't listed would result in taking a severe penalty in damage. Thanks for the response though.

**Comment by Tehmaxx** [comment]
Before you caught this monster it would have been doing similar values of significantly less damage than something like a Flibknort(the strongest catchable animal at your level) Which would have told you that the monster would be a significant downgrade in damage.

The #FAQ on the official server has a lot of useful information you should refer to optimize your play and eliminate a lot of questions you may have in the future.

**Comment by PlayTheFallen** [comment]
Issue locked to participants.
