### ISSUE TITLE
Undefined given when buying a guild item

### ISSUE THREAD

**Issue by Gyth7** [DiscordDungeons/Bugs#268]
```
When i did '#!gbuy guild sign' it gives an undefined item and executes the buy deducting gold from my guild. The items were still given. 
```
![](https://cdn.discordapp.com/attachments/308924450957426689/341930846913167372/Screenshot_20170801-204854.png)

*EDIT: Made image show on this page - Fallen*

**Comment by Sven65** [comment]
Fixed.
