### ISSUE TITLE
Battles not damaging properly.

### ISSUE THREAD

**Issue by tklaxbro** [DiscordDungeons/Bugs#269]
I am not the one who found this bug but just reporting it for the person. 

As the screenshots clearly show the battle shows an improper amount of damage dealt. 
1) 272 health, 9 damage dealt, then 252 health left.
2) 244 health, 7 damage dealt, then 227 health left.

https://cdn.discordapp.com/attachments/172382467385196544/342015066327220224/image.png
https://cdn.discordapp.com/attachments/172382467385196544/342013072564813824/image.png

**Comment by Sven65** [comment]
Fixed
