### ISSUE TITLE
Pet overheal due to lag

### ISSUE THREAD

**Issue by lewhitemale** [DiscordDungeons/Bugs#272]
I tried to heal my pet during a lag event of some sort, thought I had used the command wrong and so I issued it again. This led me to encounter a bug: When the lag passed, the bot responded to both commands and healed my pet to 30 points over its max HP.

Screenshot:
![arrpeegee_-_discord_2017-08-07_06-13-08](https://user-images.githubusercontent.com/29827796/29024410-8bb8570a-7b37-11e7-9439-912c3c7fae64.png)

**Comment by ciliorkun18** [comment]
I think you should PM mackan for that

**Comment by Sven65** [comment]
DM me instead.
