### ISSUE TITLE
Bot wont respond to anyone

### ISSUE THREAD

**Issue by MrYami** [DiscordDungeons/Bugs#274]
Bot doesn't respond to anyone on the server, readding does not fix the issue. When added to a solo server it works fine.

![image](https://user-images.githubusercontent.com/30874096/29134699-95eadd36-7d05-11e7-82b0-8b5c5a507816.png)

**Comment by tklaxbro** [comment]
close? the bot should be up now, servers were just being updated

**Comment by Sven65** [comment]
It should be fixed, if the issue persists, ask in the #rpg-support channel [here](https://discord.discorddungeons.me)
