### ISSUE TITLE
#!uset nick not working

### ISSUE THREAD

**Issue by L1ght5h0w** [DiscordDungeons/Bugs#277]
I have tried using:
```
#!uset nick 1
#!uset nick 2
#!uset nick 0
```
Nothing happens when I use any of them, not even a message saying I have to be a certain level.
I can however use something like
```
#!uset display 1
```
and it will tell me "Sorry, <name>. But you need to be level 20 to use this.

**Comment by ryudragon98** [comment]
if your name is too long the uset nicks wont work that and if you are the owner of a server the bot can not change your nick it can only change the nicks of members not owners.

**Comment by L1ght5h0w** [comment]
My name on the server is "Chester" and I am not the owner.

**Comment by ryudragon98** [comment]
the bot might not have manage nickname permissions.

**Comment by L1ght5h0w** [comment]
I am checking with a server admin to see if it has manage nickname permissions. Will update when I have a response.

**Comment by nathanielcwm** [comment]
i think the updated nicks only take effect after you do your stats

**Comment by PlayTheFallen** [comment]
when you run the command, the bot will update any relevant data for the user table *and then post your stats in the requested format*.

**Comment by Sven65** [comment]
I'll be adding a check for permissions when you use `#!uset nick`
