### ISSUE TITLE
Damage bug?

### ISSUE THREAD

**Issue by L1ght5h0w** [DiscordDungeons/Bugs#279]
Was fighting a monster, got it down to 38 health.
On the next turn, I rolled a 5 and did 5 damage, as shown in attached image.
The monster went from 38 health to 29 health, instead of 32 health like it should have.
I didn't get a critical hit, as it doesn't show that I did (evidenced in attached image).
I have not, as of yet, been able to "recreate" this bug.
![damage bug 2](https://user-images.githubusercontent.com/17111526/29316609-4f03fea6-818e-11e7-89d4-1d1f6a3acc43.png)
Picture is in black and white as I was on my phone. Can upload color picture if neeeded.

**Comment by Sven65** [comment]
Most likely it was due to a pet not showing the damage, fixed.
