### ISSUE TITLE
[REWRITE] "#!trap" doesn't give a message stating to use #!trap set/#!trap check

### ISSUE THREAD

**Issue by FlamePrince** [DiscordDungeons/Bugs#28]
![trap](https://cloud.githubusercontent.com/assets/18062412/18617717/a4210226-7dac-11e6-960a-c87a1a0bb791.png)

**Comment by FlamePrince** [comment]
The issue appears to be related to my level, as a person with adequate level can use the commands fine. This bug omits the warning message that a person is not high enough level to #!trap

**Comment by Sven65** [comment]
It's your level, it's meant to send "You need to be level X to use this"

**Comment by FlamePrince** [comment]
![fixed](https://cloud.githubusercontent.com/assets/18062412/18617769/13055c72-7dae-11e6-922c-4c90b6296ff6.png)
