### ISSUE TITLE
Suggestions: Stat redistribution 

### ISSUE THREAD

**Issue by SoraTheOne** [DiscordDungeons/Bugs#281]
This is just an idea of mine. Please take it into consideration if you are interested. 
- Strength is more dmg and crit chance
- Defense is dmg reduction and bonus health and extra healing from health item
(for the dmg reduction the best way would be base on the percentage of ur missing health. So the less percent of health u have, the less dmg u take. However i can't think of defense be any good unless we remove potion access during an adventure)
- Charisma makes ur pet take less exp to lvl up, do more dmg and maybe unique pets with special ability that only appear after putting enough point in charisma.
- Luck will be more gold out of adventure, find more thing for side missions but only gold wise and take less time for plant and trap to gather items.

**Comment by Sven65** [comment]
We're already working on a new system for the attribute system.
