### ISSUE TITLE
Error in assigning attribute points

### ISSUE THREAD

**Issue by Mathster0598** [DiscordDungeons/Bugs#286]
![1](https://user-images.githubusercontent.com/24941318/29570096-04f21ef6-8788-11e7-961f-a129ca494d2c.png)
![2](https://user-images.githubusercontent.com/24941318/29570097-04f27ad6-8788-11e7-97a6-dbde04f75f5e.png)
![3](https://user-images.githubusercontent.com/24941318/29570094-04e372e8-8788-11e7-85f9-3ada8c060108.png)
![4](https://user-images.githubusercontent.com/24941318/29570095-04e46a2c-8788-11e7-8381-94c087018cba.png)
![5](https://user-images.githubusercontent.com/24941318/29570099-04fa1a20-8788-11e7-8299-def1a0fc8f79.png)

though, I found the points by using "attributes"
![6](https://user-images.githubusercontent.com/24941318/29570221-64564804-8788-11e7-83ff-b8322b0a58b0.png)

**Comment by Sven65** [comment]
Not an issue, it literally tells you what to do.

**Comment by Mathster0598** [comment]
I was just confused though that an error popped out when I did "stats"
