### ISSUE TITLE
Looking at people's stats right after the big update

### ISSUE THREAD

**Issue by Argonian373** [DiscordDungeons/Bugs#292]
So, I was viewing one of my member's stats, and everything is fine, except it said MY name, not his to reset stats. I had already reset my stats. I don't know if you can view this, but here is a picture...

https://media.discordapp.net/attachments/343156005812568064/349754293965946891/Screenshot_2017-08-22_at_10.18.03_PM.png?width=400&height=273

**Comment by Sven65** [comment]
Interesting bug, will look into.
