### ISSUE TITLE
Strength (as far as I know only strength) is not properly calculated

### ISSUE THREAD

**Issue by SJCs2** [DiscordDungeons/Bugs#293]
When one of the users put 1000 points into strength, they only saw a 100 base dmg increase instead of the 100% increase (double dmg) they were supposed to get. I think the dmg formula may still be using the old code? 

without 1000 in strength:
https://cdn.discordapp.com/attachments/172389002190651393/349893003868897282/image.png

with 1000 in strength:
https://cdn.discordapp.com/attachments/172389002190651393/349893010630377473/image.png

(it's a 200dmg difference cause it's a crit strike for both)

**Comment by FakePeer** [comment]
Also defense too. Even you assign 1000 on defense you still get damaged. https://cdn.discordapp.com/attachments/172389002190651393/349950141530243072/image.png
