### ISSUE TITLE
Trying to assign but comes out invalid

### ISSUE THREAD

**Issue by CookiesSun** [DiscordDungeons/Bugs#295]
Im trying to assign points but it says invalid points

**Comment by CookiesSun** [comment]
![screenshot_2017-08-23-23-27-47](https://user-images.githubusercontent.com/31300018/29648419-05e7c2a0-885c-11e7-948f-5a38f38f74aa.png)
![screenshot_2017-08-23-23-27-54](https://user-images.githubusercontent.com/31300018/29648428-125b8350-885c-11e7-8193-2b9d18131cdf.png)

**Comment by ArmouredCavefish** [comment]
There is no luck anymore
There is only:
Scavenging
XP boost
Gold boost
Criticals
Salvaging
Mine boost
Lumber boost
Reaping
Strength
Defense
And Taming

**Comment by Sven65** [comment]
Not an issue, user error, check #!attributes

**Comment by CookiesSun** [comment]
But im still having problems with the other attrbutes
![screenshot_2017-08-24-07-51-34](https://user-images.githubusercontent.com/31300018/29665258-4786c2e8-88a1-11e7-98a9-32a2811208b6.png)
