### ISSUE TITLE
Mine Boost Not Functioning

### ISSUE THREAD

**Issue by ArmouredCavefish** [DiscordDungeons/Bugs#296]
I have assigned 30 Points to Mine boost and my mining skill is lvl 4, I am still getting 5 rocks, iron ore, etc. Mine boost is not adding up the value from how much I get from #!mine, please fix this!

**Comment by Sven65** [comment]
The amount of items gotten from mining varies on your skill level and the amount of points you have in mineBoost, generally starting at +1 item per 40 points.
