### ISSUE TITLE
The ally problem

### ISSUE THREAD

**Issue by TehShadowGamer** [DiscordDungeons/Bugs#300]
ok so i only have one ally and i try to ally another guild and it says i cant get more and the maximum is 3 

here is the screenshot: https://gyazo.com/38dfd9f08163304a1f164038fb288ce6

**Comment by Sven65** [comment]
Message me on Discord; Mackan#7196

**Comment by Sven65** [comment]
Issue caused when guild has allies that don't exist anymore.

**Comment by Sven65** [comment]
Fixed.
