### ISSUE TITLE
Skip turn in party adventure when healing

### ISSUE THREAD

**Issue by knightdestin** [DiscordDungeons/Bugs#307]
When someone heals himself it skipps turn of the one who has the token. Idk if intended or not, but weird.

**Comment by Sven65** [comment]
So, when the current user that has the turn uses `#!heal`, it skips their turn?

**Comment by knightdestin** [comment]
More ss about this bug, seems appear in party when we were 3. Tried after at 2, no bugs.

![bug11](https://user-images.githubusercontent.com/31276990/29729761-ce005590-89dd-11e7-872b-2c59316fb208.png)
![bug12](https://user-images.githubusercontent.com/31276990/29729766-d09f2dee-89dd-11e7-9749-1f8ffc48db71.png)

**Comment by Sven65** [comment]
When a user heals if it's not their turn the turn gets skipped back to the previous player.

**Comment by Sven65** [comment]
Fixed.
