### ISSUE TITLE
Lost turn in party adventure

### ISSUE THREAD

**Issue by knightdestin** [DiscordDungeons/Bugs#308]
Saw this bug in a 3-ppl padv : 
Someone who didn't have the token tried a padv, but on cd, so error msg. Other one do his padv (really really near in time after the one who got the error msg), so the next one who should have the token is the one who had the error cd msg, but bot said not his turn. And for a reason we don't know, the token went back to the only ppl of us who did the padv (so 2 ppl lost their token).

Not really clear, sorry....

**Comment by Sven65** [comment]
Uh, unsure what you mind, think you could clarify with steps of how to reproduce it?

**Comment by knightdestin** [comment]
Sorry was afk, here is some screenshots about the issue.

![bug1](https://user-images.githubusercontent.com/31276990/29729048-dcab9828-89da-11e7-9c36-9967b0533736.png)
![bug2](https://user-images.githubusercontent.com/31276990/29729053-dfc17c30-89da-11e7-9a96-e18a3b2a95f9.png)

**Comment by Sven65** [comment]
Thanks, we'll look into it.

**Comment by Tehmaxx** [comment]
It seems to just be losing the turn completely.

http://i.imgur.com/hjMclIf.png

**Comment by Sven65** [comment]
We're looking into it in #317, follow that issue for more info.
