### ISSUE TITLE
Side-activity bug

### ISSUE THREAD

**Issue by Rosenkreuz12** [DiscordDungeons/Bugs#31]
http://i.imgur.com/RerIa1t.png?1
http://i.imgur.com/c6IVAmf.png?1
http://i.imgur.com/titFEKK.png?1
http://i.imgur.com/s8fwD2d.png?1
http://i.imgur.com/21E23dV.png?1

simply put i can do side-activities on 3 different server at same time and get all 3 results

**Comment by Sven65** [comment]
Must be a sharding issue, need to fix ASAP

**Comment by Rosenkreuz12** [comment]
apparently said thing not limited to side-activity, it's also possible to adventure

**Comment by Sven65** [comment]
Yeah. I've since fixed it.
