### ISSUE TITLE
Party enemy reset mid adventure

### ISSUE THREAD

**Issue by Laysfamilysized** [DiscordDungeons/Bugs#310]
![screenshot_20170825-222557](https://user-images.githubusercontent.com/31356689/29729623-98180722-89e5-11e7-95a9-9477f477cca0.png)
![screenshot_20170825-222601](https://user-images.githubusercontent.com/31356689/29729628-9f4f4a82-89e5-11e7-8e34-dc7477155aa3.png)
I have no idea how this happens or why, but it happened twice so far.

**Comment by Sven65** [comment]
Fixed
