### ISSUE TITLE
Wrong Grammar

### ISSUE THREAD

**Issue by Owennnnnn** [DiscordDungeons/Bugs#312]
When you catch an octopus it says a octopus

**Comment by PlayTheFallen** [comment]
Prefered plural is Octopi, but greeks say that Octopus shares the same plural rule as the word sheep.
¯\_(ツ)_/¯

*[Reference](https://www.infoplease.com/askeds/plural-octopus)*

**Comment by Owennnnnn** [comment]
What I mean is it says a octopus instead of an octopus, because it is supposed to be an before a word that starts with a vowel.

**Comment by tklaxbro** [comment]
Seems like a replica of #129 but they still probably don't care to fix it (not complaining), they are just busy working on parties atm.

**Comment by Owennnnnn** [comment]
ok

**Comment by Pyrrhus76** [comment]
I wont go into a history lesson on the word octopi but There are 3 plural words used for octopus which are today acknowledged as correct; Octopuses, Octopi, and  Octopodes. Octopi being the less correct of the 3.

**Comment by Sven65** [comment]
It's octopi, it's correct, see [here](https://en.wiktionary.org/wiki/octopi).

**Comment by Owennnnnn** [comment]
Yes what I meant was it says **_a_** octopus instead of **_an_** octopus

**Comment by Sven65** [comment]
Oh, okay.

**Comment by Pyrrhus76** [comment]
https://www.merriam-webster.com/video/octopus

**Comment by Sven65** [comment]
Will fix in a bit
