### ISSUE TITLE
Achievement "untouchable"

### ISSUE THREAD

**Issue by Tehmaxx** [DiscordDungeons/Bugs#314]
Achievement requires 1000 defense

Bot Limits you to 800

**Comment by FelixCATus** [comment]
Image below shows that I've assigned 1000 points to defense at 0/after using attribute scroll, points wasted as the 800 points in defense limit works, should check if value entered is beyond 800.
![image](https://user-images.githubusercontent.com/23120572/29820082-c9974b88-8cf5-11e7-993d-36da25e9b1ca.png)

And as the user above stated, there's such achievement but I do not get that achievement after assigning 1000 points in.

**Comment by Sven65** [comment]
Fixed.
