### ISSUE TITLE
Party adventures sometimes get mixed up

### ISSUE THREAD

**Issue by Pyrrhus76** [DiscordDungeons/Bugs#317]
While doing combat in a party, the turn will leave our party and go to someone else in a different party preventing us from continuing our battle.

**Comment by PlayTheFallen** [comment]
@Pyrrhus76 Can you post a screenshot of this happening?

**Comment by FelixArgyle** [comment]
Mackan , I think that whilst being in a party group and other users with other party groups are in the same server it mixes the parties up , as said by Added Effects he has not had the bug happened to him whilst his group is the only group using parties in that server he is listed on  , p.s. Fallen Mackan knows of the bug issue and just said to create a post title on github with this title and no other information.

**Comment by Pyrrhus76** [comment]
Thanks Felix, yes Mackan asked that we make a post titled as I did. If you still need screenshots, I can get it for you.

**Comment by Sven65** [comment]
Yeah, screenshots woukld be great, aswell as as much info that can be gathered about the issue

**Comment by Sven65** [comment]
Do you know if it happens at a specific point of party adventures?

Like, does it happen when the mob is killed or at some other point?

**Comment by Pyrrhus76** [comment]
![sh1](https://user-images.githubusercontent.com/31291237/29748535-b94e7eba-8ae6-11e7-93c4-7d28869766c4.jpg)
![sh2](https://user-images.githubusercontent.com/31291237/29748537-b94f3dc8-8ae6-11e7-82c9-73c62d250443.jpg)
![sh3](https://user-images.githubusercontent.com/31291237/29748536-b94f2e46-8ae6-11e7-9c84-75e156e9b3e5.jpg)
![sh4](https://user-images.githubusercontent.com/31291237/29748538-b94f808a-8ae6-11e7-8d2e-38ce0ee579e5.jpg)
![sh5](https://user-images.githubusercontent.com/31291237/29748539-b94fa38a-8ae6-11e7-9ee5-e462daa9fe3e.jpg)
![sh6](https://user-images.githubusercontent.com/31291237/29748540-b94fffa6-8ae6-11e7-8025-2c69268f3a43.jpg)
![sh7](https://user-images.githubusercontent.com/31291237/29748541-b958f782-8ae6-11e7-8c75-7340c8142714.jpg)
![sh8](https://user-images.githubusercontent.com/31291237/29748543-b95a9f06-8ae6-11e7-9f78-7e8763452f09.jpg)
![sh9](https://user-images.githubusercontent.com/31291237/29748542-b95a4556-8ae6-11e7-9477-c0defe6f9509.jpg)

**Comment by Pyrrhus76** [comment]
Those screenshots show what happened from the start of the party up until it broke on us. Apparently @TruTh5502#0128 who was in a party all together, got mixed in with our group but could still actively participate in his group. Also, while he was able to actively participate in his group, he could not advance ours. Might want to reach out and get screenshots of his parties actions during the time we had our bug happen.

**Comment by FelixArgyle** [comment]
From my point of view it happens when there is another party group on the same Discord server what are adventuring , it seems to just randomly happen mid party adventure. But it  seems to work fine if there is no other party on the same discord server you are on.
