### ISSUE TITLE
Party adventure doesn't work with pet xp.

### ISSUE THREAD

**Issue by Naoeaoe** [DiscordDungeons/Bugs#318]
![2017-08-26 17_21_23- game - discord](https://user-images.githubusercontent.com/29278305/29742186-16183410-8a83-11e7-9ea3-aa75e3b26f43.png) 
![2017-08-26 17_21_36- game - discord](https://user-images.githubusercontent.com/29278305/29742191-2f795db2-8a83-11e7-8f89-e7476eb6ca99.png)

**Comment by Sven65** [comment]
Clarification; Pet XPRate works, but the pet doesn't get the XP.

**Comment by Sven65** [comment]
Fixed.
