### ISSUE TITLE
Scavenging Attribute Not Working

### ISSUE THREAD

**Issue by Owennnnnn** [DiscordDungeons/Bugs#320]
According to the wiki the attribute scavenging provides a 1:1 bonus of foraging output.  Since I am level 5 foraging and I have 5 points in  scavenging it  should output 11 but only gives 6 for the level 5 foraging.
![discordrpgforage](https://user-images.githubusercontent.com/27851824/29745521-6479888a-8a82-11e7-9824-f127ceb37794.PNG)

**Comment by ArmouredCavefish** [comment]
Uhhh You got it wrong... The formula is actually 
40 points = +1 eggs, lemons, apples, etc.
Not +1 for every point

**Comment by Owennnnnn** [comment]
Oh ok the wiki is wrong I guess then.  It does say "This page currently in the process of being written."
