### ISSUE TITLE
Pet Bugged

### ISSUE THREAD

**Issue by ArmouredCavefish** [DiscordDungeons/Bugs#321]
https://media.discordapp.net/attachments/351000864422625281/351151026843418636/Screenshot_20170827-074632.jpg <~~~~~~ this happens when Im trying to lvl up my pet? It goes over the exp requirement but it doesnt lvl up...

**Comment by FelixArgyle** [comment]
Screenshot link is dead @ArmouredCavefish 
![b06ff6](https://user-images.githubusercontent.com/12903523/29745964-e52664c8-8ac1-11e7-87bf-c82e0e16c46a.png)
 , Upload it by attaching a file at the bottom of the post, here 
![66e785](https://user-images.githubusercontent.com/12903523/29745967-064131d8-8ac2-11e7-9d86-0a251f2c3bcf.png)

**Comment by ArmouredCavefish** [comment]
https://media.discordapp.net/attachments/351000864422625281/351152262841892875/Screenshot_20170827-074632.jpg

**Comment by ArmouredCavefish** [comment]
There @FelixArgyle ^

**Comment by Sven65** [comment]
What command did it happen with?

**Comment by ArmouredCavefish** [comment]
When I did #!ladv, we beated the monster, then that happen,it didnt level up..

**Comment by ArmouredCavefish** [comment]
#!padv*

**Comment by Sven65** [comment]
Mkay, so it's the same as in #318?

**Comment by ArmouredCavefish** [comment]
The pet got exp, but it didnt level up and if we beated a monsters again it doesnt get the exp

**Comment by ArmouredCavefish** [comment]
Monster*

**Comment by Naoeaoe** [comment]
This now happens to your character in party adventures as well.
![2017-08-27 13_26_50- game - discord](https://user-images.githubusercontent.com/29278305/29749035-d2d4449c-8b2b-11e7-9d43-5173a3419161.png)

**Comment by RJain12** [comment]
You probably already figured this out but you'll have to give your pet some xp. Give it any amount of xprate and then do an adventure. Good luck!

**Comment by Sven65** [comment]
Fixed.
