### ISSUE TITLE
Leveling during a Party Issue

### ISSUE THREAD

**Issue by Pyrrhus76** [DiscordDungeons/Bugs#323]
When you gain more xp than you need to finish off your level, you will go past the xp requirements and not level up. It will take 1-2 more kills for it to recognize that you exceeded the xp requirements.

**Comment by Pyrrhus76** [comment]
![leveling bug](https://user-images.githubusercontent.com/31291237/29751723-2eb497c4-8b1f-11e7-842a-b26e143bb481.JPG)

**Comment by RJain12** [comment]
You don't need multiple kills, if this is an issue, while it is getting fixed, you can do a side activity like mine, and the small gain of xp should level you up.

**Comment by Sven65** [comment]
Fixed.
