### ISSUE TITLE
Gmglist trades glitched

### ISSUE THREAD

**Issue by RJain12** [DiscordDungeons/Bugs#324]
< 2 Iron Ores (50G each) {ID. j6va2fp9} [4 sold] >

2 Iron Ores
Offered by
Lace6754
Trade ID
j6va2fp9
Price
50 gold each
Sold
4 out of 2

**Comment by RJain12** [comment]
Shows on both Gmglist and when you search for iron using gmsearch.

**Comment by PlayTheFallen** [comment]
Screenshot?

**Comment by Sven65** [comment]
No more info was given.
