### ISSUE TITLE
Party Mention issues

### ISSUE THREAD

**Issue by Friendly777** [DiscordDungeons/Bugs#327]
![image](https://user-images.githubusercontent.com/29890152/29816944-2a117a56-8cf1-11e7-8dbb-8dbe9edcc070.png) The bot mentions the user that just did his turn.

**Comment by karasu52893** [comment]
Yeah this is what I mean cloned padv, doubled my turn every start of the party.

**Comment by Friendly777** [comment]
Ok. So it will be fixed.

**Comment by Friendly777** [comment]
Ok then.

**Comment by Sven65** [comment]
Known issue, unknown cause.

**Comment by Sven65** [comment]
Fixed.
