### ISSUE TITLE
Party commands

### ISSUE THREAD

**Issue by Tehmaxx** [DiscordDungeons/Bugs#329]
The #!commands menu only gives the follow commands for parties

[Parties]
padv, party

#!help party doesn't include padv but does include 4 n/a    commands?

http://i.imgur.com/5dOJk2h.png

**Comment by Sven65** [comment]
`party` and `padv` are their own commands.
The values of the `#!help party` command are values for the subcommands in `Variables`.
Having a value of `N/A` means no arguments are applicable.
