### ISSUE TITLE
Pet Damage Output

### ISSUE THREAD

**Issue by cj44579** [DiscordDungeons/Bugs#332]
So, Im having a problem with the pets that I catch. I've just recently Turned to level 24 and all the pets Ive Caught After Leveling up, Have their damage output reset back to 2-5. There was a bit of a delay when I tried getting the pet's stats. I'd do the "#!pet" command and It would take several minutes to get it's stats.

![](https://cdn.discordapp.com/attachments/298955020232032258/352877525153873922/Screenshot_20170831-110858.png)

Bored Shuzi~Sama (Never Senpai) #6578

**`EDIT`**
**Date:** 28th Sep 2017
**Editor:** @PlayTheFallen
**Reason:** Added image preview to issue description.

**Comment by Tehmaxx** [comment]
Not a bug, you caught a dynamic mob instead of a static one.

**Comment by cj44579** [comment]
Well, What's the difference Between them?
