### ISSUE TITLE
[SUGGESTION] Status Effects

### ISSUE THREAD

**Issue by Sven65** [DiscordDungeons/Bugs#335]

**Comment by reddragon548** [comment]
Maybe on a charge system where you gain X~Y charge per attack and when you reached Z charge, Your next attack will enhanced, granting you status effects on your attack like increased damage or make enemy bleed which they receive damage every turn or boosting the reward. And which status effect on attack, maybe random or a Skill tree where you can level using your skill point which worked seperately from attribute points. Allowing you to go for what you like.

**Comment by dibli-goost** [comment]
I think it could be like an opposite health meter, when you attack a mob the meter gets a couple of points put into it, when it reaches 100 the effect takes place. 
(Ex, Frost Sword is equipped, when you attack an enemy the enemy will start to gain frostbite (depending on the weapon and skill the amount of frostbite will vary) The enemy gets attacked enough with that sword the enemy gets frostbite and can have a turn every two turns.)

Enemys can only have one status effect active at a time.

Every turn the amount of status effect will go down a random amount, when it reaches 0 it will end.

Some ideas for status effects:
 -Frostbite, enemy can only attack every 2 turns
 -Bleeding, 2x damage against enemy
 -Poison, specific amount of damage every turn
