### ISSUE TITLE
#!gmsell wont recognize item

### ISSUE THREAD

**Issue by Thekingofsocks** [DiscordDungeons/Bugs#336]
![screenshot 2017-09-13 at 11 23 23 am](https://user-images.githubusercontent.com/31930412/30385847-543fd0a8-9876-11e7-83dc-9c5b496584f7.png)

**Comment by FelixArgyle** [comment]
Use "#!gmsell magy's scythe 1 30000" and your problem should be fixed , using variable such as 30k would not proceed to work with Global market
