### ISSUE TITLE
I can't sell my lemons

### ISSUE THREAD

**Issue by Shadowonwater** [DiscordDungeons/Bugs#337]
Kind of self explanatory. Whenever I type "#!sell lemon" nothing happens.

**Comment by FelixArgyle** [comment]
Lemons cannot be sold ,  Although you can trade them on the market.
It's best to use  "#!gbsearch lemon"  this will show a list of trades where users want to buy lemons. > to sell your lemons to a trade you would use "#!gbsell TradeID Amount"  You would get a hold of the trade id by viewing the search list.
