### ISSUE TITLE
gmglist is broken

### ISSUE THREAD

**Issue by DeMiDeWa** [DiscordDungeons/Bugs#342]
> Whoops. An error occured. Please report this in the official server.
> ReferenceError: user is not defined
>     at Gmglist.Execute (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmglist.js:69:3)
>     at client.cache.hset.then (/home/mackan/RPGBot/src/Handlers/messageCreate.js:147:18)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by Sven65** [comment]
Fixed
