### ISSUE TITLE
Negative amount of members in guild

### ISSUE THREAD

**Issue by RJain12** [DiscordDungeons/Bugs#344]
I have no idea on how this happened but see image.
![screenshot 2017-09-18 at 9 53 27 pm](https://user-images.githubusercontent.com/29895437/30576317-e57d3a58-9cbb-11e7-9f11-3e6f4824ab19.png)

**Comment by Sven65** [comment]
What commands did you use? How did you get the issue?

**Comment by RJain12** [comment]
I just did "#!guild Hidden Weaf" at first, then around 30 seconds later, I did it again: "#!guild Hidden Weaf" and it showed -1 members.

**Comment by RJain12** [comment]
I found the reason as to why it happened. There were two users in the guild, one was elder while the other was owner. The owner made the elder the new owner. Then, the old owner (new elder) left the guild.

**Comment by Sven65** [comment]
I see, thanks.

**Comment by Sven65** [comment]
Is this still an issue? If so, please open a new one.
