### ISSUE TITLE
Party Bug

### ISSUE THREAD

**Issue by RJain12** [DiscordDungeons/Bugs#346]
When someone leaves right before it's their turn right after the person does #!padv but it's not their turn yet, theres a bug and it says it's their turn when that person isn't in the party. When #!party is done, there's no error pointing to the person's turn. See images attached.
![screenshot 2017-09-23 at 7 40 49 pm](https://user-images.githubusercontent.com/29895437/30778969-5ea799a8-a097-11e7-9fc6-e083e64c9b2d.png)
![screenshot 2017-09-23 at 7 40 43 pm](https://user-images.githubusercontent.com/29895437/30778971-5ea9a216-a097-11e7-870c-e3ae9601ac14.png)
![screenshot 2017-09-23 at 7 40 22 pm](https://user-images.githubusercontent.com/29895437/30778970-5ea99712-a097-11e7-8dd1-296e91cfa748.png)
![screenshot 2017-09-23 at 7 40 17 pm](https://user-images.githubusercontent.com/29895437/30778972-5eaa10e8-a097-11e7-946f-31c65129461e.png)
![screenshot 2017-09-23 at 7 40 04 pm](https://user-images.githubusercontent.com/29895437/30778974-5eaa98ba-a097-11e7-90d7-b51773e99d02.png)
![screenshot 2017-09-23 at 7 39 41 pm](https://user-images.githubusercontent.com/29895437/30778973-5eaa777c-a097-11e7-9f90-d2eee775ff04.png)

**Comment by Sven65** [comment]
Fixed.
