### ISSUE TITLE
Sell Lemons >.>

### ISSUE THREAD

**Issue by MrBryBrain** [DiscordDungeons/Bugs#349]
I just added the bot to my discord server and it wont seem to let me sell lemons

i have been using the command correctly

#!sell lemon 4

cause I have 6 lemons in my inventory.

**Comment by FelixArgyle** [comment]
@MrBryBrain Lemons can not be sold with "#!sell" , they can however be traded on the market if you use "#!gbsearch lemon" > "#!gbsell tradeID quantity"

**Comment by MrBryBrain** [comment]
arigto gozaimasta ;)
