### ISSUE TITLE
Non-Responsive Bot / Ignoring computer ID (READ COMMENTS)

### ISSUE THREAD

**Issue by FlamePrince** [DiscordDungeons/Bugs#35]
![nonresponse](https://cloud.githubusercontent.com/assets/18062412/18656837/1167d3b8-7ecb-11e6-94e0-25ecc553a962.png)

**Bryce#0298** reported his bot unresponsive starting at 8pm AST. 
**FlamePrince#4237** reported his bot unresponsive starting at 8pm AST. 
**Whuppo#3825** reported his bot unresponsive at 7PM AST. 
**Wesp#2507** reported his bot unresponsive at 9PM AST.

- Prefix has not been changed.
- DDRPG's bot is working fine.
- No commands work for anyone - including #!ping and #!prefix commands.
- Kicking and reinviting the bot does not rectify this issue.
- Making an entire new Discord server does not rectify this issue.

**Comment by FlamePrince** [comment]
![prefix](https://cloud.githubusercontent.com/assets/18062412/18657059/16a9da22-7ecd-11e6-8819-d9cabb93c950.png)

Set up personal test server. Bot functioning fine with no extra permissions. Ignored me setting prefix to "."

**Comment by FlamePrince** [comment]
Bryce#0298's bot's perms:
https://goo.gl/UfNmiq
https://goo.gl/OKJAV
https://goo.gl/aFyIw5r

**Comment by FlamePrince** [comment]
TimerChan acknowleges the prefix and its' changes, as well if you're of proper role. It acknowledges any change of prefix and will use that new prefix to identify when you try #!setprefix'ing again. No response from DiscordRPG bot when using the #!setprefix command.

![prefix2](https://cloud.githubusercontent.com/assets/18062412/18657427/92681c70-7ed0-11e6-9a11-c120fe134595.png)

**Comment by FlamePrince** [comment]
![responsive](https://cloud.githubusercontent.com/assets/18062412/18657949/357615c6-7ed5-11e6-8b46-944b94da8b26.png)

![responsive](https://cloud.githubusercontent.com/assets/18062412/18658011/b994c10e-7ed5-11e6-8604-9691cff369bc.png)

**Comment by FlamePrince** [comment]
Speculation: When an *infected* person attempts to use the bot before anyone else has, it will terminate that bot's responsiveness in that server. This was observed when I - who had no issues with making servers with functioning DRPG bots - made a server that an *infected* person used the bot first. This ceased the bot from working on that server, no matter what I did.

Avoiding *infection* can be as easy as switching computers and making a new server, or could require a whole new account + a different computer while making a brand new server.

**Comment by SnazzyPine25** [comment]
There is a chance that that server is ignored, but I would have to check myself.
I don't know what causes this but it won't be overlooked.

**Comment by Sven65** [comment]
If the server is ignored, it needs to have the type of 'server' in the ignore table. Can you provide us with the ID's of the users?

**Comment by whuppo** [comment]
The bot on my server managed to fix itself..?

![](http://puu.sh/rhwU8/0447b9a55c.png)

**Comment by Sven65** [comment]
I restarted the bot and it seems to be fixed.

**Comment by Sven65** [comment]
Issue is fixed.
