### ISSUE TITLE
Reactions for paging through conversations are in the wrong order

### ISSUE THREAD

**Issue by Punknoodles** [DiscordDungeons/Bugs#351]
They end up as 3, 2, 1.

**Comment by Sven65** [comment]
Once again, not much I can do as all reactions are done in one go, then put in that order by the Discord API

**Comment by Punknoodles** [comment]
Oh. Well, at least visually they pop up one after another so I thought it was just sending them one by one.

**Comment by Sven65** [comment]
It is, but I send them in bursts, the library sends them one by one.

**Comment by Punknoodles** [comment]
Hmm... I've been thinking about this some more, and prototyped it in my own bot... message.react with the reaction, and .then with a callback to add the next emoji in the order? This way you make sure one is done before sending the next. I dunno if this will put a lot of stress on the bot though.
