### ISSUE TITLE
Doing sides while traveling shouldn't reset cooldown

### ISSUE THREAD

**Issue by Punknoodles** [DiscordDungeons/Bugs#352]
Currently, if you do a side while traveling (chop, mine, fish, forage, etc.) and it fails because you are traveling, it resets the cooldown and you have to do it again in 5 minutes. If you are traveling and do the command, it shouldn't stop the cooldown.

**Comment by Sven65** [comment]
Unfortunately, with the way the system is setup right now, all cooldowns are handled the same.

If you execute a command, it triggers the cooldown, resetting it directly after it's been set isn't viable right now.

**Comment by Punknoodles** [comment]
Hmm, that's too bad.

**Comment by Sven65** [comment]
Done.
