### ISSUE TITLE
Location should be displayed upon arrival

### ISSUE THREAD

**Issue by Punknoodles** [DiscordDungeons/Bugs#353]
When you arrive at a location and do `#!location`, it just tells you that you've arrived, then you have to wait for the cooldown before you can check out the location. Perhaps these could be merged into one?

**Comment by PlayTheFallen** [comment]
```js
message.channel.send('Start journey');
setTimeout(() => {
  message.channel.send('End journey');
}, travelTime);
```
*example for devs... (since i can't post on trello)*

**Comment by Sven65** [comment]
Imagine having a timeout for 2500+ users at a single time.

**Comment by PlayTheFallen** [comment]
*Personally* I think it's better to just post when the command is run ~~else b1nzy will be after all of us~~.

**Comment by Punknoodles** [comment]
@PlayTheFallen that's what I meant. If you've arrived but haven't done any commands, any command that would tell you `notme has arrived at Rivermouth!` should also, appended to the message, include the location embed. Maybe the title was read as `Automatically post location info on arrival`, but I meant the above.

**Comment by Sven65** [comment]
I see, that can be done

**Comment by holroy** [comment]
Would it be possible to also complete the command which triggered the "has arrived" message? Like, if you do an `#!adv`, it could first show "arrived at location", and then it actually would complete the requested `#!adv` (or whatever command you entered). This would also circumvent the other bug related to triggering the cooldown "falsely" when doing commands when travelling.

**Comment by Sven65** [comment]
Done.
