### ISSUE TITLE
Other reacting to quests

### ISSUE THREAD

**Issue by RJain12** [DiscordDungeons/Bugs#354]
When other people react to the emoji on a quest, it can be quite frustrating because other users purposely do it to annoy the one who is trying to do the quest.
![screenshot 2017-09-26 at 8 55 50 pm](https://user-images.githubusercontent.com/29895437/30895150-253532d0-a2fd-11e7-85bf-fea793310ce3.png)

**Comment by Sven65** [comment]
That's nothing I can do anything about.

Others using the reactions is already handled as invalid, thus not advancing the storyline.
