### ISSUE TITLE
The discord mobil app can't link

### ISSUE THREAD

**Issue by GuerreroCraft61** [DiscordDungeons/Bugs#358]
**Please describe your issue below.**  

The discord mobil app can't link
**If an error is provided, please copy the block into the space below.**

```js

< The discord mobil app can't link >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by ryudragon98** [comment]
the app is broken and has been broken for a while.

**Comment by Sven65** [comment]
Known issue. Link servers are dead.
