### ISSUE TITLE
New players unable to do side activities or check skills.

### ISSUE THREAD

**Issue by FlamePrince** [DiscordDungeons/Bugs#36]
Syro#3703 could not use #!skills/#!mine/#!chop etc. This had nothing to do with unassigned points and appeared to be in the specific person's stats generation. When they #!reset, it resolved the issue.

![newplayer](https://cloud.githubusercontent.com/assets/18062412/18672746/b849d74a-7f1f-11e6-9342-5ca0a3f0b61f.png)

Player also had an error message when he tried to reset.

![resetyes](https://cloud.githubusercontent.com/assets/18062412/18688300/1452bdc4-7f5a-11e6-9605-4cc874df3de7.png)

**Comment by Sven65** [comment]
Are you sure the player was new, or has the player gotten their stats before?

**Comment by FlamePrince** [comment]
The player was new, but had had his stats. In either case, it should have reported the error message.

**Comment by Sven65** [comment]
That's the reason behind the stats issue, the user didn't have any so the bot couldn't check them.
I'll add some checks for it later.

**Comment by Sven65** [comment]
Fixed.
