### ISSUE TITLE
Error while talking to wendell

### ISSUE THREAD

**Issue by AlphaMyth** [DiscordDungeons/Bugs#361]
>Whoops. An error occured. Please report this in the official server.
>```js
>TypeError: message.channel.permissionsFor is not a function
>    at Talk.prepareDialog (/home/mackan/RPGBot/src/Commands/Commands/Locations/Talk.js:116:24)
>    at getNPCByName.then.results 
>(/home/mackan/RPGBot/src/Commands/Commands/Locations/Talk.js:238:25)
>    at <anonymous>
>```
note that this only happens when using a private chat

**Comment by PlayTheFallen** [comment]
because you DMs don't have permissions... only servers do
same as #365 even though this one was made before it.
