### ISSUE TITLE
Item "doesn't exist" while in inventory and now disappeared from inventory. 

### ISSUE THREAD

**Issue by AJKinney1234** [DiscordDungeons/Bugs#364]
Was using the mining skill and got some weird named ores and couldn't sell them and now they disappeared from my inventory and do not exist.
![screenshot 2017-10-04 at 2 02 09 pm](https://user-images.githubusercontent.com/32523332/31191880-954c8210-a90d-11e7-99ac-6c6760e01c83.png)

**Comment by PlayTheFallen** [comment]
use single pronunciation instead of plural  
in your case - `=item Erinotite Ore` instead of `=item Erinotite Ores` *tl;dr the item command wasn't made for plural matching*
