### ISSUE TITLE
Error with Wendell Question Completion

### ISSUE THREAD

**Issue by Matt5351** [DiscordDungeons/Bugs#365]
**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```diff
!====[Matt's conversation]====!
+ Wendell - Great! Now I need you to bring those items to Scarlett at the temple.
!=============================!
```
```js
DiscordAPIError: Missing Access
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:68:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:183:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by PlayTheFallen** [comment]
the bot is missing reaction permissions

**Comment by PlayTheFallen** [comment]
Copy of #361
