### ISSUE TITLE
Pets unable to get xp during party adventures

### ISSUE THREAD

**Issue by GamerzBeHatin** [DiscordDungeons/Bugs#368]
I'm in a party with 1 other person and I have my pet xprate set to 90%, but when a mob is killed, the xp for my pet doesn't increase.
Screenshots of multiple kills not raising xp:
http://prntscr.com/gtuey7
http://prntscr.com/gtuf43
http://prntscr.com/gtuf6x
http://prntscr.com/gtufb8

**Comment by tklaxbro** [comment]
Said in #318
