### ISSUE TITLE
Wesp#2507

### ISSUE THREAD

**Issue by FlamePrince** [DiscordDungeons/Bugs#37]
This issue was reported today at 10AM EST.

![stats](https://cloud.githubusercontent.com/assets/18062412/18672903/4bccbfc8-7f20-11e6-9b30-11deea0605b6.jpg)

![stats2](https://cloud.githubusercontent.com/assets/18062412/18672905/4ce2a828-7f20-11e6-8567-0403efa4f2d4.jpg)

![stats3](https://cloud.githubusercontent.com/assets/18062412/18672911/4eec31de-7f20-11e6-9bb6-f758151bcb63.jpg)

**Comment by Sven65** [comment]
What's the issue?

**Comment by FlamePrince** [comment]
In a span of ten minutes, he went from Level 15 to Level 19.

**Comment by Sven65** [comment]
Huh. I'll look into it.

**Comment by Sven65** [comment]
Fixed.
