### ISSUE TITLE
Couldn't travel back to mournstead

### ISSUE THREAD

**Issue by ryukyo06** [DiscordDungeons/Bugs#371]
**Please describe your issue below.**  

I was looking for quest and I travel from silverkeep to mournstead and then to Rivermouth after that I saw the Island of Desolation but I didn't know it was for members only then after trying to go there, I was supposed to travel back to mournstead yet I couldn't go back there....

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
Uh, what

**Comment by Sven65** [comment]
Closed as more info was not given.
