### ISSUE TITLE
Green Dragons get one shot no matter what, even with dynamob and weak weapon

### ISSUE THREAD

**Issue by toastyonyt** [DiscordDungeons/Bugs#374]
When #!adving, Green Dragons are always a one shot with me, no matter what pet or weapon I use. Unable to catch them as a pet due to this bug.

![](https://i.gyazo.com/340514b232047446b6ea1e2a68fcd338.png)
![](https://i.gyazo.com/ac1487addee178417595f7c32e370593.png)
![](https://i.gyazo.com/6fdf5ccb1f14ef653f9061e81256f69f.png)

**EDIT**
**Editor:** @PlayTheFallen
**Reason:** Render images on the page.
**Time:** 14:04 GMT London | 10th Oct 2017

**Comment by Sven65** [comment]
Does this happen to anyone else?

**Comment by toastyonyt** [comment]
It's happening to Felix too.

**Comment by Sven65** [comment]
I see.

**Comment by Sven65** [comment]
No more info was given.
