### ISSUE TITLE
About Yeti Quest

### ISSUE THREAD

**Issue by MrPumpkinHeadFromDrpg** [DiscordDungeons/Bugs#376]
**Please describe your issue below.**  
I started the yeti quest And Then I died cause of not noticing my health and when i came back to life the yeti was gone and it didn't even reset his health or anything. Basically, I couldn't do the quest.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( <https://cdn.discordapp.com/attachments/356171037815209998/367498953547055109/2017.10.11_.05.28.47.png, https://cdn.discordapp.com/attachments/356171037815209998/367499084371591169/2017.10.11_.05.29.01.png, https://cdn.discordapp.com/attachments/356171037815209998/367499173005754369/2017.10.11_.05.29.19.png )

**Comment by Sven65** [comment]
I'll be adding a quest management command later today, which will allow you to restart the quest.

**Comment by Hiroshi-22812** [comment]
Cold North Quest:
While fighting the yeti, the NPC (Illyena) says "Undefined" if you try to talk to her.

**Comment by SamuiNe** [comment]
@Hiroshi-22812 post it as new issue, as it is different to the current issue. Thanks!

**Comment by Sven65** [comment]
You can now use the `#!quest` command to restart your quest.
