### ISSUE TITLE
random one shot at lvl 8

### ISSUE THREAD

**Issue by thereallol4** [DiscordDungeons/Bugs#377]
**Please describe your issue below.**  
i was doing a regular adventure and then i healed myself and it healed me twice and then i did the adv command and got oneshot and im only lvl 8 it took 16k gold

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < 
![image](https://user-images.githubusercontent.com/32694449/31421781-fa828412-ae0e-11e7-8dc7-567202d7f80c.png)
 > )

**Comment by Sven65** [comment]
Related to #386
