### ISSUE TITLE
#!Buy item bug

### ISSUE THREAD

**Issue by Benjymar** [DiscordDungeons/Bugs#378]
I bought a leather belt, but it did not show up in inventory. money/gold was taken from account, however.

can you fix this?
DiscordRPGBOT - Today at 5:31 PM
Benjymar bought a Leather Belt for 1,995 gold.
DiscordRPGBOT - Today at 5:32 PM
Benjymar tried to use a Leather Belt, but has none
Benjymar - Today at 5:36 PM
#!inv
DiscordRPGBOT - Today at 5:36 PM
!===== [Items (Page 1/1)] =====!
+ 783 Gold.
+ 43 x Health Potions
+ 1 x Small Dagger
+ 1 x Iron Sword
+ 21 x Rocks
+ 14 x Lemons
!============================!

**Comment by Gyth7** [comment]
When you use the `#!buy` command the item is automatically equipped. Use `#!stats` and you should see the leather belt equipped as your chest plate
