### ISSUE TITLE
Adventurer's Chestplate provides less blocking than Leather Belt?

### ISSUE THREAD

**Issue by TheDujin** [DiscordDungeons/Bugs#379]
**Please describe your issue below.**  
Upon running #!item  (with itemDisplay 2) on Adventurer's Chestplate and Leather Belt, I found that despite their item descriptions, Adventurer's Chestplate's "Damage Blocked" is 1%, while Leather Belt's "Damage Blocked" is 2%. This is a bit confusing since Adventurer's Chestplate is both more expensive and has a higher level restriction that Leather Belt.

**Comment by Sven65** [comment]
Not a bug, simply bad math.
