### ISSUE TITLE
withdraw item set perm not working

### ISSUE THREAD

**Issue by AddedFX** [DiscordDungeons/Bugs#380]
I tried to set perm for a player to withdraw items from the guild, but it doesn't seem to work, perhaps I have done the code wrong? (it worked for withdraw gold)

<img width="389" alt="setperm" src="https://user-images.githubusercontent.com/29009312/31529033-5b9c7a68-b022-11e7-90dc-be6253c3831d.PNG">
<img width="341" alt="setperm 3" src="https://user-images.githubusercontent.com/29009312/31529598-f5d4e338-b025-11e7-87c0-edb2c89e178e.PNG">
<img width="492" alt="setperm 2" src="https://user-images.githubusercontent.com/29009312/31529183-72fc6c6c-b023-11e7-9f1e-8faef67a2926.PNG">

**Comment by Sven65** [comment]
Fixed. Forgot to update the command when patch was rolled out.
