### ISSUE TITLE
#!location showing previous location before showing arrival notice

### ISSUE THREAD

**Issue by toastyonyt** [DiscordDungeons/Bugs#381]
When the user arrives at a location, it briefly shows their previous location before telling them they have arrived at the designated location.

![](https://i.gyazo.com/e934ef800818e80b36cae604b69e7fed.png)
![](https://i.gyazo.com/fe870db0c94b762a1d743df77684c7a9.png)

>**EDIT**
**Editor:** @PlayTheFallen
**Time:** 10:21 15th Oct 2017
**Reason:** Direct image rendering

**Comment by Sven65** [comment]
Fixed
