### ISSUE TITLE
The Market is Made of Spaghetti.

### ISSUE THREAD

**Issue by Dutalo** [DiscordDungeons/Bugs#382]
The markets sell system is bugged. It refuses to accept my lemons no matter how many times I input the command correctly. In short. Your bot has too much spaghetti in its coding. :/

**Comment by Gyth7** [comment]
You can't sell Lemons using the `#!sell` command, use the global market.

**Comment by Dutalo** [comment]
I did not know this. And no where did I look did it say that I couldn't. There needs to be more clarity in what can be with which commands.

**Comment by Gyth7** [comment]
If you use `#!item lemon` it clearly states there that it is unsellable, moreover if you have joined the server you can find this info in the #faq channel.

**Comment by Sven65** [comment]
Not a bug, closed.
