### ISSUE TITLE
EQUIPMENT PROBLEM

### ISSUE THREAD

**Issue by GUTZ1996** [DiscordDungeons/Bugs#384]
**Please describe your issue below.**  

CANT MINE/FISH/CHOP equipment not equiped
**If an error is provided, please copy the block into the space below.**

```js

< error here >
You don't have an axe equipped, gutz.
You don't have a fishing rod equipped, gutz.
You don't have a pickaxe equipped, gutz.
```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
Not an issue. It's simply stating you don't have them equipped.
You can buy them and then `#!use <item>` to equip them.
