### ISSUE TITLE
Using heal twice caused death.

### ISSUE THREAD

**Issue by XpRienzo** [DiscordDungeons/Bugs#386]
**Please describe your issue below.**  
While adventuring, using heal auto in succession caused a death and money loss. Screenshots attached. PS: It'd be helpful if I could be given my gold and my slain counter be reduced back.

![](https://cdn.discordapp.com/attachments/172389002190651393/369511695913058306/Screenshot_from_2017-10-16_21-16-43.png )
![enter image description here](https://cdn.discordapp.com/attachments/172389002190651393/369511702649241601/Screenshot_from_2017-10-16_21-16-25.png)

**Comment by Sven65** [comment]
Old and probably fixed.
