### ISSUE TITLE
Fickle Fishing double whale

### ISSUE THREAD

**Issue by FLSxAlex69** [DiscordDungeons/Bugs#387]
**Please describe your issue below.**  
I fought 2 ice fin whales (For quest) and got double the loot. I believe it's not intended this way.

**If an error is provided, please copy the block into the space below.**

```js

None

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

https://imgur.com/a/fS554 (Few screenshots on how to reproduce it).

**Comment by Sven65** [comment]
Please edit your issue to link directly to the images

**Comment by FLSxAlex69** [comment]
It contains few images on that link, I'm not sure how to do it.

**Comment by FLSxAlex69** [comment]
Bug fixed (According to change log)
