### ISSUE TITLE
Equipping?

### ISSUE THREAD

**Issue by Moose42088** [DiscordDungeons/Bugs#388]
I bought an axe, pickaxe, and have a fishing rod but how do i equip them.

**Comment by FLSxAlex69** [comment]
Github is for bug reports afaik.
Go to RPG support on the discord server to ask this kind of question in the future.
do #!use (item) to use it. Without () ofc

**Comment by Moose42088** [comment]
i did they sent me here

**Comment by Moose42088** [comment]
and thanks for your canky response have a bad day i guess cause you sound angry, cause i asked a question

**Comment by FLSxAlex69** [comment]
There's a reason why #RPG-Support exist, mate. As far as I'm aware, there's no bug with #!use pickaxe or #!use axe. Thanks I guess for the good luck ¯\_(ツ)_/¯
