### ISSUE TITLE
Issue with #!quest

### ISSUE THREAD

**Issue by FlamePrince** [DiscordDungeons/Bugs#39]
While in limbo trying to decide to either #!quest accept or #!quest decline, using #!quest will generate this error code.

![quest2](https://cloud.githubusercontent.com/assets/18062412/18687943/b99096dc-7f58-11e6-8faf-9b589eeb5ae9.png)

![quest3](https://cloud.githubusercontent.com/assets/18062412/18688059/1ab05baa-7f59-11e6-98cd-1bfc06c0d7b6.png)

**When this issue occurs, you cannot #!quest accept, and must #!quest decline in order to get a new quest.**

![quest4](https://cloud.githubusercontent.com/assets/18062412/18688218/b386663a-7f59-11e6-88d6-a6e0bebdfcae.png)
![quest5](https://cloud.githubusercontent.com/assets/18062412/18688222/b67372e8-7f59-11e6-811f-87437b36136e.png)
![quest6](https://cloud.githubusercontent.com/assets/18062412/18688230/bac0a654-7f59-11e6-8a34-88f32a145c05.png)

**Comment by FlamePrince** [comment]
When this issue occurs, you cannot #!quest accept, and must #!quest decline in order to get a new quest.

![quest4](https://cloud.githubusercontent.com/assets/18062412/18688218/b386663a-7f59-11e6-88d6-a6e0bebdfcae.png)
![quest5](https://cloud.githubusercontent.com/assets/18062412/18688222/b67372e8-7f59-11e6-811f-87437b36136e.png)
![quest6](https://cloud.githubusercontent.com/assets/18062412/18688230/bac0a654-7f59-11e6-8a34-88f32a145c05.png)

**Comment by Sven65** [comment]
Issue has been fixed for new players. Can't do much about the others. Should work with the process as it does now.
