### ISSUE TITLE
Frostridge Map (image) is broken

### ISSUE THREAD

**Issue by Hiroshi-22812** [DiscordDungeons/Bugs#391]
**Please describe your issue below.**  
If you do `#!map` while in frostridge it says {user}'s location: and no image

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
Fixed
