### ISSUE TITLE
Enhance items menu

### ISSUE THREAD

**Issue by djlax805** [DiscordDungeons/Bugs#394]
I don't like how the whole item name, gold amount and item requirements are the color red when either of the two requirements aren't met.  I sometimes skip over items thinking I'm not high enough level when I just don't have gold.  It would be nice if maybe there was a more clear indication of what you needed to do.  Whether the name of the item be grey, then toggle each part (item level req. / cost) with either grey or red, or possibly a third color.  It's just a suggestion and a cosmetic tweak so it's not that important.

I am level 5 but can't afford the item, but sometimes in a page full of red I skip things thinking I can't afford or high enough level.
![bug](https://user-images.githubusercontent.com/5040766/31772576-2682b956-b4ae-11e7-8ede-c3104b047918.PNG)

**Comment by Sven65** [comment]
Since we use the syntax highlighting built into Discord, we can't make a single line two seperate colors.

**Comment by djlax805** [comment]
I was able to use markdown and html tags create different colors, but I appreciate the consideration.
