### ISSUE TITLE
Damage meter(total damage dealt) against boss is wrong.

### ISSUE THREAD

**Issue by Tihealy** [DiscordDungeons/Bugs#396]
**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```
Damage meters on #!fightboss is wrong. The damage meters show the wrong total damage dealt. It may have a chance that it doesn't take account pet damages.

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

https://imgur.com/a/UcHML

First time fighting a boss (and i think the amount of experience is a bit TOO insane (54836 xp)(i have 18% xp boost from stats) for the amount of damage dealt that i did (i was 36 and gained 9 levels) i also put the rewards from the fight boss at the bottom

**Comment by Tihealy** [comment]
From the test of October 24th, at around 15:00 EDT time

https://imgur.com/yceHqGe

You can see me attacking 2 times there.

Somehow, on the second attack that i did, it did not register my second attack, nor added the damage to the total damage dealt.

**Comment by InitialP** [comment]
I will add to this as well. The very first attack didn't register too well and only applied on the 2nd attack which counted as 1 hit, although it was supposed to be hit 2.
![evidence 1](https://user-images.githubusercontent.com/29098459/31964825-3ee7ba5c-b8fd-11e7-8039-874141ea3096.PNG)
![evidence 2](https://user-images.githubusercontent.com/29098459/31964844-4deac54e-b8fd-11e7-96a0-7bd62d547500.PNG)
