### ISSUE TITLE
#!setprefix not working

### ISSUE THREAD

**Issue by FlamePrince** [DiscordDungeons/Bugs#40]
![](https://cloud.githubusercontent.com/assets/18062412/18657059/16a9da22-7ecd-11e6-8819-d9cabb93c950.png)

Icoshi#2431 also reported the same, but that "#!" did not work after the fact.

**Comment by FlamePrince** [comment]
![timerchan1](https://cloud.githubusercontent.com/assets/18062412/18689552/1f834a82-7f60-11e6-94e8-4d1b430e7d2a.png)

however the bot ceased working on his server

![prefix3](https://cloud.githubusercontent.com/assets/18062412/18689571/3129e408-7f60-11e6-889b-95924293fc86.png)

**Comment by Sven65** [comment]
Fixed the issue, database didn't update newly added servers.
