### ISSUE TITLE
donate issue

### ISSUE THREAD

**Issue by b51015** [DiscordDungeons/Bugs#402]
items can't be donated
it simply says "you have 0"
the picture should describe that well enough
I am new to GitHub but do inform me if the picture isn't working.
![]( <https://cdn.discordapp.com/attachments/371358407120125955/372523005059792898/image.png> )

**Comment by FelixArgyle** [comment]
@b51015 Hey, you seem to be using the incorrect command for **Item donating** use the correct command usage is :
"#!idonate @user item amount"

**Comment by b51015** [comment]
in that case the bot shouldn't answer.

**Comment by brunotacca** [comment]
@b51015 
**#!donate** is for gold.
**#!idonate** is for items

They both appears in the command list:
[User]
achievements, assign, attributes, buy, cancelpotion, craft, **donate**, drop, getcard, heal, **idonate**, inv, invval, item, pledge, potion, quest, redeem, reset, rpoints, sell, skills, started, stats, use, uset

And you can get a description for each command by using #!help.
Like so:
![image](https://user-images.githubusercontent.com/6067887/31992858-3fb86ae6-b95a-11e7-8ada-ce510be06c29.png)

Lastly, I think for cases like that ask, please in the official server channel #rpg-support before thinking it's a bug.

**Comment by b51015** [comment]
ok

I still think the bot should answer differently. maybe add the word gold in there?

but except for that, **SOLVED !**
