### ISSUE TITLE
Map command is broken

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#404]
**As the title says the #!map command is broken it does not display the images that should be showing the maps**  

![683ad0](https://user-images.githubusercontent.com/12903523/31999200-72ca14ac-b9cd-11e7-83c9-ab16bfb7c8cb.png)

**Comment by Hiroshi-22812** [comment]
N̶o̶t̶ ̶b̶c̶ ̶i̶ ̶u̶p̶d̶a̶t̶e̶d̶ ̶t̶h̶e̶ ̶m̶a̶p̶ ̶b̶c̶ ̶p̶p̶l̶ ̶t̶o̶l̶d̶ ̶m̶y̶ ̶t̶o̶ ̶m̶a̶k̶e̶ ̶m̶e̶m̶b̶e̶r̶s̶ ̶o̶n̶l̶y̶ ̶l̶o̶c̶a̶t̶i̶o̶n̶s̶ ̶d̶i̶f̶f̶e̶r̶e̶n̶t̶ ̶w̶h̶i̶c̶h̶ ̶i̶ ̶t̶h̶e̶n̶ ̶u̶p̶l̶o̶a̶d̶e̶d̶ ̶t̶o̶ ̶i̶m̶g̶u̶r̶,̶ ̶c̶h̶a̶n̶g̶i̶n̶g̶ ̶t̶h̶e̶ ̶l̶i̶n̶k̶

**Comment by Sven65** [comment]
not anymore
