### ISSUE TITLE
Unable to Donate?

### ISSUE THREAD

**Issue by clamismagic** [DiscordDungeons/Bugs#405]
Not sure if it's a general discord problem, but when I click on "Login with Discord" at the donation page, the link that it opens is just a blank black page. Same thing happens when clicking on the "Invite" button when trying to invite Discord Dungeons bot to my server. Am I doing something wrong, or is this a bug on Discord Dungeons / Discord itself? Thanks.

**Comment by Sven65** [comment]
As those links are handled by discord (as seen by `https://discordapp.com`), it's an issue with discord itself. I would recommend clearing the cache of your browser.
