### ISSUE TITLE
Second player showing on output

### ISSUE THREAD

**Issue by LunaMoonborn** [DiscordDungeons/Bugs#408]
When using #!adv I got a random player showing up on the information output.

![]( <https://i.gyazo.com/641e74b4a6b5e9a955274b20ab5ce614.png> )

**Comment by LunaMoonborn** [comment]
Happened again.

![]( <https://i.gyazo.com/c69ffa4aab1366da82707914acf3b97d.png> )

**Comment by Sven65** [comment]
Issue with the library.
