### ISSUE TITLE
#!inv bug

### ISSUE THREAD

**Issue by FlamePrince** [DiscordDungeons/Bugs#41]
![image](https://cloud.githubusercontent.com/assets/18062412/18787569/cf61d458-8179-11e6-86c1-4fa826b1afef.png)
![image](https://cloud.githubusercontent.com/assets/18062412/18787570/cf81556c-8179-11e6-9ed3-110ae85908e9.png)
![image](https://cloud.githubusercontent.com/assets/18062412/18787572/cf840eb0-8179-11e6-8ffe-8f890df91f44.png)
![image](https://cloud.githubusercontent.com/assets/18062412/18787571/cf84f988-8179-11e6-8c71-1b3611222db2.png)
![image](https://cloud.githubusercontent.com/assets/18062412/18787573/cf86a4ea-8179-11e6-8578-f518e3442e8f.png)

**Comment by FlamePrince** [comment]
When you don't have the 2 pages of inventory and you call for page 2, it doesn't automatically pull up page 1

![image](https://cloud.githubusercontent.com/assets/18062412/18787805/c80e49ba-817a-11e6-804d-97073dbb480b.png)

**Comment by Sven65** [comment]
I know of the issue and why it happens, I'll check it later today.

**Comment by Sven65** [comment]
Fixed.
