### ISSUE TITLE
Fruit Sapling Plant check Broken?

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#413]
**After setting a fruit sapling and waiting a full 24hours , after checking the fruit sapling I received only a fruit sapling and no other items, unless I'm wrong something other than getting the sapling I planted back.**  

An image below to show the outcome after using **#!plant check**
![9c2bcd](https://user-images.githubusercontent.com/12903523/32201491-b5ce78f0-be1a-11e7-92fd-075296ac6a82.png)

**Comment by Sven65** [comment]
Fixed.
