### ISSUE TITLE
the new #!unequip command doesn't work

### ISSUE THREAD

**Issue by InitialP** [DiscordDungeons/Bugs#418]
I tried to use the #!unequip zinc pickaxe, while it was equipped.
I have attached an image as an example.
![proof](https://user-images.githubusercontent.com/29098459/32351151-5913b066-c014-11e7-91a8-f12e7e6b1126.PNG)

**Comment by clamismagic** [comment]
#!unequip pickaxe is the correct command to unequip your pickaxe, as of now. Not sure if it was planned by Mackan, but here's a temporary solution for you. :)

**Comment by Sven65** [comment]
The intended way is `#!unequip <tool type>`, will add a check for correct usage.

**Comment by InitialP** [comment]
Yeah, I rushed to report it too quickly and only found out minutes later. When you are used to #!use items, then you get that habit to use with #!unequip.

**Comment by Sven65** [comment]
Aye.
