### ISSUE TITLE
Bought item not in inv

### ISSUE THREAD

**Issue by waltdjr** [DiscordDungeons/Bugs#419]
**Please describe your issue below.**  
Bought iron battleaxe.  Went to use it and it said I didn't have one.  Looked in inventory and it doesn't show up there either but gold is gone.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )
![screenshot_20171104-105204](https://user-images.githubusercontent.com/1770758/32406446-fd13a7a8-c14e-11e7-97e6-04b78d04da21.png)

**Comment by Gyth7** [comment]
When you buy an item using `#!buy` it auto equips. Check your `#!stats` and it will be equiped as your weapon.

**Comment by waltdjr** [comment]
Lol, I thought I checked that but obviously didn't.  I thought because I
had to equip all the other items I bought, like fishing rod, I also had to
#!use a new weapon also.

Sorry for my misunderstanding and the unneeded ticket.

Thanks for the quick response.

On Nov 4, 2017 11:02 AM, "Gyth" <notifications@github.com> wrote:

When you buy an item using #!buy it auto equips. Check your #!stats and it
will be equiped as your weapon.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DiscordDungeons/Bugs/issues/419#issuecomment-341903484>,
or mute the thread
