### ISSUE TITLE
New Item/Recipe Ideas

### ISSUE THREAD

**Issue by arndorus** [DiscordDungeons/Bugs#42]
I had the idea of a "beer" item. It would buff strength and attack for a specific time, and then have a cooldown. You could craft this item by using glass to make a mug, and combining the mug with wheat to make beer. This is a general idea, I just wanted to see what people thought about it. Thanks!

**Comment by Sven65** [comment]
As I currently do not have any plans to rework the alchemy system this issue has been closed.
