### ISSUE TITLE
#!guildad bug with guild perms

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#420]
**Whilst having my Guild Permissions set so I can do a GuildAd, it seems to not respond whilst trying to place an ad up after reacting with the check emoji.**  

Screenshot: 
![9dc89a](https://user-images.githubusercontent.com/12903523/32429018-1a697d00-c30c-11e7-92d5-d45fae1398bf.png) After that it simply does not respond with sending a guild advertisement.

**Comment by PlayTheFallen** [comment]
*`Needs more info` label was added as a reminder to devs to lookup the code for the command.*

eh, would it be that the permission nodes are f\*cked? *lol*

**Comment by FelixArgyle** [comment]
It now seems to show an error whilst trying to set a guild ad  (note that I'm not owner of the guild I just have perms to set ads) 
![292eff](https://user-images.githubusercontent.com/12903523/32613853-443760e8-c5af-11e7-855f-039cce3c0ea9.png)
