### ISSUE TITLE
#!guildad problem and also stole my gold

### ISSUE THREAD

**Issue by TehShadowGamer** [DiscordDungeons/Bugs#421]
**Please describe your issue below.**  
#!guildad problem a similar or same thing happened to felix argyle did guild ad 3 times and lost like 450k bot does not respond upon reaction and sucks up the gold in the process you can check message history for the third gold snab

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < https://imgur.com/a/JMHy0 https://imgur.com/a/VD2q2  > )

**Comment by Sven65** [comment]
Already reported in #420
