### ISSUE TITLE
Angler name mismatch.

### ISSUE THREAD

**Issue by Steamer2001** [DiscordDungeons/Bugs#423]
**Please describe your issue below.**  
The Angler at Rivermouth tells you to go to Frostridge Shore and talk to his friend Josh. When you get to Frostridge, the Angler's name is Angler John. Talking to him forwards the quest progress.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )
![screenshot 2017-11-07 at 8 00 54 am](https://user-images.githubusercontent.com/33454781/32495126-5081ce16-c392-11e7-99a3-fc4fd24f41a0.png)
![screenshot 2017-11-07 at 8 00 47 am](https://user-images.githubusercontent.com/33454781/32495130-53ee5e34-c392-11e7-85ba-fcf14c149b3b.png)

**Comment by Sven65** [comment]
Thanks, will fix.

**Comment by PlayTheFallen** [comment]
Fixed in #452 of commit https://github.com/Sven65/RPGBot/commit/e616264ddaad3f3979344c55e9885677545f39ac
