### ISSUE TITLE
New Axe (True Wood Cutter) bonus not working as expected

### ISSUE THREAD

**Issue by ChikubiNoKami** [DiscordDungeons/Bugs#425]
**Please describe your issue below.**  
I originally get 17 logs from doing the chop command, but with the new axe (True Wood Cutter) I still got 17 logs instead of the bonus coming into action.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < https://imgur.com/gallery/3SiKW > )

**Comment by InitialP** [comment]
Can verify as well. It doesn't work at all. I've got 3 following images. The first is the time I used chop prior the update. Image 2 is the time of the update in GMT. Image 3 is after the update and while having the new axe equipped.
![chop gains prior update](https://user-images.githubusercontent.com/29098459/32559698-b66a4862-c49f-11e7-9353-7d249626ee5c.PNG)
![update time in gmt](https://user-images.githubusercontent.com/29098459/32559716-be0e68dc-c49f-11e7-82e9-585e82d4a702.PNG)
![chop after update and having it equipped](https://user-images.githubusercontent.com/29098459/32559739-c9cf59c4-c49f-11e7-9714-5d817371432d.PNG)
