### ISSUE TITLE
Bug in location menu

### ISSUE THREAD

**Issue by RJain12** [DiscordDungeons/Bugs#427]
**Please describe your issue below.**  
In ravengate, two adventurer's restaurant show.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < https://cdn.discordapp.com/attachments/342476456133394432/377953735500103680/2bug.PNG > )

**Comment by Sven65** [comment]
Already reported in #426
