### ISSUE TITLE
Ending the Adventurer's Restaurant quest doesn't give bunny stew

### ISSUE THREAD

**Issue by RJain12** [DiscordDungeons/Bugs#428]
**Please describe your issue below.**  
When finishing the menu specials quest, the user does not actually receive a bunny stew.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

https://cdn.discordapp.com/attachments/342476456133394432/377956019914932235/stew.PNG
https://cdn.discordapp.com/attachments/342476456133394432/377956018807635973/bunnystew.PNG

**Comment by brunotacca** [comment]
![image](https://user-images.githubusercontent.com/6067887/32582294-2d62f466-c4d5-11e7-9e48-6167fc72adac.png)

**Comment by RJain12** [comment]
Mackan, it would be good if you restart the quest; although people have to do it again, the rewards can be repeated and making the burgers again isn't too hard.

**Comment by Sven65** [comment]
Interesting, will look into.
