### ISSUE TITLE
Adventure info mixup

### ISSUE THREAD

**Issue by Nkaiser50** [DiscordDungeons/Bugs#429]
**Please describe your issue below.**  
someone else's adventure was shown along my own, idk if its a big issue or not

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![https://i.imgur.com/BFQkkcU.png]

**Comment by Sven65** [comment]
Issue with the  library we're using. Nothing I can do.
