### ISSUE TITLE
BOT - Using a key doesn't always give the reward.

### ISSUE THREAD

**Issue by RDardelet** [DiscordDungeons/Bugs#43]
A user reported trying to use keys to open a chest.
Using ``#!use Water Key`` he got
``<user> opened a chest using a Water Key and got 10 Water Keys.
``
But he did not receive any of the 10 keys in his inventory.

Experienced by : BADEVIL#2950  (149580191356813312)
Reported in #rpg-bugs

**Comment by Sven65** [comment]
Fixed.
