### ISSUE TITLE
Tavern (One for each map)

### ISSUE THREAD

**Issue by dibli-goost** [DiscordDungeons/Bugs#435]
This is simply a tavern where random events can happen by talking in there. The main command could possibly be #!chat, which would allow you to talk in the tavern.

 When in a conversation with a tavern-goer you can progress like an #!adv using #!chat 1, #!chat 2, and just #!chat

**Comment by ryudragon98** [comment]
did you know there is a #!suggest cmd to post suggestions in the official server, since this is for bugs.

**Comment by dibli-goost** [comment]
Well before Mackan had made a suggestion thread for status effects here so that me and somebody else could put our ideas in it, thus I was assuming that you could put suggestions here. I'm sorry if I was wrong.

**Comment by Sven65** [comment]
You can put suggestions here too.

**Comment by ryudragon98** [comment]
ah my bad about my previous comment then.
