### ISSUE TITLE
#!getrole Bug

### ISSUE THREAD

**Issue by ImDewtour** [DiscordDungeons/Bugs#437]
![](https://i.imgur.com/lODNzKn.png)

Had just bought a dedicated role and tried using it and it bugged and took my role... I did get my gold back so don't worry about that. I don't think there is a big issue but posting it here incase.

Update: Did it again... and got another error:  
![](https://i.imgur.com/6Pa4oVg.png)
Don't worry again, I got my gold back from chrome :3 
#MackanPlsFix

Both have same error:
```js
DiscordAPIError: Missing Permissions
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/discord.js/node_modules/snekfetch/src/index.js:204:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
**EDIT**
`Editor:` @PlayTheFallen
`Time:` 15:36:47 GMT+0000 (GMT Standard Time) Wed Nov 15 2017 *Generated by nodejs environment*
`Reason:` Edit link markup to render images on page.

**Comment by Sven65** [comment]
Where did you use the command?

**Comment by ryudragon98** [comment]
they did it in rpg-1 in the official server.

**Comment by Sven65** [comment]
Right, thanks.

**Comment by ryudragon98** [comment]
You're welcome.

**Comment by ImDewtour** [comment]
rpg-1 the first time, and rpg-7 the second.

**Comment by Sven65** [comment]
Fixed
