### ISSUE TITLE
Uset nick unresponsive/broken

### ISSUE THREAD

**Issue by conradr10** [DiscordDungeons/Bugs#438]
Uset nick either doesn’t work says what do you want me to do or simply doesn’t get a response period

**Comment by FelixArgyle** [comment]
@conradr10 Could be since it is reaching Discord's maximum characters set in a name possibly, that has happened to me in the past.

**Comment by Sven65** [comment]
Most likely due to character limit (32) or simply missing permissions.

**Comment by ImDewtour** [comment]
@conradr10 it's the Odyssey server... for some reason it doesn't have change nick perms

**Comment by ryudragon98** [comment]
i was going back and checking and it currently looks like drpg in that server does not have the manage nick perms therefore it is the reason to why its not changing your nick in that server.
