### ISSUE TITLE
Guild Member Calculation is Broken

### ISSUE THREAD

**Issue by Takashi-22812** [DiscordDungeons/Bugs#439]
# Guild Member Calculation is broken (AF)

Well, if you do #!guild and the members pop up, the members shown is wrong. One example is that it says nova has 93 members when we only have 91, we added and subtracted people and it was still off by 4. Another one is a friends guild has only one person, but if you go #!guild, it says 4 members

(EDIT; Fixed yo shit - Mackan)

**Comment by Sven65** [comment]
`6 members and 2 elders. (9/70 total)` means 6 members, 2 elders and one owner, please provide a screenshot.

**Comment by Takashi-22812** [comment]
Lol...Here's a screenshot of the (still broken) thingy...
[Imgur](https://i.imgur.com/9e1a5By.png)
[Imgur](https://i.imgur.com/vUzTTSI.png)
[Imgur](https://i.imgur.com/QaEUGei.png)
[Imgur](https://i.imgur.com/jhlTeeh.png)

There are 12 people on the first page. Each other page holds 15 people. There are 12 people on the last page. 12+(15*4)+12 = 84.
Also there is 1 member listing on our guild member list which makes the 86th line. there are 2 lines for the title which is 86-2=84. The #!guild shows 87 members. =3

**Comment by Sven65** [comment]
80 members
6 elders
1 owner

I get that to 87 total users?

**Comment by SamuiNe** [comment]
Quite sure the Member Count displayed in the `#!guild` is total member + elder + 1 owner, so if the guild have 437 members and 10 elders, it would be 448 members (437 + 10 + 1 = 448). Marking the issue as invalid.
