### ISSUE TITLE
#!adv shows me another user's adventure

### ISSUE THREAD

**Issue by TheDujin** [DiscordDungeons/Bugs#442]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
When typing #!adv in DM, I received another user's adventure info along with my own.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![screenshot 2017-11-15 at 9 02 16 am](https://user-images.githubusercontent.com/12126984/32849845-341f1f9a-c9e5-11e7-9eea-94ee75f0f0bb.png)

**Comment by ryudragon98** [comment]
its random and cant be fixed.

**Comment by TheDujin** [comment]
Ah, okay. Should I close issue?

**Comment by ImDewtour** [comment]
Multiple adventures in one embed / Other user is in the same adventure embed

We know, it's an issue with the library, we can't do anything.

It's in the FAQ. You can close it, yes.
