### ISSUE TITLE
People in multiple sections of gmembers

### ISSUE THREAD

**Issue by RJain12** [DiscordDungeons/Bugs#445]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
When promoting one to owner, for some reason, the person is listed under both elder and owner. In the image below, notme is listed twice.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![screenshot 2017-11-15 at 7 08 53 pm](https://user-images.githubusercontent.com/29895437/32871888-828d309c-ca38-11e7-9dfc-aa84c8698908.png)

**Comment by PlayTheFallen** [comment]
*Intended*

**Comment by Sven65** [comment]
Not really intended, will look into.

**Comment by Sven65** [comment]
Is this still an issue? If so, please open a new one.
