### ISSUE TITLE
Refine equips

### ISSUE THREAD

**Issue by Throwaway12441414** [DiscordDungeons/Bugs#45]
Refining equipment to add defense or % block using ores or something. #!blacksmith
and to weapon more dmg
Master Anjn [Lvl. 3] - Today at 4:18 PM
That is a nice thought tbh
But I would argue each weapon have a max-damage cap
Like iron sword can be upgraded a few times
But more legendary, RESOURCE-COSTLY weapons have more upgrades

**Comment by Sven65** [comment]
A system like this is in the plans already, the main issue with this would be to keep track of all the different items in the game and displaying them to the user.

**Comment by Sven65** [comment]
Unable to add with the current item system.
