### ISSUE TITLE
Can only unequip Axe

### ISSUE THREAD

**Issue by FelixCATus** [DiscordDungeons/Bugs#450]
Refer title (found this when I'm trying to craft Zinc Axe)

![image](https://user-images.githubusercontent.com/23120572/33070568-6768a2a0-cef3-11e7-875f-8e00ffff6d37.png)
![image](https://user-images.githubusercontent.com/23120572/33070582-72b08e5c-cef3-11e7-9c8a-c236378ddf65.png)
![image](https://user-images.githubusercontent.com/23120572/33070590-7928251a-cef3-11e7-8b31-16b21e9e815f.png)

**Comment by Sven65** [comment]
Not a bug.
