### ISSUE TITLE
Won't let me sell items for whatever reason.

### ISSUE THREAD

**Issue by VENOM1787** [DiscordDungeons/Bugs#451]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Won't let me sell items that I have. Instead tells me I "don't have that item". Really annoying. Am I typing this wrong?

**If an error is provided, please copy the block into the space below.**

```js

<「ᐯᗴᑎᗝᗰ 」 tried to sell an unknown item!.
「ᐯᗴᑎᗝᗰ 」 tried to sell an item they don't have. >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < https://gyazo.com/fbb3a566fe544383146dbb8ccb7c9c4a > )

**Comment by ryudragon98** [comment]
you cant sell lemons using #!sell and no plurals, lemons can only be sold on the global market.

**Comment by exunious** [comment]
You can check what items you can sell or not on the DRPG website.
Or you can simply use the command: `#!item [item name]`
It will tell you Sellable or not!

Also, when you wanna sell for example: 20 apples.
You use: `#!sell apple 20` dont use the S at the end.
