### ISSUE TITLE
The ability to withdraw items from guilds in battles

### ISSUE THREAD

**Issue by RamiLego4Game** [DiscordDungeons/Bugs#453]
Hey,
I have been batteling with my guild owner, and I know that buying items is not allowed when in a battle, but then I was shocked that he can withdraw items from the guild !
In that way anyone can buy him some items, and dispose them in the guild.
In other words infinit amount of healing potions inside of a battle !

**Comment by Sven65** [comment]
Interesting, will patch, thanks.
