### ISSUE TITLE
.Gally Bug

### ISSUE THREAD

**Issue by Monikaaaaaaa** [DiscordDungeons/Bugs#457]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
When I try to add a new ally to my guild it tells me, my slots are full

**If an error is provided, please copy the block into the space below.**

```js

< error here >
Says slots are full for gally when I only have one guild registered as ally
```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image 
![screen shot 2017-11-26 at 13 41 51](https://user-images.githubusercontent.com/34003429/33240574-dc8df6a6-d2af-11e7-9740-efa108f63b83.png)
url > )

**Comment by Sven65** [comment]
I checked your guild and according to the databsae you do have 3 allies, but only one of them exists.
