### ISSUE TITLE
Attribute Percentages.

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#458]
Whilst using `#!attributes` it appears to not show the Necklace percentage whilst armour pieces that have percentages show up next to your assigned attribute.
Mackan  asked me to github it due to it being a bug.

I have 4 Donor items with xp boost effects whilst Necklace doesn't appear to be active on the attribute post.
![attribs bug1](https://user-images.githubusercontent.com/12903523/33254066-5547701a-d38a-11e7-8282-3904c74e838a.png)

![attribs bug](https://user-images.githubusercontent.com/12903523/33254067-55635fb4-d38a-11e7-9676-8957ed435acd.png)

**Comment by Sven65** [comment]
Fixed
