### ISSUE TITLE
BOT - Disbanding guild issues

### ISSUE THREAD

**Issue by RDardelet** [DiscordDungeons/Bugs#46]
1rst issue, people expect the use of the verb ``disband`` but the command to confirm the deletion of a guild is ``#!gdispand YES``

2nd issue, the integration of the user variables in the display message does not work
![image](https://cloud.githubusercontent.com/assets/9199809/19430716/9e0bc190-9455-11e6-966f-29576e140ea8.png)

Issue reported by Sprütz#8622 (205704051856244736) in #rpg-support

**Comment by Sven65** [comment]
Known issue, will fix

**Comment by Sven65** [comment]
Fixed the issue.
