### ISSUE TITLE
Journey to different location only completes when I send certain commands

### ISSUE THREAD

**Issue by RotiBakarKosong** [DiscordDungeons/Bugs#460]
So far I have tried these commands: 

- [x] adv
- [x] crack
- [ ] inv
- [ ] sides
- [ ] crack

**Comment by Sven65** [comment]
Not a bug, it's intended to be that way, as those are the commands that are dependant on your current location.

**Comment by RotiBakarKosong** [comment]
It's kind of annoying if u were in a location that didn't allow adventuring like silverkeep altar

**Comment by Sven65** [comment]
Huh?

**Comment by RotiBakarKosong** [comment]
![image](https://user-images.githubusercontent.com/32260640/33378361-8221bade-d54f-11e7-82d4-1c1eed1edc3d.png)
![image](https://user-images.githubusercontent.com/32260640/33378387-9087cb04-d54f-11e7-9f74-41d183f5386d.png)
