### ISSUE TITLE
Map command not working

### ISSUE THREAD

**Issue by Ciborn** [DiscordDungeons/Bugs#462]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Map is not showing when I type the map command, but the cooldown is working. If it could help, I'm in Silverkeep Altar, I am doing the Meditative quest, and I have to mine these 5 Silver Essences.

**If an error is provided, please copy the block into the space below.**

```js
(No error)
```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*
![image](https://user-images.githubusercontent.com/17595049/33339570-dee4a2d0-d479-11e7-9bc3-ace97dfa6950.png)

**Comment by Sven65** [comment]
Does it work in other locations?
Does it work in the location but on a different server?

**Comment by Ciborn** [comment]
Yes the map command works in all the other locations, but even in the others servers, the command don't work in Silverkeep Altar.
