### ISSUE TITLE
#!adv bug

### ISSUE THREAD

**Issue by later36** [DiscordDungeons/Bugs#464]
Was just using #!adv and all of a sudden one of my adventures had another person and their pet included in my adventure.

![](https://image.prntscr.com/image/YUYg9zkDSHGOPyiq4umWfA.png)

**Comment by ryudragon98** [comment]
this is already known and mackan cant fix it.

**Comment by Sven65** [comment]
You know the text that displayed when you went to create the issue?
It has this; ![](https://i.imgur.com/xuGDtse.png) there.

If you click on [that link](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md), the first thing you see is this issue; ![](https://i.imgur.com/xiRid0r.png)
