### ISSUE TITLE
#!advent displays last years prizes

### ISSUE THREAD

**Issue by doge-pepe-twat68** [DiscordDungeons/Bugs#465]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
using `#!advent` command displays my prizes from last year and prevents me from getting a prize from advent for this year

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*
![advent](https://user-images.githubusercontent.com/26106799/33467455-8c455bb0-d68f-11e7-8699-96ab2bf8dab6.png)

**Comment by mount2010** [comment]
More pictures
![screenshot from 2017-12-01 14 09 27](https://user-images.githubusercontent.com/13136505/33470072-712aa940-d6a1-11e7-8112-ef920a52d5e0.png)

**Comment by Sven65** [comment]
Fixed
