### ISSUE TITLE
XP from Advent does not level you up

### ISSUE THREAD

**Issue by mount2010** [DiscordDungeons/Bugs#469]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
XP from Advent does not level you up

**If an error is provided, please copy the block into the space below.**
N/A

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![screenshot from 2017-12-05 17 28 08](https://user-images.githubusercontent.com/13136505/33599686-da93c73e-d9e1-11e7-8cfa-28bc7d46a7d3.png)

**Comment by Sven65** [comment]
This has been fixed after the issue was opened.
