### ISSUE TITLE
Limes sell bug

### ISSUE THREAD

**Issue by Kyagee** [DiscordDungeons/Bugs#470]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
whenever I try to sell limes, no matter how many I try to sell, It will tell me I don't have any limes.
in addition to this, it also says that I have found 2 items. These items are "Platemail of Nightmares and Moonlit Amethyst" as you can see in the image provided bellow. I have also provided an image of my inventory. I hope this will be fixed soon

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < sell-bug  https://i.gyazo.com/c93e1a32c78d432de23513da7ab6e9b5.png > )
        my inventory  https://i.gyazo.com/e054c6c89a0b0324001628dcd546e1e7.png

**Comment by shroomyun** [comment]
it's not a bug..
>can't sell limes through #!sell
>but can sell it at global market (check #!gbsearch lime & #!help gbsell)
>use singular form of item 

hope this helps :o
