### ISSUE TITLE
Not being able to sell different things.

### ISSUE THREAD

**Issue by jad-kheirallah** [DiscordDungeons/Bugs#471]
I tried to sell my lemons and oak logs by typing these following commands:
#!sell lemon
#!sell oak log
But they're not working,they bot doesn't respond.
BUT if I do them in a row fast it says I need to rest.
Help me please ;-;.
(The screen shot shows that:
I have lemons,the bot responds to other commands,the bot doesn't respond to selling lemons)
![screenshot_1](https://user-images.githubusercontent.com/25689410/33723592-c6fff680-db75-11e7-8e30-08f6eb138560.png)

**Comment by Sven65** [comment]
You can't sell lemons, for the last time.
