### ISSUE TITLE
Bot stalled, caused death

### ISSUE THREAD

**Issue by kikukikou** [DiscordDungeons/Bugs#473]
Bot didn't respond to a few commands, then responded to them all at once. Next adventure killed me.

Details:
Used lemons with no response. Tried adventure command, still no response. Used lemons again, then bot responded with all three commands. Lemons were weirdly used though - seemed like the same exact action performed with the same results (both times healed to 177 HP). Did some sides, then tried adventure command again, but died somehow even though I had 177 HP and the beast was not strong enough to deal that much damage. 

May be related with #386 as it seems like the bot also didn't respond to the heal, then responded to both at once and was killed on the next adventure.

Screenshots:
![screenshot 2](https://user-images.githubusercontent.com/34378516/33776588-e24b1f56-dc0f-11e7-92df-7aba28bd8cf3.png)
![screenshot 3](https://user-images.githubusercontent.com/34378516/33776605-eb4043d4-dc0f-11e7-93c0-e7be4cba5467.png)

**Comment by Sven65** [comment]
Most likely due to lag with Discord.
