### ISSUE TITLE
useful?

### ISSUE THREAD

**Issue by SirTweak** [DiscordDungeons/Bugs#474]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
the adv command stopped working then it sent me this

**If an error is provided, please copy the block into the space below.**

```js

<RangeError: RichEmbeds may not exceed 25 fields.
    at RichEmbed.addField (/home/mackan/RPGBot/node_modules/discord.js/src/structures/RichEmbed.js:150:41)
    at Items.getAll.then.items (/home/mackan/RPGBot/src/Commands/Commands/Adventure/Adventure.js:268:19)
    at <anonymous>>

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < 
![screenshot_276](https://user-images.githubusercontent.com/34395748/33795493-0f4ecc94-dca8-11e7-8984-e2cdac7ef1a0.png)
> )

**Comment by Sven65** [comment]
Fixed.
