### ISSUE TITLE
!#adv wont work for me

### ISSUE THREAD

**Issue by Nathanimations** [DiscordDungeons/Bugs#475]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
!#adv wont work for me, but works for others.

**If an error is provided, please copy the block into the space below.**

```js
TypeError: Cannot read property 'defense' of undefined
    at Adv._enemyDamage (/home/mackan/RPGBot/src/Commands/Commands/Adventure/Adventure.js:618:40)
    at Adv.Execute (/home/mackan/RPGBot/src/Commands/Commands/Adventure/Adventure.js:955:24)
    at <anonymous>
```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![image](https://user-images.githubusercontent.com/34476257/33881069-9161b36a-df2b-11e7-9e14-5628ab211df1.png)

**Comment by Sven65** [comment]
Fixed.

**Comment by Nathanimations** [comment]
Oh.
