### ISSUE TITLE
#!gally remove doesnt work

### ISSUE THREAD

**Issue by doge-pepe-twat68** [DiscordDungeons/Bugs#476]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
was testing #!gally add and added hidden leaf 
but now `#!gally remove hidden leaf` doesnt work

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![gally remove](https://user-images.githubusercontent.com/26106799/33881165-f0996b0a-df6e-11e7-8bba-b8709659a909.png)

**Comment by Sven65** [comment]
I'm sorry, what?

**Comment by doge-pepe-twat68** [comment]
I "was testing #!gally add and added hidden leaf
but now #!gally remove hidden leaf doesnt work"
![gally remove](https://user-images.githubusercontent.com/26106799/33881466-d035e4b4-df6f-11e7-8cab-d274192516bd.png)
