### ISSUE TITLE
Healing Error!!

### ISSUE THREAD

**Issue by darkrai2002** [DiscordDungeons/Bugs#478]
When i use the #!heal cmmand an error appears

< TypeError: Cannot read property 'toLowerCase' of undefined
    at Heal.Execute (/home/mackan/RPGBot/src/Commands/Commands/User/Heal.js:57:13)
    

![discordrpg heal error](https://user-images.githubusercontent.com/34476272/33881314-57062970-df2c-11e7-944d-eb6fec7e66ac.png)

**Comment by Sven65** [comment]
Fixed, use `#!heal <amount>` for now
