### ISSUE TITLE
Healing error

### ISSUE THREAD

**Issue by toastie724** [DiscordDungeons/Bugs#479]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

TypeError: Cannot read property 'toLowerCase' of undefined
    at Heal.Execute (/home/mackan/RPGBot/src/Commands/Commands/User/Heal.js:57:13)
    at <anonymous>

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( ![screenshot_11](https://user-images.githubusercontent.com/34476432/33881402-9647e880-df2c-11e7-87b5-5e453645f09e.png) )

**Comment by Sven65** [comment]
Literally the issue before, #478
