### ISSUE TITLE
buying scissorgloves

### ISSUE THREAD

**Issue by skoof** [DiscordDungeons/Bugs#481]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

< Whoops. An error occured. Please report this in the official server.
TypeError: this.checkResults is not a function
    at Buy.Execute (/home/mackan/RPGBot/src/Commands/Commands/User/Buy.js:221:29)
    at <anonymous> >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < https://cdn.discordapp.com/attachments/358330362704691221/390099280603643905/Screenshot_20171212-061457.png > )

**Comment by PlayTheFallen** [comment]
**[`ADMIN`]** False reference removed for #​611, but reference persists on system. (ISSUE REMAINS CLOSED)
