### ISSUE TITLE
Buying Health Potions 

### ISSUE THREAD

**Issue by toastie724** [DiscordDungeons/Bugs#482]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

TypeError: this.checkResults is not a function
    at Buy.Execute (/home/mackan/RPGBot/src/Commands/Commands/User/Buy.js:221:29)
    at <anonymous>

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
Fixed in #481
