### ISSUE TITLE
GM Trade Complete DM Doesn't Display Item Info

### ISSUE THREAD

**Issue by Nightmare2112** [DiscordDungeons/Bugs#485]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Nightmare2112** [comment]
![image](https://user-images.githubusercontent.com/33561320/33884368-5f17aba8-df0d-11e7-9bba-53c61409776e.png)

**Comment by Sven65** [comment]
That's not a bug, it's been like that for finished trades since forever, I'll add it though.

**Comment by FelixArgyle** [comment]
Trade not finished Mackan LOOK as per these screenshots show the trade was not successfully "finished" as you say.
![8c50ee](https://user-images.githubusercontent.com/12903523/33884857-be95f2fc-df84-11e7-8c26-7fcb10bb3b95.png)
![e7a237](https://user-images.githubusercontent.com/12903523/33884858-bedaa96a-df84-11e7-8e31-0dc5cad15c2f.png)

**Comment by Sven65** [comment]
Oh, my bad, I'll look into it.

**Comment by Sven65** [comment]
Could you describe the issue in more detail?

What's supposed to happen?
What is happening instead?

**Comment by FelixArgyle** [comment]
What's suppose to happen is it should update and show the buyers name / how many of the item they've bought, as shown below 
![bfcf82](https://user-images.githubusercontent.com/12903523/33885837-e38515d6-df87-11e7-9922-21aef61cd963.png)

What's currently happening is that it's only showing "Finished" / Buyers name with no update of how many items they've bought from your trade , note: that the trade that was bought via my screenshot was only 1 item and not all 10 so it should have shown as `Trade jb3lrr72 updated. (Nightmare bought 1 Leptocite Pickaxe)`
