### ISSUE TITLE
Didn't get reward from quest

### ISSUE THREAD

**Issue by minteamocha** [DiscordDungeons/Bugs#492]
I finished the cold north quest and defeated the yeti and talked to the npc afterwards but I didn't get my reward, I talked to her again and I didn't have the quest anymore because I completed it.
![screen shot 2017-12-13 at 2 05 21 am](https://user-images.githubusercontent.com/34487447/33900950-2ad1ee32-dfab-11e7-9e4c-6ba8af59437d.png)

**Comment by Oliri** [comment]
I got the same problem too...


![image](https://user-images.githubusercontent.com/34082969/33909586-224a41a2-df5a-11e7-8c34-382b3d3b6880.png)
