### ISSUE TITLE
Battles bugged after first turn

### ISSUE THREAD

**Issue by Oliri** [DiscordDungeons/Bugs#497]
When I tried battling a friend of mine, I encountered a bug in which it did not allow for either of us to attack after the first turn. We tried starting the battle a second time, but we apparently got the same bug to happen to us again. 

(edit: the second image shows him accidentally typing "\bfight" again even after I sent a battle request, and it took it anyways without accepting the battle request. This actually puzzled me after I looked it over again...)

![image](https://user-images.githubusercontent.com/34082969/33910620-664138fe-df5d-11e7-8dc0-d1dcf8a77be9.png)
![image](https://user-images.githubusercontent.com/34082969/33910673-9257f8ce-df5d-11e7-9364-f28a648149da.png)

**Comment by Sven65** [comment]
Interesting, will look into.

**Comment by Sven65** [comment]
Unable to reproduce.

**Comment by Oliri** [comment]
I figured it out (sort of) it seems to happen only when the other player is able to be one shot by the other
