### ISSUE TITLE
Battles don't allow you to stop 

### ISSUE THREAD

**Issue by AutoTheDarkHero** [DiscordDungeons/Bugs#505]
![screenshot 2017-12-13 at 5 24 52 pm](https://user-images.githubusercontent.com/32603064/33965652-b6d61fb4-e02a-11e7-8503-d9d9c5b74f23.png)
![screenshot 2017-12-13 at 5 24 46 pm](https://user-images.githubusercontent.com/32603064/33965660-bc3e9148-e02a-11e7-904e-3e37959b5a85.png)

**Comment by Sven65** [comment]
That's because there's an hour to wait since the battle was last active.
