### ISSUE TITLE
#!gmembers

### ISSUE THREAD

**Issue by FlamePrince** [DiscordDungeons/Bugs#51]
When using #!gmembers, the members of your guild are either reported as their number or their nickname. While at first I thought this was due to people not being in the server of which you did #!gmembers, a few tests showed that this did not hold up.

**Comment by Sven65** [comment]
The issue is due to the bot not being able to find the user with the ID.
This could be because they're not on the same server, or the same shard.

**Comment by FlamePrince** [comment]
Would there be anything we could do to circumvent this issue so it shows name regardless of shard and server?

Jordan

**Comment by Sven65** [comment]
I could make it pull the usernames from the database, but for larger guilds that'd mean lots of transactions.

**Comment by FelixCATus** [comment]
![image](https://cloud.githubusercontent.com/assets/23120572/23401303/2a11bb22-fde2-11e6-841f-c9220aba205c.png)
Whether guild search function should be removed, or re added.

**Comment by Sven65** [comment]
Known issue, will look into.

**Comment by Sven65** [comment]
Fixed.
