### ISSUE TITLE
I cant catch those FISHES

### ISSUE THREAD

**Issue by TheSalamek** [DiscordDungeons/Bugs#511]
Hey !

I cant really tell if it is an bug or someting, but i have been told that it is.

I cant catch those fishes, i have tryed catch them in the normal location like 40 times and nothing is happening. Can you help me, or fix this bug ?. 
Thanks for help buddies :)

- Salámek157

                    PS: If it is not bug just its becouse of the loc or something tell me and im sorry.

**Comment by darkrai2002** [comment]
hey i'm NOT the/a developer but i DO play the game i will tell you now that i had the same problem the skill is the hardest to level but eventually you WILL get a fish and once leveled i think you get 1 everytime.

**Comment by SamuiNe** [comment]
Do you have an screenshot of the said issue? It would be really nice for us to know what is exactly the situation on your side.

**Comment by Sven65** [comment]
Invalid issue.
