### ISSUE TITLE
,uset Permissions

### ISSUE THREAD

**Issue by Nightmare2112** [DiscordDungeons/Bugs#512]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Using ,uset nick is giving permissions error, even with admin privlages

**If an error is provided, please copy the block into the space below.**
```js
DiscordAPIError: Privilege is too low...
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:218:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by TW-Dodger** [comment]
Hm. Is the bot in a higher role than the user attempting to change their nickname? I found that issue earlier myself, did that and it fixed it.

**Comment by Sven65** [comment]
Lack of perms due to the bot not being able to change owner nicknames.
