### ISSUE TITLE
Battles not working

### ISSUE THREAD

**Issue by bhaddie** [DiscordDungeons/Bugs#513]
It keeps saying that I’m not in a battle and it doesn’t appear if I kill them

![](https://cdn.discordapp.com/attachments/390373866821910530/391356890698874890/image.png)

**Comment by darkrai2002** [comment]
Im NOT a/the developer but i DO play the game just so you know you have to turn pvp battles ON then invite a player to fight hem THEN the bfight command should work

**Comment by SamuiNe** [comment]
Try `#!uset battle 1` then `#!bfight <user>`, probably due to that reason.

**Comment by alex5488** [comment]
I got this error in my server, too. All of us have pvp enabled and we fight, but then when one of us reaches 0 hit points, it automatically quits us out of the battle. We don't get anything from it and when we look at our stats, it's as if the last few turns of battle never happened.

**Comment by Sven65** [comment]
This has been fixed after the issue was opened.
