### ISSUE TITLE
Trade Bug

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#514]
Trade was listed up for 0g note: the trade is a buying trade. But 0g should be an invalid amount.
it also works with gmsell aswell.

![469423](https://user-images.githubusercontent.com/12903523/34063939-d407774e-e238-11e7-8411-dafcc74f3240.png)
![9dd0c3](https://user-images.githubusercontent.com/12903523/34063999-3db7268a-e239-11e7-99ae-a89bb420c69f.png)

**Comment by RJain12** [comment]
![screenshot 2017-12-16 at 12 07 52 am](https://user-images.githubusercontent.com/29895437/34068718-591e582e-e1f5-11e7-93c1-cc72abe52a4b.png)
![screenshot 2017-12-16 at 12 07 46 am](https://user-images.githubusercontent.com/29895437/34068719-5936fb36-e1f5-11e7-86eb-8a76c5cf8ded.png)
![screenshot 2017-12-16 at 12 07 41 am](https://user-images.githubusercontent.com/29895437/34068720-594dff2a-e1f5-11e7-9cb3-2bdb977d6639.png)
![screenshot 2017-12-16 at 12 07 29 am](https://user-images.githubusercontent.com/29895437/34068721-5964edfc-e1f5-11e7-885d-a39c69c5ea00.png)
![screenshot 2017-12-16 at 12 07 22 am](https://user-images.githubusercontent.com/29895437/34068722-597ad7a2-e1f5-11e7-8d0b-7e62c7336320.png)
![screenshot 2017-12-16 at 12 07 15 am](https://user-images.githubusercontent.com/29895437/34068723-59941d16-e1f5-11e7-82dc-27cb133f6bb1.png)
![screenshot 2017-12-16 at 12 07 01 am](https://user-images.githubusercontent.com/29895437/34068724-59abcb96-e1f5-11e7-9a6c-2cb553c17bc2.png)

**Comment by SamuiNe** [comment]
Not sure if this is intended or not, though probably it isn't.

**Comment by Sven65** [comment]
Fixed
