### ISSUE TITLE
My guild is broken

### ISSUE THREAD

**Issue by bhaddie** [DiscordDungeons/Bugs#519]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

it says I'm in a guild, I tried joining a guild, it says I'm already in one, then I #!gleave & #!gdisband, it says I'm in a non existing guild


```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

http://prntscr.com/hpg3jr

**Comment by SamuiNe** [comment]
There is a possibility that bot got confused by the current guild name, since the current guild you're in is named `None`. Need to do some experiments first, however.

**Comment by SamuiNe** [comment]
After testing around, apparently the guild named `None` doesn't cause this bug, and you're not in the guild. Due to this reason, its likely an isolated case.
