### ISSUE TITLE
Can’t travel from Sariila to Rivermouth / level 87

### ISSUE THREAD

**Issue by FruitLoopsBB** [DiscordDungeons/Bugs#521]
![4b170938-40af-462f-99cf-a0d9ecd4ca56](https://user-images.githubusercontent.com/34712847/34208847-34723b1e-e590-11e7-80e6-9b54fea2fcb1.jpeg)

**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Error message appears when player tries to travel from Sariila to Rivermouth. “Missing Access”

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

**Comment by FruitLoopsBB** [comment]
Thanks for answering. And yes, read messages, send messages and add reactions are enabled.


Von: Mackan<mailto:notifications@github.com>
Gesendet: Donnerstag, 21. Dezember 2017 09:17
An: DiscordDungeons/Bugs<mailto:Bugs@noreply.github.com>
Cc: FruitLoopsBB<mailto:aynonuthin@hotmail.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [DiscordDungeons/Bugs] Can’t travel from Sariila to Rivermouth / level 87 (#521)


Does the bot have permission to add reactions?

**Comment by PlayTheFallen** [comment]
Are there any permission overrides that deny permissions for the bot in that channel?

**Comment by Sven65** [comment]
This has been fixed after the issue was opened.
