### ISSUE TITLE
levels are messed up probably happened when mackan changed the walls

### ISSUE THREAD

**Issue by nathanielcwm** [DiscordDungeons/Bugs#524]
i expect it is fixable by just doing an adventure
![e718b082-1f45-48f3-b1b9-04f6d91fc7d9](https://user-images.githubusercontent.com/22572406/34368668-94d1dae0-eaf0-11e7-92fa-87f0b668d20b.png)

**Comment by Sven65** [comment]
Yup, that can be fixed with an adventure.
