### ISSUE TITLE
XP Bug

### ISSUE THREAD

**Issue by DarkPyroNinja** [DiscordDungeons/Bugs#525]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Having an abundance of XP over my level limit.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < https://imgur.com/VqIEFxD > )

**Comment by ryudragon98** [comment]
not really a bug this was caused by the removal and change of some xp walls all you have to do is mine, chop, fish, or forage and it will fix it.

**Comment by DarkPyroNinja** [comment]
Tyvm.
