### ISSUE TITLE
Gaining 3 levels just by foraging.

### ISSUE THREAD

**Issue by WildArticunoAppeared** [DiscordDungeons/Bugs#529]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
I went foraging, gained just 2 XP and then I gained three levels. I went from Level 11 to 14.
https://cdn.discordapp.com/attachments/254861154105557002/397306883758751744/unknown.png

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
Not an issue, xp walls were changed recently.
