### ISSUE TITLE
quest get bug

### ISSUE THREAD

**Issue by Rosenkreuz12** [DiscordDungeons/Bugs#53]
Waffles The Cat got this error when doing ``quest get``

![](http://i.imgur.com/STsfK22.png?1)

**Comment by Sven65** [comment]
Fixed.

**Comment by Rosenkreuz12** [comment]
apparently 2 day ago someone got this bug again 

![](https://gyazo.com/cc4d4a271fdb5f78c216f287b79c60b8)
