### ISSUE TITLE
Discord bot sending more then one message

### ISSUE THREAD

**Issue by idonknowyet** [DiscordDungeons/Bugs#531]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.** 
The discord rpg bot in the server im in keeps sending more then one message and i dont know how to fix the problem 

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

https://gyazo.com/79482a213b35a2e8f58aae9d060f41ac

**Comment by Sven65** [comment]
Known issue, it happens.
