### ISSUE TITLE
Channel #rpg-3 is broken Again !!!

### ISSUE THREAD

**Issue by BADEVILEVIL** [DiscordDungeons/Bugs#534]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

Bot don't react on any commands on channel #rpg-3...

**If an error is provided, please copy the block into the space below.**

```js

< [8:08 PM] BOTDiscordRPG: 
!========[ BADEVIL's adventure ]========!
% Rolled a 5
- Lost 8 HP.
+ Dealt 521 HP Damage
+ EvilDEAD dealt 1,641 HP damage.
- EvilDEAD took 9 HP Damage.
+ EvilDEAD has 8,351/12,125 HP left
+ BADEVIL has 4,182/7,900 HP left.
+ The enemy Pleofresh was slain by BADEVIL!
+ Rewards: 683 Gold and 283 XP.
+ EvilDEAD got 660 XP.
!========================================!
[8:08 PM] BOTDiscordRPG: BADEVIL cracked a geode and got a Rock.
[8:15 PM] BADEVIL: #!adv
[8:15 PM] BADEVIL: #!crack
[8:21 PM] BADEVIL: #!adv
[8:21 PM] BADEVIL: #!crack
[8:22 PM] BADEVIL: #!adv
[8:22 PM] BADEVIL: #!crack
[8:25 PM] BADEVIL: #!adv
[8:25 PM] BADEVIL: #!crack >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
We know of issues with the bot randomly dying, we're working on it.
