### ISSUE TITLE
Level Up Bug

### ISSUE THREAD

**Issue by allmachtig** [DiscordDungeons/Bugs#535]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
There is a leveling bug with the bot. I leveled up three times simultaneously without really doing anything. I believe this was what happened. 

1. The bot/server lagged, registering the commands at a later date than given.
2. I gave multiple commands.
3. The bot registered the all commands simultaneously.
4. During one of the commands I leveled up.
5. Because these commands were registered simultaneously, each command registered as a level up while normally only one would have registered as a level up.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < https://imgur.com/a/Jo4iW > )

**Comment by Sven65** [comment]
Known issue.
