### ISSUE TITLE
'buyfield' command not working

### ISSUE THREAD

**Issue by NuuMoo** [DiscordDungeons/Bugs#537]
![screenshot 2018-01-09 22 31 41](https://user-images.githubusercontent.com/35289152/34760656-30d0d86e-f58d-11e7-9ae1-c95998cc3cc1.png)
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
I'm not sure what to do here... I saw on the official server that there was a new command called 'buyfield' for crops and such. I tried buying a field in Copperfall but it gave me the error message I attached.

**If an error is provided, please copy the block into the space below.**

```js

< TypeError: message.channel.hasPerm is not a function
    at Buyfield.Execute (/home/mackan/RPGBot/src/Commands/Commands/Locations/Buyfield.js:127:23)
    at <anonymous> >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
Fixed

**Comment by NuuMoo** [comment]
Thank you so much!
