### ISSUE TITLE
Mining requirement much higher than level requirement for Meditation Magic quest

### ISSUE THREAD

**Issue by jemnidad** [DiscordDungeons/Bugs#538]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
I and a few other players just got to level 20 and started the Meditation Magic quest only to find that our Mining levels are much too low for the level 10 requirement to mine Silver Essence. I'm at level 6 and I've been mining as often as possible for as long as I've been grinding.
This requirement just seems to be out of balance.
Rickard told me to go ahead and submit a suggestion.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by RJain12** [comment]
If you are level 6 it might take a while to reach level 10 so I suggest that you buy essence from the global market if you are keen on getting a Silverkeep rune. This will allow you to get the quest done without having this quest there for a long time.

**Comment by Sven65** [comment]
Unknown issue
