### ISSUE TITLE
Party Failure - Stuck In Party!!!!!

### ISSUE THREAD

**Issue by Nightmare2112** [DiscordDungeons/Bugs#542]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

< see image>

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < https://cdn.discordapp.com/attachments/400964621424656384/400964741721489409/unknown.png > )

**Comment by shroomyun** [comment]
party broke 
![party01](https://user-images.githubusercontent.com/33994869/34869300-6b5e8d24-f7c1-11e7-9f52-c8c092af8056.png)
![party02](https://user-images.githubusercontent.com/33994869/34869326-855f105e-f7c1-11e7-8c8b-f3f5cf3704d8.png)
![party03](https://user-images.githubusercontent.com/33994869/34869337-8bb4c50c-f7c1-11e7-8452-be95f297a462.png)

**Comment by Sven65** [comment]
Fixed

**Comment by shroomyun** [comment]
thank you \o/
