### ISSUE TITLE
cannot unequip iron pickaxe

### ISSUE THREAD

**Issue by tamabooty** [DiscordDungeons/Bugs#546]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
I am trying to craft a steel pickaxe but my iron pickaxe is equipped. I cannot get it to unequip so that I can use it as a craft material. I entered "$unequip iron pickaxe" and the RPG Bot gave the output "Sorry, tamabooty, but that's an invalid tool."

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by TW-Dodger** [comment]
Not a Bug. It's "unequip <type>", so "unequip pickaxe"
