### ISSUE TITLE
Guild ad (owner mixup)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#547]
Whilst having the permission node for setting out guild ads, when a user that is **not the owner** sets out and ad, on the in guild adverts it shows that the user who set the ad as the owner.

Forexample with Hidden Leaf's latest guild ad, Bunny posted the guild ad whilst Damien Moon is owner of the guild on the display it shows Bunny as the Owner of the guild. _very lazy to screenshot it, but it's in the channel._

**Comment by nathanielcwm** [comment]
lol
![image](https://user-images.githubusercontent.com/22572406/34989881-2066b1fc-faff-11e7-839f-6600750940de.png)
can confirm

**Comment by PlayTheFallen** [comment]
[**DEV REFERENCE TO SOURCE**](https://github.com/Sven65/RPGBot/blob/master/src/Commands/Commands/Guild/Guildad.js#L226)

used the author's username, not the guild owner username

**Comment by Sven65** [comment]
Fixed by Fallen in PR 76
