### ISSUE TITLE
buyfield error message

### ISSUE THREAD

**Issue by MaximumRide93** [DiscordDungeons/Bugs#553]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Tried to #!buyfield 
used the green checkmark to confirm, didn't work - says time limit ran out. 
after the error, I tried again and it worked the second time, but thought I'd mention it anyway - feel free to close if it's not necessary :) 

**If an error is provided, please copy the block into the space below.**
DiscordRPGBOT - Today at 16:00
Whoops. An error occured. Please report this in the official server.
```js
< DiscordAPIError: Cannot execute action on a DM channel
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:218:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) >
```
You don't own a field here, MaximumRide93 use #!buyfield to buy one.

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url 
![image](https://user-images.githubusercontent.com/35571835/35108130-9ce5811a-fc6a-11e7-94ae-26bd90bc43e5.png)
> )

**Comment by PlayTheFallen** [comment]
since this is in DMs the bot doesn't have permission to clear reactions from the message

**Comment by francisyzy** [comment]
I also had this issue when buying field. Nothing game breaking since I still could plant.

```
DiscordAPIError: Missing Access
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:218:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
![screen shot 2018-02-11 at 9 21 44 pm](https://user-images.githubusercontent.com/24467184/36073819-995c6738-0f71-11e8-8972-cefcab58a09f.png)
ignore the funny nicknames

**Comment by PlayTheFallen** [comment]
@francisyzy did you check the bot's permissions for the server

**Comment by francisyzy** [comment]
Hmm, should external emojis be enabled?
![screen shot 2018-02-23 at 3 27 33 am](https://user-images.githubusercontent.com/24467184/36559909-44d45734-184a-11e8-9b94-25f29d7edfb4.png)

**Comment by Sven65** [comment]
This has been fixed after the issue was opened.
