### ISSUE TITLE
Party + Pet

### ISSUE THREAD

**Issue by shhunter777** [DiscordDungeons/Bugs#554]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

< When in a party with a few people, I wanted to train up my pet (Rock, level 81), and it took me an hour to realize it gained no xp. Not too upset, but this should be fixed. >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by PlayTheFallen** [comment]
either you didn't set a pet xp ratio or the party didn't have pets enabled

**Comment by shhunter777** [comment]
I can assure you both were on, I can provide screenshots if necessary. It was definitely a glitch/bug.
