### ISSUE TITLE
Level up bug with side activities

### ISSUE THREAD

**Issue by Zackboi28** [DiscordDungeons/Bugs#555]
**Please describe your issue below.**  

Hi i found this bug like a week ago or so and i ignore it because i thought it was just an error but it happened again. The issue is that if you are close to level up and you do any of the side activities sometimes you can level up twice as i show in the screenshot, this happened at first in the discord server and now it happened on my own server

PD: You can see in the adventure menu that my max hp it's 750 but after the 2 level ups my max it's 850

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below**

![screenshot](https://user-images.githubusercontent.com/35639912/35187894-64961cd6-fe02-11e7-8db6-f16262de5b15.png)

**Comment by Sven65** [comment]
Known issue.
