### ISSUE TITLE
#recipe dirty water vial

### ISSUE THREAD

**Issue by doge-pepe-twat68** [DiscordDungeons/Bugs#558]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
`#!recipe dirty water vial` shows an error although you can clearly craft it since I have already

**If an error is provided, please copy the block into the space below.**

```js
TypeError: Cannot read property 'formatNumber' of undefined
    at Recipe.Execute (/home/mackan/RPGBot/src/Commands/Commands/General/Recipe.js:131:45)
    at <anonymous>
```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
Fixed
