### ISSUE TITLE
Traveling to mire issue (I am not sure if it's happening at other locations)

### ISSUE THREAD

**Issue by C4NDaSavage** [DiscordDungeons/Bugs#560]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
I tried to travel Miree and it gave me an error.

**If an error is provided, please copy the block into the space below.**

```js

ReferenceError: currentLocation is not defined
    at Travel.Execute (/home/mackan/RPGBot/src/Commands/Commands/Locations/Travel.js:172:21)
    at <anonymous>

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by PlayTheFallen** [comment]
this is likely to happen once you have arrived and attempt to travel to another location without executing a different command that doesn't involve location change.

**Comment by Sven65** [comment]
Should be fixed
