### ISSUE TITLE
Market Trade (outdated?)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#561]
Hi, so after trying to sell an item to a trade that is active and shown with `#!gbsearch log` the trade 
`< 2,000,000 Logs (35G each) {ID. jb234xxh} [1,991,340 bought] >` seems to not work in selling logs to it.
My theory is the bot is recognizing it to be an outdated/canceled Trade.

As per the image shows me trying to sell to the trade - _for an odd reason searching the trade id with 
`#!gminfo` does not work_
![7478543](https://user-images.githubusercontent.com/12903523/35418020-58cd84be-0273-11e8-821a-402db256d731.png)

**Comment by Sven65** [comment]
Unknown issue, unknown cause, has probably been fixed since
