### ISSUE TITLE
Stuck in ghost battle.

### ISSUE THREAD

**Issue by DemonicRoze** [DiscordDungeons/Bugs#562]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Someone challenged me to a battle on another server a LONG time ago, and i have since left that server and cant contact the person. Well i was playing with the battle commands and accepted it somehow, despite being on a completely different server than before and that person never having been on this one. I dont know how to end the battle so i can get on with buying stuff again.  :/
It said "@invalid-user, DemonicRoze has accepted your challenge." Then it let me fight 1 time to see that old friends name in the bots response block. Ive tried proposing a draw, ive tried #!bstop (to which it says i cant because the battle is still active), and id really rather not try reseting my whole character.  >.<

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
Would you mind providing your Discord ID so we can clear the battle for you?

**Comment by DemonicRoze** [comment]
DemonicRoze#3638

**Comment by Sven65** [comment]
This has been fixed with the `#!bstop` fix.
