### ISSUE TITLE
Location bug.

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#566]
Whilst I traveled to RavenGate, I appeared to find a bug whilst using `#!location` , it's pretty much easy to notice what's wrong by the image 😃 
![ec7d1f](https://user-images.githubusercontent.com/12903523/35637499-bd86ae34-06f7-11e8-8dfd-1fe9b59e122e.png)

**Comment by Sven65** [comment]
Unable to reproduce.

**Comment by Sven65** [comment]
Updated in #604
