### ISSUE TITLE
Error while attempting to travel

### ISSUE THREAD

**Issue by ricefuhrer** [DiscordDungeons/Bugs#567]
When attempting to travel from Mournstead to Silverkeep, I got an error message from the bot. I don't know if this has anything to do with attempting to travel again while my character was still in the middle of making its journey to Mournstead, but I was able to normally proceed afterwards.

```js

 Whoops. An error occured. Please report this in the official server.
ReferenceError: currentLocation is not defined
    at Travel.Execute (/home/mackan/RPGBot/src/Commands/Commands/Locations/Travel.js:172:21)
    at <anonymous> 

```

![]( 
https://cdn.discordapp.com/attachments/392889654669606913/408468670583668736/Screen_Shot_2018-01-31_at_7.46.15_PM.png  )

**Comment by PlayTheFallen** [comment]
this is most likely because you were traveling to a location and you hadn't updated your location prior to doing so. *either that or something else was edited that we can't see here*

**Comment by Zanthr** [comment]
I got a similar problem for what I assume is a similar reason. Might want to have #!travel update location before checking it. Either that, or just having it post text that says "hey traveler, do some stuff before you leave." so the player has to update their location before traveling again.
![dungeonbug](https://user-images.githubusercontent.com/12092146/36342882-ceec78ec-13d2-11e8-81b7-18c3a000e866.PNG)
