### ISSUE TITLE
gmsell error

### ISSUE THREAD

**Issue by Rosenkreuz12** [DiscordDungeons/Bugs#57]
icyblade got following bug when tried to sell orchid sword on global market
![](https://cdn.discordapp.com/attachments/173361708885213186/240089017301860354/IMG_20161024_082737.jpg)

and nedr also got same error
![](http://i.imgur.com/fSN8rmd.png?1)
though later it's found out the reason for nedr's error be the iron battleaxe is still equipped

**Comment by Sven65** [comment]
Fixed.
