### ISSUE TITLE
Error when using #!gbbuy

### ISSUE THREAD

**Issue by ChickenSoup2730** [DiscordDungeons/Bugs#572]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

Error response when attempting to post a buying request on global market. It may be noted that this has also happened to someone else before and we both have done a reset on our characters prior to having this issue.

**If an error is provided, please copy the block into the space below.**

```js
TypeError: Cannot read property 'activated' of null
    at Gbbuy._isMember (/home/mackan/RPGBot/src/Commands/Commands/Market/Gbbuy.js:92:25)
    at Gbbuy.Execute (/home/mackan/RPGBot/src/Commands/Commands/Market/Gbbuy.js:208:26)
    at <anonymous>
```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![img_0899](https://user-images.githubusercontent.com/36148506/35791091-1a59bff8-0a1c-11e8-8e1f-0674170997f7.PNG)

**Comment by PlayTheFallen** [comment]
After looking at the error and the lines in question, your profile may be partially invalid.
_You shouldn't have to restart your profile._

**Comment by jenjenayjen** [comment]
I am having this issue as well. How is this fixed?

**Comment by Sven65** [comment]
Issue is with the "member" field of the users profile being null

**Comment by Sven65** [comment]
This has been fixed after the issue was opened.
