### ISSUE TITLE
Quest problems

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#573]
User (400821947480670208) is stuck on the Meditative Magic per `undefined` message.
The user was on the step to gather the Silver Essence, whilst they gathered them and trying to talk to the Rune Guru the message in the screenshot below appears. 
![50f36b](https://user-images.githubusercontent.com/12903523/35829999-0b31b110-0b08-11e8-9ef0-d88a102a10e3.png)

**Comment by PlayTheFallen** [comment]
What was the message before? *I can't find the stage.*

**Comment by FelixArgyle** [comment]
Just read back with the user and it seems that they only had 3 Silver Essence whilst the quest asks for 5, but still it shouldn't show an undefined message it should show something such as "<user>, I still need those Silver Essence."
![751f1b](https://user-images.githubusercontent.com/12903523/35944025-6a7f5d4c-0c9e-11e8-989e-ae4b93db5c3c.png)
Note: This screenshot isn't the same user as the one who had the undefined message, but it's the message before the Silver Essence step.

**Comment by PlayTheFallen** [comment]
**DEV REF**
npc.noEssence is undefined for npc 24 (RuneGuru.js)
