### ISSUE TITLE
uset nick appear to be broken

### ISSUE THREAD

**Issue by mewchan1197** [DiscordDungeons/Bugs#574]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by PlayTheFallen** [comment]
Related to #252 and #438
