### ISSUE TITLE
Guild ally bug

### ISSUE THREAD

**Issue by Takashi-22812** [DiscordDungeons/Bugs#575]
__**Issue:**__
Guild ally (for the nova guild) isn't letting me add more than 1 ally even though it should let me have 3 allies.

![]( <https://media.discordapp.net/attachments/380057308417228800/411551157174009863/Screenshot_2018-02-09_at_8.55.48_AM.png?width=360&height=300> )

**Comment by PlayTheFallen** [comment]
You already posted this. #565

**Comment by Takashi-22812** [comment]
oh
