### ISSUE TITLE
Pet doing too little damage 

### ISSUE THREAD

**Issue by TytoOwlet** [DiscordDungeons/Bugs#576]
I have caught and battled with about 10 different pets today. All from level 20-24 so they should be doing a fair amount of damage but they're all doing 3-5 points of damage each time.

**Comment by TytoOwlet** [comment]
The pet species wasn't always different I'd like to add, there was about 5 different species I think. All had the same problem though. Most of them I don't even see on the beast list on the wiki so I'm guessing new monsters have been added recently and something went wrong along the way.

**Comment by ryudragon98** [comment]
once at lvl 21 you will encounter mobs that are known as dynamobs they are mobs that are scaled to your level they will have high hp and deal low damage, if you look on the wiki there's a pets page where you can see all static pets if you have tagbot in your server you can do tagbot petlist and it will show you the list any mob not listed in the list is a dynamob and do not ma. as of now flibknort a lvl 21 pet is the best pet when leveled for those who do not have a membership. if you have a membership then you can go for the green dragon which is better than flibknort when leveled.

**Comment by TytoOwlet** [comment]
I currently have a 'soiffaine' which isn't even in the wiki from what I see. It is level 22 and doing at max 5 damage.
