### ISSUE TITLE
LEMONs

### ISSUE THREAD

**Issue by tyler489** [DiscordDungeons/Bugs#577]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Lemons cannot be sold? Bot refuses to respond to #!sell lemon

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
You can't sell lemons.
