### ISSUE TITLE
Location repeated twice in Ravengate description.

### ISSUE THREAD

**Issue by ChickenSoup2730** [DiscordDungeons/Bugs#578]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

A location is repeated twice(Adventurer's restaurant) when using #!location at Ravengate.

**If an error is provided, please copy the block into the space below.**

N/A

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![img_0943](https://user-images.githubusercontent.com/36148506/36088469-d0f54926-0fad-11e8-8887-7b59f5286a62.PNG)

**Comment by Sven65** [comment]
Same issue as #566
