### ISSUE TITLE
Unable to unequip item 

### ISSUE THREAD

**Issue by TytoOwlet** [DiscordDungeons/Bugs#579]
I am unable to unequip my copper pickaxe (for replacing it with a zinc pickaxe) 

It gives me "Sorry, (name), but that's an invalid tool."

I'm typing it correctly so I don't know where it's going wrong. I was able to unequip using the same process without any problem yesterday.

**Comment by Sven65** [comment]
It's `unequip <tool type>`, in this case, `pick`
