### ISSUE TITLE
Not Getting Any Player Exp After A Adventure

### ISSUE THREAD

**Issue by Kaeleomel** [DiscordDungeons/Bugs#580]
Issue: I'm not getting any player exp after an adventure so I can't level anymore, I took a break for about 14 months.

Imgur link of stats before and after aswell as attributes: https://imgur.com/a/rEwll

**Comment by ryudragon98** [comment]
do #!pset xprate 0 you have the pets xprate at 100 which makes so the pet only gets xp and not you.

**Comment by Kaeleomel** [comment]
i just did let me go do another adv real quick

**Comment by Kaeleomel** [comment]
that fixed it thank you ryudragon98 :)

**Comment by ryudragon98** [comment]
no problem
