### ISSUE TITLE
Minor bug: #!Equip: command with no text

### ISSUE THREAD

**Issue by Lyrcaxis** [DiscordDungeons/Bugs#583]
**Please describe your issue below.**  

#!Equip command functions but has no text.

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![tldr]( < http://prntscr.com/ig3kiy > )

**Comment by ryudragon98** [comment]
there is no equip cmd. when you buy from #!items it auto-equips.
