### ISSUE TITLE
#!Mine without a pickaxe starts timer

### ISSUE THREAD

**Issue by Lyrcaxis** [DiscordDungeons/Bugs#584]
When someone attemps to `Mine` without a pickaxe, then buys a pickaxe ,uses it and tries,
he's prompt to wait for stamina to regenerate
(might be the same with `chop` or `fish` didn't try)

**Comment by PlayTheFallen** [comment]
this issue is known with the command execution order...
- check for discrepancies with message object
- check if command exists
- attempt to execute command
- update cooldown

**Comment by Sven65** [comment]
Not a bug, if you use the command, it triggers the cooldown.
