### ISSUE TITLE
Cannot change Nicks

### ISSUE THREAD

**Issue by RewiredTV** [DiscordDungeons/Bugs#587]
![9f4b7988-68a5-42fa-818e-877b9b60f320](https://user-images.githubusercontent.com/35697577/36575785-cbaa1bfc-181a-11e8-8b56-c91ec36dd036.jpeg)
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Cannot change nicknames. Get error about privilege too low. Bot has all privileges on server.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by ryudragon98** [comment]
the bot doesn't have the permission to change nicks or the bot is placed below you and it can not change your nick, and if you are the owner of the server the bot can not change your nick it can only change the nick of the members in your server.
