### ISSUE TITLE
Global Market item check error

### ISSUE THREAD

**Issue by GingkathFox** [DiscordDungeons/Bugs#589]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
I tried to check my sell on the global market, and I got this:
```
502 Bad Gateway

nginx/1.4.6 (Ubuntu)
```

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by FelixArgyle** [comment]
It's best to change your trade display to the embed version (it shows it like that because that api is on v3)  
To change it use -  #!uset tradedisplay 2

**Comment by GingkathFox** [comment]
that worked, thanx Felix!
