### ISSUE TITLE
Friend broke their character?

### ISSUE THREAD

**Issue by GhostSama** [DiscordDungeons/Bugs#590]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Friends stats said 1,900 / 1,400 and now they can't do side quest

**If an error is provided, please copy the block into the space below.**

```js
Whoops. An error occured. Please report this in the official server.
```js
TypeError: Cannot read property 'scavenge' of undefined
    at Forage.Execute (/home/mackan/RPGBot/src/Commands/Commands/Sides/Forage.js:166:37)
    at <anonymous>
```

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
Could you provide some more info?

**Comment by Sven65** [comment]
This has been fixed after the issue was opened.
