### ISSUE TITLE
Irregular amount of silver essence in Silverkeep altar 

### ISSUE THREAD

**Issue by Vishaakha** [DiscordDungeons/Bugs#591]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
After putting all my attributes in mine boost. I should be getting 89 per mine. Which works fine with all except silver essence. I have been getting them in different amount. Some of them are 63,75, 73,64 and 68.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Vishaakha** [comment]
![img_20180227_123213](https://user-images.githubusercontent.com/36877021/36718672-a44b1b86-1bc8-11e8-8f0b-8e1d2de1d03f.jpg)
![img_20180227_123109](https://user-images.githubusercontent.com/36877021/36718682-b041389e-1bc8-11e8-8bb3-fbee41d00d10.jpg)
![img_20180227_123142](https://user-images.githubusercontent.com/36877021/36718684-b0fe96f0-1bc8-11e8-8d37-3896b03622e1.jpg)
![img_20180227_123158](https://user-images.githubusercontent.com/36877021/36718685-b1ac72ca-1bc8-11e8-9629-2ccdab551dcb.jpg)
![img_20180227_123124](https://user-images.githubusercontent.com/36877021/36718687-b2e0cd62-1bc8-11e8-8ee5-084b63480ff8.jpg)

**Comment by Sven65** [comment]
Not a bug, the formula has a minimum and a maximum amount based on your stats that it randomizes between.
