### ISSUE TITLE
Guild Permissions

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#595]
After an experience of leaving my guild (in the past) before I left I had permissions to advertise the guild via `#!setperm` , after leaving and rejoining (for testing a bug) I still had the permission set to me, this can be tested since I cannot locate the time/place of when this occurred but I do hope this helps solve this issue.

**Comment by PlayTheFallen** [comment]
Issue Confirmed
Todo:
- [ ] Add check for guild permissions
- [ ] Remove guild permissions if true
