### ISSUE TITLE
Bugs with leveling up?

### ISSUE THREAD

**Issue by therealshade** [DiscordDungeons/Bugs#597]
I'm not level 7 when I have more than enough XP to go from level 6 to 7. If there's a command to level up now, I haven't checked. But if there isn't, I don't know why I'm not level 7.

**Image proof below:**
[https://prntscr.com/io7dpe](https://prntscr.com/io7dpe)

**Comment by ryudragon98** [comment]
to lvl up simply do #!forage and you should lvl up.

**Comment by therealshade** [comment]
ok

**Comment by Sven65** [comment]
Closed as invalid.
