### ISSUE TITLE
Bug with #!attributes page

### ISSUE THREAD

**Issue by Ammonil** [DiscordDungeons/Bugs#598]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
When I do #!attributes, it shows all the attributes, and how many points I have put into each one, like it should. But, it doesn't tell me the effect of those attributes. For example, I have 2 defense points, and it says -0 damage.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )
![image](https://user-images.githubusercontent.com/37168115/37133395-6d120b5a-2250-11e8-9f30-cdd300240d41.png)

**Comment by ryudragon98** [comment]
this is not a bug. each attribute takes a certain number of points to show a 1%, -1, or +1. defense takes 10 points to get a -1 dmg, and other attributes can take more if you have tagbot in your server you can do tagbot attributes to see the formulas and how many points it takes for each attrib. you can also check the wiki for the formulas as well.

**Comment by Ammonil** [comment]
Thanks for the help!

**Comment by ryudragon98** [comment]
no problem.
