### ISSUE TITLE
Stats page on website not working

### ISSUE THREAD

**Issue by pitothepowerof3** [DiscordDungeons/Bugs#599]
When I attempt to log in with discord to view my stats on discorddungeons.me, I get all 0 stats and a PHP error, shown below. I'm a level 6 player, so it's not because I haven't created a character.

```Notice: Undefined index: user in /var/www/html/stats/index.php on line 47```

![image](https://user-images.githubusercontent.com/9117849/37183845-0c133bba-2306-11e8-8e1b-d7e3e4c3c108.png)

Looks like you might want to check your database, I obviously don't have access to your backend so I can't suggest anything further.

**Comment by ryudragon98** [comment]
looks like that page is out of date as those stats are no more, luck and charisma were removed.

**Comment by Sven65** [comment]
Unrelated to the bot itself.
