### ISSUE TITLE
lead bug

### ISSUE THREAD

**Issue by Rosenkreuz12** [DiscordDungeons/Bugs#60]
doing lead followed by any random words will result in DRPG bot typing for quite some time and an error message

![](http://i.imgur.com/B8tWTeW.png?1)

**Comment by Sven65** [comment]
Known issue. The lead command is being reworked.

**Comment by Rosenkreuz12** [comment]
lead guild lead to this error
![](http://i.imgur.com/E0eNgBG.png?1)

**Comment by Sven65** [comment]
This has been fixed.
