### ISSUE TITLE
Pet leveled up message 

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#600]
Whilst leveling a pet and receiving a chest at the same time, if the pet levels up no message saying "PetName Leveled up!" it just shows the XP that was gained.

The screenshot below shows it (as it happened in #rpg-1) 
![7375a4](https://user-images.githubusercontent.com/12903523/37228444-04cda18c-2424-11e8-8075-d1a75fae1c35.png)

**Comment by FelixArgyle** [comment]
Unsure, it's hard to re-produce getting a chest and levelling up at the same time.

**Comment by Sven65** [comment]
I see, might have to do a quick test with the testbot to increase the chances and whatnot

**Comment by Willard21** [comment]
No longer an issue. 
![image](https://user-images.githubusercontent.com/24826881/48309284-56b06780-e53c-11e8-8a26-571272746a67.png)
