### ISSUE TITLE
Undefined Message (NPC)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#602]
User talked to NPC (Felix), (Hubert) and got an undefined message.
![e7319e](https://user-images.githubusercontent.com/12903523/37338102-c1612ee0-26f9-11e8-908a-c9df702a74ab.png) 
![d0a544](https://user-images.githubusercontent.com/12903523/37338465-df1cd97e-26fa-11e8-9687-8c54250e36ac.png)
Best to check all the NPC's per there may be more that are experiencing this.

**Comment by PlayTheFallen** [comment]
**Dev Notes**  
Might be to do with a property in either of the NPCs that has remained undefined or undeclared.  
Related to #573 but with latest updates *and will affect future expansion mentioned by Mackan*.
