### ISSUE TITLE
Connections duplicating 

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#604]
Whilst using `#!location` the Connections appear to duplicate area Buckleport.
![a450a4](https://user-images.githubusercontent.com/12903523/37339314-9ed53020-26fd-11e8-8df0-e21889e0925e.png)

**Comment by Sven65** [comment]
Unable to reproduce

**Comment by knightdestin** [comment]
Happened to me today too. Was on the location (Tower of Eternity) for the quest, and did the quest. I searched two times into the location for information, and didn't leave it during the whole time for crafting things (had all compos needed on me). After completing quest, Buckleport get doubled. I left location to Desert, came back, now triple.
Did all the commands in my own server.

![bug1](https://user-images.githubusercontent.com/31276990/37428188-bc351e7c-27cb-11e8-98bd-d012ec510014.PNG)
![bug2](https://user-images.githubusercontent.com/31276990/37428193-bf348dd8-27cb-11e8-8f9f-216ace082314.PNG)
![bug3](https://user-images.githubusercontent.com/31276990/37428196-c1f07870-27cb-11e8-97c9-77cb7c014507.PNG)

**Comment by Zoey50451Rockz** [comment]
It happened to me today as well.. I finished the quest, went to the new island, then decided to go back to the Tower of Eternity. Then I checked the location, and saw this:
![a](https://user-images.githubusercontent.com/37601426/37688347-fbb097e4-2c75-11e8-9c0b-b277cb2ca48f.PNG)

**Comment by Sirfirelord69** [comment]
![image](https://user-images.githubusercontent.com/42024016/44615593-545d3c00-a870-11e8-8494-5c2dc4edf4c8.png)
The number of Buckleports has never changed, its always 4, but i have not seen it elsewhere.
