### ISSUE TITLE
Error with #!task accept/decline

### ISSUE THREAD

**Issue by Naoeaoe** [DiscordDungeons/Bugs#609]
`TypeError: message.channel.permissionsFor is not a function
    at Task.Execute (/home/mackan/RPGBot/src/Commands/Commands/User/Task.js:187:23)
    at `<anonymous>`
![2018-03-13 23_41_45- discordrpg - discord](https://user-images.githubusercontent.com/29278305/37371467-20f0aebc-2718-11e8-8ba8-e25edcb8f087.png)
![2018-03-13 23_41_33- discordrpg - discord](https://user-images.githubusercontent.com/29278305/37371472-24b7b036-2718-11e8-95c2-c0c990eca159.png)

Don't think I need to say anything...

**Comment by PlayTheFallen** [comment]
@Naoeaoe was this run in DMs?
