### ISSUE TITLE
#!talk alex bug

### ISSUE THREAD

**Issue by doge-pepe-twat68** [DiscordDungeons/Bugs#610]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
I tried to talk to alex and it gave me this error

**If an error is provided, please copy the block into the space below.**

Whoops. An error occured. Please report this in the official server.
```js
TypeError: Cannot read property 'prefix' of undefined
    at Talk._prepareDialog (/home/mackan/RPGBot/src/Commands/Commands/Locations/Talk.js:509:166)
    at <anonymous>
```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by sap-spectre** [comment]
same issue for me as well.

**Comment by shroomyun** [comment]
![_20180315_055342](https://user-images.githubusercontent.com/33994869/37432641-faf7ecdc-2813-11e8-90d6-99c03355bbad.JPG)
same '-');;
