### ISSUE TITLE
Tasks Blacklist 

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#611]
If a user has a membership the tasks only come down to membership items e.g. green hide / green hide armor, erinotite staff and so on.

**Comment by Nightmare2112** [comment]
Other task do appear for members.

**Comment by FelixArgyle** [comment]
Filters for tasks -

Blacklist Types: **Rune** , **Armor - Helmet, Chestplate, Boots** , **Tools**, **Weapon** | **Donator** 

A fairly few given other items to blacklist: **Money Bag (100k)#481** due to it not being able to craft. , **Letter#129** , **Letter Piece#128** , **Bear#462** **Felix's Fur#657** as you get 1 per 7 days of checking a trap.

Not sure if it's already added but some things require level requirements to get so make sure when a user asks for a task that it doesn't give an item that isn't their level.

_Ignore the refrence for 481 (item id matched to a closed issue.)_

**Comment by FelixArgyle** [comment]
@tklaxbro, when you asked, do non-members get affected with getting member items in tasks, they actually do.  (thought that had been fixed by Mackan)

![AKdEqFQ](https://user-images.githubusercontent.com/12903523/55285321-684bbc00-53c4-11e9-8c34-324c8145aafb.png)
Turbie is not a member, their id - 104420589497757696
yet they received "green hide chestplate" in their task.  

[posting it here cause it's for "tasks" in general]

**Comment by Sven65** [comment]
done some stuff
