### ISSUE TITLE
Bug with DM.

### ISSUE THREAD

**Issue by Naoeaoe** [DiscordDungeons/Bugs#612]
I don't know how to replicate this, I traveled to Dawnburg and after arriving I got this:
DiscordAPIError: Cannot execute action on a DM channel
    `at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by PlayTheFallen** [comment]
Command?

**Comment by Naoeaoe** [comment]
`#!travel`

**Comment by PlayTheFallen** [comment]
Did you run another command before this?

**Comment by Sven65** [comment]
No more info given, closing.
