### ISSUE TITLE
Missing Permissions Error

### ISSUE THREAD

**Issue by jfinalfunk** [DiscordDungeons/Bugs#613]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
I started a buyfield transaction, but decided to let it time out. Before it timed out, I did #!adv and then got the error seen below. After a few minutes, I tried again and it worked fine.

**If an error is provided, please copy the block into the space below.**

```js

Whoops. An error occured. Please report this in the official server.
DiscordAPIError: Missing Permissions
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![image](https://user-images.githubusercontent.com/1727943/37477295-96052e86-2834-11e8-93bc-918701d25cd7.png)

**Comment by PlayTheFallen** [comment]
The bot is missing manage messages. The action it attempts to do is removing reactions from its own message.
