### ISSUE TITLE
User travels while traveling 

### ISSUE THREAD

**Issue by RJain12** [DiscordDungeons/Bugs#616]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
If a user travels while traveling, the following error is produced. 

**If an error is provided, please copy the block into the space below.**

```js
ReferenceError: currentLocation is not defined
    at Travel.Execute (/home/mackan/RPGBot/src/Commands/Commands/Locations/Travel.js:172:21)
    at <anonymous>
```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by ryudragon98** [comment]
this a known error, its because while traveling you dont have a set location and the travel cmd goes by your current location to determine where you are able to go, so it will give this error if you use the travel cmd while traveling.
