### ISSUE TITLE
Multiple Buckleports

### ISSUE THREAD

**Issue by nathanielcwm** [DiscordDungeons/Bugs#617]
When you do location in the tower of eternity there are multiple buckleports

Before Quest:
![before](https://cdn.discordapp.com/attachments/402096009804513310/424758451441369099/unknown.png)

After:
![after](https://cdn.discordapp.com/attachments/402096009804513310/424762915099377686/unknown.png)

**Comment by Sven65** [comment]
Same issue as #604
