### ISSUE TITLE
#!stats command not working for new player

### ISSUE THREAD

**Issue by pizzalorddex** [DiscordDungeons/Bugs#619]
**Please describe your issue below.**  
Brand new player, I tried to use the stats command to start the adventure and got an error back.

**If an error is provided, please copy the block into the space below.**

```js

TypeError: Cannot read property 'name' of undefined
    at Stats._sendStats (/home/mackan/RPGBot/src/Commands/Commands/User/Stats.js:89:80)
    at <anonymous>

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![screen shot 2018-03-20 at 21 38 55](https://user-images.githubusercontent.com/37597645/37681793-f1e05eae-2c87-11e8-9c0d-f215bc4da546.png)

| EDIT | |
| ---: | :--- |
| Editor | @PlayTheFallen |
| Timestamp | Wed, 21 Mar 2018 12:19:14 GMT |
| Reason | Fix Image Formatting<br>Remove `<img/>` tag |

**Comment by Sven65** [comment]
Dev note; It's running into an issue when pulling the ring name because there is no ring

**Comment by Sven65** [comment]
Should be fixed

**Comment by pizzalorddex** [comment]
The error I get using the stats command is still the same
