### ISSUE TITLE
Plant bug

### ISSUE THREAD

**Issue by Rosenkreuz12** [DiscordDungeons/Bugs#62]
apparently when you do plant check within 24 hours of planting it'll throw you with NaN

![](https://images-1.discordapp.net/.eJwFwUsOgyAQANC7sJevDOgdTJp4AEKQgI06BKarpnfve1_26RdbWSVqYxXiOEfCfvBB2GPJvCCWK8d2Dp7wFpEopnrnh4ZQzhhQTnrvrVZGeRB6ln4GaRcwzkkNAGJPPecn7BUpaKlgUnLSECKFhRvLtQ-vjb9bYb8_XMIqbQ.XinplqnPiKhOngZnK613ZwFGPVE)

![](http://i.imgur.com/eumwcaO.png?1)

**Comment by Vaculity** [comment]
I had planted that a few hours ago and I got that issue as well.

**Comment by Sven65** [comment]
Fixed the issue.
