### ISSUE TITLE
location and map commands, issue

### ISSUE THREAD

**Issue by WinterRose11** [DiscordDungeons/Bugs#620]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

< location and map commands show nothing, please help. everything else works. trying to quest and play but am unable to see where I am going or NPC's. Still able to see all other commands. >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by PlayTheFallen** [comment]
Can you please use the format correctly... thanks
