### ISSUE TITLE
Inventory not displaying all of my items

### ISSUE THREAD

**Issue by manicmonky** [DiscordDungeons/Bugs#621]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
When my inventory got large enough to spill over to the second page, I was looking through what I had in order to do some crafting. I sent #!inv and saw the first page of items, then #!inv 2 to see the second page. I knew I had Rock Salt in my inventory but neither list showed it. After selling a few fish and getting back down to 1 page, I saw my Rock Salt again.

I believe the inventory pages, at least between 1 and 2, are calculating off by one so an item is not being displayed anywhere when it should be.

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![dd_inv_error](https://user-images.githubusercontent.com/37624238/37712483-055f3e64-2ce2-11e8-84c2-34b059e6af9c.png)

**Comment by Sven65** [comment]
Interesting, will look into.

**Comment by RJain12** [comment]
The rock salt was probably the first item on your second page of inventory. After you got rid of rocks, the rock salt moved back to the first page and then you checked the 2nd page so it wasn't there. It might be different but that's what it looks like based on the order you have after selling/crafting until you have 1 page left.

**Comment by manicmonky** [comment]
Look at the screenshot on the left. It shows page 1 and page 2 of my inventory. The rock salt is not displayed on either page until after I sold enough items to drop down to only one page of items.

**Comment by FelixArgyle** [comment]
mhm, as RJain said as I see you were selling things mid past the two screenshots, as the Rocksalt would be on the second page once crafting rocks into sand the rocksalt then got put onto the first page as from your current items you had e.g. the ones under in red below, if you were to check page two before the crafting then it would have been listed on the second page. (you mostlikely got mixed up with this.)
![75d4fb](https://user-images.githubusercontent.com/12903523/38732723-371a12d2-3f5a-11e8-83f0-be68838a62e3.png)

**Comment by Sven65** [comment]
Not an issue from what I can read from other comments.
