### ISSUE TITLE
Location and Maps commands show nothing

### ISSUE THREAD

**Issue by WinterRose11** [DiscordDungeons/Bugs#622]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Location and map commands show nothing. Pulls up the discord bot but no information is given by the bot. Error on both pc and android for the same user. 

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( <https://i.imgur.com/IPxayv4.png> )

**Comment by Sven65** [comment]
Does the bot have permission to embed links in the server?

**Comment by WinterRose11** [comment]
The bot has every permission

**Comment by Sven65** [comment]
Interesting.

I can't seem to reproduce the issue.

**Comment by WinterRose11** [comment]
Hmm. What's the next step then?

**Comment by Sven65** [comment]
I don't know, try it again?

**Comment by WinterRose11** [comment]
Problem still persists. Any other ideas?

**Comment by Sven65** [comment]
None, sorry.

**Comment by Sven65** [comment]
Unable to reproduce.
