### ISSUE TITLE
Travel Bug

### ISSUE THREAD

**Issue by AkashicBearer** [DiscordDungeons/Bugs#623]
I did #!travel tower and then I did #!travel ash 
It started traveling to Ash gate, and then I  clicked on the OK for traveling to Tower, No error message was shown, but it traveled to Tower instead of ashgate. ( I think this can work with all the locations)

![The Screenshot](https://media.discordapp.net/attachments/172382467385196544/426355526717407233/unknown.png?width=360&height=157)

**Comment by Sven65** [comment]
Dev note; Lock user travel somewhere, probably with redis

**Comment by loopyd** [comment]
This happened to me as well when taking the fairy from Frostridge to Rivermouth (in that direction).  `#!adv` seems to keep you stuck, I was able to get out of it (in my case) with a `#!chop` command, which updated the location and pulled me out of the loop.

**Comment by Sven65** [comment]
Should be fixed
