### ISSUE TITLE
Doing #!inv in DM and then clicking on "x" reaction

### ISSUE THREAD

**Issue by P1M5** [DiscordDungeons/Bugs#625]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
When you dm the bot #!inv and then click the "x" reaction it shows the error below

**If an error is provided, please copy the block into the space below.**

```js

< Whoops. An error occured. Please report this in the official server.
DiscordAPIError: Cannot execute action on a DM channel
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( <http://imgur.com/Myy4R5l> )

**Comment by PlayTheFallen** [comment]
**Dev Note**
Permission check not correctly invoked.

**Comment by Sven65** [comment]
Error is that the bot can't remove user reactions in a DM.
