### ISSUE TITLE
Scrolling_pages_feature.exe has stopped working!

### ISSUE THREAD

**Issue by YaboiNoah** [DiscordDungeons/Bugs#626]
This happened when i was scrolling through pages of #!inv, it's completely dead somehow. 

![bug](https://user-images.githubusercontent.com/37693416/37823610-89df1c8c-2ebc-11e8-8529-7e5ff933323d.png)]

**Comment by Sven65** [comment]
Dev note; It seems the reactioncollector dies without throwing an error
