### ISSUE TITLE
Error when doing #!quest (I found out you needed to activate the Embed links and it worked)

### ISSUE THREAD

**Issue by Smoketrain** [DiscordDungeons/Bugs#627]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
When I do #!quest on my server the bot gives me an error
I have Read Messages, Send Messages, Manage Messages, Embed Links, Use External Emojis, and Add Reactions on in permissions.

**If an error is provided, please copy the block into the space below.**

```js

< DiscordAPIError: Missing Access
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![error](https://user-images.githubusercontent.com/37713902/37850732-ac1f909c-2eb2-11e8-9b63-31ec9ef0cf25.PNG)

**Comment by ryudragon98** [comment]
does the bot have react perms?

**Comment by Smoketrain** [comment]
yes

**Comment by PlayTheFallen** [comment]
MANAGE_MESSAGES?

**Comment by Smoketrain** [comment]
i have updated what i have allowed and still the error

**Comment by Sven65** [comment]
TODO: Add check to see if the bot has embed perms

**Comment by RyGuy88228** [comment]
@PlayTheFallen needs `EMBED_LINKS` and `SEND_MESSAGES`

**Comment by Sven65** [comment]
Old and probably fixed
