### ISSUE TITLE
Remove guild tag

### ISSUE THREAD

**Issue by player9689** [DiscordDungeons/Bugs#628]
When ive set guild tag i cant remove it when i do gset tag 0 it becomes 0 doesnt go away

**Comment by PlayTheFallen** [comment]
**`DEV NOTE`**
[Value of guild tag isn't set to null or undefined](https://github.com/Sven65/RPGBot/blob/master/src/Commands/Commands/Guild/Gset.js#L230-L246)
suggest using a term such as `N0N3` or `R3M0VE` to match *numbers would be used as a method of acknowledgement*
