### ISSUE TITLE
Ignored when using DM

### ISSUE THREAD

**Issue by Rosenkreuz12** [DiscordDungeons/Bugs#63]
lyruk got ignored by the bot while playing using DM he's still able to play on the official server but not on DM

![](https://cdn.discordapp.com/attachments/172389002190651393/241280575028068353/unknown.png)

**Comment by Sven65** [comment]
I don't know what causes the issue at all, but it might be due to the user spamming the commands.

**Comment by Sven65** [comment]
Not an issue, most likely ignored for spamming.
