### ISSUE TITLE
Fuck you for fucking wasting my time doing this stuff reporting your fucking mistakes!!!

### ISSUE THREAD

**Issue by MeguminExplosion** [DiscordDungeons/Bugs#631]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

< Damn the Quest for Temple of Moukn is bug fuck i can't take the quest waste of fucking time you better fucking fix this fuck idiot for not looking at this fucking bug fuck, fuck you!!!!! Damn wasted my time crafting compass damn only to show you can't even get quests are you fucking kidding me do you? Well you reall fucking pissed me off fuck you!>

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
Closed due to poster not being able to report a bug properly.
