### ISSUE TITLE
Donator Items Xp Boost Calculations

### ISSUE THREAD

**Issue by Nightmare2112** [DiscordDungeons/Bugs#632]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
After Running multiple test, with  0 Stat Attribs, Assigned To Xpboost On Static Mob Green Dragon,
It appears that the Xpboost on Chest,Helm,Boots, And Necklace's is not being applied, or applied how intended. Please see the attached spreadsheet with The Xp Info. You Will See In Picture one That, Using Regular Armour (without boost) Actually produces the same (less at times due the range of xp awarded) as equipping the multiple xpboost items with a total of 50% Xpboost.  This was repeated again, while wearing the Ring of XP (1.5X), as well as tested and logged after assigning 200% xpboost in stats. All results return the same and Xpboost that is supposed to be granted from other Items is not correctly or as expected.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![image](https://user-images.githubusercontent.com/33561320/37868645-697e664a-2f80-11e8-902a-2da0122a8da1.png)
^^^^ With No Assigned Xpboost Stats
![image](https://user-images.githubusercontent.com/33561320/37868651-76dcf72a-2f80-11e8-8abb-ee47e3140c68.png)
^^^^ With 200% Xpboost From Stats
![]( < image url > )

**Comment by Sven65** [comment]
(Sorry for the delay, had stuff to do)

Right, just checked on the adv command, at the moment the boost you get from the attributes, (xpBoost and goldBoost), both from status points and the items are added as boosts based on the base amount of gold and xp you get from the kill.

After this, if you have a ring, the ring boost is applied to the rewards and after that the necklaces.

To me, it seems like there's no reason this should be happening, where are you getting the expected XP from?

**Comment by Nightmare2112** [comment]
No worries :D , So the expected was just a the base xp * the Amount of Boost From Items (50%) , Even if you take the "expected" out and just look at the xp data, while using items totaling 50% xpboost, there was little if any XP gain. Kills without the items averaged 968xp , while when equipping the items they averaged 828xp. It's hard to explain without knowing exactly the base xp and such i should be recieving. However if you test on a character you should be able to see, how xpboost from items arent applying.
As additional example currently gain around 6k xp from each mob. However when i equip my items there is No noticeable difference where based off.

**Comment by Nightmare2112** [comment]
If it would be easier we can get together in game one day to test and show you in action just DM me or ping me im always available.

**Comment by Sven65** [comment]
Should be fixed in adventures.

**Comment by Nightmare2112** [comment]
Help ❤️

**Comment by PlayTheFallen** [comment]
[`DEV`] Keep open. (25/07/18)

**Comment by Sven65** [comment]
Right, it wasn't fixed, but I know the issue.

It seems like the issue with donator item xpboost and such not working properly is that they're not adding any %, but rather adds that amount of xp or gold.
Example; 10% xpBoost from items adds 10 xp to the reward instead of 10%

**Comment by Takashi-22812** [comment]
You could use a multiplier, like multiply the whole thing by 1.1 will give you 110% of the original 100, (this wont add onto the first amount since you multiplied the total xp) For example, if you normally get 1000xp and the donator item had 10% xp boost, multiplying it by 1.1 will make it 1100xp total. Alternatively you could do xp + 0.1xp which has the same effect

**Comment by InitialP** [comment]
Here are the combinations and my gains. I have 0 in xpboost and all in Salvaging. Item boost values are as displayed if I type in #!item command for examination of each of them. I am a level 1111.

Ring of Strength + Vampiric Amulet (gold boost 1%)= ~4000 xp.
Ring of Strength + Amulet of Blue Slime (xp boost 30%)= ~4000 xp
Ring of Mischief (Xpboost boost 1.5x) + Vampiric Amulet= ~6000 xp
Ring of Mischief + Amulet of Blue Slime= ~6000 xp

Could these sections have something to do with the amulet or some of amulets being non functional?
![image](https://user-images.githubusercontent.com/29098459/43355987-c399a09e-925f-11e8-8b63-fd23efe7ea83.png)

**Comment by Nightmare2112** [comment]
Yes, ring works. No other items to my knowledge

**Comment by Nightmare2112** [comment]
the reason it has two differnt names is because it’s handled and calculated at differnt times and stored separate. The issue has been identified, maths just have to be worked on by Mackan
