### ISSUE TITLE
Error link 

### ISSUE THREAD

**Issue by CorruptedArrow** [DiscordDungeons/Bugs#634]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
So I was trying out a command to check if I could get the description of Guild Tag, so I did this command: #!gitem guild Tag and it sent me an error link.

**If an error is provided, please copy the block into the space below.**

```js

http://api.discorddungeons.me/v3/egitem/undefined?r=jf7krefl


```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

<img width="1476" alt="screenshot 2018-03-25 18 50 15" src="https://user-images.githubusercontent.com/32755985/37883138-7eed6d9a-305d-11e8-9e33-7e47a6a6cb87.png">

**Comment by CorruptedArrow** [comment]
FYI, I said the command was #!gitem guild Tag but since the prefix was different, I just told you the normal prefix...

**Comment by Sven65** [comment]
Already reported in #618
