### ISSUE TITLE
Traveling to current location gives error of not high enough level

### ISSUE THREAD

**Issue by manicmonky** [DiscordDungeons/Bugs#636]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
I thought I was in Copperfall and was trying to travel to Silverkeep. Upon entering #!travel Silverkeep, I got a message indicating I needed to be level 20 to do that. After a couple tries, thinking I typed wrong, I did a #!location and found out I was already in Silverkeep, so I just traveled further along the path I wanted to with no more errors.

But it seems like the message I should have received for traveling to the same location should have indicated I was already in that location instead of saying I wasn't high enough level.

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![dd_travel_current_location_error](https://user-images.githubusercontent.com/37624238/38169234-46c73816-352a-11e8-9692-a885b27dee24.png)

**Comment by PlayTheFallen** [comment]
Silverkeep is your current location, I assume that it would be referring to Silverkeep Alter.

**Comment by Sven65** [comment]
As fallen said, the `#!travel` command uses a fuzzy search to determine where you want to travel, in this case it matched it to silverkeep altar as it doesn't include the current location in the search.
