### ISSUE TITLE
#!gmglist typo

### ISSUE THREAD

**Issue by InitialP** [DiscordDungeons/Bugs#638]
If you type in #!gmglist command, it lists all item trades that are listed to be sold. If you take a closer look at the list, all of the listed trades have the word "bought" used, which is normally found when using #!gblist command. Normally, it should be "sold", just like it's shown when using #!gminfo command.

![gmglist](https://user-images.githubusercontent.com/29098459/38195018-25592906-3673-11e8-9027-be397b6acf08.PNG)
![gblist](https://user-images.githubusercontent.com/29098459/38195087-9836a7aa-3673-11e8-94d5-307c6bfbe005.PNG)
![gminfo](https://user-images.githubusercontent.com/29098459/38195132-ca439960-3673-11e8-91f9-ea9baa4df61b.PNG)

**Comment by Sven65** [comment]
Interesting, will fix when I get the time
