### ISSUE TITLE
bot won't respond if you change it's nickname

### ISSUE THREAD

**Issue by Rosenkreuz12** [DiscordDungeons/Bugs#64]
as title said, the bot won't respond when mentioned if you changed it's nick

on main server
![](http://i.imgur.com/8fCCpjn.png?1)
on other server 
![](http://i.imgur.com/vbm2Yhsg.png)

**Comment by SnazzyPine25** [comment]
Ah, I see. It's because discord changes the mention format, making the bot not think its a command.

**Comment by Sven65** [comment]
The bug has been fixed.

**Comment by archagy** [comment]
Trying to run 

#!uset nick 1
#!uset nick 1
