### ISSUE TITLE
Guild members 

### ISSUE THREAD

**Issue by ghost** [DiscordDungeons/Bugs#644]
A friend of mine accidentally kicked them self out of their guild and when they try to join back they can't (guild is closed). I left too to see what would happen, it now displays the number of members as -1. Is there a way to fix this? (guild owner used `#!gkick` on their user by mistake)

Guild :   『RPG Terminal』

It just shows like this now ↓ ↓ ↓ 

![image](https://user-images.githubusercontent.com/38238883/38538756-8c8b74ce-3cd8-11e8-899f-b07dc5834958.png)

**Comment by Sven65** [comment]
Reported in #344
