### ISSUE TITLE
Rune capacity upgrades don't seem to work?

### ISSUE THREAD

**Issue by InitialP** [DiscordDungeons/Bugs#645]
The new rune capacity upgrades have come out as some of us already know. I bought the upgrade 2 times. From what I've been told, the default capacity is 25. Correct me if I'm wrong. When I bought the upgrade twice, I noticed the rune upgrade displaying in the #!stats output, which is great. Currently it's at 27, which I understand is the maximum runes I can have (different runes and their quantities stack to that number from what I understand).
Now, the issue here is that when I count my total combined number of runes, it totals to 23. I tried making 4 more to get to that magical 27 and I get the error saying that I'm exceeding the number. I've got the images attached so you can have a look. Thanks in advance.

![rune capacity bug 1](https://user-images.githubusercontent.com/29098459/38692868-0a2bf9bc-3e7d-11e8-88e8-4e35c068a7fc.PNG)
![rune capacity bug 2](https://user-images.githubusercontent.com/29098459/38692878-109e0074-3e7d-11e8-9abd-8e26cf1f956b.PNG)
![rune capacity bug 3](https://user-images.githubusercontent.com/29098459/38692886-19a2a0bc-3e7d-11e8-9552-91f43fc06dd1.PNG)
![rune capacity bug 4](https://user-images.githubusercontent.com/29098459/38692893-216dd794-3e7d-11e8-8933-a0b1ba3ce134.PNG)

**Comment by InitialP** [comment]
I have just tried making 3 runes and it works in this instance, which brings me to 26 total.

**Comment by PlayTheFallen** [comment]
**DEV**
Issue identified as `>=` (Greater than or equal to).
https://github.com/Sven65/RPGBot/blob/master/src/Commands/Commands/User/Craft.js#L158

**Comment by PlayTheFallen** [comment]
**DEV**
PR created Sven65/RPGBot#92

**Comment by Sven65** [comment]
Fixed
