### ISSUE TITLE
Conflicting Item Description (Minor bug)

### ISSUE THREAD

**Issue by Slayer3201** [DiscordDungeons/Bugs#647]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
A simple glitch in the item descriptions of the Adventurer's armor set. Unsure if actual stats are bugged too. I.E. Adventurer's Chestplate says in description that it blocks 5% damage, but in the shown stats, Damage Blocked says 1%.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![](https://i.gyazo.com/d3e2223541dce2a44636b78a287c70e2.png)

![](https://i.gyazo.com/adbafa26a55aadadd14b094f349c1a21.png)

**Comment by ryudragon98** [comment]
the descriptions are not glitched its more of mackan forgetting to update it, both of those items block 1%.
