### ISSUE TITLE
Bought item lost money didn't get item

### ISSUE THREAD

**Issue by Murfurder** [DiscordDungeons/Bugs#649]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
I tried buying a Family Cutlass from the normal market (#!buy) in the starting town. The transaction
cost me the 32K gold but did not give the item. **Edit** I didnt realize the item auto equipped. I do have it. Can I suggest a message that says it auto equips?

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![buyingcutlass](https://user-images.githubusercontent.com/38389439/38774014-4dcd3cac-4022-11e8-97bb-f26391050b52.PNG)
![prebuyinv](https://user-images.githubusercontent.com/38389439/38774017-563408c6-4022-11e8-9863-29f707d569fd.PNG)
![postbuyinv](https://user-images.githubusercontent.com/38389439/38774018-58628320-4022-11e8-9bc0-e7acf92c5853.PNG)

**Comment by FakePeer** [comment]
It’s already equip to you.

**Comment by ryudragon98** [comment]
*they already know*

**Comment by PlayTheFallen** [comment]
*Resolved and Invalid*
