### ISSUE TITLE
Inv bug

### ISSUE THREAD

**Issue by PearMasterYt** [DiscordDungeons/Bugs#650]
![screenshot 2018-04-18 at 10 05 00](https://user-images.githubusercontent.com/37669011/38926479-21c1a182-4303-11e8-9aac-ed0a8a8c9489.png)
When both me and my friend tried to go to our inventory we got this message.

**Comment by PlayTheFallen** [comment]
Requires permissions: Manage Messages and Add Reactions in the channel you are using it in.
https://discordapp.com/developers/tools/permissions-calculator
`reactpaging` was added in [4.2.8](https://forum.discorddungeons.me/viewtopic.php?f=9&t=35)
