### ISSUE TITLE
Can't start Dungeon here at Redhorn

### ISSUE THREAD

**Issue by Fire0x** [DiscordDungeons/Bugs#652]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Says no duegon when i do #!dungeon start at Redhorn

**If an error is provided, please copy the block into the space below.**

```js

There's no dungeon here, Fire0x.

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![image](https://user-images.githubusercontent.com/25399774/39237802-d7f2ddc4-48bf-11e8-9b36-4214d1b6f09e.png)

**Comment by Sven65** [comment]
Your screenshot literally says why, it's at `Redhorn Dungeon.`
