### ISSUE TITLE
Gold bug

### ISSUE THREAD

**Issue by wisnudwii** [DiscordDungeons/Bugs#654]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Gold was reduced by 50%
After selling things i reached 1 mil, the after 1/2 an hour or so my discord crashed then my gold was 518k

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > ) 

![](https://cdn.discordapp.com/attachments/363705322508124172/438672911533080576/unknown.png)

![](https://cdn.discordapp.com/attachments/363705322508124172/438673037617922049/unknown.png)

**Comment by Sven65** [comment]
Did you die between this time?
There was an issue with death messages not showing up, which was fixed.

**Comment by Sven65** [comment]
No response from author, closing the issue
