### ISSUE TITLE
.pheal auto bug

### ISSUE THREAD

**Issue by OPPAI-Kami** [DiscordDungeons/Bugs#655]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**
I couldn’t use .pheal auto... it just said that it was invalid 
**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by PlayTheFallen** [comment]
Do you have a screenshot of both the command run and the response?

**Comment by OPPAI-Kami** [comment]
I found the problem, it was because my pet was full health.

**Comment by InitialP** [comment]
Additional input from me as well. 
![capture](https://user-images.githubusercontent.com/29098459/39280096-4146b752-48f5-11e8-8c73-5484361d7964.PNG)

**Comment by Sven65** [comment]
From my test I just did, it appears to be with healing items of negative healing value

**Comment by Sven65** [comment]
Was fixed long ago
