### ISSUE TITLE
Levelup alerts

### ISSUE THREAD

**Issue by PlayTheFallen** [DiscordDungeons/Bugs#656]
**`THIS IS A REDIRECT POST FROM MY DMS IN DISCORD`**

**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

Level up message doesn't show, also occurs after healing *knightdestin*.
![](https://skype.is-la.me/c146ca.png)

**If an error is provided, please copy the block into the space below.**

N/A

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

*From Silencer2101 in DMs 25/04/18 19:55 GMT London (BST)*
1. The mob before i should have leveled up.
2. The next mob that was attacked.
3.the following that i probably should have leveled up on.
4. The last mob i attacked before check stats because i didnt get the notification.
5. the being 400~ XP above the level threshhold.
![](https://cdn.discordapp.com/attachments/438400907420499968/438774796512133120/Screenshots.jpg)

*Issue reported by Silencer2101#5359 (216740508310044672) in DMs.
Also reported by Knightdestin#6666 (153870043590033408) in tavern.*

If another user has also experienced this, please attach screenshots of **both** the command(s) run and the message(s) returned.

**Comment by InitialP** [comment]
Here is some more 
![capture](https://user-images.githubusercontent.com/29098459/39280140-7ab4c592-48f5-11e8-9ece-f8d8170803ac.PNG)

**Comment by shroomyun** [comment]
Is also happening to me recently... there was a level up because max health of my pet and mine changed 
![_20180426_091434](https://user-images.githubusercontent.com/33994869/39280271-f591383c-4930-11e8-9c5a-dbd6b4a94e68.JPG)
![_20180426_091418](https://user-images.githubusercontent.com/33994869/39280277-fd77fee6-4930-11e8-8a4b-e7cda4e367a9.JPG)

**Comment by Sven65** [comment]
Issue is that the levelup message doesn't show
