### ISSUE TITLE
(Dungeon) Stairs

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#658]
Whilst you enter upon stairs it (sometimes) spawns with a chest / mob encounter message but does nothing if you respond with a checkmark/move but with moving it just moves position whilst if it were with a mob it should do the run messages, seems like it's making a void finding of a chest / mob.

**Comment by Sven65** [comment]
Clarification;

When descending a dungeon, there's sometimes a chance of the status message having a false message about the tile you're on.
