### ISSUE TITLE
Travel bug

### ISSUE THREAD

**Issue by tyler489** [DiscordDungeons/Bugs#659]
**Please describe your issue below.**  
When traveling from a location that allows #!adv to a location that doesnt (silverfall alter) doing #!adv will allow you to adventure once in that location

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  

![](https://i.gyazo.com/db13774ba7b322d67075dd0a66197367.png)

**Comment by PlayTheFallen** [comment]
This issue would occur at any location that had adventures, sides, market disabled or if a user's previous location had any of these disabled.

**Comment by PlayTheFallen** [comment]
the cooldown bit is hard coded into the message handler, even if we were to try and reverse it's affect it would be too early to do such *unless of course the whole bot is rewritten to improve performance, which i do not see happening any time soon* :/

**Comment by tyler489** [comment]
I feel like you could add a did fail flag of some kind assigned to a simple check  of the msg handler. If it failed then set the cool down to 0. But i dont know if thats possible or not. Just a theory

**Comment by lifeofchrome** [comment]
^ I'm sorry I was trying to play around with GitHub issues and used this as a test and messed up twice in a row. Disregard.

**Comment by lifeofchrome** [comment]
And I just clicked the wrong button. _facepalm_
