### ISSUE TITLE
Can't craft exact amount of runes that I can hold. It is restricted to 1 minus to the max amount. 

### ISSUE THREAD

**Issue by sap-spectre** [DiscordDungeons/Bugs#660]
I got capacity to hold 48 runes but I can't hold the exact number. 
Seems mine is restricted to max of 47 runes and it does says I got 48 capacity.

screenshot:
https://i.imgur.com/Dsoqqp8.jpg
 
Silverkeep rune = 43
Sariila rune = 4  (there in screenshot and no other runes)

**Comment by Sven65** [comment]
Already reported in #645
