### ISSUE TITLE
Selling fish bug

### ISSUE THREAD

**Issue by tyler489** [DiscordDungeons/Bugs#668]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
selling freshwater fish or tropical fish without using there full name gives 0 coins

**If an error is provided, please copy the block into the space below.**

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  

https://gyazo.com/1b029e2ddd5d0cecae52cbd42bfe4a0e
https://gyazo.com/abb3731212b18394ef0ac4eae78b2a12
​

**Comment by Sven65** [comment]
Fixed
