### ISSUE TITLE
Inv bug

### ISSUE THREAD

**Issue by Rosenkreuz12** [DiscordDungeons/Bugs#67]
when you try to do #!inv followed by number that is over your max page it'll throw you an error 
![](http://i.imgur.com/CyILIyM.png?1)
but it weirdly doesn't happen to me so it probably only affect those with lower than 8 pages ? not sure
![](http://i.imgur.com/N2eWBw2.png?1)

**Comment by Sven65** [comment]
Issue has been resolved.
