### ISSUE TITLE
Dungeons not generating 

### ISSUE THREAD

**Issue by lightningAsura** [DiscordDungeons/Bugs#671]
I keep trying to start a dungeon but it consumes the entrance fee without generating an actual dungeon even after waiting 3+ mins 

![](https://i.imgur.com/QYkUZ05.png)

**Comment by tyler489** [comment]
Happened to me to.. was able to use the dungeon i had yesterday but when i tried to gen one it took my 35k and didnt give me one

**Comment by Sven65** [comment]
Should be fixed
