### ISSUE TITLE
bug when crafting items with # values in name

### ISSUE THREAD

**Issue by tyler489** [DiscordDungeons/Bugs#673]
**Please describe your issue below.**  
i attempted to craft 29 "dummy item 2" for a quest using the command #!craft dummy item 2 29 and it only crafted 2 dummy item 2. im guessing this is because the bot assumes that the "2" is a quanity AND an item name? attempting to #!craft dummy item 2 1 still craft 2 
running #!craft dummy item 2 attempts to craft 2 of the Dummy item 1... there has to be a second numeric variable behind but it is ignored by the bot

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
To fix; Make the bot check if the full string is an item

**Comment by Willard21** [comment]
Well if there's items called `dummy item` and `dummy item 2`, then the syntax for crafting 2 of the first one or 1 of the second one would be exactly the same: `#!craft dummy item 2`. That's not something that can be fixed, so the items just need to be renamed. Specifying the number of `dummy item 2`s to craft can be fixed, but specifying the number would be *required* for it to work, which is bad design, so again, the items just need new names.
