### ISSUE TITLE
DM timeout doesn’t happen

### ISSUE THREAD

**Issue by duaner02** [DiscordDungeons/Bugs#675]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

In DM the bot doesn’t remove the reaction options after the time limit.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  

*You may use github's standard way of presenting images, or use an image uploader (like imgur)*
![ea74d169-3aae-4347-b341-f62141153fdc](https://user-images.githubusercontent.com/20850617/40072043-22032f2c-5838-11e8-9b63-f9398cac8337.jpeg)

**Comment by duaner02** [comment]
Also happens when I click the ❌

**Comment by PlayTheFallen** [comment]
Bot can't remove reactions in DMs.
