### ISSUE TITLE
#!location info repeating 

### ISSUE THREAD

**Issue by doge-pepe-twat68** [DiscordDungeons/Bugs#676]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
arrived at tower of infinity and did #!location
theres 5 buckleports in the location box

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![buckleport](https://user-images.githubusercontent.com/26106799/40090052-b6a09d62-58f2-11e8-9371-5eece514d486.png)

**Comment by ryudragon98** [comment]
this is known, mackan has said he cant reproduce it yet others can.

**Comment by Sven65** [comment]
Already reported in #604
