### ISSUE TITLE
Uset display can't be changed.

### ISSUE THREAD

**Issue by Melrim** [DiscordDungeons/Bugs#677]
Tried using the command "#!uset display 2" in various servers. Although the bot feedback is always "Display set to 2", there is no change and adventure display is stuck at display 1. Also tried to DM Discord rpg bot directly but same results. I'm not sure if anyone is experiencing the same issue or it's just me. Using laptop and smartphone, similar results.

**Comment by Sven65** [comment]
This might be due to the bot lacking permissions to embed links as it can't send embeds if it doesn't have that permission.
