### ISSUE TITLE
Purchasing Items at the market but not getting the items

### ISSUE THREAD

**Issue by Bravils-Best** [DiscordDungeons/Bugs#68]
Early today I bought 8 string at 75 gold each, 1 plank for 75 gold, and then 100 string at 1 gold each.
However I did not get any of the items I had paid for so I am wondering if its a bug or I missed a step somewhere in the game its self I needed the string and the plank to make the butterfly net and now I'm low on gold.
Please resolve this issue to your earliest convenience or make a way to receive missing items please I would greatly appreciate it cheers and have a good one

**Comment by Rosenkreuz12** [comment]
do provide pictures to proof that you indeed bought the items at said prices.
