### ISSUE TITLE
Leather Belt buying bug

### ISSUE THREAD

**Issue by L0S7-L3910N** [DiscordDungeons/Bugs#680]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
I've bought a leather belt, but it's not shown at inventory (#!inv).... and now.... many bot commands aren't working

**If an error is provided, please copy the block into the space below.**

```js

<Lost Legion - Today at 8:30 AM
#!stats
DiscordRPGBOT - Today at 8:30 AM
!======== [Lost Legion's Stats] ========!
+ Health: 117/300HP.
+ Inventory is in #!inv
+ Weapon: Iron Flail
+ Ring: None | Helmet: None
+ Chestplate: None | Boots: None
+ Necklace: None
+ Fishing Rod: Fishing Rod | Pickaxe: Pickaxe
+ Axe: Axe
+ Level 6 | (883/1,050 XP)
+ 3,105 Gold
+ Slain 0 times. Killed 55 enemies and 0 players.
+ Quest Points: 0
+ Unassigned: 0 points.
!=======================================!
Lost Legion - Today at 8:30 AM
#!items
DiscordRPGBOT - Today at 8:30 AM
!=====[ Items (Page 1/42) ]=====!
+ Health Potion - 5 Gold {Lvl. 1}
+ Greater Health Potion - 10 Gold {Lvl. 5}
+ Grapes - 15 Gold {Lvl. 5}
- Mushroom - 30 Gold {Lvl. 8}
+ Healing Nectar - 40 Gold {Lvl. 3}
+ Cherry - 40 Gold {Lvl. 6}
- Even Greater Health Potion - 50 Gold {Lvl. 8}
+ Carrot - 60 Gold {Lvl. 5}
- Apple - 80 Gold {Lvl. 10}
- Banana - 90 Gold {Lvl. 10}
+ Iron Sword - 100 Gold {Lvl. 2}
+ Wheat - 100 Gold {Lvl. 5}
- Enhancing Stone - 100 Gold {Lvl. 10}
+ Freshwater Fish - 200 Gold {Lvl. 4}
+ Milk - 200 Gold {Lvl. 1}
!===============================!
Lost Legion - Today at 8:30 AM
#!items 2
DiscordRPGBOT - Today at 8:30 AM
!=====[ Items (Page 2/42) ]=====!
+ Snail - 200 Gold {Lvl. 4}
+ Tropical Fish - 250 Gold {Lvl. 4}
+ Blowfish - 250 Gold {Lvl. 4}
+ Crab - 270 Gold {Lvl. 4}
+ Turtle - 320 Gold {Lvl. 4}
+ Octopus - 400 Gold {Lvl. 4}
+ Iron Mace - 500 Gold {Lvl. 3}
+ Fishing Rod - 500 Gold {Lvl. 5}
+ Iron Flail - 750 Gold {Lvl. 4}
+ Red Visor - 995 Gold {Lvl. 1}
+ Red Karate Belt - 1,000 Gold {Lvl. 2}
+ Pickaxe - 1,500 Gold {Lvl. 1}
+ Axe - 1,500 Gold {Lvl. 1}
+ Leather Belt - 1,995 Gold {Lvl. 2}
- Iron Battleaxe - 2,500 Gold {Lvl. 7}
!===============================!
Lost Legion - Today at 8:31 AM
#!adv 2
DiscordRPGBOT - Today at 8:31 AM
!========[ Lost Legion's Adventure ]========!
% Rolled a 4
- Lost 8 HP.
+ Dealt 11 HP Damage
- Pet Rock took 4 HP Damage.
- Pet Rock has 0/50 HP left
+ Lost Legion has 109/300 HP left.
+ The enemy Lurght has 86/185 HP left.
!============================================!

Type #!adventure 1 to run, or #!adventure 2 to continue.
Lost Legion - Today at 8:32 AM
#!buy leather belt 1
DiscordRPGBOT - Today at 8:32 AM
Lost Legion bought a Leather Belt for 1,995 gold.
Lost Legion - Today at 8:32 AM
#!use leather belt
DiscordRPGBOT - Today at 8:32 AM
Lost Legion tried to use a Leather Belt, but has none
Lost Legion - Today at 8:32 AM
#!inv
DiscordRPGBOT - Today at 8:32 AM
!===== [Lost Legion's Inventory (Page 1/1)] =====!
+ 1,110 Gold.
+ 1 x Health Potion
+ 1 x Small Dagger
+ 10 x Rocks
+ 1 x Glass
+ 42 x Logs
+ 12 x Rock Salt
+ 1 x Plank
+ 108 x Lemons
!================================================!
Lost Legion - Today at 8:32 AM
aaaaa
#!bug
DiscordRPGBOT - Today at 8:32 AM
To report a bug, please go to https://github.com/DiscordDungeons/Bugs/issues, thanks.
Lost Legion - Today at 8:35 AM
#!sell leather belt
DiscordRPGBOT - Today at 8:35 AM
Lost Legion tried to sell an item they don't have.
Lost Legion - Today at 8:35 AM
#!sell Leather Belt 1
DiscordRPGBOT - Today at 8:36 AM
Recovering Lost Legion's stamina in 2 seconds.
Lost Legion - Today at 8:45 AM
#!fish
#!mine
#!forage
#!adv 2
Papa Xav - Jak's Husbando - Today at 9:02 AM
!rank
MEE6BOT - Today at 9:02 AM

Xav (三十三才さん)
Rank
16/3267
Lvl.
39
Exp.
7049/9655 (tot. 143094)
CFMisaki - Today at 9:12 AM
#!adv
#!adv
Ooo damn
Lost Legion - Today at 10:08 AM
#!inv
BUUUUUUG
#!HELP
#!bug>

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )
![1](https://user-images.githubusercontent.com/39607819/40524616-a9d82568-6005-11e8-84c5-75a0666c56d4.PNG)
![2](https://user-images.githubusercontent.com/39607819/40524617-aa19dada-6005-11e8-9d19-63652ccca56e.PNG)
![3](https://user-images.githubusercontent.com/39607819/40524618-aa67387a-6005-11e8-94bb-9e776d48d93f.PNG)
![4](https://user-images.githubusercontent.com/39607819/40524619-aaba776a-6005-11e8-9564-9514d4edcd6b.PNG)
![5](https://user-images.githubusercontent.com/39607819/40524621-ab070b34-6005-11e8-8942-abb127456cb6.PNG)
![6](https://user-images.githubusercontent.com/39607819/40524622-ab43710a-6005-11e8-8ac0-1b4a119b8820.PNG)
![7](https://user-images.githubusercontent.com/39607819/40524623-ab8b185c-6005-11e8-9195-e78fe91e6472.PNG)
![8](https://user-images.githubusercontent.com/39607819/40524624-abdc8ca0-6005-11e8-8137-13e240adea6a.PNG)
![9](https://user-images.githubusercontent.com/39607819/40524625-ac1c86f2-6005-11e8-80e5-225e3c4e0910.PNG)
![10](https://user-images.githubusercontent.com/39607819/40524627-ac6032a8-6005-11e8-9bb7-dbfa5ec290cf.PNG)
![11](https://user-images.githubusercontent.com/39607819/40524628-ad014f08-6005-11e8-811f-be3f091072fe.png)

**Comment by ryudragon98** [comment]
when you do #!buy leather belt or any other armor/weapon it will automatically equip. as for the bot not responding its probably a shard down in which mackan would need to restart the bot.

**Comment by Sven65** [comment]
When buying equipment, it gets automatically equipped, if you check `#!stats`, it should say it's equipped.

The issues with the bot not responding is as  @ryudragon98 said, most likely due to the shard being down.
