### ISSUE TITLE
Dungeon not resuming 

### ISSUE THREAD

**Issue by SavvyPrawn** [DiscordDungeons/Bugs#684]
I have DiscordRPG bot in another server, and sometimes it's really slow. Usually when it's slow I leave it be, then resume it, but recently it doesn't let me resume for a little while. It says something about an error and to report it... So that's what I'm doing. It doesn't allow me to resume my dungeon for a little, and I have to try a few times before it resumes.

**Comment by CritX** [comment]
Is it this one?
![6adabcc6-44d8-4e9b-b6bf-eb6dcf5dc0c5](https://user-images.githubusercontent.com/16049993/40792330-4f570b54-64bf-11e8-8622-c9613ba09c24.png)

**Comment by Sven65** [comment]
Reported in #662
