### ISSUE TITLE
Dungeon bug

### ISSUE THREAD

**Issue by Xeno8917** [DiscordDungeons/Bugs#685]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Me and a friend went into a party before entering a dungeon and we each entered the dungeon on our own. Since we are both in the dungeon and in a party, we can't #!adv to continue because we are in a party, and we can't leave the party because it says we are in a dungeon. So we are stuck in the dungeon unable to do anything.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![](https://cdn.discordapp.com/attachments/244367260062318592/453578317585711114/unknown.png)

**Comment by Sven65** [comment]
Not an issue, contact the support team in the official server at https://discord.discorddungeons.me
