### ISSUE TITLE
Dungeons Error

### ISSUE THREAD

**Issue by SoraXO** [DiscordDungeons/Bugs#686]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
When I try to start a dungeon, it says that I cannot start a dungeon while i'm in a party, even though i'm not in a party. This issue occurs regardless of which server I enter the command in.

**If an error is provided, please copy the block into the space below.**

```js

< error here >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < 
<img width="438" alt="screen shot 2018-06-07 at 2 14 23 pm" src="https://user-images.githubusercontent.com/40028513/41098899-29f19516-6a5d-11e8-923c-cb6a3ee525ef.png">
 > )

**Comment by Sven65** [comment]
Is this still an issue? If so, please re-open it.

**Comment by Willard21** [comment]
![image](https://user-images.githubusercontent.com/24826881/48297232-0caa8180-e469-11e8-91dc-846fa1d569a7.png)
