### ISSUE TITLE
Crafting output quantities not honored

### ISSUE THREAD

**Issue by somefriggnidiot** [DiscordDungeons/Bugs#687]
**What is happening?**  
`craft plank 10` results in 10 logs being used to create 40 planks, but `craft iron ingot 10` uses 20 iron ores to craft 10 iron ingots. Generically, `craft plank A` uses A materials to create X product, while `craft iron ingot B` uses Y materials to create B products.

**What is expected to happen?**
`craft plank X` should result in X planks being created (or >X, since you get multiple products per material used.)

**Comment by PlayTheFallen** [comment]
I think it's created to make `X` lots of {item}.

From the look of things, Planks#91 are created in sets of **4**.
Meaning that if you specify `X` as 10, then it would create 10 \* 4 = 40.

*Mathematical sums / equations / calculations have been displayed in full to help understand the answer when reading.*

**Comment by ManniXxx** [comment]
I'm Currently in a party with my pet xp rate 100 and then i do a adventure as a party then the xp goes to me instead of the pet. 
![bug](https://user-images.githubusercontent.com/40247156/41372384-04bf92d8-6f45-11e8-99c9-cf02e34d406f.PNG)
