### ISSUE TITLE
Party Issues

### ISSUE THREAD

**Issue by ManniXxx** [DiscordDungeons/Bugs#688]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
So I was in a party And i wanted to make my pet to have all the exp i received Then I get the exp instead of my pet receiving it.

**If an error is provided, please copy the block into the space below.**

```js

< >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![bug](https://user-images.githubusercontent.com/40247156/41372681-e923ea1e-6f45-11e8-9840-e943c7a4598f.PNG)

**Comment by Willard21** [comment]
Does this issue still exist? I've never seen it actually _display_ the wrong pet xp in parties.
