### ISSUE TITLE
Stuck in Dungeon with Party

### ISSUE THREAD

**Issue by UncleRicky** [DiscordDungeons/Bugs#691]
I have had an issue where my friend and I went into a dungeon as a party and encountered mobs. However, we could not attack them because we were in a party. Whenever i tried to do `#!adv` or `#!padv`, the bot would reply `You can't do this while in a party, Uncle Ricky.` If somebody could force a teleport, force exit, or something else that would help me disband my party, that would be great. Heres a screenshot:

![dungeon issue](https://user-images.githubusercontent.com/40417752/41638510-b7fc760e-7427-11e8-92e4-2b5b7a6800a4.png)

**Comment by PlayTheFallen** [comment]
Are you able to `dungeon resume` and then use the leave emoji?

**Comment by UncleRicky** [comment]
i tried but nothing happened. I tried multiple emojis and im no sure if they were the one to leave, but heres a pic.
![screenshot 2018-06-22 at 4 00 17 pm](https://user-images.githubusercontent.com/40417752/41796704-8c102a26-7635-11e8-8c9f-69c10fc5f2b0.png)
(by the way that was my old username)

**Comment by Sven65** [comment]
Doesn't look like an issue since stairs can be found to leave the dungeon.
