### ISSUE TITLE
Can't kick from my parties.

### ISSUE THREAD

**Issue by SavvyPrawn** [DiscordDungeons/Bugs#697]
I was playing in a party with some friends, one of them left for a while, and since I didn't want to disband the party, I tried kicking them, but a error came up and said to report the problem. When I tried kicking my friend, the bot said:

Whoops. An error occured. Please report this in the official server.

TypeError: this._endTurn(...).catch is not a function
    at Party._kick (/home/mackan/RPGBot/src/Commands/Commands/Parties/Party.js:392:62)
    at <anonymous>

**Comment by Sven65** [comment]
If this is still an issue, please open a new one.
