### ISSUE TITLE
Trapped in Dungeon

### ISSUE THREAD

**Issue by BugDoctor1** [DiscordDungeons/Bugs#698]
**Describe the bug**
When I caught a Soix in Redhorn Dungeon, the dungeon map did not display again. Though catching the monster did result in the battle ending, the dungeon map did not reappear. When I tried fighting the mob I just caught, the message "There's no mobs here, BugDoctor1." appeared. I cannot exit the dungeon, or move in it. I am trapped.

**To Reproduce**
1. Encounter a monster. Fight it.
2. Use the command #!catch.
3. Continue using the command in Step 2 until you successfully catch it.
4. Become trapped in the dungeon.

**Expected behavior**
I expected the battle to end, the dungeon map to appear, and then go on my merry way to loot chests and explore the rest of the dungeon.

**Screenshots**
![rpg-4 - discord 6_30_2018 3_09_49 pm](https://user-images.githubusercontent.com/40723067/42128365-ba09d402-7c77-11e8-8b55-f00d8f51dc43.png)
![rpg-4 - discord 6_30_2018 3_10_51 pm](https://user-images.githubusercontent.com/40723067/42128370-cf0f963e-7c77-11e8-936c-5e166e4bf11f.png)
![rpg-4 - discord 6_30_2018 3_11_24 pm](https://user-images.githubusercontent.com/40723067/42128374-e291ae04-7c77-11e8-8f90-c1fa45c58aef.png)
![rpg-4 - discord 6_30_2018 3_12_29 pm](https://user-images.githubusercontent.com/40723067/42128382-07540c8c-7c78-11e8-8378-3a8f43fd4854.png)
![rpg-4 - discord 6_30_2018 3_13_19 pm](https://user-images.githubusercontent.com/40723067/42128386-25416118-7c78-11e8-8771-9f1fbe3de0b2.png)

**Version**
4.3.8

**Additional context**

**Comment by Sven65** [comment]
Use `#!dungeon resume` to resume the dungeon.

**Comment by Sven65** [comment]
Was fixed, but issue not closed.
