### ISSUE TITLE
/stats would not work if used on self

### ISSUE THREAD

**Issue by jch02140** [DiscordDungeons/Bugs#70]
When you use /stats on yourself, it returns an error:

> Whoops. An error occured. Please report this in the official server.
> ``TypeError: Cannot read property 'id' of undefined at TextChannel.permissionsFor (/root/RPGBot/node_modules/discord.js/src/structures/GuildChannel.js:60:25) at Data.user.get.then (/root/RPGBot/cmds/user.js:565:30)``

However, it works if you use it to check other users' stats.

**Comment by Sven65** [comment]
Do you mean mentioning yourself or just the raw command?

**Comment by jch02140** [comment]
Just when you type /stats without any parameters

**Comment by Sven65** [comment]
Right. Is it in a private message?

**Comment by jch02140** [comment]
Do you mean private room? It is in a public text channel of another private room if that is what you meant...

**Comment by Sven65** [comment]
I meant a private message with the bot.
Seeing as it's not, that helps me locate the issue in the code.

**Comment by jch02140** [comment]
I have just found another bug with /item command. It gives the following error with any valid item names.

> TypeError: Cannot read property 'id' of undefined
>    at TextChannel.permissionsFor (/root/RPGBot/node_modules/discord.js/src/structures/GuildChannel.js:60:25)
>    at Object.keys.map (/root/RPGBot/cmds/general.js:264:63)
>    at Array.map (native)
>    at Data.item.getAll.then (/root/RPGBot/cmds/general.js:259:21)

**Comment by Sven65** [comment]
It's an issue with the bots permissions in the channel.

**Comment by Sven65** [comment]
Would you mind passing me an invite to your server through DMs at Mackan#7196?

**Comment by jch02140** [comment]
I can't seem to figure out where to send DM... >_<

It isn't my own server though but it is a public server... I think I might be able to ask the server admin to fix the permission...

> discord.gg/qQdBDWf 

It is in the #rpg channel

**Comment by Sven65** [comment]
Right. Give me a couple of minutes to get the verification level done.

**Comment by Sven65** [comment]
Couldn't get information on bot's permission.
