### ISSUE TITLE
Adventure time bug which pings the user before u can do #!adv

### ISSUE THREAD

**Issue by Crysenfire** [DiscordDungeons/Bugs#702]
![screenshot 157](https://user-images.githubusercontent.com/41297636/42764287-d23edf40-8947-11e8-82f4-ebf7d5409034.png)

**Comment by ryudragon98** [comment]
if you have issues with a bot other than DiscordRPG then go to its support server. since this is not a bug regarding the DiscordRPG bot

**Comment by Sven65** [comment]
Not related to the DRPG Bot.
