### ISSUE TITLE
reaping seed from field while traveling

### ISSUE THREAD

**Issue by epikhi** [DiscordDungeons/Bugs#703]
Hi so I had my seeds reaped from Silverkeep instead of Copperfall while I was in Copperfall.
I expected that when I had done ",plant check" that it would reap the seeds from Copperfall since I have been in Copperfall for several minutes (I had done ",travel copperfall" from silverkeep and left the computer for several minutes and then came back and immediately did ",plant check" and seeds got reaped from silverkeep instead of copperfall)

1. (from silverkeep) ,travel copperfall
**Discordbot**: βrandon has started their journey to Copperfall!
2. &plant (aldebaran bot to check plant status)
3. ,check plant
**Discordbot**: βrandon has arrived to Copperfall! 
βrandon checked the Wheat Seed they planted 11 days ago.
There was 3 Wheat leftover.
You already have a sapling planted here, βrandon.
4. &plant (aldebaran bot to check plant status)
5. ,location
**Discordbot**: Copperfall
6. &plant (aldebaran bot to check plant status)
7. ,check plant
**Discordbot**: βrandon checked the Apple Seed they planted 4 days ago.
There was 2 Apples leftover.

![screen shot 2018-07-16 at 1 19 14 pm](https://user-images.githubusercontent.com/41307239/42782178-fab985d8-88fc-11e8-9a17-13de5048a8db.png)
![screen shot 2018-07-16 at 1 19 35 pm](https://user-images.githubusercontent.com/41307239/42782179-fad77fc0-88fc-11e8-952c-4bc591c42a04.png)
![screen shot 2018-07-16 at 1 19 49 pm](https://user-images.githubusercontent.com/41307239/42782181-faf898c2-88fc-11e8-9785-04d53da1c365.png)
![screen shot 2018-07-16 at 1 20 07 pm](https://user-images.githubusercontent.com/41307239/42782182-fb113dd2-88fc-11e8-98fa-69c2bfde4093.png)
![screen shot 2018-07-16 at 1 20 17 pm](https://user-images.githubusercontent.com/41307239/42782183-fb2b04e2-88fc-11e8-89dd-41c367df7b5f.png)

**Comment by doolphoo** [comment]
Whenever you travel to a location, you have to type `#!location` or else whatever command you type will still register you in the old location.

One example of this is in altars. If you travel to an altar and type `#!mine`, you can get other materials but you won't get any Essence.
