### ISSUE TITLE
Sgitem Guild Sign broken

### ISSUE THREAD

**Issue by Nykrole** [DiscordDungeons/Bugs#707]
**Describe the bug**
Assuming the Sgitem command will pull up the relevant wiki regarding the item's description, the command is broken for the Guild Sign item, returning a bad link.

**To Reproduce**
1. Type "Sgitem guild sign"
2. Broken link is sent through chat rather than item description (link in question: http://api.discorddungeons.me/v3/egitem/undefined?r=jjwknsn1)

**Expected behavior**
It should return an item description of some kind.

**Screenshots**
![untitled_li](https://user-images.githubusercontent.com/41535423/43043744-9d5bf014-8d4e-11e8-86dd-172f10c553ed.png)

**Version**
i dont know

**Additional context**
no

**Comment by Sven65** [comment]
Already reported in #628
