### ISSUE TITLE
#!stats command still not working for new player

### ISSUE THREAD

**Issue by pizzalorddex** [DiscordDungeons/Bugs#711]
**Describe the bug**
Cannot use the stats command to generate player info to play the game.

**To Reproduce**
Just type "#!stats" using my discord account.

**Expected behavior**
To receive my stats page/message

**Screenshots**
<img width="668" alt="screenshot 2018-07-31 at 09 10 53" src="https://user-images.githubusercontent.com/37597645/43443779-28cfcb98-94a2-11e8-907b-3dcf715db66c.png">

**Version**
Discord: 0.0.251
MacOS: 10.14 (18A336e) (problem was present before this OS version)

**Additional context**
First submitted this bug in March, however, the fix doesn't seem to have worked.

**Comment by FelixArgyle** [comment]
@pizzalorddex Use #!rpoints and your problem should be fixed.

**Comment by pizzalorddex** [comment]
I've tried #!rpoints. When I do this it returns the message "You already have the new attributes, PizzaLordDex", however, when I then try to use the #!stats command again it still gives me the same error.

**Comment by Nightmare2112** [comment]
Your current user data looks very strange, as if it failed originally when creating it. I would suggest using
#!reset yes.

**Comment by pizzalorddex** [comment]
Thanks, Nightmare this worked! After such a long time waiting I can finally use this just as all my free time is gone again HAHAHAHA! But really, glad to have some direction other than "it's fixed", thanks again!!
