### ISSUE TITLE
Guildad

### ISSUE THREAD

**Issue by Sirfirelord69** [DiscordDungeons/Bugs#712]
![rwee](https://user-images.githubusercontent.com/42024016/43566342-ac4360a6-9660-11e8-8838-2e52dcde193e.png)
The guildad takes your money and doesn't put up an ad. This issue has happened to other guilds too, notably La famillia

**Comment by PlayTheFallen** [comment]
Known, but reason is not.

**Comment by Sven65** [comment]
The reason is known, it tries to delete the old guild ad by the message ID that is stored in the database, but it fails to find it.
