### ISSUE TITLE
Missing access

### ISSUE THREAD

**Issue by Drago2014** [DiscordDungeons/Bugs#715]
![screenshot_2018-08-03-18-21-54-325_com  #discord](https://user-images.githubusercontent.com/42067807/43645013-44e0b8ac-974e-11e8-80d8-1f6fa9f806c3.png)

**Comment by ryudragon98** [comment]
give bot read message history, manage message, and add reaction perms.

**Comment by Drago2014** [comment]
idk how to do that??

**Comment by RainTheVappy** [comment]
Server settings,role, Discord Dungeons and check all the permissions mentioned above
