### ISSUE TITLE
Rune is getting used if it used from same place!!

### ISSUE THREAD

**Issue by sap-spectre** [DiscordDungeons/Bugs#717]
When I used a silverkeep rune from place silverkeep itself the rune got used. 
(and I lost a rune). 
Could be good if it tell something else and not use the rune in those cases.

[ If it doesn't seem to be bug, take it as a suggestion ]

**Comment by RainTheVappy** [comment]
It's not a bug lmao

**Comment by PlayTheFallen** [comment]
**NOTE:** The game doesn't take into account where your current location is (if you *teleport* from one location to another). Either way, the rune would be expended and deemed ineffective the next time you try to use it.
