### ISSUE TITLE
Felix's Trap Ring#668 (Salvaging ring is broken)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#722]
**Describe the bug**
My ring does not do what it is intended to do, it's meant to boost salvaging by 1.5x

**To Reproduce**
I check my Felix's Trap and it outputs the same item quantities as I get without the ring.

**Expected behavior**
I expect to get more items, 1.5x more

**Version**
 4.3.15 

**Additional context**
Fix my ring, please 😢

**Comment by Nightmare2112** [comment]
That's cuz items aren't rewarded on a 1 :1 ratio with salvaging points, so you are only boosting your "salvaging points" by 1.5 not the actual reward. If you were a higher lvl you would notice a greater boost, however at your lvl even with max Salvaging, it will have little effect as it currently is :sob:
