### ISSUE TITLE
Error on #!gban add 

### ISSUE THREAD

**Issue by DeMiDeWa** [DiscordDungeons/Bugs#723]
**Describe the bug**
Adding people into the guild blacklist results in an error. Both by ID and mention

**Screenshots**
https://puu.sh/Bo5Fj/7a401f92b0.png
https://puu.sh/Bo5IQ/3dccbe6480.png

**Version**
4.3.16

**Comment by DeMiDeWa** [comment]
Please fix these bugs too.

The bot add a new list as long as the data entered contains numbers. It should check whether the data entered is a user ID or not.

Also, there will be an error if the user enters data without a number at all.

**The bot added new list without verifying it**
https://puu.sh/BoREi/9f661f8aa9.png
https://puu.sh/BoRGt/c872a45959.png

**Error when adding new list that doesn't contain numbers**
https://puu.sh/BoRFt/de8066ee9c.png

_Well, I haven't tried all the possibilities that might produce errors._

**Comment by Sven65** [comment]
Please post each of them as a new issue as this one is already closed, thanks.
