### ISSUE TITLE
Armors with Boosts

### ISSUE THREAD

**Issue by KCCAsiPri** [DiscordDungeons/Bugs#726]
Issue: 
I have three XP boosting pieces of armor amd one necklace, but the XP boost doesn't work. In total it should add up to 11% increase (I am level 225, but I should be getting exp as someone who is level 247). Yet I still get the same amount of xp (from the Aldebaran bot)

Reproduction:
No current way but to check out my grinding

**Comment by RainTheVappy** [comment]
This is NOT Aldebaran support server or report bugs page

**Comment by KCCAsiPri** [comment]
The difference in xp is about 300.

**Comment by ryudragon98** [comment]
this github is not for aldebaran if you have questions/issues that involve aldebaran then take it to aldebarans support server.

**Comment by KCCAsiPri** [comment]
Oh my gosh I'm literally saying that Aldebaran is only proof... 
THE MAIN POINT IS 
THAT I don't get the PROJECTED AMOUNT OF XP (of a level 247) BECAUSE THAT'S THE ESTIMATE OF WHAT I'm SUPPOSED TO GET

**Comment by KCCAsiPri** [comment]
It has almost nothing to do with Aldebaran, it is entirely of the xp boost stats on the armors. In other words, they're broken.

**Comment by PlayTheFallen** [comment]
Duplicate of #632 
and... Aldebaran has nothing to do with us, it has absolutely no physical interaction with any of the game.
