### ISSUE TITLE
Random comma at end of "Cludlavese" enemy

### ISSUE THREAD

**Issue by numbermaniac** [DiscordDungeons/Bugs#728]
This enemy appears to have a comma at the end of its name. Throughout the whole fight, this enemy's name included a comma at the end, which I have not seen on any other enemy.

**Screenshots**
![screen shot 2018-09-09 at 4 47 58 pm](https://user-images.githubusercontent.com/5206120/45261995-8960b580-b450-11e8-8dd0-b0092600f96c.png)
![screen shot 2018-09-09 at 4 52 19 pm](https://user-images.githubusercontent.com/5206120/45262003-c036cb80-b450-11e8-8dce-e0ab005a6a5e.png)

**Version**
4.3.17

**Comment by RainTheVappy** [comment]
typo on dynamob names?

**Comment by numbermaniac** [comment]
I'm not sure what you mean by dynamob, but yeah this appears to be a typo in the enemy's name.

**Comment by Willard21** [comment]
I caught one of those once. `tried to catch a Cludlavese,, but failed.`

**Comment by RainTheVappy** [comment]
It's an existing mob and have been reported before
