### ISSUE TITLE
!ginvite gives TypeError.

### ISSUE THREAD

**Issue by inoxety** [DiscordDungeons/Bugs#734]
**Describe the bug**
When attempting to invite someone to my guild, an error messages is given. 

**To Reproduce**
To reproduce, simply invite someone to a guild.

**Expected behavior**
It was meant to invite someone.

**Screenshots**
http://prntscr.com/kvf6pc

**Version**
4.3.17

**Comment by Sven65** [comment]
Same issue as #725
