### ISSUE TITLE
Party Kick error

### ISSUE THREAD

**Issue by LastApril** [DiscordDungeons/Bugs#735]
I can't kick someone in party and have to disband and then re-create it
![1](https://user-images.githubusercontent.com/25956347/45917045-aefead80-be99-11e8-99a3-f060f575abcd.PNG)
![2](https://user-images.githubusercontent.com/25956347/45917046-af974400-be99-11e8-8813-dcd1473915cc.PNG)

Edit : and after creating a party and start i have to padv 2 times

**Comment by PlayTheFallen** [comment]
**[`DEV`]** Promise is not returned. (Commands/Parties/Party.js#L392)
