### ISSUE TITLE
Gminfo command broken

### ISSUE THREAD

**Issue by Sirfirelord69** [DiscordDungeons/Bugs#737]
**Describe the bug**
The bot returns broken links instead of the trade info message. 

**To Reproduce**
1. Go to '#!gmglist'
2. Copy any 'trade code'
3. Use '#!gminfo'

**Expected behavior**
Bot returns a link which goes to a 502 error

**Screenshots**
![image](https://user-images.githubusercontent.com/42024016/45995335-434f5700-c0ca-11e8-9f8f-ef6c6b639946.png)
![image](https://user-images.githubusercontent.com/42024016/45995351-506c4600-c0ca-11e8-8b6b-f128a88b9283.png)

**Version**
4.3.18

**Comment by ryudragon98** [comment]
to resolve this issue use #!uset tradedisplay 2

**Comment by PlayTheFallen** [comment]
**[`NOTE`]** The etrade api was depreciated a while back.
