### ISSUE TITLE
Guild audit pages broken

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#738]
**Describe the bug**
Changing pages with the #!gaudit doesn't work

**To Reproduce**
1. Type #!gaudit
2. Click the Right arrow emoji, it will not show the next page is what happens.

**Expected behavior**
I expect it to show the other pages within my guild audit

**Screenshots**
![a8e0f6](https://user-images.githubusercontent.com/12903523/46249504-31bcd500-c465-11e8-9eb4-4f09edf01b98.png)
![37cf60](https://user-images.githubusercontent.com/12903523/46249503-31bcd500-c465-11e8-9b16-705ef16ff024.png)

**Version**
4.3.18

**Comment by Sven65** [comment]
Should've autoclosed
