### ISSUE TITLE
problem with the shop

### ISSUE THREAD

**Issue by Pagop** [DiscordDungeons/Bugs#739]
explanation of the problem: When buying an item from the shop, the item isn't in my inventory. When I buy it a second time, it gives me two of the items at once,making me spend twice the money on something.

**To Reproduce**
I just used the usual command to buy something from the shop.
**Expected behavior**
Recieving my item on the first buy.

**Screenshots**
![s80930-002426](https://user-images.githubusercontent.com/43711168/46251017-35d1fe00-c437-11e8-8386-5a9cd1c21253.jpg)
**Version**
idk
**Additional context**

**Comment by ryudragon98** [comment]
this isnt a bug. when you purchase weapons or armor from the in-game shop they will auto-equip.

**Comment by RainTheVappy** [comment]
If you bought a weapon from the bot shop, the weapon will equip automatically.

**Comment by Sven65** [comment]
Not a bug.
