### ISSUE TITLE
Discord RPG app bug

### ISSUE THREAD

**Issue by Rosenkreuz12** [DiscordDungeons/Bugs#74]
someone trying to sell blowfish item decreased but money doesn't cashed in

![](https://cdn.discordapp.com/attachments/173361708885213186/246313039886942209/Screenshot_2016-11-10-17-03-251.png)
![](https://cdn.discordapp.com/attachments/173361708885213186/246313066936008705/Screenshot_2016-11-10-17-05-201.png)
![](https://cdn.discordapp.com/attachments/173361708885213186/246313089232797696/Screenshot_2016-11-10-17-05-351.png)
![](https://cdn.discordapp.com/attachments/173361708885213186/246313211635302401/Screenshot_2016-11-10-17-06-041.png)

**Comment by Sven65** [comment]
Unable to see the issue.
