### ISSUE TITLE
Negative xp 

### ISSUE THREAD

**Issue by Malfujitaka** [DiscordDungeons/Bugs#740]
i got negative xp when my pet get 5000 xp while having the 100% xprate for pet. 

![image](https://user-images.githubusercontent.com/33747311/46619215-26983200-cb54-11e8-90bd-f93aac78c4b6.png)

![image](https://user-images.githubusercontent.com/33747311/46619230-30ba3080-cb54-11e8-8884-e7103c26683a.png)

but if pet gets below than 5000 xp, i'll get the positive xp. but still, it happened when i already set my pet xprate to 100%

![image](https://user-images.githubusercontent.com/33747311/46619267-4891b480-cb54-11e8-9608-3162d3898ce5.png)

![image](https://user-images.githubusercontent.com/33747311/46619306-5e9f7500-cb54-11e8-8262-70dfb7849619.png)

![image](https://user-images.githubusercontent.com/33747311/46619324-6828dd00-cb54-11e8-9aba-941ab10acda8.png)

![image](https://user-images.githubusercontent.com/33747311/46619336-71b24500-cb54-11e8-93cd-fafe1897303a.png)

**Comment by Malfujitaka** [comment]
update

apparently it happens when my pet gets xp lower than 5000 as well. it's random

![image](https://user-images.githubusercontent.com/33747311/46619597-10d73c80-cb55-11e8-86bb-6376c30587cb.png)

**Comment by DeMiDeWa** [comment]
![](https://puu.sh/BHHok/3cbea93324.png)
![](https://puu.sh/BHHnN/27cfd58d52.png)

But sometimes it give you bonus
![](https://puu.sh/BHHuZ/95d357a60c.png)

**Comment by Sven65** [comment]
Closed as it doesn't follow the issue template.
