### ISSUE TITLE
Character Gaining XP Points Instead Of Pet

### ISSUE THREAD

**Issue by DemorLevel1Challenge** [DiscordDungeons/Bugs#741]
I never change my pets xprate from 100 because i only level up my pet. 
After killing an Octocat enemy today I got xp instead of my type rock pet. I was told to type #!pset xprate 0 and then #!pset xprate 100 again in #rpg-support after explaining my issue. 
I tried killing another enemy Ogre minutes after and the problem is not solved. I can't type #!adv anymore until this bug is fixed because I don't want to level up from level 1. This bug already added my character 17 unwanted XP points.
Thank You For Reading

**Comment by Sven65** [comment]
Closed as it doesn't follow the issue template.
