### ISSUE TITLE
Character Gaining XP Points Instead Of Pet

### ISSUE THREAD

**Issue by DemorLevel1Challenge** [DiscordDungeons/Bugs#743]
**Describe the bug**
Character gaining XP points instead of pet. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Type #!pset xprate 100
2. Type #!adv
3. Character gets XP points instead of pet is what happens.

**Expected behaviour**
I expect my pet to gain XP points instead of my character. 

**Screenshots**
![2018-10-08_11-33-20](https://user-images.githubusercontent.com/43964625/46621917-747a4f00-caee-11e8-9818-42c6aebfe1de.jpg)
![2018-10-08_11-29-29](https://user-images.githubusercontent.com/43964625/46621925-7a703000-caee-11e8-902b-a3d6ab533af1.jpg)

**Version**
4.3.19

**Additional context**
My character is level 1 and my pets type is Rock.

**Comment by Sven65** [comment]
Same as #742

**Comment by PlayTheFallen** [comment]
Duplicate of #742
