### ISSUE TITLE
Global Market (Membership commands)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#745]
**Is your feature request related to a problem? Please describe.**
With commands `#!gmavg` and `#!gbavg` are quite bad with the average values of an item, since it tracks all completed trades aswell as active trades, all completed trades mess around with the average value such as small daggers.
![2f4779](https://user-images.githubusercontent.com/12903523/46906559-4b1f5000-cf40-11e8-9b24-6a21ed4cc0d7.png)
whilst current active trades are
![000189](https://user-images.githubusercontent.com/12903523/46906564-6a1de200-cf40-11e8-8030-969b46663aa4.png)
As you can see this really messes with the feature of market averages. 

**Describe the solution you'd like**
What I think would be a good solution is the bot should only track last 5 completed trades so it can even out a fair average, with it tracking all it really just shows the feature being really pointless of a use.

- Was going to report as a bug but as I see it, it's not a bug and is an intended thing.

**Comment by RainTheVappy** [comment]
It will be nice to have a "fully filled" order that'll count toward avg rather than all set ones, which means cancelled/taken isn't counted

**Comment by Sven65** [comment]
This bug has been fixed by the indroduction of other moderation tools.
