### ISSUE TITLE
Trade Bug 

### ISSUE THREAD

**Issue by vladykins** [DiscordDungeons/Bugs#746]
**Describe the bug**
received the following when I gmstopped a trade:

DiscordRPGBOTToday at 2:52 PM
vladykins stopped trade jnah0iip. Results: 20,979 gold
Whoops. An error occured. Please report this in the official server.

TypeError: Cannot read property 'price' of undefined
    at Gmstop.Execute (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmstop.js:152:211)
    at <anonymous>

**Comment by Valicek1** [comment]
For me, the same: 

Trade id: jnetep4g
```
TypeError: Cannot read property 'price' of undefined
    at Gmstop.Execute (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmstop.js:152:211)
    at <anonymous>
````
