### ISSUE TITLE
lead scavenging

### ISSUE THREAD

**Issue by Mistyglowy** [DiscordDungeons/Bugs#747]
Ancient bug. #!lead scavenging (used to show nothing) is now giving an error. 

![](https://cdn.discordapp.com/attachments/461125560949669899/502647087540862986/unknown.png)

**Comment by PlayTheFallen** [comment]
**[`DEV`]**
```js
let field = args[0], value;
switch(field) {
  // ...
  case "scavenging":
    value = user.attributes[field];
    break;
  // ...
}```

**Comment by PlayTheFallen** [comment]
**[`DEV`]** Pending review and push to master.
