### ISSUE TITLE
#!inv bug

### ISSUE THREAD

**Issue by ghost** [DiscordDungeons/Bugs#755]
https://prntscr.com/lgt3p1

at the first #!inv = "2 x octopi"
at the second, after selling one octopus = "1 x octopus"

this is a small bug, but I spent some time trying to sell "octopi" and giving "unknown item"

**Comment by Willard21** [comment]
It's not a bug, it's just proper grammar

**Comment by DeMiDeWa** [comment]
don't use plural next time
