### ISSUE TITLE
Manage Perms Issue

### ISSUE THREAD

**Issue by shroomyun** [DiscordDungeons/Bugs#758]
_Reporting in behalf of user **CVSMERECAT#6246**_

> Manage permissions perm likely broken for concerned user despite the perm checker site says she has the necessary perms to perform the commands.

![perms](https://user-images.githubusercontent.com/33994869/48321375-df7be180-e5d6-11e8-9040-03c5ead55f20.jpg)

**Comment by Willard21** [comment]
![image](https://user-images.githubusercontent.com/24826881/48322635-38a33f80-e5ee-11e8-8590-442af4132d47.png)
