### ISSUE TITLE
Death of opponent in PVP causes error

### ISSUE THREAD

**Issue by A-Guy-without-A-Hat** [DiscordDungeons/Bugs#762]
**Describe the bug**
Once one player has beaten the other sufficiently enough to warrant a final blow. The delivery of the final attack #!bfight caused an error which canceled the match. 

**To Reproduce**
Has only occurred once. I do not know how to reproduce. 

**Expected behavior**
Opponent player was supposed to be slain, and a redistribution of Gold was to take place. 

**Screenshots**
<img width="917" alt="screen shot 2018-11-16 at 12 47 45 pm" src="https://user-images.githubusercontent.com/45105699/48638178-d8b9e980-e99d-11e8-8a0c-13e8eb1deb33.png">

**Version**
DRPG Version 4.3.24 - Made by Mackan#7196

**Additional context**
Happened on a privately run server between two lvl 5. the winning player had around 178,519 Gold and defeated had around 19,787.

**Comment by Willard21** [comment]
Will fix soon:tm:, but in the meantime, don't lose a fight with more than 50 gold (that's how you reproduce it)
