### ISSUE TITLE
AdventureEmbed 2 Doesn't Ping Next Person In Parties

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#764]
**Describe the bug**
Embedded party adventures don't show whose turn is next.
Edit: Jk it does, but it's still not a ping, so it's nearly impossible to see in a fast moving party. Might need to be moved to ideas, but it's already here so I'll leave it.

**To Reproduce**
1. `#!uset adventureEmbed 2`
2. `#!padv` (when you don't get the kill shot)

**Expected behavior**
The next player should be pinged, same as `adventureEmbed 1`

**Comment by Sven65** [comment]
Closed as it does what it's supposed to.
