### ISSUE TITLE
Mentioning the bot anywhere in a message will treat the second word as a command

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#768]
**Describe the bug**
Mentioning the bot anywhere in a message will treat the second word as a command.

**To Reproduce**
1. `randomThing \<command\> @DiscordRPG
2. Get a response

**Expected behavior**
Either the first word shouldn't be ignored (if this was intended behavior) or it should only work if the message *starts* with the mention.

**Screenshots**
![image](https://user-images.githubusercontent.com/24826881/49329103-f069a400-f53f-11e8-871c-f217c4e1180a.png)

**Comment by PlayTheFallen** [comment]
i was working on a method *for another project* that would gather all prefixes and treat them as if they were regex patterns

`/^({prefixA}|{prefixB}|...)/`

this can be implemented into the game simply by doing something like [regex pattern environment](https://regex101.com/r/EL599h/2).
