### ISSUE TITLE
Error `formatNumber` on `#!runes`

### ISSUE THREAD

**Issue by DeMiDeWa** [DiscordDungeons/Bugs#769]
**Describe the bug**
Well, i just want to see how would it look like but it show me an error instead. 

**To Reproduce**
1. Do `#!runes`
2. See error

**Expected behavior**
The bot should show me how many runes I have and the maximum I can have.

**Screenshots**
![](http://puu.sh/CdjZY/24ae3b6862.png)

**Version**
DiscordRPG 4.5.0 (Steel Sunflower)

**Additional context**

**Comment by Sven65** [comment]
Fixed.
