### ISSUE TITLE
typo in attributes

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#770]
**Describe the bug**
Typo in attributes
**To Reproduce**
1. type #!attrbutes
2. you see the typo under lumber boost 

**Expected behavior**
not to show typo

**Screenshots**
![a2750c](https://user-images.githubusercontent.com/12903523/49581825-8bc2a500-f996-11e8-9830-361058b7e8d2.png)

**Version**
The latest

**Comment by Sven65** [comment]
Probs fixed, if not, open a new issue.

**Comment by FelixArgyle** [comment]
Not fixed (check next time with `#!attribs`)

**Comment by Willard21** [comment]
Not applicable to mine or forage as the amount of item boost depends on the item. All essences have reduced effect from mineboost, and olive seeds and sugar beet seeds have reduced effect from scavenging. That means we can't really display a specific number in attribs without it being wrong for some items. So even though it's not "fixed", it's also not a bug or typo.
