### ISSUE TITLE
Plant

### ISSUE THREAD

**Issue by cap-noodles** [DiscordDungeons/Bugs#771]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**
What is the current version at the time of creating this issue?

**Additional context**

**Comment by cap-noodles** [comment]
```
ReferenceError: user is not defined
    at Plant.Execute (/home/mackan/RPGBot/src/Commands/Commands/Sides/Plant.js:308:41)
    at <anonymous>

```
that's what #!plant check and #!plant set (seed) do.

**Comment by SordyGR** [comment]
#!buyfield [copperfall]
#!plant set wheat seed
this chain of commands brought this error in [rpg-6]: 

Whoops. An error occured. Please report this in the official server.
ReferenceError: user is not defined
    at Plant.Execute (/home/mackan/RPGBot/src/Commands/Commands/Sides/Plant.js:308:41)
    at <anonymous>

**Comment by Sven65** [comment]
Fixed.
