### ISSUE TITLE
Uset nick is broken

### ISSUE THREAD

**Issue by doge-pepe-twat68** [DiscordDungeons/Bugs#773]
**Describe the bug**
#!uset nick currently does not work on other servers, besides the main server (have tried on 3 different servers).
Yes they have the correct perms, checked on all three servers, and I am not owner of any of them.

**To Reproduce**
1. Go to a different server with drpg (works on a few others)
2. #!uset nick 1-3
3. Outputs error while saying nickname has changed, when it hasnt been

**Screenshots**
Top: DRPG Server
![image](https://user-images.githubusercontent.com/26106799/49625041-a42ad200-fa1f-11e8-849a-c8037783cbd3.png)
Bottom: Various Other Servers
![image](https://user-images.githubusercontent.com/26106799/49625048-aa20b300-fa1f-11e8-9b89-4e905ffbcca2.png)

**Comment by Willard21** [comment]
Who knows? We just need proper error handling so people will stop reporting these things in #support lol

**Comment by doge-pepe-twat68** [comment]
yes of course they are tklaxbro, i make sure to check 3x, even when helping others in fixing their perms, that it's not a problem in their server itself
