### ISSUE TITLE
Changing guild name outside the official server doesn't change the guild role

### ISSUE THREAD

**Issue by DeMiDeWa** [DiscordDungeons/Bugs#775]
**Describe the bug**
If you change the name of your guild on other server (outside Discord Dungeons server), the bot will not change the name of guild role (assuming your guild have one).

**To Reproduce**
1. Move to other Discord server (other than Discord Dungeons server)
2. Do `#!gset name <new name>`, hit Enter
3. Move back to Discord Dungeons server, do `#!stats` and look at `Guild` section on your stats
4. Click on your nick (i'm using Discord desktop version), then look at your guild role. In my case, the blue role is my guild role.

**Expected behavior**
When you changed your guild name via other server, the name of guild role on Discord Dungeons should also changed (assuming you have one).

**Screenshots**
*Before changing my guild name*
![](https://puu.sh/CelUr/fb70ebe028.png)

*Changing guild name on my server*
![](https://puu.sh/CelZR/ae4818079e.png)

*After changing my guild name*
![](https://puu.sh/Cem0W/699dcb2038.png)

**Version**
DiscordRPG 4.5.0 (Steel Sunflower) *~~Well, actually, this bug is really old. I was just too lazy to take the pics and report it.~~*

**Additional context**
*Maybe the bot should tell the user that they have to do that on Discord Dungeons (?) Like `#!gdisband`*
*Oh, also, it doesn't change the name of the guild channel. I forgot about it, but i'm too lazy to take the pictures from start again.*

**Comment by Sven65** [comment]
This is because the role doesn't exist on your server and there is no way for the bot to get the role from your server at the moment.

**Comment by DeMiDeWa** [comment]
Well, i'm talking about the rold on Discord Dungeons server.

**Comment by Sven65** [comment]
I know, your role on the DD server doesn't exist on your server, hence the bot can't find it.

**Comment by Willard21** [comment]
I'll just have it not let you change your guild's name outside the official server if you have a role. A couple other commands already do that, like `#!leave`
