### ISSUE TITLE
lost money

### ISSUE THREAD

**Issue by AzureFlamez** [DiscordDungeons/Bugs#78]
so i started playing discord RPG again today

![](http://puu.sh/skiSj/903cf2bffb.png)
i did all they commands in PM back when i was playing cause the server i was in was just a spam fest and i today when i started playing again i checked my stats and saw i lost a lot of money and i dont know why since im pretty sure i didnt transfer any to the guild or another player

![](http://puu.sh/skiCC/149660e0e7.png)

![](http://puu.sh/skiLN/5633e416d9.png)

**Comment by Rosenkreuz12** [comment]
yeah looks like that old gold bug, that happens few weeks ago just go on main server and ask mackan to get refund for the price of that conjurer's foresight, alternatively you could just sell that conjurer's foresight on global market by using gmsell command

**Comment by Sven65** [comment]
Is the gold bug back?
God dammit.

**Comment by AzureFlamez** [comment]
sorry i dont think its back, i think i quit when it happened and only found out about it when i started playing again yesterday
