### ISSUE TITLE
Dungeon Mimics

### ISSUE THREAD

**Issue by Neu-Shuvi** [DiscordDungeons/Bugs#786]
-Last hit on dungeon mimics wont show-
Here's a screenshot 
![1](https://user-images.githubusercontent.com/46419478/50736446-c1a6b380-11f8-11e9-9b5b-4379c70a242f.PNG)
![2](https://user-images.githubusercontent.com/46419478/50736447-c4090d80-11f8-11e9-81ca-79685f9fec4a.PNG)

**Comment by Willard21** [comment]
Not just mimics, but all mobs that drop item loot. Probably breaks quests too.
