### ISSUE TITLE
Owner and Elder at the same time?

### ISSUE THREAD

**Issue by PlayTheFallen** [DiscordDungeons/Bugs#79]
![image](https://cloud.githubusercontent.com/assets/8607699/20858923/ca47a5c8-b947-11e6-9e0a-ed3152c04304.png)

Former Elder of guild is now the owner / leader, but shows under Owner and Elder.

_Submitted by `Kitten Clan Leader#7048` in `#rpg_bugs`._

**Comment by Sven65** [comment]
Single case issue. No fixing needed.
