### ISSUE TITLE
Donator item 🌀Cloak of Oblivion🌀 not working or equipable

### ISSUE THREAD

**Issue by Cyro65** [DiscordDungeons/Bugs#790]
**Describe the bug**
The Donator item 🌀Cloak of Oblivion🌀 a chest piece level 60 not equipable and doesn't show armor amount.
**To Reproduce**
1. #!item 🌀Cloak of Oblivion🌀
2. #!use 🌀Cloak of Oblivion🌀
3. when doing #!item 🌀Cloak of Oblivion🌀 it will not show armor or defense amount.
4. when doing #!use 🌀Cloak of Oblivion🌀 it won't do anything and won't equip.

**Expected behavior**
when doing #!use 🌀Cloak of Oblivion🌀 it should equip lol

**Comment by PlayTheFallen** [comment]
Alternative: `#!item Cloak of Oblivion`

**Comment by Cyro65** [comment]
No I’ve tried this, still does not work. When I say use and form any type of combination of cloak of oblivion with or without symbols caps or no caps, nothing happens

**Comment by PlayTheFallen** [comment]
![image](https://user-images.githubusercontent.com/8607699/51407768-b6d31380-1b54-11e9-8a92-d25a46b75e7e.png)

**Comment by Cyro65** [comment]
![crt](https://user-images.githubusercontent.com/46823888/51407832-95593400-1b22-11e9-8474-e49c5d515b38.PNG)

**Comment by Cyro65** [comment]
Yes... I know.... as I said
USE doesnt work

**Comment by PlayTheFallen** [comment]
did you take the emojis out?

**Comment by Saederup92** [comment]
Are you sure you aren't already wearing it? 🤔

**Comment by Cyro65** [comment]
Yes to both
ive tried with and without emojis. I wouldn't waste your time.

**Comment by Cyro65** [comment]
![crt2](https://user-images.githubusercontent.com/46823888/51408027-14e70300-1b23-11e9-82fe-78107bea6a05.PNG)

**Comment by Cyro65** [comment]
Is it a problem with the item itself?

**Comment by Willard21** [comment]
The type is wrong. It says it's a `Chestplate` while all working chestplates are of type `Chest`

**Comment by Cyro65** [comment]
So is this something the devs will fix or do I need to? And if so how?

**Comment by Willard21** [comment]
Mackan will have to do it since only he has access to edit items.

**Comment by Sven65** [comment]
Fixed.
