### ISSUE TITLE
Bot Not Joining Server

### ISSUE THREAD

**Issue by AllenMa04** [DiscordDungeons/Bugs#791]
**Describe the bug**
Tried inviting the DRPG bot several times. It says authorized after inviting the bot, but the bot didn't join the server. 

**To Reproduce**
1. Go to https://bot.discorddungeons.me/?utm_medium=referral&utm_source=main
2. Click on Invite and select a server.
3. Select a server and get authorized.
4. The DRPG bot does not get added.

**Expected behavior**
The bot should have joined the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/34803890/51420739-ab2e1f80-1b49-11e9-9f16-69f64a5effea.png)
![image](https://user-images.githubusercontent.com/34803890/51420747-bed98600-1b49-11e9-876a-7612b37289a3.png)

**Comment by PlayTheFallen** [comment]
*Context required*
- What are your permissions for that server?
- Are you sure that it's not lower down on the members list?

**Comment by ryudragon98** [comment]
I went and tested to see if I could invite the bot to their server I was given the manage server perms which is required in order to invite bots, I was able to complete the Authorization but the bot failed to join the server and it did not show in the members list.

**Comment by MalekTHEghost** [comment]
hm why not trying to invite it on another server

**Comment by Willard21** [comment]
Bots joining servers is handled by Discord itself. Even if the bot was completely dead and its servers destroyed, you should still be able to add it to your server. So this can't be a bug on our end.
