### ISSUE TITLE
Rune capacity not showing on stats.

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#792]
**Describe the bug**
On user `302541966623899651` their rune capacity does not show within their stats.
I assume that this may be happening to other few users, not sure on the cause but surely you guys will find it.

**To Reproduce**
Hard to reproduce as it only seems to effect few users
1. Have user `302541966623899651` type `#!stats` / or you type `#!stats 302541966623899651`
2. You will see their stats with no `rune` capacity stuff on it.

**Expected behavior**
I'd expect it to show the `rune` capacity on all users, such as `302541966623899651`
**Screenshots**
This shows `302541966623899651` stats, as you see there is no `rune` part ![98fc96](https://user-images.githubusercontent.com/12903523/51646014-1ba9c600-1fba-11e9-9337-55c33ada4aac.png)

Is my stats, this shows my `rune` part ![d7bb01 1](https://user-images.githubusercontent.com/12903523/51646040-409e3900-1fba-11e9-9491-4a72942c7304.png)

**Version**
DRPG Version 4.7.0

**Comment by Willard21** [comment]
Do they have any runes? Pretty sure it doesn't show if you don't have any.

**Comment by FelixArgyle** [comment]
> Do they have any runes? Pretty sure it doesn't show if you don't have any.

Mhm, they have runes, 
![db71aa](https://user-images.githubusercontent.com/12903523/51648910-cffd1980-1fc5-11e9-8978-deb8075943bf.png)

**Comment by lightningAsura** [comment]
Afaik, the rune capacity doesn't show unless you upgraded it, and upgrading the capacity isn't currently possible due to 'the npc not respoding' bug

**Comment by PlayTheFallen** [comment]
Depends on #788

**Comment by Willard21** [comment]
Doesn't really depend on it. It should show the capacity if you have at least 1 rune since the default capacity isn't common sense (I don't even know it).
