### ISSUE TITLE
i think i found typing mistake at lemontree plaza npc alex

### ISSUE THREAD

**Issue by OverlordSakuya** [DiscordDungeons/Bugs#800]
**Describe the bug**
I wanted to do daily task and noticed word knives i tried #!recipe knives didnt worked tried #!item knives also didnt worked even tried writing knive nothing i think it should be knifes
**To Reproduce**

**Expected behavior**

**Screenshots**
![bug](https://user-images.githubusercontent.com/47494725/52532045-47051280-2d27-11e9-9c5c-05ed32f41dc2.PNG)

**Version**
DRPG Version 4.7.0 

**Additional context**

**Comment by marekkora** [comment]
the singular of knives is knife

**Comment by PlayTheFallen** [comment]
[ADMIN] Resolved by @marekkora
