### ISSUE TITLE
Error with #!talk in bots DM

### ISSUE THREAD

**Issue by Xenocores** [DiscordDungeons/Bugs#801]
**Describe the bug**
When I used `#!talk npcname` in bots DM error message appeared.
I'm still was able normally upgrade equip, but sometimes bot don't place number emojis.

**To Reproduce**
1. Start talking with npcs in bots DM (That happened to me with Pope Seth, and Urist npcs).
2. See how appears error.
3. Continue talk and see more error messages.

**Expected behavior**
??

**Screenshots**
http://prntscr.com/mj3y1c

**Version**
DRPG Version 4.7.0

**Comment by Willard21** [comment]
Fixed over a month ago, just still waiting for an update.

**Comment by Willard21** [comment]
Should be fixed now
