### ISSUE TITLE
tagbot renamed to offensive name

### ISSUE THREAD

**Issue by JaneDohh** [DiscordDungeons/Bugs#804]
Someone decided to change the "TagBot" to "FagBot".  This is an offensive term in english, so please correct it back.

**Comment by tklaxbro** [comment]
I’m no representation of DRPG but I do know this is not the place to handle this issue. Please message a staff member on discord if you feel action needs to be done.

**Comment by tklaxbro** [comment]
Closing, not a bug nor the place to report this problem.
