### ISSUE TITLE
Bug + Feature request [Market]

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#805]
**Describe the bug**
Using #!gbsell id [over what's left of a trade]  i.e say there is 500 apples being bought and it has 30 already sold using #!gbsell id 99999  will sell the remaining apples that are left to be sold to.

[FEATURE REQUEST] - instead add an "all" variable to sell / buy to a remaining trade
(do think the update really lack on not thinking already counter effects against removing so the default sells / buys all from a trade)

**To Reproduce**
![90258b](https://user-images.githubusercontent.com/12903523/52761788-2b1bac80-3058-11e9-86d7-1f51f529a52b.png)

**Expected behavior**
I expect their to be an all variable and for this to be better fitting for the market

**Version**
The version that broke market -  4.8.0
**Additional context**
**GET WILLARD TO ACTUALLY TEST EVERY DETAIL IN EVERY LITTLE CHANGE**

**Comment by Willard21** [comment]
Re: Additional context
NO U

**Comment by Willard21** [comment]
The amount being capped at the number of remaining trades is intended behavior, so that portion of this bug report isn't really a bug and won't be changed. Will add an `all` option tho.
