### ISSUE TITLE
Attribute points issue

### ISSUE THREAD

**Issue by iSaluki** [DiscordDungeons/Bugs#806]
I cannot assign any new attribute points. I levelled up to level 3 and then got 5 points. I assigned 2 to strength and that worked fine. Then I assigned 2 to luck but the not ignored the command. The same happened when I tried to assign the last one to charisma.

**Comment by Saederup92** [comment]
Try running `#!attributes`. Luck and charisma are no longer attributes that can be assigned to :)

**Comment by iSaluki** [comment]
Thanks. That's working. I was following the Wiki on that one (the starter guide page is a bit outdated).

**Comment by Saederup92** [comment]
The wiki still needs some reworking

**Comment by Willard21** [comment]
Yup, wiki is super outdated, but it's not a bug so I'll close this.
