### ISSUE TITLE
Bug with < and > in DRPG Suggests

### ISSUE THREAD

**Issue by BuoYancYdabl** [DiscordDungeons/Bugs#807]
When someone write word inside < > it doesnt count!

**Comment by Willard21** [comment]
Why would it?

**Comment by BuoYancYdabl** [comment]
> Why would it?

If this isnt a bug so what is this?

**Comment by Saederup92** [comment]
Can you give an example? 🤔

**Comment by Willard21** [comment]
I don't know, you didn't describe a bug. Near as I can tell you want `#!<adv>` to work for some reason

**Comment by BuoYancYdabl** [comment]
I talking about Discord Sugfestions. When you write simple words in < > it doesnt cound in when you make post/comment!

**Comment by BuoYancYdabl** [comment]
Example: This is the <letter> before me. The word "leter" disapear in final.
![screenshot_2019-02-24-18-27-49](https://user-images.githubusercontent.com/36867670/53301990-12827200-3862-11e9-9bbf-e14f5ced8243.png)

**Comment by Willard21** [comment]
Ah, that would be due to markdown or markup formatting. GitHub uses the same thing. 
![image](https://user-images.githubusercontent.com/24826881/53302008-530ccc00-381f-11e9-9dbe-feb93ddf5c9c.png)

**Comment by BuoYancYdabl** [comment]
So this is a bug, or its unfixable?

**Comment by Willard21** [comment]
Not a bug. You can use `&lt;` for the Less Than symbol and `&gt;` for the Greater Than symbol. If you want to suggest a change, that would need to be done to [Fider](https://getfider.com/)

**Comment by BuoYancYdabl** [comment]
Okay thanks! I was suprised that this markdowns just delete very important information :)

**Comment by Sven65** [comment]
For reference, we use [fider](https://github.com/getfider/fider) for the ideas platform

**Comment by Willard21** [comment]
Looks like he already found it, reported it, and Fider fixed it in Master. https://github.com/getfider/fider/issues/726 :+1:

**Comment by BuoYancYdabl** [comment]
Yes, i reported this issue to fider and they fixed it!
