### ISSUE TITLE
Charged for weapon update but not applied

### ISSUE THREAD

**Issue by TacoLord321** [DiscordDungeons/Bugs#809]
I upgraded my Nova dagger to +8 and was charged the gold but is still showing as +7

Had roughly 313,509 gold before talking to Urist (slightly more due to adv while traveling to Redhorn.
Switched weapons
Talked to Urist and selected Nova Dagger to upgrade by 1

Reacted with 1 to confirm
used adv to test new weapon but forgot to equip
Equipped but was still +7, used adv, received the timed out message from Urist

Only had 66614 gold afterwards.

Tried to talk to Urist to upgrade weapon again but immediately got message that I didn't have enough gold.
![gold before update](https://user-images.githubusercontent.com/48126615/53640486-5676cd80-3bfa-11e9-9cac-cb232fa4df5c.PNG)
![urist upgrade](https://user-images.githubusercontent.com/48126615/53640498-5d054500-3bfa-11e9-89f5-dccf65d3a406.PNG)
![after upgrade](https://user-images.githubusercontent.com/48126615/53640504-61316280-3bfa-11e9-886d-889b0796b011.PNG)
![after upgrade 2](https://user-images.githubusercontent.com/48126615/53640505-6393bc80-3bfa-11e9-8a68-9e67583b8d67.PNG)
![attempting upgrade afterwards without gold](https://user-images.githubusercontent.com/48126615/53640507-668ead00-3bfa-11e9-9326-a92c1f62dfb8.PNG)

**Comment by Willard21** [comment]
Removing the weapon from your inventory after selecting it but before finalizing the upgrade will make Urist think you're trying to scam him. "Is this some kind of joke?" is his "you're no longer holding this item" message. That used to be a dupe glitch before it was patched :eyes:

**Comment by Sven65** [comment]
So is this an actual issue anymore, @Willard21?

**Comment by Sven65** [comment]
Closed as it's stale and seemingly not an issue anymore.
