### ISSUE TITLE
Mine

### ISSUE THREAD

**Issue by TheRealLoneWolf** [DiscordDungeons/Bugs#810]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**
What is the current version at the time of creating this issue?

**Additional context**

**Comment by TheRealLoneWolf** [comment]
error occurs when the following is done, at least to me, travel to silverkeep alter, once there, use the command #!mine, then this should appear
Whoops. An error occured. Please report this in the official server.
TypeError: Cannot read property 'indexOf' of undefined
    at Mine._canMine (/home/mackan/RPGBot/src/Commands/Commands/Sides/Mine.js:165:34)
    at Mine.Execute (/home/mackan/RPGBot/src/Commands/Commands/Sides/Mine.js:235:12)
current version: DRPG Version 4.8.0 - Made by Mackan#7196

**Comment by Willard21** [comment]
Appears to occur when you've never started a quest before. Do (or at least start) a quest to get it working for you.
