### ISSUE TITLE
#!drop is buggy

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#811]
**Describe the bug**
When trying to drop an item that ends in a number, having multiple items with the same base name prevents it from matching the item.

**To Reproduce**
1. Get a small dagger +1
2. Get a small dagger +2
3. Try to drop either of them

**Expected behavior**
It should drop the item.

**Screenshots**
![image](https://user-images.githubusercontent.com/24826881/54574790-ace85800-49bf-11e9-83cc-1725327446e3.png)

**Version**
4.8.1

**Comment by tyler489** [comment]
Whatever fixed #673 should fix that to

**Comment by Willard21** [comment]
Yeah I used some hacky fix for #!drop when I added meta items. Didn't realize it wasn't working right. Think I thought better solutions for the other commands later.
