### ISSUE TITLE
[Minor] Text Error

### ISSUE THREAD

**Issue by Bunbuns** [DiscordDungeons/Bugs#812]
When Playing in the quest "Bakoushi's Bunny", a text error can be found. The story states that the bunny is "on fire" but when you actually fight the mob it displays at bunny "of fire". Also when the story is narrated the text "pulls of a bunny" is displayed instead of "pulls out a bunny". Thank you!

Version 4.8.1 30 March 

sorry i just had to point it out

**Comment by Sven65** [comment]
Fixed "pulls of a bunny".
