### ISSUE TITLE
Location arrival grammar

### ISSUE THREAD

**Issue by lifeofchrome** [DiscordDungeons/Bugs#814]
**Describe the bug**
"Username arrived **to** Location" is incorrect grammar, "Username arrived **at** Location" is correct.

**To Reproduce**
1. Arrive at a location.

**Expected behavior**
The word to should be replaced with the word at.

**Version**
4.9.0

**Additional context**
This bug has occurred 136,696 times.

**Comment by Sven65** [comment]
Closed as "to primeval" sounds better than "at primeval"
