### ISSUE TITLE
#!gset not showing Color hex

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#817]
**Describe the bug**
Looking at my `#!gset` guild settings I noticed that the Color isn't being updated no matter what.

**To Reproduce**
1. Change your Role color to anything and type #!gset
2. Once you type #!gset navigate to the "Color" part you'd notice it would say it's #0
**Expected behavior**
I expect it to show my actual guild role color there perhaps?
**Screenshots**
![98su7L4](https://user-images.githubusercontent.com/12903523/56721210-5ff65f00-677f-11e9-99c8-bf66a8de976f.png)

**Version**
4.9.1
**Additional context**
TEST YOUR ACTUAL STUFF GOD DAMN IT!

**Comment by Willard21** [comment]
`#!uset nick 0` also still shows 1
