### ISSUE TITLE
spelling mistake in #!inv

### ISSUE THREAD

**Issue by juliantang406** [DiscordDungeons/Bugs#819]
**Describe the bug**
Says "Octopi" when the correct spelling is "Octopuses" (look it up) in inventory

**To Reproduce**
Steps to reproduce the behavior (will only work if you have more than 1 octopus in your inventory):
1. Type "#!inv"
2. Find octopuses in your inventory.
3. You will see that it says "Octopi" instead of "Octopuses"

**Expected behavior**
Should say "<number other than 1> x Octopuses"

**Screenshots**
![image](https://user-images.githubusercontent.com/51039857/58377379-c19f1a00-7f33-11e9-846c-e57910dbea94.png)

**Version**
DRPG Version 4.10.0 on 5/25/19

**Additional context**
Could also be "Octopodes."

**Comment by PlayTheFallen** [comment]
https://english.stackexchange.com/a/271

**Comment by PlayTheFallen** [comment]
*quoting from stackexchange/a/271 above*
- "octopuses" is apparently most common in UK *even though i've never used it myself*
- "octopodes" is rare
- "octopi" is often objectionable

**Comment by PlayTheFallen** [comment]
[ADMIN] Stale issue.
