### ISSUE TITLE
Delayed talk command

### ISSUE THREAD

**Issue by TheCaneOfTheTophat** [DiscordDungeons/Bugs#823]
Description:
I talked to an NPC that sells items (mainly Felix), and then I canceled, I tried to talk to other NPC's and the bot tells me i'm already talking to somebody else.

Reproduction:
1. Go to a place which has an NPC that sells items
2. Talk to it, but cancel the conversation
3. Talk to any other NPC

Screenshots:
![image](https://user-images.githubusercontent.com/45758760/59549673-ca4ea300-8f69-11e9-8608-0c9ab203d754.png)

Version:
DRPG Version 4.11.2

Additional Context:
After a while, You are able to talk again.

**Comment by Sven65** [comment]
Already reported in #820
