### ISSUE TITLE
Items that should be added to Task Blacklist

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#824]
**Describe the bug**
Some items still need to be added to the blacklist; the list is below.

Money Bag (100k)#​481 - Item is unobtainable
Letter#129  - Craftable (BUT) really really rare to craft only so few have it as it requires opening chests to get Letter Pieces.
HG Pendant#709 - Donor Item
Bear#462 - You get this from setting a trap and checking it after 7 days time (so 1 per 7 days)
Felix's Fur#657 Donor Item + You get this from setting a trap and checking it after 7 days time (so 1 per 7 days) [Yes it may be public but it still is a donor item as such.]
Immortal King's Sacrament#656 - Donor Item [Yes it may be public but it still is a donor item as such.]
Felix's Trap#655 - Donor Item [Yes it may be public but it still is a donor item as such.]
Nova Starlight Absorber#696 Donor Item [Yes it may be public but it still is a donor item as such.]
Nova Dagger#617 Donor Item [Yes it may be public but it still is a donor item as such.]
Nova Energy Blade#641  Donor Item [Yes it may be public but it still is a donor item as such.]
Golden Small Dagger#526 Donor Item [Yes it may be public but it still is a donor item as such.]

Would say just add all craftable weapons to the list as it's really stupid to hand in a crafted weapon for a task when they cost "materials" that are also offered for tasks.
**Version**
4.11.2

**Comment by Sven65** [comment]
I'll be looking at it.

**Comment by Sven65** [comment]
Fixed.
