### ISSUE TITLE
Emoji error prevents dialogs

### ISSUE THREAD

**Issue by sham3l3ss** [DiscordDungeons/Bugs#827]
**Describe the bug**

**To Reproduce**
1. Talking to Urist causes the issue
2. Inventory command causes the issue
3. Any command that uses Emoji

**Expected behavior**
No explanation should be needed, but the command should execute instead error.

**Screenshots**
![15608903209754817311211899373369](https://user-images.githubusercontent.com/7201326/59718207-801a2b80-91ce-11e9-870e-016fe73cbfca.jpg)
![15608903787857039520722657403738](https://user-images.githubusercontent.com/7201326/59718238-96c08280-91ce-11e9-8958-3af064a905b9.jpg)

**Version**
What is the current version at the time of creating this issue?

4.11.2

**Additional context**

This seems to only happen on our guild server. Cannot replicate error anywhere else

**Comment by PlayTheFallen** [comment]
Unable to reproduce.

**Comment by Sven65** [comment]
Most likely an error with the bot not having reaction permissions.

**Comment by PlayTheFallen** [comment]
@Sven65 ![](https://did-you-get.ratelimited.today/6XeWRmZ.png)

**Comment by Sven65** [comment]
Ask for a server invite in their DMs and check the perms, do a #!debug etc

**Comment by sham3l3ss** [comment]
Issue seems to be resolved
