### ISSUE TITLE
Error when doing "adventure" command

### ISSUE THREAD

**Issue by Knightdestin** [DiscordDungeons/Bugs#828]
**Describe the bug**
After a few "adventure" commands, now with new DiscordRPG update, I'm getting an error message each time I'm doing a fight.
Tried with all different "adventureembed" value, still same error each time.
By tracking my fight with "stats" command, I can see my gold, xp and kill count increase (while at the same time, my pet's HP and mine are also decreasing) each time I'm doing a fight.

**To Reproduce**
Just doing "adventure" command with my profile.

**Expected behavior**
A message showing the results of my fight.

**Screenshots**
![bug](https://user-images.githubusercontent.com/52168915/60030155-01236800-9692-11e9-8b5f-1a3df4043c5d.jpg)

**Version**
4.12.0

**Additional context**

**Comment by Sven65** [comment]
Issue with the database stuff, will look into.

**Comment by Sven65** [comment]
Fixed.
