### ISSUE TITLE
Achievementstats bug

### ISSUE THREAD

**Issue by lightningAsura** [DiscordDungeons/Bugs#829]
**Describe the bug**
Locationsvisited & npcinteractions numbers in achievementstats sometimes completely reset or add get lowered down.

**To Reproduce**
1. Travel to different locations
2. Interact with several npcs
3. Check your achievementstats everytime you travel or interact with an npc, and after a while of doing so
4. See that at one point your locationsvisited & npc interaction numbers may be completely reset or go down, going to the locations that had their count reset doesn't increase that achstat anymore (it is as if it's already registered but just wiped out from your record)

**Expected behavior**
You expect that every location you visited & every npc you interact with would be counted and add to your achievementstats without them going down or count into the negative.

**Version**
4.12.0

**Comment by Sven65** [comment]
Any more context on this? I.e what NPCs cause it?

**Comment by lightningAsura** [comment]
Afaik, it just happens randomly, after taking to x number of npcs, it just gets reset for no known reason, same with traveling, and the problem extends to other achstats as well, i.E I bought stuff using 1000 lux gots its ach then later it just got reset back to 0 or a lower count.

**Comment by Sven65** [comment]
Alright, I'll look into it.

**Comment by Sven65** [comment]
Is this still an issue? If so, please re-open,
