### ISSUE TITLE
!gcreate may be bugged

### ISSUE THREAD

**Issue by Alevard** [DiscordDungeons/Bugs#83]
No matter what Guild name I come up with it already exists. Even got frustrated and put in a random name that no one could possibly have like "Boy that Italian family at the other table sure is quiet" And the bot still says that name is taken lol.

So possibly borked? I dunno.

**Comment by Sven65** [comment]
Sounds borked, lemme see

**Comment by Sven65** [comment]
Right, I can't seem to find the issue. Mind coming into the official server and pinging me to reproduce the issue?

**Comment by Sven65** [comment]
Fixed.
