### ISSUE TITLE
Kept quest items

### ISSUE THREAD

**Issue by widlflame123456** [DiscordDungeons/Bugs#832]
After completing quest The land above kept piston quest item.

**To Reproduce**
1. Finish quest 
2.check inv
3.see error

**Expected behavior**
Quest npc takes items to fix ship

**Screenshots**
![4](https://user-images.githubusercontent.com/52178802/60387426-f3def280-9a70-11e9-86c8-fb9e7ab95bd5.PNG)
![5](https://user-images.githubusercontent.com/52178802/60387427-fe00f100-9a70-11e9-810d-0f6a94658437.PNG)

**Version**
14.0.2

Only the pistons remain. William takes the other supplies

**Comment by Willard21** [comment]
Duplicate of #582
