### ISSUE TITLE
Spelling error in items

### ISSUE THREAD

**Issue by widlflame123456** [DiscordDungeons/Bugs#833]
**Describe the bug**
whenever you search for an item you search for the singular term not plural. Ie: log instead of logs

**To Reproduce**
1. "#!item grape"
2. get error saying multiple items found
3. try "#!item grapes" instead

**Expected behavior**
"#!item grape" pulls up item script instead of the plural spelling "grapes"
**Screenshots**

![image](https://user-images.githubusercontent.com/52178802/60403517-697bb900-9b6c-11e9-8cdf-7db8bd0f3108.png)
*Version**
What is the current version at the time of creating this issue?
4.12.1
**Additional context**

**Comment by Sven65** [comment]
This is due to the name of the item being "grapes", both as a single item and as multiple.
