### ISSUE TITLE
User ID's look ups

### ISSUE THREAD

**Issue by Dragoneyr** [DiscordDungeons/Bugs#834]
**Description**
I do not seem to be able to find users on their user ID's anymore. What happens when you try #!stats user_ID is you're supposed to get the stats of the user in the request. But it will instead return your own stats. The same thing goes for #!inv, except that it will move to the page number of the user ID you've put in.

**To Reproduce**
1. You must have developer mode enabled.
2. Tap and hold or right click on a user, then scroll down until you see copy user ID. Click/tap that.
3. Go to any Discord channel or pm the Discord Dungeons bot himself.
4. Type #!stats or #!inv and paste in the user ID.

**Expected behavior**
This should return the stats or inventory of the person in the request. But it will instead return your own stats or inventory.

**Screenshots**
![Screenshot_20190707-123811_Discord](https://user-images.githubusercontent.com/52624311/60767420-41cea880-a0b8-11e9-9d9e-3075aaee8142.jpg)
![Screenshot_20190707-121500_Discord](https://user-images.githubusercontent.com/52624311/60767421-41cea880-a0b8-11e9-9aab-1d408c017998.jpg)

**Version**
4.12.1

**Additional context**
User doesn't need to be in the same channel as you to find their results.

**Comment by sk-555** [comment]
Can't reproduce for the `#!stats` command, seems to be working just fine for multiple different users.
<img width="782" alt="Screen Shot 2019-07-07 at 8 17 40 PM" src="https://user-images.githubusercontent.com/19984339/60768166-59c41d80-a0f4-11e9-8c68-453fd3a6d389.png">
<img width="619" alt="Screen Shot 2019-07-07 at 8 17 35 PM" src="https://user-images.githubusercontent.com/19984339/60768167-59c41d80-a0f4-11e9-9b61-1a773ccc2fe9.png">

+1 for the `#!inv`, though.

**Comment by Willard21** [comment]
584310956302008330 isn't a user ID. You probably copied a message ID on accident. `#!inv` has never supported ID lookups for other users, so it belongs as a feature request rather than a bug report.
