### ISSUE TITLE
#!party invite and #!party join not working

### ISSUE THREAD

**Issue by Spordra** [DiscordDungeons/Bugs#835]
When I do #!party create it works.

When I do #!party invite this error shows up

Whoops. An error occured. Please report this in the official server.
TypeError: Cannot read property 'current' of undefined
    at Party._invite (/home/mackan/RPGBot/src/Commands/Commands/Parties/Party.js:210:25)

If my friend does #!party join this error shows up

Whoops. An error occured. Please report this in the official server.
TypeError: Cannot read property 'current' of undefined
    at Party._join (/home/mackan/RPGBot/src/Commands/Commands/Parties/Party.js:327:25)

**Comment by Willard21** [comment]
Workaround: everyone in the party needs to have #!traveled first at some point in the game for it to work.
