### ISSUE TITLE
recipe command is broken

### ISSUE THREAD

**Issue by ImadeAcode** [DiscordDungeons/Bugs#839]
**Describe the bug**
```
The recipe command outputs this error message:
Whoops. An error occured. Please report this in the official server.
TypeError: Cannot read property 'name' of undefined
    at Execute.crafts.map.craft (/home/mackan/RPGBot/src/Commands/Commands/General/Recipe.js:93:35)
    at Array.map (<anonymous>)
    at Recipe.Execute (/home/mackan/RPGBot/src/Commands/Commands/General/Recipe.js:92:10)*To Reproduce**
```
1. Go to any channel drpg has access to
2. Request any recipe, e. g. `#!recipe String`
3. See error

**Expected behavior**

**Version**
4.12.1

**Comment by Willard21** [comment]
![image](https://user-images.githubusercontent.com/24826881/61909019-af6f3700-aef6-11e9-85b9-d8726e86c1dd.png)
I'm cornfused.

**Comment by widlflame123456** [comment]
Recipe commands work for me as well

**Comment by AlinAtAxual** [comment]
It does work now. Shadowfixed!

**Comment by Sven65** [comment]
I'll reopen it since the issue hasn't actually been fixed by us :)
