### ISSUE TITLE
Uset invsort: item type doesn't groop gemstones together

### ISSUE THREAD

**Issue by widlflame123456** [DiscordDungeons/Bugs#841]
**Describe the bug**
When you set your inventory to sort by item type sapphires don't get grouped with the rest of the gemstones.

**To Reproduce**
1. Set your inventory to sort by item type
2. Open inventory 
3. See error 
**Expected behavior**
Sapphires appear with the other gemstones

**Screenshots**
![20190726_105539](https://user-images.githubusercontent.com/52178802/61964245-6ae9a700-af9b-11e9-9e38-449297cbfb2f.jpg)
![20190726_105607](https://user-images.githubusercontent.com/52178802/61964266-750ba580-af9b-11e9-96dc-b9395f230819.jpg)

**Version**
Lime poodle
**Additional context**

**Comment by FelixArgyle** [comment]
That's because the type is "Dummy" for gemstones, gemstones aren't their own type of item.

**Comment by Sven65** [comment]
See above comment by @FelixArgyle. To request it as a feature, please do so at https://drpg.xyz/Ideas.
