### ISSUE TITLE
Pet xp glitch 2.0

### ISSUE THREAD

**Issue by Emdosis** [DiscordDungeons/Bugs#845]
**Description**
If your pet was dead during the previous battle (meaning: at the end of your last battle) then, if you one-shot the subsequent battle (with a live pet), the pet won't get its (designated amount of) xp; the player will get all of the xp instead.

**Steps to reproduce behavior:**
1. Make sure your pet is getting xp.
2. Let your pet die in battle.
3. Win battle (or leave battle) while having dead pet.
4. Heal pet and start a new battle.
5. If mob was defeated in one shot, go to step 6. 
If mob is still alive after initial strike go back to step 1 (this could take a while, pls don't get frustrated (；^ _ ^)).
6. Get all xp instead of sharing it with your pet.

**Expected behavior**
Pet gets xp it's supposed to get.

**Screenshots**
Here's one example:

![](https://cdn.discordapp.com/attachments/596759091028819968/610472975992487948/AMZ0bTwpVLLPAAAAAElFTkSuQmCC.png)

**Version**
4.12.2

**Comment by Sven65** [comment]
This is most likely due to how we handle the pet death tracker and that a pet won't get any xp from a fight if it previously died in that fight.

**Comment by Sven65** [comment]
It was because `#!pheal` didn't set the pet to y'know *not* be dead.
