### ISSUE TITLE
Pet Rock stuck at level 0 after reset

### ISSUE THREAD

**Issue by Aogamint** [DiscordDungeons/Bugs#846]
**Description**
As the title said, my Pet Rock stuck at level 0 after a reset. I was level 20-30 and have some early game pets, but until I heard Pet Rock is one of the best pet, I knew I have to reset (so I can also relocate my stats, so that's a win-win)

**Steps to reproduce (In my case)**
1. Reach like level 20-30
2. Catch some pets at that level (my previous pet is around level 24)
3. Reset
4. See Pet Rock at level 0

**Expected Behavior**
After reset (twice), I've seen my Pet Rock stuck on level 0 (even though I was putting 25% XP on him and he did get some XP, but it showed 2/0 XP and no progress).

**Screenshot**

First reset (after level 20+)

![ed764b80745a26ba4a212a8e854d3b6a](https://user-images.githubusercontent.com/54044008/62921185-4854ec00-bdeb-11e9-86de-ce2a8aa6206d.png)

Second reset (right after the previous reset)

![6b49262ce4ebebe06aee14f028e769cf](https://user-images.githubusercontent.com/54044008/62921178-45f29200-bdeb-11e9-86a0-b696da5b4064.png)

**Version** at the time
"DRPG Version 4.12.2"

**Additional Context**
I'm in my private discord server, so I don't really know is that effect anything on this one.

**Comment by Willard21** [comment]
What's your user ID?

**Comment by Aogamint** [comment]
299342357797535745

**Comment by Willard21** [comment]
"`Killed 0 enemies`"
Try killing a couple :eyes:

**Comment by Aogamint** [comment]
Alright, but it probably ends up like the previous reset. The 2/0 XP one.

**Comment by Aogamint** [comment]
Bug fixed. It probably just a visual glitch. Thanks for helping. 

![e8e3a898a855245bc59de8a5ae30ca38](https://user-images.githubusercontent.com/54044008/62922587-19d91000-bdef-11e9-8cb8-2f44b54c6a9e.png)

![eb35ac06786cf76351e674a9f3b2f300](https://user-images.githubusercontent.com/54044008/62922588-1ba2d380-bdef-11e9-8194-9e118700bcb3.png)
