### ISSUE TITLE
Blacksmith- DiscordAPIError: Unknown Message

### ISSUE THREAD

**Issue by Destroya1103** [DiscordDungeons/Bugs#847]
**Describe the bug**
After a failed attempt at inserting a gem socket into a Fishing rod, I tried once more.
After receiving the prompt: 
'+ Urist the Blacksmith - Which item do you want to put this socket on? (Page 1/1)
+ 1.) Fishing Rod
+ 2.) Small Dagger
!===[Type your selection in chat or 'c' to cancel]===!'

This error occurred.

>Whoops. An error occured. Please report this in the official server.
```js
DiscordAPIError: Unknown Message
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**
1. Go to Urist the Blacksmith
2a. Click on '+ 1 - Yes please. I need a gem socket added to my item.'
2b. Click on '+ 1.) Fishing Rod'
2c. Click on '+ 1 - Do it.'
3. See error 

**Expected behavior**
As I am unsure what exactly the error affected, this will be left alone. [N/A]

**Screenshots**
http://prntscr.com/owzb1t

'''

Screenshot - Image attached below.

**Version**
Q: What is the current version at the time of creating this issue?
A: I am unsure how to check the current version of this.

**Additional context**

![RPG Bug](https://user-images.githubusercontent.com/37131626/63639860-e7d57280-c666-11e9-97c5-458ae4bf8de7.png)

If this error resulted in the failed attempt, could the 5,000 Gold be returned?

**Comment by Willard21** [comment]
Nah, the error was thrown way before the fail, so it wouldn't have affected it. You just got unlucky. The error was in Discord.js, so I'm not sure how to fix it, but thanks for reporting it :+1:

**Comment by Destroya1103** [comment]
I figured that was the case. What does that bit of code pertain/relate to?

**Comment by Sven65** [comment]
It relates to Discord.js not being able to find message to remove the reactions from.

**Comment by Sven65** [comment]
Closing due to being stale. If issue still persists, re-open this.
