### ISSUE TITLE
Donate BUG 

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#851]
**Describe the bug**
DM Notification's of Item donations has a bug when you donate "all" to a user without typing all of the items name out.  EDIT: Just found out that it also happens when you use #!sell i.e #!sell even greater all

**To Reproduce**
1. Donate something without using its full name, i.e #!idonate @Felix Argyle even greater all
2. Ask the person who you tried to donate to check their dm, they will get a message saying something like 
[Thu, 19 Sep 2019 03:48:38 GMT] TurbiePants!#8352 (ID: 104420589497757696) donated 0 Even Greater Health Potion to you.
the message when the person donating an item still shows in chat that they donated an item to you but that message is false and it doesn't actually donate anything at all.
**Expected behavior**
Expect it to either donate the full amount if used all with not using the full name or a message saying please use the full item name to donate this item instead of processing like it's donated something.

**Screenshots**
![ASeJPp9](https://user-images.githubusercontent.com/12903523/65212391-e15adf00-dadc-11e9-9383-1878121c84fa.png)
![2u4ea2c](https://user-images.githubusercontent.com/12903523/65212392-e15adf00-dadc-11e9-9dca-902888319876.png)

**Version**
4.12.2

**Additional context**
_pls test more_

**Comment by Willard21** [comment]
The problem was the amount was set before the item search (since the amount is an optional parameter, it had to be checked first), which meant the searched name wasn't known when `all` was converted to a number, so only full item names worked. Pretty sure it's been this way forever, but opened a fix now.
