### ISSUE TITLE
Enchanted/upgraded items showing up on market search

### ISSUE THREAD

**Issue by Laysfamilysized** [DiscordDungeons/Bugs#852]
Items that can be enchanted or upgraded show up on market partial match list , when typing item name that can be enchanted/upgraded wrong or leaving out a bit.

To reproduce search for item that can be modified, and leave out a bit of the item name.

![image](https://user-images.githubusercontent.com/31356689/66272409-050a7d00-e872-11e9-89a4-29fc51be0010.png)
![image](https://user-images.githubusercontent.com/31356689/66272468-da6cf400-e872-11e9-9a54-658acf470b4a.png)

**Comment by Sven65** [comment]
This shouldn't happen.
