### ISSUE TITLE
Grammar: "Arrived to" should be "arrived at", or at least "travelled to"

### ISSUE THREAD

**Issue by QuackingPlums** [DiscordDungeons/Bugs#853]
**Describe the bug**
The only prepositions that can follow '_arrive_' are '_at_', '_in_', and '_on_'.

Issue #814 was closed because 'arrived to Primeval sounds better' - not to a native English speaker, it shouldn't. :P

If we are particularly attached to the preposition '_to_' then please consider changing it to "<player> _travelled to_ <location".  That would work. E.g.:
"…travelled to Primeval."
"…travelled to Tower of Eternity."
"…travelled to Mournstead."
"…travelled to Frostridge Shore."

**To Reproduce**
1. #!travel <somewhere>
2. Arrive

**Expected behavior**
Either "_arrived at_" or "_travelled to_"

**Version**
What is the current version at the time of creating this issue?
4.12.1

**Additional context**
Incorrect grammar is incorrect, however good it may sound or however often it is misused. ;)

**Comment by Sven65** [comment]
Alright. Seeing as this is the second time this has been reported, we'll have a look at what we can do.
