### ISSUE TITLE
Inaccessible Areas In Dungeons

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#854]
**Describe the bug**
Willard broke Dungeon map generations with that latest update

**To Reproduce**
Don't really need to fill this part in.
**Expected behavior**
Dungeons aren't meant to have a 1-3 tile type of room layouts, This was fixed previously by Mackan
**Screenshots**
https://cdn.discordapp.com/attachments/173016788274118656/635795132813148160/image0.png

**Version**
4.12.3
**Additional context**
rip dungeons

**Comment by Willard21** [comment]
Technically they weren't meant to have a 2 tile layout, but 3 tiles has always been possible and was never fixed. This is an easy fix though. Just have to increase the minimum distance by 1 to get back to preventing the 2 tile floors. I must have used the wrong number there.

**Comment by Willard21** [comment]
Will just redo the floor generation algorithm to remove walls that block off sections of the floor. Will also go ahead and fix the very not-random chest and spawn placement while I'm at it.
