### ISSUE TITLE
Can't ping the bot if it has a nickname

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#855]
**Describe the bug**
Giving the bot a nickname will stop pings from working since the ping format becomes `<@!170915625722576896>` instead of the normal `<@170915625722576896>`. I think Fallen tried to tell me that before the update but I didn't understand what he was saying lol.

**To Reproduce**
1. @SpookordRPG ping
2. Get no response

**Comment by PlayTheFallen** [comment]
`/<@!?(\d+)>` -> `[fullMatch, ...captures]` where captures includes mentioned user target (conditional requirement to check who was mentioned - bot or exchange target i.e. donate, idonate, battle, etc.)

**Comment by Willard21** [comment]
I already fixed it. Anyway, I was removing it from an array, so I couldn't use regex. I just used `max(indexof(string1), indexof(string2))`. Seemed easier than manually looping over the array to use regex.

**Comment by PlayTheFallen** [comment]
And that concludes to be more functional - as in literal functions being utilized in this new revision?

**Comment by Sven65** [comment]
Uh, we can just use the d.js function for it?

https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=isMemberMentioned

**Comment by Willard21** [comment]
We do use that, but that's only a boolean. It doesn't say whether the message is `@DiscordRPG ping` or `ping @DiscordRPG`, it just returns `true` for both. So I need the index of it to know where to remove it from the args array.
