### ISSUE TITLE
Infinite Talking

### ISSUE THREAD

**Issue by Takashi-22812** [DiscordDungeons/Bugs#856]
Talking to leviathan in sarilla, then one-shotting it leads to being stuck in the state of "you are already talking to someone"

**Comment by Sven65** [comment]
Does the problem persist if you wait with talkimg for a while?

**Comment by Willard21** [comment]
Other users that reported it have said that it does resolve itself (after the 70 second auto timeout I assume), but the conversation is still supposed to end immediately. It assumes every quest conversation ends with a plainDialog, but the battles don't. Can either show a dialogue when the battles starts (like "The Leviathan lunges at you" or whatever), or just throw in a `user.stopTalking()` for each one.
