### ISSUE TITLE
#!getrole 

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#857]
**Describe the bug**
Using #!getrole gives out the Donor role to non-donor users, it also disallows users to create guild roles because of this.

**To Reproduce**
1. use #!getrole
2. it will say "You now have the donator role, TacoLord"  using it again does not allow for a guild role to be created

**Expected behavior**
for it to add a new guild role if you are using #!getrole

**Version**
4.12.4 

**Additional context**
I told mackan to make a new cmd for creating guild roles so the issue does not occur and have #!getrole give existing roles that the user should have.

**Comment by Willard21** [comment]
> Using #!getrole gives out the Donor role to non-donor users

According to the API, Taco is a donor. If his userData is wrong then that's a different issue unrelated to getrole, but the getrole command was correct to give him the role.
![image](https://user-images.githubusercontent.com/24826881/68095377-80118400-fe6e-11e9-9ebd-4b92b9493d09.png)

The guild role problem is from Mackan returning early if any roles were assigned, which is the case for donors. There's 2 possible easy (< 30 seconds) solutions.
* 1 is to not return if a guild role wasn't assigned, in which case it might show an error message such as "only the guild owner can get a role," which might confuse a donor that didn't want the guild role anyway, but no harm done either way.
* The other would be to not reassign a role the user already has, in which case running the command once would assign the donor role, then running it a second time would create the guild role.

**Comment by Sven65** [comment]
The API data is correct, so the command's doing what it's told to do. The way to fix this is to make the command able to assign multiple roles, and able to create the guild role if it doesn't exist.
