### ISSUE TITLE
Tax not refunded on trade cancel/stop

### ISSUE THREAD

**Issue by JHE-Dev** [DiscordDungeons/Bugs#861]
When stopping a GMsell trade (not sure of buying) the tax is not being refunded.

**To Reproduce**

1. Check inventory "Gold"
2. Sell an item on the general(?) market with the #!gmsell command. [for example 1 butterfly_net for 20.000 Gold.]
3. Pay the "tax". [ 2.000 Gold in this case]
4. Check inventory "Gold". [correctly reduced by 2.000 Gold in this case]
5. Stop the sale of the item with the #!GMstop command. 
6. Check inventory "Gold". [the item is correctly returned, but the "tax" is not. see screenshot]

**Expected behavior**

When a fee is requested for trading an item, that fee is paid when the item is actually traded. (like VAT is being paid only when you pay for the item, not when you pick it of the shelf)

**Screenshots**

![2019-11-07 18_17_38-@DiscordRPG - Discord](https://user-images.githubusercontent.com/57498967/68412631-dba08200-018c-11ea-9ed4-a3698a4b9ce2.png)

**Version**
What is the current version at the time of creating this issue?

ehh, where can I find this? (I'm a newb)

**Additional context**

Willard21_2 said it was alright to post as a bug :)
_PS: edited the screenshot to hide some unnecessary inventory chat and the exact amounts of the items (not that it matters much since I'm just starting out)_

**Comment by PlayTheFallen** [comment]
[REF] This is version 4.12.4 named Copper Pizza.

**Comment by Willard21** [comment]
You can check version with `#!debug`, but in all honesty it doesn't help keep track of anything. There's only 1 version of the bot, so nobody is going to file a bug report for an older version. Even if we fix a bug and forget to close the issue, then look at the old bug later, we'd still just have to rely on memory to remember if we fixed it or not lol.

**Comment by Sven65** [comment]
It does help us keep track. Every release of the bot, i.e. new version comes with a changelog which includes the bugs we've fixed.

**Comment by Sven65** [comment]
Actually disregard that, I read the report wrong. We'll look at it.

**Comment by Willard21** [comment]
I mean, it doesn't help *me* keep track of anything when fixing bugs. The changelog is useful for reference, but I've never needed to know what version of the game a bug was reported in. Guess I shouldn't assume you don't use it for anything tho lol
