### ISSUE TITLE
Not all achievements are granted at the correct time

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#862]
**Describe the bug**
Some achievements require performing an action that doesn't trigger the achievement, so instead, the achievement is granted later, when an unrelated command is used

**To Reproduce**
1. #!assign defense 800
2. Don't get `Untouchable` achievement
3. #!donate 141610251299454976 1
4. Get `Untouchable` achievement

**Expected behavior**
It should grant the achievement immediately after meeting the requirements (in the #!assign command in this case, not sure if there's other achievements that do this)

**Comment by Sven65** [comment]
I believe I've got this fixed in the `bug/dd-862` branch of RPGBot, but I can't test it, as my rabbitMQ won't connect properly.

**Comment by Sven65** [comment]
Stale.
