### ISSUE TITLE
Custom guild icon

### ISSUE THREAD

**Issue by TacoLord321** [DiscordDungeons/Bugs#863]
**Describe the bug**
Gaudit and gmembers doesn't display custom icon. Displays the icon set before custom icon was bought

**To Reproduce**
1. Set a guild icon, buy custom icon, set custom icon that works doing #!guild, doing gmembers and gaudit displays old icon

**Expected behavior**
Expected gaudit and gmembers to display the correct icon or no icon at all

**Version**
Iron taco I think

Edited 2020-12-13 by @Sven65, as it refers to guild icons and not guild tags.

**Comment by Sven65** [comment]
Sorry for taking a year to respond to this issue.


As you mention that it happens to gmembers **and** gaudit, I'm more curious about the first one, since `#!gaudit` shows intended behavior.

I'll look at the issue and see if I can reproduce it.

**Comment by Sven65** [comment]
I'm not quite following what you mean by a custom tag means the icon?

**Comment by Sven65** [comment]
So. I can't make it display the custom icon in gaudit or gmembers, as the custom icon is an image URL, and Discord doesn't let me display images in a good way unless it's in an embed, as such, this issue isn't fixable.
