### ISSUE TITLE
DRPG Playing Status Goes Away

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#864]
**Describe the bug**
When the bot is first launched, it says `Playing Type #!stats to start your adventure!`, then eventually that status goes away and is left with nothing.

**To Reproduce**
1. Watch the bot for a day or 2

**Expected behavior**
It should keep a Playing status forever

**Screenshots**
![image](https://user-images.githubusercontent.com/24826881/68721131-0a489f00-0577-11ea-8a3b-9e25279bdabc.png)
![image](https://user-images.githubusercontent.com/24826881/68721147-16346100-0577-11ea-9c00-d06354a8b693.png)

**Comment by PlayTheFallen** [comment]
Status timeout? Also possible that Discord's new custom status effects this, but remains unlikely.

**Comment by Sven65** [comment]
I'll hijack this to say that the status doesn't get set since d.js update, because we need to change `game` to `activity` in `setPresence`
