### ISSUE TITLE
New Discord update breaks dungeon formatting

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#865]
**Describe the bug**
If there's more than 1 space in a row in a code block, all but 1 is removed. This breaks text alignment on everything, but it makes dungeons especially bad.

**To Reproduce**
1. Use any command that relies on multiple spaces to align text.

**Screenshots**
Before update:
![image](https://user-images.githubusercontent.com/24826881/68766636-d73cf480-05e4-11ea-9e41-7ec3733dce06.png)
After update:
![image](https://user-images.githubusercontent.com/24826881/68766682-eae85b00-05e4-11ea-87d5-a330c40d371c.png)

**Additional context**
This appears to only affect OS X and Linux versions of Discord (Windows users haven't commented on it). Replacing the "empty" tile with a zero-width-space on each side of a normal space appears to fix the issue.

I know this isn't a DRPG bug, but since it *can* be fixed on our end, we should fix it.

**Comment by sk-555** [comment]
+1 and cool fix idea, just wanted to add this video as a further demonstration of it in effect -
[Video](https://www.youtube.com/watch?v=77phY92c2x8)
[Source: OS X]

**Comment by Willard21** [comment]
Discord seems to have fixed the problem on their end (thank gawd it was actually a bug).
