### ISSUE TITLE
Gset image throws errors sometimes

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#876]
**Describe the bug**
```js
TypeError: Cannot read property 'url' of undefined
    at Gset._setImage (/home/mackan/RPGBot/src/Commands/Commands/Guild/Gset.js:601:28)
```

**To Reproduce**
Not sure. Might be the first time you use the command or something.

**Screenshots**
![image](https://user-images.githubusercontent.com/24826881/69432956-51196000-0d00-11ea-8664-8861c1e0f93c.png)

**Additional context**
This was from last month, so before the most recent update.

**Comment by Sven65** [comment]
This is getting fixed in the next release

**Comment by Sven65** [comment]
Unable to reproduce.
