### ISSUE TITLE
Party travel

### ISSUE THREAD

**Issue by TacoLord321** [DiscordDungeons/Bugs#877]
**Describe the bug**
Attempting to travel while partying displays error message

**To Reproduce**
1. Join/create party
2. Do #!travel <name>
3. Get error message saying party class undefined

**Expected behavior**
Whole party travels to the location
Or message saying can't travel while in party

**Screenshots**
![unknown-1](https://user-images.githubusercontent.com/48126615/69470842-5067e480-0d67-11ea-902c-db57fb721064.png)

**Comment by Willard21** [comment]
Smh Snazzah
