### ISSUE TITLE
Stats display error 

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#878]
**Describe the bug**
The display uset seems to have been changed during the latest updates that have occurred, this follows to whatever your display is set to using `#!stats` on other users will show that output to your display settings, this seems to cause a bug with new users on having their display as `null`

**To Reproduce**
1. Make new account then do `#!stats`
2. See error appear.
|
1. Look at old times you do `#!stats` on users and you will see that the output would be whatever that user has set and not your own.

**Expected behavior**
Expect that there be no errors for new users.
Not sure if Mackan wants so it shows your display for seeing other users stats if that is the case then just expect what I said above.

**Screenshots**
![9b8oUGJ](https://user-images.githubusercontent.com/12903523/69623339-0a23c580-1086-11ea-96a4-7b84a3c80435.png)
is where the error is at^ 

![6JvoosC](https://user-images.githubusercontent.com/12903523/69623311-fc6e4000-1085-11ea-90d4-a3050d3a0845.png)
Me viewing another user's stats before the latest updates, I always use display 2.

**Error Message**
`TypeError: Cannot read property 'display' of null
    at Stats._sendStats (/home/mackan/RPGBot/src/Commands/Commands/User/Stats.js:108:24)`

**Version**
4.13.1

**Comment by Willard21** [comment]
Using your own display settings when you use the command on other people was intentional. Fix for the error is pending approval now.
