### ISSUE TITLE
#!gset shows the wrong icon for flags

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#879]
**Describe the bug**
If your guild icon is 2 characters long, like 🇺🇸 then #!gset will show the icon for the first half of it, which is 🇺 here.

**To Reproduce**
1. #!gset icon 🇺🇸
2. #!gset

**Expected behavior**
It should show 🇺🇸.

**Comment by Sven65** [comment]
This might be fixable by storing the actual emoji instead of the HTML encoded version in the database.

**Comment by Willard21** [comment]
Probably, but the bug is mostly just with the #!gset display. I think flags work fine as icons in other commands.

**Comment by Sven65** [comment]
Aye, I was mainly thinking of just using the emojis/emoji codes directly, as rethinkDB supports UTF16 in strings, and it'd be a way to get rid of the `entities` library dependency.

**Comment by Sven65** [comment]
What do you think, @Willard21? And how about you, @sudojunior?

**Comment by sudojunior** [comment]
It seems reasonable, the main concern I have is how you'd identify the primary keys and how often you'd be running queries on that.

**Comment by Sven65** [comment]
What do you mean by the primary keys? They're UUID's for guilds.

**Comment by sudojunior** [comment]
Ah right, I was thinking more about how you'd identify the emojis themselves or store them.

**Comment by Sven65** [comment]
Oh alright. I'm thinking of either using their actual emoji codes, like "🙂", or their Discord name, such as `:smile:`, but I'm not sure which would be the best, or the easiest.

**Comment by Sven65** [comment]
After looking at it, the issue is due to the way we parse the icon from the DB, and it was only built for a single code point, and not two, which explains the flags, being that they're two codepoints.

I've changed it to decode with entities as it was easier, and it works again.
