### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by banana-cream-Pi** [DiscordDungeons/Bugs#880]
In the description of Item Claws#20(Wolferine wannabe? Here you go.), Wolverine is misspelled Wolferine. It should be, "Wolverine wannabe? Here you go". It's not technically a bug but it is a mistake. Best wishes ~ BCPI

**Comment by Willard21** [comment]
Only Mackan can correct item typos. So just ping him not the whole Dev team >.>

**Comment by banana-cream-Pi** [comment]
Sorry, I didn't know. I figured the developers would be the ones fixing things. Sorry again.

**Comment by Willard21** [comment]
Smh thinking developers fix things. That's just silly.

**Comment by Sven65** [comment]
Sorry for taking a year to respond, you've done right by posting it here, I'll be fixing it with the next release.

**Comment by banana-cream-Pi** [comment]
Oh my gosh, it's you! Wow Thanks for taking the time to respond. Sick game
btw.

**Comment by Sven65** [comment]
Yeah, it's me, I should've responded a year ago, but y'know, life happens :P

**Comment by banana-cream-Pi** [comment]
Cool, it's fine thanks for getting around to it.

**Comment by tklaxbro** [comment]
Surprise! I am here also.

**Comment by banana-cream-Pi** [comment]
wow, neato
