### ISSUE TITLE
Advent bug (still occurs with not resetting for next year)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#881]
**Describe the bug**
Your previous Advent from last year does not get reset, please make sure this does not happen next year too (you said it was fixed last year)
**To Reproduce**
1. Get a person that done advent last year and have them to do `#!advent
2. You will see that it says "You already got your advent for today"

**Expected behavior**
Expect that this does not occur and resets your advent ready for next year.
**Screenshots**
![8RR5KuE](https://user-images.githubusercontent.com/12903523/69907524-f5468980-1419-11ea-9d07-9cb45b525ad4.png)

**Version**
4.13.1

**Additional context**
P.s. I got scammed by this ;-; pls give me an advent

Actually get the issue fixed this time, thank!

**Comment by Sven65** [comment]
We reset this manually.
