### ISSUE TITLE
#!travel bug

### ISSUE THREAD

**Issue by Pondering73** [DiscordDungeons/Bugs#885]
#!travel brings up an error. Refer to screenshot.

![Screenshot_20191201-131724_Discord](https://user-images.githubusercontent.com/58401297/69919252-934d4a80-1440-11ea-814e-5540171964bd.jpg)

**Comment by Willard21** [comment]
Duplicate of #877

**Comment by Pondering73** [comment]
Is it the same? I'm not in a party

**Comment by Willard21** [comment]
Yeah. You can see it's the same error message on both. Do `#!party` to fix it if you're not actually in a party.
