### ISSUE TITLE
Tasks [decline / re-roll]

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#886]
**Describe the bug**
There's an error with tasks, whilst talking to `Alex` you are actually meant to Decline an offer, there is a bug that bypasses so you don't have to use the command `#!task decline`.
It seems like a small percentage of users actually have to decline an offer to "re-roll" each time.

Users would prefer that you don't have to decline as it just adds another few extra seconds ontop of `#!talk alex` each time, best to just remove that command and fix so all users can just re-roll by talking to the NPC.

**To Reproduce**
1. Find a user that can re-talk to alex and get a new offer without using `#!task decline` _i can re-roll by just talking_
Best to also find a user that has to use `#!task decline` to re-roll each time 
User: FFFyre#4083 (109195818711396352) is one that has this experience
2. Have both use `#!talk alex` and then `#!talk alex` again

**Expected behavior**
That you'd have to `#!task decline` before talking to alex again for a new task
As mentioned earlier,
"Users would prefer that you don't have to decline as it just adds another few extra seconds ontop of `#!talk alex` each time, best to just remove that command and fix so all users can just re-roll by talking to the NPC." 
that would be much better for people.

**Version**
What is the current version at the time of creating this issue?
4.13.1

**Comment by Willard21** [comment]
~~I'm unmotivated tell me what causes this~~

**Comment by FelixArgyle** [comment]
> ~I'm unmotivated tell me what causes this~

I wouldn't know what the cause would be, likely something with user data or something wrong with checking of users asking for a task, that's my guesses.
It happens to a small number of people as I did say so really hard to find the route of the cause as you'd need a few users to come and show you it.

**Comment by Willard21** [comment]
Well reading the code makes it look like it should only ever make you decline it if you've never started a task before.
