### ISSUE TITLE
Location command doesn't work in Aeston Mill

### ISSUE THREAD

**Issue by ItMayBeMe** [DiscordDungeons/Bugs#898]
**Describe the bug**
The location command doesn't work in Aeston Mill, also, we can't talk to the NPC that should be here according to the map: Leal

**To Reproduce**
1. Go to 'Aeston Mill'
2. Enter the command '#!location'
4. The bot doesn't respond

**Expected behavior**
The bot should answer to the command.

**Version**
4.14.0

**Comment by Sven65** [comment]
Fixed
