### ISSUE TITLE
Caeli Altar Spacing

### ISSUE THREAD

**Issue by turbiepants** [DiscordDungeons/Bugs#899]
**Describe the bug**
Caeli Altar doesn't have a spacing inbetween their name.

**To Reproduce**
1. #!travel caeli altar
2. it says unavailable location
3. Then do #!travel caelialtar
4. You're able to

**Expected behavior**
Expecting to work with a space inbetween caeli and altar.

**Screenshots**
![caeli1](https://user-images.githubusercontent.com/43326333/71544404-069f9900-29ba-11ea-9c92-c083902d3c66.png)
![caeli2](https://user-images.githubusercontent.com/43326333/71544406-099a8980-29ba-11ea-93a6-cc486f850bb1.png)

**Version**
4.14.0

**Additional context**
-

**Comment by Sven65** [comment]
Fixed
