### ISSUE TITLE
"Started Aeston First Firework" shown twice while traveling.

### ISSUE THREAD

**Issue by ItMayBeMe** [DiscordDungeons/Bugs#900]
**Describe the bug**
When traveling from Silverkeep to Caeli Farm, the bot displays "Started Aestons First Firework" twice as a requirement.

**To Reproduce**
1. Go to 'Silverkeep'
2. Travel to Caeli Farm '#!travel Caeli Farm'
3. Observe the requirements from the bot response.

**Expected behavior**
The bot should show the requirement only once.

**Bot output**

```
Silverkeep ➡ Mournstead ➡ Rivermouth ➡ Frostridge Shore ➡ Aeston ➡ Aeston Outpost ➡ Firebend Keep ➡ Amplewood Island ➡ Caeli City ➡ Caeli Farm

Requirements:
Quests
======
✅ Started Aestons First Firework
✅ Started Aestons First Firework
Travel Expenses
===============
✅ Boat: 1000 Gold
✅ Boat: 1500 Gold
✅ Boat: 5000 Gold
✅ Level: 125
Time: 14 minutes and 54 seconds


Would you like to proceed?
```

**Version**
4.14.0

**Comment by Willard21** [comment]
I'm guessing 2 locations along the route have the quest requirement. But yeah should only appear once.

**Comment by Willard21** [comment]
Can't reproduce. Mackan may have fixed it during all his hotfixes right after this update. Reopen or comment if this is still a thing.
