### ISSUE TITLE
cannot create party in new location

### ISSUE THREAD

**Issue by TacoLord321** [DiscordDungeons/Bugs#902]
**Describe the bug**
unable to #!party create in new locations

**To Reproduce**
1. Go to Aeston
2. do #!party create 
3. See error

**Expected behavior**
to have a party created 

**Screenshots**
![Screenshot_20191228-134457~2](https://user-images.githubusercontent.com/48126615/71548195-c4099c80-2978-11ea-9caf-faf4c443696e.png)

**Version**
Lime Duck

**Additional context**
parties work fine in old locations

**Comment by Willard21** [comment]
Fixed in next update (I made an oopsy on the normal documentation)
