### ISSUE TITLE
Unknown location listed in Caeli City

### ISSUE THREAD

**Issue by ItMayBeMe** [DiscordDungeons/Bugs#903]
**Describe the bug**
Doing a #!location in Caeli City lists a location with name ??? and reachable in ???s.

**To Reproduce**
1. Go to 'Caeli City'
2. Enter the command '#!location'
3. Observe the weird unknown location.

**Expected behavior**
Either the location shouldn't be listed, or if it exists, its real name should be shown.

**Version**
4.14.0

**Comment by PlayTheFallen** [comment]
Either this has been fixed already, and I've not been made aware of this or this is something completely different.

![](https://did-you-get.ratelimited.today/9mpXgEZ.png)

**Comment by turbiepants** [comment]
![gix](https://user-images.githubusercontent.com/43326333/71557881-42ecfb00-2a87-11ea-8d83-37829e54e15d.png)

**Comment by Sven65** [comment]
Can't reproduce, so probably fixed.

**Comment by Sven65** [comment]
Apparently, it's not fixed.

**Comment by Sven65** [comment]
The issue's fixed now. The `???` part was because we were adding a malformed location ID to the connections, as for having two connections to amplewood island, that was because we were pushing the quest connection twice.
