### ISSUE TITLE
travel error

### ISSUE THREAD

**Issue by TacoLord321** [DiscordDungeons/Bugs#904]
**Describe the bug**
returning user cannot travel

**To Reproduce**
1. do #!travel 
2. get error message

**Expected behavior**
user who hasn't completed quest be able to travel 

**Screenshots**
![Screenshot_20191229-002436](https://user-images.githubusercontent.com/48126615/71552831-04493900-29d2-11ea-8fab-52c5d29cd4bd.png)

![Screenshot_20191229-002453](https://user-images.githubusercontent.com/48126615/71552832-0ad7b080-29d2-11ea-804d-c2884a53641a.png)

![Screenshot_20191229-002523](https://user-images.githubusercontent.com/48126615/71552836-11662800-29d2-11ea-8aa2-221941bc73b4.png)

**Version**
lemon goose or lime duck

**Additional context**

**Comment by Willard21** [comment]
I don't think this is a new error. But it's caused by the bot only checking specific falsey values instead of all falsey values, since drpg has historically been extremely inconsistent in what data is being stored.
