### ISSUE TITLE
The player's username is not updated in real time

### ISSUE THREAD

**Issue by Ciborn** [DiscordDungeons/Bugs#906]
**Describe the bug**
When using DiscordRPG, commands such as `#!stats` and `#!adv` that can show the player's username at the top actually shows the old username if the player's username has been updated recently. This bug causes the automatic nickname update to work incorrectly (see screenshot below). *This also causes Aldebaran to not work correctly using the health monitor. The API also does not return the player's updated username.*

**To Reproduce**
1. Update your username
2. Use `#!stats` or `#!adv`
3. Look at the username at the top of the bot's message (it is not updated)

**Expected behavior**
The username shown at the top of the bot's message is supposed to be the updated player's username.

**Screenshots**
![image](https://user-images.githubusercontent.com/17595049/72188210-0790eb80-33fa-11ea-9013-8dbc6f2eec6d.png)

**Version**
4.14.1 Gold Duck

**Comment by Sven65** [comment]
This might be an issue with Discord.js itself not updating the cached user in time.

**Comment by Willard21** [comment]
Nah, I'm pretty sure it's an issue with us overriding the cached username in a few commands. It's probably a mistake.
