### ISSUE TITLE
Mine Boost Rings Don't Work

### ISSUE THREAD

**Issue by sk-555** [DiscordDungeons/Bugs#907]
**Describe the bug**
Mine Boost rings do not multiply the Mine Boost attribute by the specified amount, unlike other rings of the same nature.

**To Reproduce**
1. Equip a Mine Boost ring.
2. Use `#!mine`, and observe no changes / bonuses compared to before the ring was equipped.

**Expected behavior**
Mine Boost attribute to be multiplied by the ring's multiplier, as with most other rings.

**Screenshots**
<img width="266" alt="mineboost 0" src="https://user-images.githubusercontent.com/19984339/72200437-8cc0e280-3484-11ea-93fb-3553d2d20fd8.png">
<img width="630" alt="mineboost 1" src="https://user-images.githubusercontent.com/19984339/72200439-93e7f080-3484-11ea-9c4c-4f2164c5c238.png">

**Version**
[4.14.1 / Gold Duck](https://blog.discorddungeons.me/changelog-of-4-14-1/)

**Additional context**
Shoutout to Willard

**Comment by Sven65** [comment]
Clarification; Rings don't actually affect the attrib points themselves
