### ISSUE TITLE
#!plant info - Error when you don't have any seeds planted at all

### ISSUE THREAD

**Issue by zayonarts** [DiscordDungeons/Bugs#909]
**Describe the bug**
I used #!plant info, without having a seed planted and showed up me an error text.

**To Reproduce**
1. Go to 'any channel where you can use DRPG commands and use #!plant info, without having any seeds planted at all on any fields you own'

**Expected behavior**
I guess there should be a message like "You do have this fields (and next to the fields owned to show that you have no seeds planted)

**Screenshots**
![image](https://user-images.githubusercontent.com/17950489/72794262-65b49e80-3c44-11ea-828b-e8b565f5e622.png)

**Version**
4.14.1
![image](https://user-images.githubusercontent.com/17950489/72794595-ef646c00-3c44-11ea-948b-eb5670b7b12c.png)

**Additional context**
-

**Comment by Willard21** [comment]
Ah, I think that should only happen if you've bought a field and never planted a seed before. I'm sure I tested just with no seeds planted, but I didn't reset to test. Thanks for reporting :+1:

**Comment by zayonarts** [comment]
Oh, good to know, every time I see something that gives a weird error or something, what I think is not gonna happen soon, for sure I will report it.

**Comment by luckeygamer13** [comment]
I have this same issue.
![Capture](https://user-images.githubusercontent.com/28549098/79473113-aec18800-7fd2-11ea-9c6a-92735327850f.PNG)
I didn't plant anything and used #!plant info
