### ISSUE TITLE
Adventure Bug on private channels

### ISSUE THREAD

**Issue by MrNeonRed** [DiscordDungeons/Bugs#913]
**Describe the bug**

When typing #!adventure it gives me an error.

**To Reproduce**

1. Go to 'channel with only access able on specific role '
2. Type #!adventure'
3. Get error
4. profit?

**Expected behavior**
Literally can't adventure on private channel.

**Screenshots**

![v](https://user-images.githubusercontent.com/22456268/74273905-7cb15280-4d11-11ea-9da5-9ef76be3b978.png)

**Version**
What is the current version at the time of creating this issue?
4.14.2

**Additional context**
None.

**Comment by Willard21** [comment]
It's because you don't have a pet. The easiest workaround is to #!reset since I'm willing to bet you made your account years ago and are probably level 1. We'll get it fixed though.

**Comment by MrNeonRed** [comment]
4 years is not that long
is it?
and i literally just started.

**Comment by Willard21** [comment]
Nah it's still a bug that needs to be fixed. You definitely made your account a few years ago. Probably just forgot about it.

**Comment by MrNeonRed** [comment]
Probably, closing yet again.

**Comment by Willard21** [comment]
No u.

**Comment by MrNeonRed** [comment]
It's done you literally don't need to open this issue
STAHP

**Comment by Willard21** [comment]
It's done for *you* but this is a bug tracker, not a support desk. It's not done until the bug is gone from the bot.

**Comment by MrNeonRed** [comment]
It is done for _you_ as well, since you don't need to keep this issue open to keep track of the bug.

**Comment by Willard21** [comment]
I actually do though, because closed bug reports mean the bug is gone. Open bug reports mean the bug is still in the bot.

**Comment by MrNeonRed** [comment]
Alright.
