### ISSUE TITLE
#!location bug

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#915]
**Describe the bug**
Doing #!location at the location Amplewood Island (with the quest completed) 

**To Reproduce**
1. Go to  Amplewood Island
2. Type #!location and you see the error

**Expected behavior**
No error duh
**Screenshots**
![5dupGNU](https://user-images.githubusercontent.com/12903523/75285662-613e5f80-585a-11ea-833a-40dfe3c906d8.png)

**Version**
4.14.3

**Additional context**
this is a mackan bug wowe!

**Comment by Willard21** [comment]
Duplicate of #905
