### ISSUE TITLE
[Minor] Grammar: Ring of XP

### ISSUE THREAD

**Issue by sk-555** [DiscordDungeons/Bugs#916]
**Describe the bug**
When examining the `Ring of XP#31` item, its description contains a minor grammatical error.

**To Reproduce**
1. Perform the `#!item Ring of XP` command to examine the Ring of XP.
2. View description.

**Expected behavior**
Expected description:
> Gives the user an xp boost.

**Screenshots**
Actual description:
> Gives the user a xp boost
<img width="421" alt="Screen Shot 2020-02-26 at 7 01 35 PM" src="https://user-images.githubusercontent.com/19984339/75339283-2c1e2580-58cb-11ea-9c87-06c1b724b804.png">

**Version**
4.14.3 / [Orange Duck](https://blog.discorddungeons.me/changelog-version-4-14-3/)

**Additional context**
Furthermore, the description is missing a period (`.`) at the end of the sentence. I'm not sure what to think of this, but considering both of the other public rings have this period at the end of their descriptions, I feel as though it should be added, to retain consistency. This is reflected in the _Expected description_.
<img width="406" alt="Screen Shot 2020-02-26 at 7 05 35 PM" src="https://user-images.githubusercontent.com/19984339/75339388-638cd200-58cb-11ea-9ced-444808e4ad83.png">

Not a big or important bug report.

**Comment by Willard21** [comment]
Fixed.
