### ISSUE TITLE
Leveling

### ISSUE THREAD

**Issue by VanillaFalcon** [DiscordDungeons/Bugs#918]
**
![46E779D1-AE78-4E98-8514-5653B0E3A718](https://user-images.githubusercontent.com/25309382/75650529-b9d77900-5c1b-11ea-8b63-badf69740cbb.png)
Describe the bug**
I was told I leveled to 5, tried to use the catch commands and it said I had to be level 5.

**Comment by Saederup92** [comment]
Try doing `#!stats` to see your level. Mee6 levels are unrelated to your level on the DRPG bot :P

**Comment by VanillaFalcon** [comment]
Ty
