### ISSUE TITLE
Cannot access rpg bot at all in any server

### ISSUE THREAD

**Issue by plasmium1** [DiscordDungeons/Bugs#924]
The bot simply does not respond to my commands at all, the header is correct, and other bots react perfectly fine, yet this one bot seems unresponsive, and other people have also seen the phenomenon. Is there a way to rectify this issue?

**Comment by Willard21** [comment]
You're either 
1.) Banned
2.) Using the wrong prefix everywhere (try `DiscordRPG ping`)
or
3.) The bot is dead
Either way I seriously doubt it's a bug.
