### ISSUE TITLE
Leveled up without the Heal and Attribute Points

### ISSUE THREAD

**Issue by jajamski** [DiscordDungeons/Bugs#925]
**Describe the bug**
So i just leveled up to 129 without any of the level up announcement

**Screenshots**
This is when it happened

![Untitled](https://user-images.githubusercontent.com/63182346/78468613-cdf32680-7743-11ea-9a8e-37535bdf31dd.png)

This also my stat after leveled up with no heal and points

![Untitled2](https://user-images.githubusercontent.com/63182346/78468627-e5321400-7743-11ea-8545-17db57f2c13e.png)

**Version**
Version 4.14.7

**Additional context**
Here is my User ID: jjm#3863 (292684449878114304) pls give me my points ;-;

**Comment by Willard21** [comment]
![image](https://user-images.githubusercontent.com/24826881/78469783-c868f280-76e9-11ea-8880-e36acf2bbabc.png)

**Comment by Willard21** [comment]
The bug was that you leveled up twice at once on your previous level. You probably got a double message on the turn you leveled up, which leveled you up twice. No clue what's causing *that*, but either way this bug doesn't exist.

**Comment by jajamski** [comment]
![Untitled3](https://user-images.githubusercontent.com/63182346/78469843-e0bf2880-774e-11ea-80a7-016f55d91ab1.png)
Yeah, just scrolled far up and this actually happend and i didn't notice it at first. Anyway thanks for the respond Willard^^
