### ISSUE TITLE
Leptocite Shears requirements increase when you add gems

### ISSUE THREAD

**Issue by inthere29** [DiscordDungeons/Bugs#933]
<img width="403" alt="lept1" src="https://user-images.githubusercontent.com/62954731/80417274-660ca780-88cd-11ea-9735-3d093af529e2.png">
<img width="401" alt="lept2" src="https://user-images.githubusercontent.com/62954731/80417284-6a38c500-88cd-11ea-97f2-56c4cd208dae.png">

**Describe the bug**
Leptocite Shears when you buy them, require foraging skill level 30. When you add gems, they require level 40. Screenshots attached.

**Comment by Willard21** [comment]
It's only on 2SJ and 2SJJ (since those items need to be updated), but yeah.

**Comment by Sven65** [comment]
Please follow the full issue template next time you create an issue.
What version is the bug in?

**Comment by inthere29** [comment]
4.14.3

**Comment by Sven65** [comment]
thank you :)

**Comment by Sven65** [comment]
Should be fixed now.

**Comment by inthere29** [comment]
Nope still broken, need me to send a screenshot?

**Comment by Sven65** [comment]
Please do.

**Comment by Sven65** [comment]
Right! *there* we go, now it should actually be fixed.
