### ISSUE TITLE
#!uset shows the wrong default value for reactPaging

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#934]
**Describe the bug**
When doing #!uset by itself, the default value shown for reactPaging is 2, when in fact it's enabled by default, which is setting 1.

**To Reproduce**
1. #!reset YES
2. #!uset
3. Check pagination
4. See inconsistency

**Expected behavior**
It should show 1 as the default.

**Comment by Sven65** [comment]
Please follow the full issue template next time you create an issue.
What version is the bug in?

**Comment by Willard21** [comment]
All versions between the one where Tyler added it, and the current one.
