### ISSUE TITLE
Query time out

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#935]
**Describe the bug**
Not sure what it's on exactly, but seems like there's a ton of query time out bug on things, the thing I've found it on mostly is upgrades + enchants etc

-- Update
It seems like even tho you're finished with the stuff (upgrading or enchanting) the message thinks it still is active so times out regardless.
**To Reproduce**
1. Go and upgrade / enchant weapon and for every message block it instantly pushes the "query timed out" message whilst the message is actually still active

**Expected behavior**
To not instantly push a query time out message, and only push it when the actual message times out
**Screenshots**
![bug](http://felix-argyle.is-into.men/63Pm2ou.png)

**Version**
4.15.0 
**Additional context**
likely to do with the update with d.js

**Comment by Sven65** [comment]
Gonna fix it by ending options that are set with something other than the reason `time`, and add a check to the timeout messages.

**Comment by Sven65** [comment]
Actually, do we even need the query timeout messages, @sudojunior, @Willard21?

**Comment by sudojunior** [comment]
The timeout messages? Could remove them.
As for the implications on the code or environment, not so sure.

What version of `discord.js` is the bot on? *Probably somewhere around 12.3.x*

**Comment by Sven65** [comment]
Yeah, the ones that are sent in the chat. For D.js, `^12.4.1`

**Comment by Sven65** [comment]
I've added a number (`[n]`) to the different timeout messages which should make it easier to figure out where they're coming from.

**Comment by Sven65** [comment]
Stale.
