### ISSUE TITLE
#!adv ping @everyone

### ISSUE THREAD

**Issue by QHpix** [DiscordDungeons/Bugs#936]
**Describe the bug**
Pinging @everyone by escaping adventure

**To Reproduce**
1. Name your pet "```@everyone" (without quotes)
2. simply do #!adv

**Expected behavior**
Not being able to escape the code embed

**Screenshots**
![image](https://user-images.githubusercontent.com/26481794/82192796-c0a98a00-98f4-11ea-9791-5df85220b0ac.png)

**Version**
4.15.0

**Comment by FelixArgyle** [comment]
Recommend just disabling so the bot can ping everyone. (not really needed to have that enabled for the bot as there never a time the bot announces things for everyone with a ping.)

one of the devs should just consider blocking so "`" can be used in naming pets so people can't troll on a massive scale on servers

**Comment by Sven65** [comment]
Temporary fix would be as Felix said, disable it's everyone perms.

A permanent fix would either be disabling backticks in pet names, or escape mentions, unsure of which would be the best right now.

**Comment by Saederup92** [comment]
If removing the everyone perms still turns out to be annoying, the server can have a role named `everyone` that noone will be assigned to in addition to removing the perms.

**Comment by PlayTheFallen** [comment]
[REF] discord.js v12.x
https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=send
allowedMentions and disableMention options in MessageOptions

**Comment by Sven65** [comment]
I'm unsure which path to take on this. Any input, @Willard21, @sudojunior, @FelixArgyle?

**Comment by sudojunior** [comment]
> I'm unsure which path to take on this. Any input, ...?

You should be able to manually override the allowedMentions property when the message is sent, or to physically decline setting a pet name like that.

**Comment by Sven65** [comment]
I feel like the easier thing would be to check if the pet name has any mentions that aren't the bot iself, using the [`message.mentions`](https://discord.js.org/#/docs/main/stable/class/MessageMentions) property.

**Comment by Willard21** [comment]
We should also prevent having "```" in the name, since people use that to break formatting, which I don't think should be allowed.
