### ISSUE TITLE
Laxis Shears

### ISSUE THREAD

**Issue by turbiepants** [DiscordDungeons/Bugs#937]
Laxis Shears 2s skill requirement are downgraded from laxis shears after putting gemslots on it. Definitely related to: https://github.com/DiscordDungeons/Bugs/issues/933

1. Craft 1 laxis Shears
2. go to redhorn and add gemslot
3. See error

**Expected behavior**
I expect it to stay as forage skill level 40 after upgraded.

**Screenshots**
![laxi](https://user-images.githubusercontent.com/43326333/82508760-9e07b300-9b38-11ea-99bf-b87f2a881374.png)
![laxis](https://user-images.githubusercontent.com/43326333/82508763-a06a0d00-9b38-11ea-8869-dc35915a840f.png)

**Version**
4.14.0

**Comment by Sven65** [comment]
Fixed. It was a DB issue.
