### ISSUE TITLE
Pet will not gain any experience

### ISSUE THREAD

**Issue by anniellerpg** [DiscordDungeons/Bugs#942]
**Describe the bug**
At level 164, caught an Ogre to replace Baltion and Ogre will not gain any XP even at 100% xp rate and not dying at all during an adventure. Edit: I tried it again and my pet leveled up but the xp says 320/120 so maybe you cant level up more than once? 

**To Reproduce**
1. Be at level 164
2. Catch Ogre
3. Set pet xprate to 100%
4. Kill mob without pet dying
5. See error

**Expected behavior**
I was expecting my pet to receive all the XP after killing the mobs but it was given to me instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/67406438/85662261-860ddc80-b66c-11ea-8f72-b49c8b2220bf.png)
![image](https://user-images.githubusercontent.com/67406438/85662309-932acb80-b66c-11ea-841c-46a840d0ca68.png)
![image](https://user-images.githubusercontent.com/67406438/85663818-637cc300-b66e-11ea-9917-4efb7d0cfa5c.png)

**Version**
4.15.0

**Additional context**
Attempted in party and out of party but neither worked.

**Comment by Willard21** [comment]
Just for more details: your pet apparently needs to end the previous battle still alive in addition to staying alive for the entire next battle to receive exp.

**Comment by XpRienzo** [comment]
![image](https://user-images.githubusercontent.com/16952077/89056626-f1d51a80-d379-11ea-8d51-e598c24ad5f8.png)
Apparently, even if it gains experience at times, it'll not level up. To add to the above.

**Comment by Sven65** [comment]
I can't make sense of this.

As the bug with multiple levels has been fixed, I'll close this.
