### ISSUE TITLE
Query timed out

### ISSUE THREAD

**Issue by Dx8pi** [DiscordDungeons/Bugs#943]
Yes, this has already been reported by Felix, however I found another issue with it.
If you're talking to someone that has a query in their responses; You cannot talk to someone else, or the same NPC, until you get the "Query timed out".
That's more or less it. Now I am a programmer, just way below your level, but I do believe that just stopping the loop or whatever that's constantly checking the reactions/messages of the user after a reaction/correct message has been given would fix this issue.
Kthxthatsallformebye

**Comment by Willard21** [comment]
"Stopping the loop" :joy:

**Comment by Sven65** [comment]
Please add on to the other issue, #935
