### ISSUE TITLE
attributes don't add to my stats

### ISSUE THREAD

**Issue by willm12310** [DiscordDungeons/Bugs#944]
after i have put all my attribute points on and then check it hows I've added them but still says + or - 0 so im not sur  if u have to have a certain amount to get a boost or if it just isn't working. Because when i do #!adv after adding them i still take the same amount of damage and deal the same amount of damage and ithought this would change.

**Comment by Willard21** [comment]
You should check the wiki or ask in support. All the attributes require at least 10 points to have any effect. Less than that and the effect is 0.
