### ISSUE TITLE
Disabled Pets Can Gain Dungeon XP

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#946]
**Describe the bug**
If your pet is disabled with xprate higher than 0%, it can get xp when leaving a dungeon.

**To Reproduce**
1. #!pset xprate 100
2. #!pset disabled true
3. #!dungeon start
4. Kill mobs
5. Leave dungeon
6. See who gets the experience

**Expected behavior**
Disabled pets shouldn't gain xp.

**Screenshots**
![image](https://media.discordapp.net/attachments/172389002190651393/747619630297907210/Screenshot_20200825-075306.png?width=310&height=671)
![image](https://media.discordapp.net/attachments/172389002190651393/747619630545109004/Screenshot_20200825-075314.png?width=310&height=671)

**Comment by Sven65** [comment]
Can't reproduce.
