### ISSUE TITLE
Fishing rod. 

### ISSUE THREAD

**Issue by Meowgumin** [DiscordDungeons/Bugs#948]
I already bought fishing rod and was about to go fishing but it said i can't cause i didn't equipped it, even though i have it in my inventory? Is this a bug? I thought it is auto-equip?

**Comment by FelixArgyle** [comment]
Not a bug. Auto-equip is only for Weapon, Armor(Helmet, Chestplate, Boots).
Tools do not auto-equip, you equip items by using `#!use item` so in your case `#!use fishing rod`
-- Would recommend closing the issue

**Comment by Meowgumin** [comment]
Oh oh.
THANKS!
