### ISSUE TITLE
#!gleave doesn't work properly

### ISSUE THREAD

**Issue by ghost** [DiscordDungeons/Bugs#950]
**Describe the bug**
Attempting to leave a guild with #!gleave does not work outside of the official discord server.  The bot states that the guild you are attempting to leave has an active role, even when they do not.

**To Reproduce**
1. Join any guild that doesn't have an active role in the official server
2. Attempt to leave the guild in a private discord server by typing #!gleave
3. Bot tells you that your guild has an active role, and you must execute #!gleave in the official server 

**Expected behavior**
Bot should not say that a guild without an active role has one.
Bot should let users leave guilds with #!gleave outside of official server.

**Screenshots**
https://cdn.discordapp.com/attachments/172389002190651393/760585178010878003/784327.png
https://discordapp.com/channels/172382467385196544/172389002190651393/760585180552495144

**Version**
4.15.1

**Comment by Willard21** [comment]
As usual, the bug is with falsey values. The role is an empty string "", which obviously isn't a role, but the code only checks for null and undefined to decide if the role doesn't exist.

**Comment by Mastro5** [comment]
Hello there is a bug that when you do #!sell rock all you get like 300 coins when you had 5 rocks but when you do #sell rock you get 100 coins so you will get 500 coins which is 200 times better than by doing all so I think you should fix the bug for the servers economy.

**Comment by FelixArgyle** [comment]
> Hello there is a bug that when you do #!sell rock all you get like 300 coins when you had 5 rocks but when you do #sell rock you get 100 coins so you will get 500 coins which is 200 times better than by doing all so I think you should fix the bug for the servers economy.

@Mastro5 That is not related to this issue in any way., create a new bug report following the template https://github.com/DiscordDungeons/Bugs/issues/new?template=bug_report.md

**Comment by Sven65** [comment]
Seems fixed.
