### ISSUE TITLE
#!gcreate bugs

### ISSUE THREAD

**Issue by Rosenkreuz12** [DiscordDungeons/Bugs#96]
if you create a guild and then proceed to disband it and then tries to create guild again the bot would think that you are still inside a guild despite stats showing none
basically
```
Genghis Tebo [Lvl. 28] - Today at 4:20 AM
#!gcreate Lords of Light
DiscordRPGBOT - Today at 4:20 AM
You're already in a guild, Genghis Tebo.
```
that would happen

**Comment by Punknoodles** [comment]
the workaround is to join a guild then leave again. the bot will recognize you aren't in a guild

**Comment by Sven65** [comment]
Is this using the `#!gdisband` command?

**Comment by Punknoodles** [comment]
I used #!disband YES and that caused this to happen. I think it only happens when you are disbanding, because leaving someone else's guild fixes it.

**Comment by Sven65** [comment]
Ah
