### ISSUE TITLE
Battles does not accept ID

### ISSUE THREAD

**Issue by RainTheVappy** [DiscordDungeons/Bugs#970]
**Describe the bug**
Same as title

**To Reproduce**
Have your #!uset battles 1
#!battle someone using ID

**Expected behavior**
battle

**Screenshots**
no

**Version**
latest as of now

Use `#!info` to find the version.

**Additional context**
no one even uses #!battle anymore why not just discard it

**Comment by Willard21** [comment]
I think requiring users to mention someone for a battle is fine. The person you're challenging kinda needs to respond asap for the battle, so the ping is either useful, or not a problem (if they're already in the channel).

**Comment by Sven65** [comment]
Gonna keep it as mentions.
