### ISSUE TITLE
#!adv sometimes executes adventure twice

### ISSUE THREAD

**Issue by Creative0708** [DiscordDungeons/Bugs#975]
**Describe the bug**
Sometimes on a server, one adv command causes the adventure to be executed twice without a cooldown.

**To Reproduce**
1. Go to a busy server
2. Have people execute the adv command
3. Find that sometimes, the bot executes an adventure twice.

**Expected behavior**
When executing adv, the bot is supposed to execute only one command instead of two.

**Screenshots**
<img width="1237" alt="img1" src="https://user-images.githubusercontent.com/62843679/104533768-0122ea00-55e1-11eb-9454-51d0482a9959.png">
<img width="1200" alt="img2" src="https://user-images.githubusercontent.com/62843679/104533867-2fa0c500-55e1-11eb-8361-6749111c77af.png">

**Version**
4.15.4

**Comment by Boom-H** [comment]
im pretty sure its because of lag or something that ur message gets deleted
