### ISSUE TITLE
A reset of items in dinv in dungeon without dying

### ISSUE THREAD

**Issue by Prime1237** [DiscordDungeons/Bugs#978]
**Usually when you die in dungeon the whole process will be lost and then exit the dungeon, not sure what happened but apparently I couldn't click on the the next-floor button and had to wait a bit. I came back after a few minutes resuming the run only to find out all the items were lost**

**To Reproduce**
1. Go to 'dungeon"
2. Click on 'the moving button up down left right fast with the final destination the entrance'
3. unable to click on the 'tick mark' moving to the next floor
4. nothing happen but resuming after a few minutes

**Expected behavior**
The whole process was lost

**Screenshots**
![Screenshot_20210124-213649_Discord](https://user-images.githubusercontent.com/77928931/105635138-04955b80-5e94-11eb-9ab5-3644bd4cebc2.jpg)

**Version**
What is the current version at the time of creating this issue?

Use `#!info` to find the version.

**Additional context**
Can I have my two rubies back lol, I'm very sad that I lost two after while not playing the game and this happened to me when I finally decided to continue playing. Pls T_T
My user name is prime #2046

**Comment by Sven65** [comment]
From what I can make out of the screenshot, there were no rubies in your progress. As for how to reproduce it, I'd need to know that in order to well, reproduce it so I know how to fix it.

**Comment by Sven65** [comment]
As no more info has been provided, I will be closing the issue.
