### ISSUE TITLE
Octopi Item

### ISSUE THREAD

**Issue by ShieldGame** [DiscordDungeons/Bugs#980]
**Describe the bug**

**To Reproduce**
1. Go to '#!inv'
2. Click on '→'

**Expected behavior**

**Screenshots**
http://cdn.discordapp.com/attachments/806442035832946710/806443418250248212/Octopi.png
**Version**
What is the current version at the time of creating this issue?
4.15.4
Use `#!info` to find the version.

**Additional context**

**Comment by FelixArgyle** [comment]
That's not a bug nor an incorrect description of the item. Octopi is one of three plural names for Octopus.

**Comment by ShieldGame** [comment]
ok
