### ISSUE TITLE
Stack in ghost battle

### ISSUE THREAD

**Issue by LOPEZwas** [DiscordDungeons/Bugs#982]
I was playing discord rpg in a server when someone said to me if I want to battle so I accept. We stay fighting during  a time until he disconnect. Hours later I saw that I cannot buy the fishing rod because I was in a battle, I also tried with other objects but nothing. So I contact him and I write him to do bdraw accept I wait during some days and nothing, he never connect discord. So I tried some methods like killing me or other thing but didn't work. And I was going to do /reset when a friend said to me that I can report the problem. So That I do. (If it is of help my discord Id is LÓPEZ_was#1788).

**Comment by FelixArgyle** [comment]
Type out `#!bstop` it should stop the battle without needing the other play available.

**Comment by LOPEZwas** [comment]
Thanks
