### ISSUE TITLE
Item fly

### ISSUE THREAD

**Issue by ShadowGaming100** [DiscordDungeons/Bugs#993]
Whoops. An error occured. Please report this in the official server.
TypeError: Cannot read property 'tool' of null
    at Item.Execute (/home/mackan/RPGBot/src/Commands/Commands/General/Item2.js:273:29)

**Comment by FelixArgyle** [comment]
Fly isn't an item.
// error is a check for users "tool", axe, fishing rod, shears, pickaxe etc.
Could you perhaps DM me `Felix Argyle#6969`, I assume you're an old user which is likely causing the error.
 (also in future use the templates provided when creating an issue.)
