### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#996]
**Describe the bug**
Some guy did search in silverkeep and it did this error

**To Reproduce**
1. do search in silverkeep? or maybe anywhere

**Expected behavior**
to not error duh
**Screenshots**
![15087980765139](http://senpai.pls-fuck.me/8zgqhpj.jpg)

**Version**
4.15.5

**Additional context**
guy that triggered it was a lower level

**Comment by FelixArgyle** [comment]
Just an update to this, it seems to happen not just in silverkeep
happened to another user in Bibliothecam Magnam
so search itself is all borked up

**Comment by Sven65** [comment]
After checking the code, it seems to be an overlooked part on my end, where the new "max amount" feature is being applied to every search, even when there is no maxAmount set, leading to the issue.

To fix should only need another check.
